### ISSUE TITLE
Enchantment: Don't close the injector after injecting

### ISSUE THREAD

**Issue by FedeArre** [R3nzTheCodeGOD/R3nzSkin#1]
I love the fork, works flawlessly and is so nice to have again the skin changer working, but a very small change compared to the original is that the injector closes after injecting, forcing to reopen it every match.

Is just removing 2 lines, not big deal.
https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/a349e3390ba02bce266b1e5ffcea0fb93212548e/R3nzSkin_Injector/R3nzSkin_Injector.cpp#L144-L146

**Comment by 6oody** [comment]
i guess he added the closing idea bc like if u r streaming or sharing ur screen in discord noone will know that u r using the prog

> I love the fork, works flawlessly and is so nice to have again the skin changer working, but a very small change compared to the original is that the injector closes after injecting, forcing to reopen it every match.
> 
> Is just removing 2 lines, not big deal.
> https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/a349e3390ba02bce266b1e5ffcea0fb93212548e/R3nzSkin_Injector/R3nzSkin_Injector.cpp#L144-L146
