### ISSUE TITLE
Spirit Guard Udyr doesn't work properly

### ISSUE THREAD

**Issue by Xayunara** [R3nzTheCodeGOD/R3nzSkin#10]
No animation bear stance 
No flame pop phoenix

Udyr's stances doesn't evolve after 4 points in anything

**Comment by krukuhehe** [comment]
I'm sure Ultimate skins don't work as they intended to do. Some Legendary skins also has problems with voice lines and particles. Other skins works fine.

**Comment by R3nzTheCodeGOD** [comment]
I explained this problem nicely
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/7#issuecomment-890404019
