### ISSUE TITLE
Closes when injected.

### ISSUE THREAD

**Issue by Salim-Bek** [R3nzTheCodeGOD/R3nzSkin#100]
It used to work normally , same patch , same version but now when i press start to inject the game closes

**Comment by yxngh** [comment]
Patch 12.8 out already

**Comment by Salim-Bek** [comment]
It was even before the patch ,it presisted after it

**Comment by yxngh** [comment]
reinstall game then
had same issue

**Comment by sonitaaaaa** [comment]
Reinstall the update, its conflict with the old patch. (This is the client/game problem, not the tool it self)
