### ISSUE TITLE
How to manually update on R3nzskin, I still want to use it in 2024

### ISSUE THREAD

**Issue by Maqpwa** [R3nzTheCodeGOD/R3nzSkin#1000]
Hi! Can someone guide me on how to manually update R3nzskin? I play on the China server, and since there's no Vanguard, I still want to use this application as it remains usable.

**Comment by tangmuduo** [comment]
Hey, man, we are on the same server.

**Comment by Maqpwa** [comment]
> Hey, man, we are on the same server.

Do you know how to manually update, i still really want to use this app xd?

**Comment by tangmuduo** [comment]
You know, we can only use 13.24 file injection to ensure the normal operation of the game without flashback. This is the only method that I can actually test before the author makes 14.1 optimization, although there are some risks.


                       
原始邮件
                       
                     

发件人："Maqpwa"< ***@***.*** &gt;;

发件时间：2024/1/11 9:59

收件人："R3nzTheCodeGOD/R3nzSkin"< ***@***.*** &gt;;

抄送人："tangmuduo"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [R3nzTheCodeGOD/R3nzSkin] How to manually update on R3nzskin, Istill want to use it in 2024 (Issue #1000)




  
Hey, man, we are on the same server.
  
Do you know how to manually update, i still really want to use this app xd?

**Comment by tangmuduo** [comment]
> > 嘿，伙计，我们在同一个服务器上。
> 
> 你知道怎么手动更新吗，我还真想用这个app xd？
Because the version 14.1 updated last night will flash back today and will not work normally, so my suggestion is to use it temporarily as I said, and wait for the optimized version.

**Comment by 1Wizzy** [comment]
No, guys, vanguard will be integreted into TP developed by Tentent.
It's hard to say we can fix it easily to use in China Server.

**Comment by hotline1337** [comment]
You will need a bypass to inject the DLL into the game.
