### ISSUE TITLE
Version 13.24 is still available in Tencent League of Legends, but the skin will be reset every time you die.

### ISSUE THREAD

**Issue by Eff0rtly** [R3nzTheCodeGOD/R3nzSkin#1001]
Version 13.24 is still available in Tencent League of Legends, but the skin will be reset every time you die.Hope there is a solution

**Comment by Eff0rtly** [comment]
Judging from Tencent Valorant’s experience, Tencent will not enable Vanguard in League of Legends.

**Comment by Maqpwa** [comment]
Can i have the 13.24 version of r3nzskin?

**Comment by tangmuduo** [comment]
> 腾讯英雄联盟13.24版本依然有，但是每次死亡皮肤都会重置。希望有解决办法

Yes, I have noticed this problem, but at least it can be used. I hope the author can see that it can be optimized in time. We are all waiting.

**Comment by tangmuduo** [comment]
> 我可以要13.24版本的r3nzskin吗？

Here's the link, the 13.24 version you want.

https://github.com/R3nzTheCodeGOD/R3nzSkin/releases

**Comment by Papermars** [comment]
also could be used  in TW

**Comment by hotline1337** [comment]
#1 and The patterns might be mismatched, but soon there will be Vanguard implemented into the game, for your safety I suggest you to not use the skin changer.

**Comment by prluo** [comment]
Version 3.2.5 can't use in 14.1,

**Comment by bellyr** [comment]
Can someone fix this issue? All CN players are waiting QAQ
