### ISSUE TITLE
Can someone give me the previous injector and dll

### ISSUE THREAD

**Issue by Reraz** [R3nzTheCodeGOD/R3nzSkin#1002]
This version has some problems.

**Comment by tangmuduo** [comment]
Sir, I have a link to the old file here. You can open it and find the 13.24 version R3sk.

https://github.com/R3nzTheCodeGOD/R3nzSkin/releases

**Comment by Reraz** [comment]
thanks

**Comment by Reraz** [comment]
i forgot you could see the previews versions and their files haha.

**Comment by Reraz** [comment]
Looks like the problem persists.
