### ISSUE TITLE
R3SKIN

### ISSUE THREAD

**Issue by ho9e** [R3nzTheCodeGOD/R3nzSkin#1003]
Failed to find pattern: 48 8B 0D ???? 48 8B DA 48 8B 52 30

**Comment by tangmuduo** [comment]
Sir, the China server can use version 13.24 R3. You can try it on the local server. Maybe it will work.

**Comment by hkz1ws** [comment]
use version 13.24 R3，each time the hero dies, the skin will revert to the default

**Comment by Reraz** [comment]
probably is the server, mine works fine.

**Comment by tangmuduo** [comment]
> 使用13.24 R3版本，每次英雄死亡，皮肤都会恢复默认

You know, we can only use the last version of the file now, but it still works normally, isn't it?

**Comment by tywhisky** [comment]
> probably is the server, mine works fine.

Actually the Taiwan Server (Also Riot Client) has the same issue. But click confirm button, the R3n will inject correctly.

But each time start the game all alert the above message. Could give me some tips for this issue? Maybe I can build dll by myself to fix it.

**Comment by songqingyuan001** [comment]
The version 14.1 of r3z skin,Taiwan and japanese service is ok, Chinese service can't be used. error:Failed to find pattern: 48 8B 0D ???? 48 8B DA 48 8B 52 30

**Comment by hotline1337** [comment]
The patterns might be mismatched, but soon there will be Vanguard implemented into the game, for your safety I suggest you to not use the skin changer.
