### ISSUE TITLE
ARAM Crashes 14.1

### ISSUE THREAD

**Issue by WGPL777** [R3nzTheCodeGOD/R3nzSkin#1004]
Game crashes everytime on arams when skin changer is running

**Comment by ZEERDEER** [comment]
same

**Comment by phamlebaoanh123** [comment]
Hope they'll still update until vanguard is released

**Comment by L-evi** [comment]
Me too, OS: Windows 11

**Comment by ahmetcicek-ae** [comment]
same

**Comment by ZEERDEER** [comment]
> Hope they'll still update until vanguard is released

You can turn off vanguard manually

**Comment by anhpham258** [comment]
> > Hope they'll still update until vanguard is released
> 
> You can turn off vanguard manually

turn off vanguard = turn off league

**Comment by hotline1337** [comment]
The patterns might be mismatched, but soon there will be Vanguard implemented into the game, for your safety I suggest you to not use the skin changer.
