### ISSUE TITLE
Zed shadows (W spell) is broken (they are looking like classic shadows)

### ISSUE THREAD

**Issue by TraxYzq** [R3nzTheCodeGOD/R3nzSkin#1005]
i need a new update (and I would also like to thanks the guy who created the skin changer)

**Comment by hotline1337** [comment]
#1

**Comment by slayer99234** [comment]
Also Galaxy slayer zed skin q flick

**Comment by slayer99234** [comment]
![images](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/157699844/862818ff-c70a-4cd8-883a-71a0ab91a801)
