### ISSUE TITLE
the game will crash when Fiddlesticks releases his passive.

### ISSUE THREAD

**Issue by hydy100** [R3nzTheCodeGOD/R3nzSkin#1006]
After entering the game, the program was successfully injected, but the passive game crashed when Fiddlesticks was released.

**Comment by MemeME7000** [comment]
true i used the ward with a target dummy in training mod and quiked me out of the game

**Comment by tangmuduo** [comment]
> game我在训练模式中使用了带目标假人的结界，并让我退出了游戏

Failed to find pattern: 48 8B 0D ???? 48 8B DA 48 8B 52 30           Is that so?

**Comment by Reraz** [comment]
Its probably just for the new version and he wont probably fix it because the skinchanger just have 2 more weeks.

**Comment by thegreenflash1** [comment]
> Its probably just for the new version and he wont probably fix it because the skinchanger just have 2 more weeks.

where did u get the information it will only be 2 more weeks? i thought vangaurd happens in march?

**Comment by Reraz** [comment]
> > Its probably just for the new version and he wont probably fix it because the skinchanger just have 2 more weeks.
> 
> where did u get the information it will only be 2 more weeks? i thought vangaurd happens in march?

Beginning or march or end of February

**Comment by xiangxiaoyi123** [comment]
Failed to find pattern: 48 8B 0D ???? 48 8B DA 48 8B 52 30

**Comment by HarIki012** [comment]
> > game我在训练模式中使用了带目标假人的结界，并让我退出了游戏
> 
> Failed to find pattern: 48 8B 0D ???? 48 8B DA 48 8B 52 30 Is that so?
just like this
![{DC1BBE26-2B34-4390-A889-4595114DE675}](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/74295251/757e543a-51bf-455f-bb3d-e23a2387ed99)

**Comment by tangmuduo** [comment]
> 找不到图案:48 8B 0D？？？？48 8B DA 48 8B 52 30

Yes, that's right. Because of the change of the new version mode, the injected port is suspected to be officially disabled, so the 14.1 version of R3sk can't work normally in our game.

**Comment by hotline1337** [comment]
#1 and the patterns might be mismatched, but soon there will be Vanguard implemented into the game, for your safety I suggest you to not use the skin changer.
