### ISSUE TITLE
I accidentally increase the DPI to the skin changer and can't revert it

### ISSUE THREAD

**Issue by discoveranytime** [R3nzTheCodeGOD/R3nzSkin#1011]
I lost control my mouse when I alt+tabbed and I accidentally increase the DPI of the application. I did this on patch 13.24 and when I updated the program to 14.1 the issue still persists. I have tried reinstalling the application. I have tried changing the resolution in game, switching from full-screen to border less. Nothing works. When I try moving the window around all I see is a yellow box

How do I reset the application? 

![DPI Bug](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/132519591/62f7933d-ab9c-4cb7-82c4-bc9065854533)

https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/132519591/6b531e62-cafd-4777-8722-02c614f14b7a

**Comment by JaxonNing** [comment]
hhhhhh crazy

**Comment by KirCloud** [comment]
try delete c:\user\yourusername\Documents\R3nzSkin this folder

**Comment by hotline1337** [comment]
> try delete c:\user\yourusername\Documents\R3nzSkin this folder

this.
