### ISSUE TITLE
cn server error Failed to find pattern: 48 8B 0D ? ? ? ? 48 8B DA 48 8B 52 30

### ISSUE THREAD

**Issue by mandxy** [R3nzTheCodeGOD/R3nzSkin#1012]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/43473135/56afc5af-2e37-4e9f-9ea3-5f9498085071)

**Comment by O8N1** [comment]
yep

**Comment by O8N1** [comment]
Me too

**Comment by makabaka2869** [comment]
13.24

**Comment by inception33** [comment]
same issue

**Comment by renjieliu1** [comment]
+1

**Comment by liangyi9812** [comment]
same issue

**Comment by Reraz** [comment]
delte the files and download the last version, also delete the files from documents named r3nskin

**Comment by ho9e** [comment]
> 删除文件并下载最新版本，并从名为 r3nskin 的文档中删除文件

Which file do you want to delete?

**Comment by hotline1337** [comment]
china server is no longer supported by r3nzskin

**Comment by bellyr** [comment]
> china server is no longer supported by r3nzskin

not a lucky news

**Comment by helin98** [comment]
Modify this line error to the offset of the previous version, file in memory.hpp

**Comment by chuest** [comment]
国服用[这个](https://github.com/chuest/R3nzSkin/actions/runs/7620395395/artifacts/1187526651)即可
