### ISSUE TITLE
is it safe?

### ISSUE THREAD

**Issue by Kerballl** [R3nzTheCodeGOD/R3nzSkin#1014]
![aaa](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/89897658/e214eb9c-bda9-4d72-a410-3a09be3bb984)

![Ekran Görüntüsü (78)](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/89897658/c950f04a-3837-4fa1-ba54-582c1fc89f1e)
I ask to riot about when vanguard comes 3rd party programs and custom skins are ban reason? and they said if it doesnt change game folder that much its not. so i think it seems ok? but probably i wont use it for now  (its turkish i know and my english not that good bear it please )

**Comment by iaiaian1** [comment]
Should be fine until vanguard implementation.

**Comment by Kerballl** [comment]
he said its not ban reason but its not directly ban reason its not it their terms

**Comment by anhpham258** [comment]
In my opinion, riot does not prohibit mod skin. But Vanguard isn't sure about it, there are a few Valorant players who have been banned just for using the unicode text app running in the background. Vanguard is anti-hack software at kernel level, who knows what it'll do when handling 3rd app's injection

**Comment by Reraz** [comment]
Vanguard will detect the skinchanger as something malicious. It will detect everything that is not normal from league files you open league.

**Comment by hotline1337** [comment]
safe until vanguard gets added
