### ISSUE TITLE
> aram euw riven worlds 2012在游戏中选择了皮肤(已拥有)，游戏只是在通常皮肤菜单打开时关闭

### ISSUE THREAD

**Issue by AlexCo1d** [R3nzTheCodeGOD/R3nzSkin#1016]
> aram euw riven worlds 2012在游戏中选择了皮肤(已拥有)，游戏只是在通常皮肤菜单打开时关闭

Sir, I did a test. I found that R3 can play the 14.1 client game normally by injecting the 13.24 dll extension file, and the built-in dragon skin in the new version is also synchronized, so the game will not flash back. I hope it will be helpful to you and the author's update.

_Originally posted by @tangmuduo in https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/998#issuecomment-1886050539_

**Comment by AlexCo1d** [comment]
Find that 13.24 patch's dll file also work for 14.1 but when i die i have to re-choose the skin.

**Comment by NQBFS** [comment]
Really? This is very interesting

**Comment by wannanacryry** [comment]
> Find that 13.24 patch's dll file also work for 14.1 but when i die i have to re-choose the skin.

Were you playing on Tencent server ? I have a same problem. 13.24 patch's dll file is work for 14.1 Tencent server , 14.1 patch's dll file Client will show error when after game loaded. So,I can only use 13.24 patch's dll file on 14.1 Tencent server game.
Starting from 13.24 version, I found that after the player dies, the character's skin also be changed to the default. i cant make sure what's the problem it is .

**Comment by Reraz** [comment]
That happened to me and i just deleted the files and the files on Documents, downloaded them again and fixed

**Comment by AlexCo1d** [comment]
> > Find that 13.24 patch's dll file also work for 14.1 but when i die i have to re-choose the skin.
> 
> Were you playing on Tencent server ? I have a same problem. 13.24 patch's dll file is work for 14.1 Tencent server , 14.1 patch's dll file Client will show error when after game loaded. So,I can only use 13.24 patch's dll file on 14.1 Tencent server game. Starting from 13.24 version, I found that after the player dies, the character's skin also be changed to the default. i cant make sure what's the problem it is .

I am playing international server(US), according to ur description, we are in the same bug situation.

**Comment by chuest** [comment]
国服用[这个](https://github.com/chuest/R3nzSkin/actions/runs/7620395395/artifacts/1187526651)即可

**Comment by dadaya6** [comment]
dll文件在哪啊，为什么我找不到啊

**Comment by dadaya6** [comment]
> ```
>           > aram euw riven worlds 2012在游戏中选择了皮肤(已拥有)，游戏只是在通常皮肤菜单打开时关闭
> ```
> 
> 先生，我做了一个测试。我发现 R3 通过注入 13.24 dll 扩展文件可以正常玩 14.1 客户端游戏，并且新版本内置的龙皮也是同步的，所以游戏不会闪回。希望对您和作者的更新有所帮助。
> 
> _引用自 [in #998 （comment）](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/998#issuecomment-1886050539)_

dll文件找不到啊

**Comment by hotline1337** [comment]
Don't use the old releases if you want stability, performance, and security.
