### ISSUE TITLE
How to inject DLL

### ISSUE THREAD

**Issue by pidanpro** [R3nzTheCodeGOD/R3nzSkin#1017]
![微信图片_20240117000016](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131292481/c5811c7f-ae2e-42cf-8028-65ad10a6e2fc)

**Comment by bylldgo** [comment]
dont use fullscreen

**Comment by pidanpro** [comment]
> 不要使用全屏 不要使用全屏


What does it have to do with full screen

**Comment by bylldgo** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/126079646/56712e21-6c89-41d5-bcdd-733aabc47589)


And you didnt start..

**Comment by pidanpro** [comment]
> ![image](https://private-user-images.githubusercontent.com/126079646/297395751-56712e21-6c89-41d5-bcdd-733aabc47589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTg5NjcsIm5iZiI6MTcwNTQ5ODY2NywicGF0aCI6Ii8xMjYwNzk2NDYvMjk3Mzk1NzUxLTU2NzEyZTIxLTZjODktNDFkNS1iY2RkLTczM2FhYmM0NzU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMzM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2E2NjgyYjU3ZmQ3YmFiOTZkODVlNTk2MzM5ZGI5ZDZhNGQwNjAwMmRmYmViZTkwZjg1NmRhODRlMWJhZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vt5aFM6xPasoALznj_n3NEbrtgr7cayaIjazoplMpV8)
> 
> you didn't start the program您没有启动程序

![微信图片_20240117214001](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131292481/c42143fd-a2db-40c6-8430-40183f1371bd)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131292481/034a809b-d396-496c-aa9d-a8a01f586ff8)

**Comment by pidanpro** [comment]
> ![image](https://private-user-images.githubusercontent.com/126079646/297395751-56712e21-6c89-41d5-bcdd-733aabc47589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTg5NjcsIm5iZiI6MTcwNTQ5ODY2NywicGF0aCI6Ii8xMjYwNzk2NDYvMjk3Mzk1NzUxLTU2NzEyZTIxLTZjODktNDFkNS1iY2RkLTczM2FhYmM0NzU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMzM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2E2NjgyYjU3ZmQ3YmFiOTZkODVlNTk2MzM5ZGI5ZDZhNGQwNjAwMmRmYmViZTkwZjg1NmRhODRlMWJhZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vt5aFM6xPasoALznj_n3NEbrtgr7cayaIjazoplMpV8)
> 
> you didn't start the program

![微信图片_20240117214001](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131292481/8e180a82-d2f4-4cae-a2ed-42c4fe2c03ba)
Started, but shows no injection

**Comment by bylldgo** [comment]
Do not play in full screen mode ,Play in frameless screen mode

**Comment by bylldgo** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/126079646/8cea915c-dd66-4e86-bad2-87f387c14b6b)

**Comment by pidanpro** [comment]
> ![image](https://private-user-images.githubusercontent.com/126079646/297406813-8cea915c-dd66-4e86-bad2-87f387c14b6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDE1MTksIm5iZiI6MTcwNTUwMTIxOSwicGF0aCI6Ii8xMjYwNzk2NDYvMjk3NDA2ODEzLThjZWE5MTVjLWRkNjYtNGU4Ni1iYWQyLTg3ZjM4N2MxNGI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNDIwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTI3MjhmNzY2NDc0NDZjNzdlOTI0NDA0ODBlYjVhZjYyZWIxMDNkYTY5ZTEyMmJjNTFhNjk1OGE2ZDIxMWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s7ec1gIpi0091zisGN9gT8ETGwtbVDXRpZ-xEzCRWck)

![微信图片_20240117214001](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131292481/ba9615c2-4b96-4738-8c99-5f0020d594f0)
Still ineffective

**Comment by laozhouy** [comment]
![QQ截图20240119233119](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/157139320/d894f846-8091-45b9-aabd-f2ae74dde35f)

**Comment by laozhouy** [comment]
Unable to inject

**Comment by Reraz** [comment]
delete the files and the files from documents and download the again.

**Comment by pidanpro** [comment]
> delete the files and the files from documents and download them again.

Where should I put the prepared files?

**Comment by Reraz** [comment]
wherever you want the new files as always
