### ISSUE TITLE
Randomly crashes (EUW)

### ISSUE THREAD

**Issue by GangstaVik** [R3nzTheCodeGOD/R3nzSkin#1022]
basically even tho am following the steps provided in the desc mentioning the fact that it can cause crash if you inject too early and so on... it simply won't let me play with the menu injected.
Could it be some code-related problem?

**Comment by emlautarom1** [comment]
Same for me in LAS. It might run well for a couple of games but then it can randomly crash. Injecting mid game or with launcher only is irrelevant.

**Comment by hotline1337** [comment]
This might be caused because of your CPU/GPU. Try enabling DirectX 9 in the LOL Launcher.
