### ISSUE TITLE
How to 100% reset everything?

### ISSUE THREAD

**Issue by Tjonna** [R3nzTheCodeGOD/R3nzSkin#1023]
Basically the program takes up my entire screen, can't see anything anymore. But when I remove everything and re-install basically, I keep the same settings.

**Comment by v1aggr** [comment]
![League of Legends Screenshot 2024 01 21 - 13 24 30 58](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/157287511/4c2854d8-f48e-4fe6-96ff-4599abe7e2f8)

**Comment by Tjonna** [comment]
Yes, something like that. Is there a way to 100% reset this so it gets fixed?

**Comment by R3nzTheCodeGOD** [comment]
Go to `documents->R3nzSkin` and delete the file named **R3nzSkin64**.
