### ISSUE TITLE
Skin get's DISABLED AFTER DEATH  (must be Reselected )

### ISSUE THREAD

**Issue by NyroY64** [R3nzTheCodeGOD/R3nzSkin#1024]
when u die the skin is disabled and must be reselected

**Comment by ChaiJohn216** [comment]
My friends and I got same problem，there is a Announcement：
R3nzSkin will no longer be supported by 2024 due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends. I think thats why.

**Comment by R3nzTheCodeGOD** [comment]
1de72084f64e2c39a63a71e5abd7f3103f9421e3 should be fixed
