### ISSUE TITLE
14.2 pattern error

### ISSUE THREAD

**Issue by Jaroslawx** [R3nzTheCodeGOD/R3nzSkin#1027]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/77592125/0002f577-3764-455b-a6f9-d07335da65fc)

Has someone fixed pattern error, after new patch?

**Comment by SerenityxSystem** [comment]
> ![image](https://private-user-images.githubusercontent.com/77592125/299224074-0002f577-3764-455b-a6f9-d07335da65fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODU3NDUsIm5iZiI6MTcwNjA4NTQ0NSwicGF0aCI6Ii83NzU5MjEyNS8yOTkyMjQwNzQtMDAwMmY1NzctMzc2NC00NTViLWE2ZjktZDA3MzM1ZGE2NWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4MzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzY2U2ZjEwMTA4YWQ5YzRhODE4NjJlNDIyYjk5NzllZTZmZTY2YTUxNmMwODA1ZWJhMTM1NTE4NGZmOGJmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0X7_txtjCGtOqMtgS341czlHLIuNCruo0CJ8tDJ8R6g)
> 
> Has someone fixed pattern error, after new patch?

Do not use the version from the person above me.

**Comment by zklici0us** [comment]
Do not use that version for your safety.
