### ISSUE TITLE
Update 14.2 Mod Skin

### ISSUE THREAD

**Issue by toolgamepc-com** [R3nzTheCodeGOD/R3nzSkin#1028]
I'm gay, and I'm trying to steal data from people here.

**Comment by NelasDeSearun** [comment]
It works
thanks my hero!
And can you teach me how to make it right when it doesn't work?
MORE CARE ---> Will you continue to update???
Eventually THX MAN..

**Comment by SerenityxSystem** [comment]
thanks for the virus

**Comment by SerenityxSystem** [comment]
> > thanks for the virus
> 
> False positives. You can also find out what R3nz had to say about Virus

You promote your own skin changer you numbnut, thats not a false positive, i have sweeped through your application. 

Ill report your account to Github, have fun to getting Terminated

**Comment by zhang-bu-gao-wa** [comment]
How do I use it on a server in China?

**Comment by Courage0224** [comment]
THX MAN

**Comment by SerenityxSystem** [comment]
Do not download this guys tool. Its a virus and i have already reported him to github.

**Comment by SerenityxSystem** [comment]
不要下载这个家伙的工具。这是一个病毒，我已经向 github 报告了他。

**Comment by Stxrmy9** [comment]
do not download i downloaded itt and used it and it said that my account logged in from another device fucking vietnamese scammer

**Comment by codercoin98** [comment]
wow, it works.thanks

**Comment by zklici0us** [comment]
Don't use this version if you love your data.

**Comment by SerenityxSystem** [comment]
> > Do not download this guys tool. Its a virus and i have already reported him to github.
> 
> Are you an idiot? Why spam this issue when everyone can verify and learn about it themselves? Are you jealous??

why isn't your repo open huh? hiding something? oh yes you are, since i sweeped through your account. If you had your stuff open you'd be terminated right away instead of hiding on your vietnamese site you little scammer. And using someone elses work to promote your "own" code is cringe aswell.

**Comment by SerenityxSystem** [comment]
> > > > Do not download this guys tool. Its a virus and i have already reported him to github.
> > > 
> > > 
> > > Are you an idiot? Why spam this issue when everyone can verify and learn about it themselves? Are you jealous??
> > 
> > 
> > why isn't your repo open huh? hiding something? oh yes you are, since i sweeped through your account. If you had your stuff open you'd be terminated right away instead of hiding on your vietnamese site you little scammer. And using someone elses work to promote your "own" code is cringe aswell.
> 
> Do you understand anything about open source? I wouldn't be here talking to an idiot like you. I'll keep working and ignore you

how about you get a real job instead of scamming people off of their data?
Do you understand anything about open source you poser? You use a code that was posted on multiple cheating sites 10 years ago, so don't talk to me about knowing stuff or work, you little copy and paste kid

**Comment by SerenityxSystem** [comment]
> > I leave my version here and people can use it or not. Everyone can verify the version themselves. I'm not doing any nonsense here. Thanks everyone.
> 
> People are smart enough to learn and test it. I repeat it here. Now I continue my work with the Chinese version.

"continue my work with the chinese version" aka searching through cheating forums to find a working chinese version. 

If you knew anything about coding you'd know that you just have to swap little to no code around you moron hahahahahah

**Comment by SerenityxSystem** [comment]
this guy is disabled hahaah

**Comment by someb0dy89** [comment]
> it's here: https://github.com/R3nzTheCodeGOD/R3nzSkin

no, it's here
https://github.com/toolgamepc-com/toolgamepc/

**Comment by zhang-bu-gao-wa** [comment]
Sorry, thank you, I haven't read the email for a long time, I've deleted this file, what happens if I've opened it, I haven't noticed anything wrong with my computer at the moment.

**Comment by SerenityxSystem** [comment]
> Sorry, thank you, I haven't read the email for a long time, I've deleted this file, what happens if I've opened it, I haven't noticed anything wrong with my computer at the moment.

删除属于该程序的所有文件。并查看您的本地磁盘，看看是否有隐藏的文件夹您不认识。

**Comment by null15** [comment]
Feeling mixed feelings? I ran it on a VM for you, my results? xD

Don't install, the fact the github is just a .rar file should already tell you this aint no good

**Comment by ibai7** [comment]
Does anyone know the CharacterDataStack?

**Comment by Reraz** [comment]
I kind of knew they were malicious files.
