### ISSUE TITLE
Do not download other mod programs that are being spammed here, just wait for an update!

### ISSUE THREAD

**Issue by SerenityxSystem** [R3nzTheCodeGOD/R3nzSkin#1029]
Especially the tool from Toolgamepc.com
its a virus... so if you value your data DO NOT download it!

**Comment by zklici0us** [comment]
+1 wait for R3nz update.

**Comment by MejaiReponse** [comment]
yea we trust in R3nz only. That being said hope it gets updated soon and thanks r3nz!

**Comment by MejaiReponse** [comment]
would it be possible to just update it ourselves for now until r3nz updates cuz i kinda wanna use it rn

**Comment by nolifecoding** [comment]
Well, will he? The announcement made itself quite clear :(

**Comment by Jaroslawx** [comment]
> Well, will he? The announcement made itself quite clear :(

Untill Vanguard will not be added, you can use skin changer and there will be updates.

**Comment by megmeyxxx** [comment]
wards don't work.

**Comment by SerenityxSystem** [comment]
> [SerenityxSystem](https://github.com/SerenityxSystem) and [zklici0us](https://github.com/zklici0us) Is one.
> 
> * Thank you for promoting my website.
> * If there is a Virus, prove it and explain to everyone.
> * Everyone can verify the Virus.
> * I do not force anyone to use Mods on my website. I just want to share my ModSkin with everyone while waiting for R3nz to update. People can use it or NOT.
> * Thanks everyone.

Get off this Repo scum
