### ISSUE TITLE
CharacterDataStack

### ISSUE THREAD

**Issue by Longweii** [R3nzTheCodeGOD/R3nzSkin#1033]
Hey, can anyone post new CharacterDataStack? So far nobody posted it on unknowncheats.

**Comment by R3nzTheCodeGOD** [comment]
CharacterDataStack pattern should already working.

**Comment by Longweii** [comment]
So what should I be looking for to update then?

**Comment by R3nzTheCodeGOD** [comment]
Just wait a bit I'll release the update soon.

**Comment by R3nzTheCodeGOD** [comment]
1de72084f64e2c39a63a71e5abd7f3103f9421e3 should work now
