### ISSUE TITLE
does this support on Mac?

### ISSUE THREAD

**Issue by xinranwangxwan559** [R3nzTheCodeGOD/R3nzSkin#1034]
I am using Mac OS and I cannot configure this guI. Does anyone know how to set up on Mac?

**Comment by 15805658608** [comment]
You can try to compile this project on Mac. 😊

**Comment by xinranwangxwan559** [comment]
> You can try to compile this project on Mac. 😊

Hi there, could you teach me how to compile this?

**Comment by hotline1337** [comment]
No, and it's not coded for it, if you want to use it you better find an alternative or rewrite the source code from scratch
