### ISSUE TITLE
Exe not opening

### ISSUE THREAD

**Issue by Burittoxd** [R3nzTheCodeGOD/R3nzSkin#1037]
When I try to open the exe file this shows up 
![image_2024-01-26_124651550](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/109846695/e53104b6-1a9f-413e-938f-af3fe33616a4)

**Comment by Gappy7** [comment]
Yeah got the same problem

**Comment by hotline1337** [comment]
What country are u from?

**Comment by Burittoxd** [comment]
> What country are u from?

I solved it its from the antivirus (turkey)
