### ISSUE TITLE
Cant inject dll

### ISSUE THREAD

**Issue by DarkSissi** [R3nzTheCodeGOD/R3nzSkin#1039]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/145767273/539a7491-7d9b-4934-9ed2-f1a7dd049709)

already use Borderless mode,CN Tencent Server

**Comment by SPECIALTIGER-007** [comment]
same

**Comment by hotline1337** [comment]
Afaik tencent uses some anti dll injection technique, try putting R3nzSkin.dll into the League Of Legends "Game" folder and name it hid.dll, maybe this will work.
