### ISSUE TITLE
it doesnt work with 12.8

### ISSUE THREAD

**Issue by plzfixthisfcknapp** [R3nzTheCodeGOD/R3nzSkin#104]
plz fix it it doesn't work with 12.8 patch

**Comment by R3nzTheCodeGOD** [comment]
Already working?

**Comment by plzfixthisfcknapp** [comment]
but im doing all the steps its not working im playing in tr btw can u help me

**Comment by DexyStorm** [comment]
same here. game just crashes on boot

**Comment by R3nzTheCodeGOD** [comment]
1. which server are you playing on ?
2. which operating system are you using ?

**Comment by senmao1994** [comment]
> 

In the win11 system, the Chinese server crashed
spectator mode

**Comment by senmao1994** [comment]
> 1. which server are you playing on ?
> 2. which operating system are you using ?

In the win11 system, the Chinese server crashed
spectator mode

**Comment by senmao1994** [comment]
> 1. which server are you playing on ?
> 2. which operating system are you using ?

In Windows 11, the Chinese server crashed
very strange，it was OK yesterday

**Comment by DexyStorm** [comment]
1 EUW
2 Windows 11

**Comment by plzfixthisfcknapp** [comment]
1. TR
2. Windows 10 it was working before 1 week but it is not working for 3 days
