### ISSUE TITLE
Trojan:Win32/Formbook!ml

### ISSUE THREAD

**Issue by missjudy** [R3nzTheCodeGOD/R3nzSkin#1041]
Detected in R3nzSkin_Injector.exe. Whilst this may well be a false positive, the alert of virus="FormBook" is a serious concern. What part of the program could trigger a false positive of this kind?

**Comment by renzynx** [comment]
bro the source is there just go and learn c++ and find out?

**Comment by missjudy** [comment]
> bro the source is there just go and learn c++ and find out?

The issues section was created so that people can solve your doubts. If you're a fucking retarded moronic incel you shouldn't comment.

**Comment by bmwx6comp** [comment]
He literally gave you a reasonable answer, what is your concern? You basically have all the source, give some details about your trojan mate

**Comment by missjudy** [comment]
> He literally gave you a reasonable answer, what is your concern? You basically have all the source, give some details about your trojan mate

"Hello doctor I have this symptom what could it be?

- Go study Medicine and find out lol"

Reasonable answer

**Comment by johnnrails** [comment]
When I need a house I plan to study architecture and engineering to build it, then I'll learn computing to learn how to build my own computer too, then I'll learn more about C++ just to understand the source code and solve your problem.

**Comment by missjudy** [comment]
> When I need a house I plan to study architecture and engineering to build it, then I'll learn computing to learn how to build my own computer too, then I'll learn more about C++ just to understand the source code and solve your problem.

No need to. If you don't know the answer just shut up that's what everyone has always done

**Comment by hotline1337** [comment]
Anti-virus software falsely reports R3nzSkin as malicious because it uses specific Win32 APIs required for DLL injection or game memory scanning, which are features not commonly found in programs.
