### ISSUE TITLE
Lags and disconnection

### ISSUE THREAD

**Issue by Jaroslawx** [R3nzTheCodeGOD/R3nzSkin#1043]
Can skin changer cause lags and disconnections while playing game? Even if my internet connection is 100% working? Anyone have the same problem?

**Comment by fadedninna** [comment]
nope

**Comment by Jaroslawx** [comment]
Maybe problem is, that i have turned on before game start in lobby more times? So best way is to turn off, after game and turn back in next game?

**Comment by Jaroslawx** [comment]
I think, maybe porofessor and summoner spell board sync can be the problem i turned it off and turn on skinc when game start.

**Comment by hotline1337** [comment]
It might cause lags if your CPU/RAM cannot handle it. Consider upgrading your hardware or optimizing R3nzSkin on your own (compiler + linker optimization)
