### ISSUE TITLE
Concerns about Valorant accounts after using R3nzSkin

### ISSUE THREAD

**Issue by JiangYue2003** [R3nzTheCodeGOD/R3nzSkin#1044]
It is known that the R3nzSkin project is also valid on CN servers, can I ask if the residue after the dll file has been executed will be detected by Valorant's anti-cheat system 'Vanguard' and defined as an illegal programme? I'm playing both League and Valorant at the same time, and I'm worried that using it will affect my Valorant account.
  :)

**Comment by hotline1337** [comment]
As far as League Of Legends doesn't implement Vanguard you are safe to use it, when Vanguard will come you won't be even able to inject R3nzSkin too. So you are fine anyways.

**Comment by JiangYue2003** [comment]
Good news! Now I can tour Valorant without worrying while using Skin, thanks!
