### ISSUE TITLE
I cannot download the zip

### ISSUE THREAD

**Issue by Dinmar9** [R3nzTheCodeGOD/R3nzSkin#1046]
![Screenshot_1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/131899108/20a67228-39c8-4235-96a5-7a95f18af3e5)

It says to check connection to the internet but I have connection and I tried to download something else it works perfectly. I also tried to download the zip from other browser, but still it doesn't work.

**Comment by wlr3r** [comment]
ctrl+J and trust this file

**Comment by hotline1337** [comment]
disable your antivirus
