### ISSUE TITLE
我是中国玩家，R3NZ 2024年确定不支持了吗？

### ISSUE THREAD

**Issue by JunePapa** [R3nzTheCodeGOD/R3nzSkin#1047]
作者，你好，我是一位中国玩家，对你很钦佩，因为你在当兵的同时还能开发出这款插件，不知道你现在是否服兵役结束。这块软件真的如你的公告所言2024年不再更新了吗？

**Comment by JunePapa** [comment]
更新

**Comment by hotline1337** [comment]
it is true that when vanguard comes r3nzskin will unfortunately be no longer supported

**Comment by safeqwafsd** [comment]
现在用不了了吗

**Comment by JunePapa** [comment]
没有 还可以用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月5日(周五) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [R3nzTheCodeGOD/R3nzSkin] 我是中国玩家，R3NZ 2024年确定不支持了吗？ (Issue #1047)




 
现在用不了了吗
