### ISSUE TITLE
R3nz skin could be saved.

### ISSUE THREAD

**Issue by QiyanuReeves** [R3nzTheCodeGOD/R3nzSkin#1051]
R3nz skin could be saved riot released an article saying that only 1% of something will get affected to there might be a chance for R3nz. I got the info from Mattylovesgaming latest video.

**Comment by PwccaCode** [comment]
bro an internal injection will never not get detected by vanguard.

You will very likely get banned for messing with the game memory.
support will very likely end at patch 14.5

**Comment by hotline1337** [comment]
> bro an internal injection will never not get detected by vanguard.
> 
> You will very likely get banned for messing with the game memory. support will very likely end at patch 14.5

You are wrong.

Vanguard won't even let you inject when it gets implemented to League Of Legends. You are safe.
