### ISSUE TITLE
Windows defender flagged it Win32/Znyonm

### ISSUE THREAD

**Issue by MrTsud0** [R3nzTheCodeGOD/R3nzSkin#1055]

**Comment by MrTsud0** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/101712568/f13f14ca-a9c9-4cbe-9b4c-0e23d975d902)

**Comment by MrTsud0** [comment]
No matter how many times i scan and remove or quarantine this detection it always show up again and again XD what is this? and its always Active even i already deleted all the components of R3nzskin
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/101712568/357b5979-d848-412e-b9d3-b97b902efeb2)
it has a file named drRLpoN8.exe, but i cant see it in my folder even i enable the hidden files? please explain it to me before closing this!

**Comment by hotline1337** [comment]
Anti-virus software falsely reports R3nzSkin as malicious because it uses specific Win32 APIs required for DLL injection or game memory scanning, which are features not commonly found in programs.
