### ISSUE TITLE
R3nzSkin not opening 

### ISSUE THREAD

**Issue by Coronelxd0** [R3nzTheCodeGOD/R3nzSkin#1057]
Hello ! I downloaded the files and put them inside the game directory but it seems that when I try to open the injector it shows nothing , and dosen't open. Yes I have it to open on administrator,turned off the windows defender, but still no luck. Can anybody help me ?

**Comment by Pierreluc14** [comment]
On google write microsoft visual c++ click the first link and install all x64 x86 of Microsoft Visual C++ Redistributable from 2022 to 2008.

**Comment by Coronelxd0** [comment]
I installed all of them ,still dosen't open.

**Comment by Pierreluc14** [comment]
You are on windows 10 or windows 11 ?

**Comment by Coronelxd0** [comment]
Windows 11

**Comment by Coronelxd0** [comment]
Windows 11

**Comment by Pierreluc14** [comment]
Vanguard will release in all server in 14.6 or highter not vory long before R3nzSkin no longer work anyway.

**Comment by hotline1337** [comment]
disable your antivirus, download .net framework 4.8+, and c++ redistributable 2022 x64
