### ISSUE TITLE
I had multiple trojans on my pc and my friends pc after downloading this

### ISSUE THREAD

**Issue by TrojanBuster907** [R3nzTheCodeGOD/R3nzSkin#1058]
be extra careful when downloading this, best decision would be to not download it at all, I had 80+ so did my friend and I made sure it wasn't anything else I downloaded.

**Comment by Pierreluc14** [comment]
False postitive and I tested the apps it work correctly and do not have any virus.

**Comment by sansbruhgaming** [comment]
Bro's name is "TrojanBuster907" 😭😭😭😭😭

**Comment by ywwa** [comment]
> Joined GitHub `4 days ago`

**Comment by camus57** [comment]
"Joined 5 days ago" , why did you do that?

**Comment by hotline1337** [comment]
Make sure to download R3nzSkin ONLY from the github repository, as links distributed anywhere else may be malicious./
