### ISSUE TITLE
crushed

### ISSUE THREAD

**Issue by uzcre** [R3nzTheCodeGOD/R3nzSkin#106]
closes game when injected and said fail to find pattern im waiting for update bcoz it patched 12.9 today in jp

**Comment by R3nzTheCodeGOD** [comment]
6b43a81ab1bfd449abd9874541bebb5d0d53d0e0

Btw, I'm on the TR server and I didn't get a failed to find pattern error. If you keep getting pattern not found error send the pattern to me

**Comment by uzcre** [comment]
its fixed !!! ty!!!!!!!!! <3
