### ISSUE TITLE
Vanguard

### ISSUE THREAD

**Issue by Jaroslawx** [R3nzTheCodeGOD/R3nzSkin#1062]
Next patch vanguar on Phillipines? So will be updates with next patches for other servers?
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/77592125/9323681a-c0ec-4b92-9330-84e8f6a15f63)

**Comment by Pierreluc14** [comment]
Unfortunately you will have to wait for 14.6 patch notes

**Comment by Pierreluc14** [comment]
You will need to wait for patch notes 14.5

**Comment by hotline1337** [comment]
suppose that's a good news, the longer they take to introduce vanguard globally the more r3nzskin has time left ;d

**Comment by Pierreluc14** [comment]
> suppose that's a good news, the longer they take to introduce vanguard globally the more r3nzskin has time left ;d

Vanguard will release in April for all regions https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s

**Comment by Pierreluc14** [comment]
> suppose that's a good news, the longer they take to introduce vanguard globally the more r3nzskin has time left ;d

Vanguard will release in April for all regions https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s

**Comment by Pierreluc14** [comment]
> suppose that's a good news, the longer they take to introduce vanguard globally the more r3nzskin has time left ;d

Vanguard will release in april for all regions https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s
