### ISSUE TITLE
Got banned by third party applications

### ISSUE THREAD

**Issue by GuiSaiUwU** [R3nzTheCodeGOD/R3nzSkin#1066]
Server: Brazil
My alt account that I was used to play with R3nzSkin got banned by third party applications, I sent a ticket over to riot, saying that I never used any 3rd party app (trying to lie ofc) the ticket said to wait 3-4 days investigation to see if it was a proprely ban and if it wasnt they would contact me, now has been 23 days since I got that reply... so yes, banned, atleast it wasnt in my main account <3 😔
proof of the ticket (in portuguese ofc bcs I play here in Brazil)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/107002177/fe85ef35-534a-4afb-8c77-9f4143afeb69)

**Comment by Romantikc** [comment]
same

**Comment by Pierreluc14** [comment]
Amywahy likely R3nzSkin is likely to no longer work in all server because of Vanguard.

**Comment by Pierreluc14** [comment]
This not change much because 14.5 is likely the last patch R3nzSkin will work in all server.

**Comment by jaejangg** [comment]
thank god i didnt play a match yet

**Comment by Pierreluc14** [comment]
> thank god i didnt play a match yet

This no change much R3nzSkin will is likely to no longer work in 14.6 in all server because of Vangauard.

**Comment by dzopix** [comment]
did u buy the account?

**Comment by hotline1337** [comment]
R3nzSkin is safe. You probably bought a botted account.

**Comment by GuiSaiUwU** [comment]
I haven't, this account I made because I got inspired by an OTP aurelion sol (the acc name is Aurelion101), I level up and played it as any other person, I even have another alt account named Aurelion102

**Comment by Romantikc** [comment]
> R3nzSkin is safe. You probably bought a botted account.

yep, my bad, support answer day after, banned bcs of botted acc
