### ISSUE TITLE
Battle queen katarina

### ISSUE THREAD

**Issue by uuhudd** [R3nzTheCodeGOD/R3nzSkin#1068]
When i choose the battle quenn katarina,the daggers and effects goes forever,and when i choose a different skin,the effects doesnt change,its stay on battle quenn katarina,please fix it.

**Comment by Pierreluc14** [comment]
Unlikely a fix because of Vanguard coming likely in all server in 14.6

**Comment by Pierreluc14** [comment]
Known bug https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1019 and with Vangaird coming soon likely in all server in 14.6 a fix is unlikely.

**Comment by Pierreluc14** [comment]
Known bug https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1019 and with Vanguard coming soon likely in all server in 14.6 a fix is unlikely.

**Comment by hotline1337** [comment]
#1
