### ISSUE TITLE
Still crashes on EUW.

### ISSUE THREAD

**Issue by Salim-Bek** [R3nzTheCodeGOD/R3nzSkin#107]
So i reinstalled the league client as people mentioned to fix the crash after injection (Start)
i used the new version from 2 hours ago , it only worked for one game.

**Comment by alphaaced** [comment]
Try reinstalling the zip file.

**Comment by Salim-Bek** [comment]
> Try reinstalling the zip file.

Tried that hundred times dosen't work . what actually worked for me is deleting  the R3NZSKIN.json file on Riot Games /League of legends / Game .

**Comment by 04255** [comment]
> > 请尝试重新安装 zip 文件。
> 
> 尝试了一百次不起作用。真正对我有用的是删除Riot Games /League of Legends / Game上的R3NZSKIN.json文件。

yeah, it work .
fck json clash

**Comment by R3nzTheCodeGOD** [comment]
If you haven't deleted R3nzSkin.json from the recycle bin, can you send it to me? I want to examine it.

**Comment by 04255** [comment]
> If you haven't deleted R3nzSkin.json from the recycle bin, can you send it to me? I want to examine it.

I got it back from the recycle bin.How can I send it to you?
I don't even know how to read its contents " .json"

**Comment by 04255** [comment]
[Uploading R3nzSkin.zip…]()

**Comment by 04255** [comment]
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/8741860/R3nzSkin.zip)
