### ISSUE TITLE
Bros. The 14.5 version update, what server did Vanguard test on?

### ISSUE THREAD

**Issue by makabaka2869** [R3nzTheCodeGOD/R3nzSkin#1072]
Bros. The 14.5 version update, what server did Vanguard test on?

**Comment by notyourgrandpa** [comment]
We have one on Ph server

**Comment by Miessen** [comment]
did you try it yet?

**Comment by makabaka2869** [comment]
> 我们在 Ph 服务器上有一个
> 
> 编辑：自更新以来仍然没有尝试过modskin

Can the Philippine server, can the new version use R3 normally? Is Vanguard online?

**Comment by mmotkim** [comment]
VN server not working, 403 error code

**Comment by Pierreluc15** [comment]
In the philppine for testing but in all server in april
