### ISSUE TITLE
falta de arquivo

### ISSUE THREAD

**Issue by PATOLORDX** [R3nzTheCodeGOD/R3nzSkin#1076]
![Captura de tela 2024-03-09 134040](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/162501130/09e9274c-4993-4de4-ac92-a056825f1696)
![Captura de tela 2024-03-09 134119](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/162501130/027d8efe-54c7-46df-bd58-428aed345428)
QUANDO INSTALO É ABRO DIZ QUE FALATA ´´MSVCP140.dll nao foi encontrado. ´´ é ´´VCRUNTIME140.dll nao foi encontrado. apos isso nao abre nada mesmo baixando muitas vezes

**Comment by Pierreluc15** [comment]
https://learn.microsoft.com/pt-pt/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by PATOLORDX** [comment]
MUITO OBRIGADO, FUNCIONOL AQUI :D
