### ISSUE TITLE
Trojan virus?

### ISSUE THREAD

**Issue by puppybrained** [R3nzTheCodeGOD/R3nzSkin#1077]
There are a lot of people saying this has a virus and that their accounts were hacked. Is this true? Has anyone been using it on their main account for a long time without getting their info stolen?

**Comment by WGPL777** [comment]
uses it since near two years, never had any problem with someone getting into my account, even if just turn on two-step verification and u should be fine even if something leak ur data

**Comment by Pierreluc15** [comment]
Not virus on R3nzSkin

**Comment by puppybrained** [comment]
and is it banable at all?

**Comment by WGPL777** [comment]
yk, it should be safe until VANGUARD will come out on all servers (for now its on philipines but ppls said it got again delayed but I didn't checked) so ig until vanguard won't come out ur safe to use, but I don't really use it rn since maybe riot collect some kind of data before and flags accounts who use it rn but its just my tought, so at all ur safe to use before vanguard comes out

**Comment by Pierreluc15** [comment]
> yk, it should be safe until VANGUARD will come out on all servers (for now its on philipines but ppls said it got again delayed but I didn't checked) so ig until vanguard won't come out ur safe to use, but I don't really use it rn since maybe riot collect some kind of data before and flags accounts who use it rn but its just my tought, so at all ur safe to use before vanguard comes out

On all server in april 

https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s

**Comment by Pierreluc15** [comment]
> yk, it should be safe until VANGUARD will come out on all servers (for now its on philipines but ppls said it got again delayed but I didn't checked) so ig until vanguard won't come out ur safe to use, but I don't really use it rn since maybe riot collect some kind of data before and flags accounts who use it rn but its just my tought, so at all ur safe to use before vanguard comes out

On all server in april https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s
