### ISSUE TITLE
腾讯代理的英雄联盟短时间不会引入Vanguard反作弊，还可以继续使用吗The League of Legends represented by Tencent will not introduce Vanguard anti-cheating for a short time. Can it continue to be used?

### ISSUE THREAD

**Issue by Xzz2194588563** [R3nzTheCodeGOD/R3nzSkin#1083]
The League of Legends represented by Tencent will not introduce Vanguard anti-cheating for a short time. Can it continue to be used?腾讯代理的英雄联盟短时间不会引入Vanguard反作弊，还可以继续使用吗

**Comment by Pierreluc15** [comment]
R3nzSkin Will no longer work in april 2024 the info from https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s

**Comment by Pierreluc15** [comment]
Tencent in Valorant not use Vanguard why it will use it in league of legends ?

**Comment by Pierreluc15** [comment]
Only Riot region will have Vanguard.

**Comment by Pierreluc15** [comment]
Read the announcement R3nzSkin will no longer be supported by 2024 due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by ez4s1mple1943** [comment]
请问这是那里的消息？我看到的消息是4月所有区服都会上线Vanguard

**Comment by xhr2** [comment]
腾讯的Vanguard和TP合并了，WeGame有公告

**Comment by hotline1337** [comment]
yes, i guess.

**Comment by safeqwafsd** [comment]
腾讯代理的怎么用这个换肤啊
