### ISSUE TITLE
R3nzSkin

### ISSUE THREAD

**Issue by AJoKeRK** [R3nzTheCodeGOD/R3nzSkin#1086]
when is the next update coming ? cause there is an issue with the skin changer :
failed to find pattern 48 8b 0d

**Comment by CountryballsQer** [comment]
> when is the next update coming ? cause there is an issue with the skin changer : failed to find pattern 48 8b 0d

Same bro same and again

**Comment by ProgrammingDump** [comment]
they will release a new version for patch 14.6 be patient

**Comment by SekiSR76** [comment]
my champions do no dmg without the skins

**Comment by Pierreluc16** [comment]
> my champions do no dmg without the skins

Not true because it just a skin

**Comment by SekiSR76** [comment]
> it

nah, don't be so serious about it, just joking

**Comment by SekiSR76** [comment]
> > my champions do no dmg without the skins
> 
> It not true when you said do no dmg without the skins because it just a skin it not affect the gameplay. In game only you can see you use R3nzSkin.

nah, don't be so serious about it, just joking

**Comment by KomariVGC** [comment]
Tencent servers have not been tested yet

**Comment by KomariVGC** [comment]
Tencent servers have not been tested yet
