### ISSUE TITLE
14.6 UPDATED SIGS:

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#1087]
CharacterDataStack - 48 8D 8A ? ? ? ? 4D 8B E0

CharacterDataStack__Push - E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0

**Comment by Visusline** [comment]
How did you manage to obtain them? I am in the outbound part but I can't get the correct address location and then sign it.

**Comment by TraxYzq** [comment]
> CharacterDataStack - 48 8D 8A ? ? ? ? 4D 8B E0
> 
> CharacterDataStack__Push - E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0

Can you could put this in a file? so that people can install the skin changer because there are some ppl who do not know how to put this in the content of the skin changer file. ty

**Comment by Visusline** [comment]
![ChinaServer](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/163219488/ae3baad5-902a-4889-b0c4-cdeac6e03a14)
change to .7zip

**Comment by malvadeza777** [comment]
@Visusline what?

**Comment by Tommychanwh** [comment]
> CharacterDataStack - 48 8D 8A ? ? ? ? 4D 8B E0
> 
> CharacterDataStack__Push - E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0

how to check this after update?plz let me know ,next time i can change this by my self thanks

**Comment by creatineabuser** [comment]
@Visusline can't build project with new offsets fsr. Did u try to build it?

**Comment by Visusline** [comment]
> @Visusline can't build project with new offsets fsr. Did u try to build it?

working

**Comment by malvadeza777** [comment]
download file plz

**Comment by AidanXu** [comment]
download visual studio 2022, update the sigs in memory.hpp based on the commit then rebuild
