### ISSUE TITLE
R3nzSkin 14.6 update 

### ISSUE THREAD

**Issue by creatineabuser** [R3nzTheCodeGOD/R3nzSkin#1089]
Updated version of R3nzSkin (for 14.6) 
[R3nzSkinUpdate14.6.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/14676247/R3nzSkinUpdate14.6.zip)

**Comment by shadinz** [comment]
it works, ty

**Comment by malvadeza777** [comment]
THNKS BRO

**Comment by Nixo81** [comment]
god bless you

**Comment by SWAM1010** [comment]
why when I download it I get that it cannot be opened because it is empty, any help please?

**Comment by caerizu** [comment]
> why when I download it I get that it cannot be opened because it is empty, any help please?

Disable antivirus maybe

**Comment by SWAM1010** [comment]
> > why when I download it I get that it cannot be opened because it is empty, any help please?
> 
> Disable antivirus maybe

i did but not works

**Comment by tommysebastien** [comment]
> why when I download it I get that it cannot be opened because it is empty, any help please?

Use a different zip file opener. The windows one don’t work for me.

**Comment by KomariVGC** [comment]
> 
> why when I download it I get that it cannot be opened because it is empty, any help please?
close windows defender

**Comment by KomariVGC** [comment]
> 
> why when I download it I get that it cannot be opened because it is empty, any help please?

close windows defender

**Comment by PartidaPasmado** [comment]
where did you get this?

**Comment by Xzz2194588563** [comment]
nice

**Comment by liliyucai123** [comment]
how to use it in china

**Comment by Xzz2194588563** [comment]
把那个dll文件直接复制到英雄联盟的game文件夹内。[

> 如何在中国使用它

Copy that dll file directly into the game folder of League of Legends.

**Comment by Crocordeil** [comment]
good bro, thanks
