### ISSUE TITLE
Viruses 

### ISSUE THREAD

**Issue by akDKi1saf** [R3nzTheCodeGOD/R3nzSkin#1092]
Virustotal used to have little red flags but now there are at least 30 red flags. Do not download

**Comment by PetjaPaivarinta** [comment]
nah

**Comment by polypores** [comment]
I only trust Kaspersky 😂
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/50510627/825e4062-169d-4d34-a0d6-c47476f050a6)
