### ISSUE TITLE
failed to find pattern id: 8D 8E ? ? ? ? FF 74 24 4C

### ISSUE THREAD

**Issue by xxtarlit** [R3nzTheCodeGOD/R3nzSkin#1093]
need update cuz of 14.7 patch

**Comment by Player-221** [comment]
![$K1TQWP(8`A@GL`C%C$ )5P](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/81342434/80225af6-c75c-4915-a758-6bd7a741682b)
what should i do

**Comment by liliyucai123** [comment]
怎么更新

**Comment by liliyucai123** [comment]
how to update
