### ISSUE TITLE
Can you teach me how to modify the offset myself?

### ISSUE THREAD

**Issue by hansaes** [R3nzTheCodeGOD/R3nzSkin#1096]
Can you teach me how to modify the offset myself?

**Comment by caerizu** [comment]
Get baseults offset dumper, open R3nzskin sourcefile find memory.hpp file and get the pattern for the offsets you wanna update then go into a league game and use the offset dumper and get the offsets after that watch these and learn. 
For getting new signatures or patterns: https://www.youtube.com/watch?v=wTk6iDzv15Q&t=1418s
This for undetected cheatengine: https://www.youtube.com/watch?v=_auePp1nTHs&t=843s
Offset dumper tutorial: https://www.youtube.com/watch?v=L2jSwq0HJPM
