### ISSUE TITLE
valorant vanguard

### ISSUE THREAD

**Issue by erikdu** [R3nzTheCodeGOD/R3nzSkin#1097]
if i install valorant, will i be banned for it's vanguard?

**Comment by sshindae** [comment]
There are some delays with the implementation of Vanguard, so until they announce it in the patch notes that the Vanguard will be active - we should be fine.

**Comment by Pierreluc20** [comment]
Confirmed R3nzSkin is broken on PBE it not inject 
![R3nzSkin on PBE](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166042133/d262ebd4-a21d-4e6d-8c04-764d66110907)

**Comment by Pierreluc20** [comment]
Unlikely you will be bannned because from testing have Vanguard run in background on live server R3nzSkin work fine but on PBE who Vanguard is implemented R3nzSkin do not inject.

**Comment by PaulOliquino** [comment]
I think R3nzSkin causes bans now, not sure, just got banned today.

**Comment by Pierreluc20** [comment]
> I think R3nzSkin causes bans now, not sure, just got banned today.

Anyway will stop working for good soon 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166042133/bf1dc24c-5091-47ed-9cbc-03e8defb9978)

R3nzSkin on PBE 14.8

**Comment by Pierreluc21** [comment]
R3nzSkin will no longer work on patch 14.9 Hey there, Our first target date is Patch 14.8 for the Philippines. We'll be making sure everything is working properly there, and then we'll roll out to the rest of our Riot regions in Patch 14.9.
