### ISSUE TITLE
how to install the skin changer?

### ISSUE THREAD

**Issue by LarryHex123** [R3nzTheCodeGOD/R3nzSkin#1098]
Hi, I don' t know how to install this skin changer. There is no R3nzSkin_Injector.exe in the zip. How to do it?

**Comment by Pierreluc20** [comment]
It was deleted by your antivirus or windows defender.

**Comment by LarryHex123** [comment]
I cannot find the exe on the website.
![微信图片_20240404204747](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/163754655/d5851dc0-34bb-424e-bce8-f93602f25409)

**Comment by Pierreluc20** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/releases

**Comment by LarryHex123** [comment]
Thank you! I did it!

**Comment by safeqwafsd** [comment]
How do we solve the last one? R3nzskin status reality Not injected

**Comment by Pierreluc20** [comment]
> How do we solve the last one? R3nzskin status reality Not injected

From what server ?

**Comment by safeqwafsd** [comment]
> > 我们如何解决最后一个问题？R3nzskin 状态现实 未注入
> 
> 从什么服务器？

R3nzskin_injector.exe opens and the fourth menu says Not injected

**Comment by Pierreluc20** [comment]
> > > 我们如何解决最后一个问题？R3nzskin 状态现实 未注入
> > 
> > 
> > 从什么服务器？
> 
> R3nzskin_injector.exe opens and the fourth menu says Not injected

You try to inject on PBE or Live server ?

**Comment by safeqwafsd** [comment]
> > > > 我们如何解决最后一个问题？R3nzskin 状态现实 未注入
> > > 
> > > 
> > > 从什么服务器？
> > 
> > 
> > R3nzskin_injector.exe打开，第四个菜单显示未注入
> 
> 您尝试在 PBE 或 Live 服务器上注入？
Unfortunately, I will not, whether it is because I am Tencent agent lol?
