### ISSUE TITLE
guys if i use skin changer do i get perma banned from riot vanguard?for third party program

### ISSUE THREAD

**Issue by lxZio** [R3nzTheCodeGOD/R3nzSkin#1099]
guys if i use skin changer do i get perma banned from riot vanguard?for third party program

**Comment by Pierreluc20** [comment]
Unlikely you will get banned because when Vanguard will global release R3nzSkin will be broken for good it will not inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166042133/e11611a8-23a9-4f76-9b53-6c64753d200e)

**Comment by Pierreluc20** [comment]
Unlikely you will be bannned because from testing have Vanguard run in background on live server R3nzSkin work fine but on PBE who is implemented R3nzSkin do not inject.

**Comment by Secr3ts** [comment]
nobody knows vanguard isn't on LoL yet, but probably yes once it will be rolled out

**Comment by adilyx** [comment]
@Secr3ts do you know when vanguard will be in the game ? i dont find any info on this
