### ISSUE TITLE
Battle queen katarina

### ISSUE THREAD

**Issue by Kataenjoyer** [R3nzTheCodeGOD/R3nzSkin#110]
Can you fix the daggers of battle queen katarina it doesnt works :(

**Comment by alphaaced** [comment]
#1

**Comment by Kataenjoyer** [comment]
i dont underqtand i can fix the skin by myself but how ?

**Comment by alphaaced** [comment]
you cant fix the sins. Some characters have certain server sided animations that skin changers cant access.
