### ISSUE TITLE
R3NZSKIN ERROR

### ISSUE THREAD

**Issue by Abdullah2332** [R3nzTheCodeGOD/R3nzSkin#1100]
What is the Problem here ?
anyone has a solution

![64](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/111985248/56f24c4d-f756-43fe-89c4-455419d71ac2)

**Comment by Pierreluc20** [comment]
Open it in plane mode without internet.

**Comment by Abdullah2332** [comment]
i dont know it got fixed from alone .

**Comment by Abdullah2332** [comment]
sad
