### ISSUE TITLE
What should I do if my ui is confused

### ISSUE THREAD

**Issue by awei0929** [R3nzTheCodeGOD/R3nzSkin#1101]
![924B782C5D6AA5CAB8C1B995BBA2B1BA](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/76504578/5eadbded-cae0-41bd-bcb5-d30e8789f156)
Changed the shortcut keys for the skin。So it's like this。I've been trying to find his "config" but I can't

**Comment by awei0929** [comment]
I have tried to fix the game file. And uninstalling the entire game didn't help either

**Comment by awei0929** [comment]
This yellow one is' R3nz ', and my new shortcut keys still work. But it's still the case after many attempts. And two versions in a row are like this. I think it's a configuration file problem

**Comment by awei0929** [comment]
Go to documents->R3nzSkin and delete the file named R3nzSkin64. How can I find this file, please。

**Comment by Pierreluc20** [comment]
Try to delete R3nzSkin folder.

**Comment by awei0929** [comment]
try delete c:\user\yourusername\Documents\R3nzSkin this folder。I found the answer in other Issues. But I'm working right now, so I think we can sort this out when I get back from work
