### ISSUE TITLE
Failed to find r3nzSkin.dll in the current directory - injector.autoUpdate0

### ISSUE THREAD

**Issue by HideInCringe** [R3nzTheCodeGOD/R3nzSkin#1102]
Hi, could you help me with this problem please? I understand absolutely nothing about this)
![m7l8MlaE9V0](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166364820/ac8551c2-6efd-4bf6-803e-83aed061d788)

**Comment by Pierreluc20** [comment]
Put the DLL on the desktop.

**Comment by EzraelP** [comment]
ive came to that same problem any solution?
