### ISSUE TITLE
When i open file and i click START  my client close instant someone know why ?

### ISSUE THREAD

**Issue by KNOXDOL** [R3nzTheCodeGOD/R3nzSkin#1103]

**Comment by Pierreluc20** [comment]
No and R3nzSkin will stop working soon anyway from 14.8 PBE it not longer inject because of Vanguard 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166042133/1fc2f759-6938-40eb-8fa9-88a4537b3d39)
R3nzSkin will not work past April or May.

**Comment by Pierreluc21** [comment]
Not worth to fix it R3nzSkin will no longer work on patch 14.9 Hey there, Our first target date is Patch 14.8 for the Philippines. We'll be making sure everything is working properly there, and then we'll roll out to the rest of our Riot regions in Patch 14.9.
