### ISSUE TITLE
Stuttering\micro-lagging on recent patch 

### ISSUE THREAD

**Issue by silentiumbravo** [R3nzTheCodeGOD/R3nzSkin#1104]
After the last update, while in game, the mouse freezes for 1-2 seconds, repeating every 5-10 sec. I still can use skills , but the mouse lags and the camera shots to the map's edges. 
The same error continues even after I turn the injector on\off, only the pc restarting helps.

**Comment by Pierreluc20** [comment]
R3nzSkin will stop working soon anyway from 14.8 PBE it not longer inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166042133/9ba3cd0b-8609-4384-ba41-3ce9071073ea)

**Comment by Pierreluc21** [comment]
Not worth to fix it R3nzSkin will no longer work on patch 14.9 Hey there, Our first target date is Patch 14.8 for the Philippines. We'll be making sure everything is working properly there, and then we'll roll out to the rest of our Riot regions in Patch 14.9.
