### ISSUE TITLE
Will this software be safe to use after the implementation of Vanguard a few days ago?

### ISSUE THREAD

**Issue by PaulOliquino** [R3nzTheCodeGOD/R3nzSkin#1105]
Vanguard has recently been placed into the game, I recently got a permanent suspension but it wasn't due to the skinchanger, I made an appeal and Riot support team said it was due to unauthorized access on my account. I just want to make sure that this software can still be used even with Vanguard, thanks in advanced!

**Comment by Pierreluc21** [comment]
Vanguard is only on PBE for now since 28 March 
![IMG_0059](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/166627122/82b995a0-b66b-4225-a022-c91e2dae4aeb)

**Comment by Pierreluc21** [comment]
R3nzSkin will end on patch 14.9 Hey there,

Our first target date is Patch 14.8 for the Philippines. We'll be making sure everything is working properly there, and then we'll roll out to the rest of our Riot regions in Patch 14.9.

**Comment by Pierreluc21** [comment]
The league of legends tweet about Vanguard coming https://twitter.com/LeagueOfLegends/status/1778470780596334629?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet%7Ctwtr%5Etrue
And from Riot comment on Reddit Hey there,Our first target date is Patch 14.8 for the Philippines. We'll be making sure everything is working properly there, and then we'll roll out to the rest of our Riot regions in Patch 14.9

**Comment by Pierreluc22** [comment]
> Sure as hell no it won't be, it's literally written on the main repo.

It will just not inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/5642617b-226e-48f8-9fd7-bbe07cc6eee4)
