### ISSUE TITLE
patch 14.8 added vanguard to ph server, I am worried that it is not working anymore due to vanguard or just because its new patch

### ISSUE THREAD

**Issue by mish20011** [R3nzTheCodeGOD/R3nzSkin#1106]

**Comment by Pierreluc22** [comment]
> its still working with me

On PH server no.

**Comment by Leang1906** [comment]
> its still working with me

 it is not working for me every time new patch coming up.

**Comment by Pierreluc22** [comment]
> > its still working with me
> 
> it is not working for me every time new patch coming up.

It work on 14.8 without update.

**Comment by Rakkagg** [comment]
NOT WORKING ANYMORE

**Comment by Pierreluc22** [comment]
> NOT WORKING ANYMORE

Only in PBE and PH server for now will be global release next week. 
![IMG_0194](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/fcce2066-7d33-4172-b26c-ebab8bc97f06)
