### ISSUE TITLE
Removing the R3nzSkin 

### ISSUE THREAD

**Issue by WueeM** [R3nzTheCodeGOD/R3nzSkin#1107]
How do i remove the skin changer completely ? I don't want to get banned by vanguard :(

**Comment by Alixxx-please** [comment]
Just delete the folder it's in

**Comment by Pierreluc22** [comment]
> How do i remove the skin changer completely ? I don't want to get banned by vanguard :(

You will not get banned by Vanguard

**Comment by Fusorvanahil** [comment]
if you didnt reject in folders no problem you wont ban in the game

**Comment by Abdullah2332** [comment]
i am using it its working perfectly

**Comment by Pierreluc22** [comment]
> i am using it its working perfectly

Will not longer work in 14.9 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/6f6b306f-73be-4232-82af-90acd4af2a80)
![IMG_0166](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/cb139765-4af0-48a5-a52c-788855038277)

**Comment by Rakkagg** [comment]
NOT WORKING ANYMORE . WE NEED UPDATE FOR 14.8

**Comment by Pierreluc22** [comment]
> NOT WORKING ANYMORE . WE NEED UPDATE FOR 14.8

It work correctly without update.
