### ISSUE TITLE
Regarding the Chinese mainland version of LOL anti-cheat system

### ISSUE THREAD

**Issue by SLJ2000** [R3nzTheCodeGOD/R3nzSkin#1110]
The Chinese mainland version of LOL’s anti-cheating system uses Tencent Game Company’s TP anti-cheating system. It is uncertain whether Valorant’s anti-cheating system will be introduced. If the Chinese mainland version does not reference Valorant’s anti-cheating system, will the author Continue to update R3NZ?

**Comment by SLJ2000** [comment]
I started using R3NZ in 2022. I am very grateful to the author for his hard work and selfless dedication. Thank you very much!

**Comment by Pierreluc22** [comment]
> The Chinese mainland version of LOL’s anti-cheating system uses Tencent Game Company’s TP anti-cheating system. It is uncertain whether Valorant’s anti-cheating system will be introduced. If the Chinese mainland version does not reference Valorant’s anti-cheating system, will the author Continue to update R3NZ?

You forget if it continue to update R3nzSkin it will only work in chine.

**Comment by liubo0203** [comment]
期待中国继续的R3

**Comment by Pierreluc22** [comment]
> 期待中国继续的R3

他们不太可能继续只针对中国更新 R3nzSkin.

**Comment by liubo0203** [comment]
> > 期待中国继续的R3
> 
> 他们不太可能继续只针对中国更新 R3nzSkin.

我感觉也是 :(

**Comment by SLJ2000** [comment]
> > 期待中国继续的R3
> 
> 他们不太可能继续只针对中国更新 R3nzSkin.

那咋办嘛！没皮肤用，要死了

**Comment by SLJ2000** [comment]
> > 期待中国继续的R3
> 
> 他们不太可能继续只针对中国更新 R3nzSkin.

市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了

**Comment by Pierreluc22** [comment]
> 市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了

但由于 Vanguard 在 14.9 补丁中在全球发布，他们不太可能继续仅针对中国进行更新

**Comment by nitznic** [comment]
> > > 期待中国继续的R3
> > 
> > 
> > 他们不太可能继续只针对中国更新 R3nzSkin.
> 
> 市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了

自己更新呗，短期内改几个偏移就行，你都找到这了，这还是问题吗？

**Comment by SLJ2000** [comment]
> > > > 期待中国继续的R3
> > > 
> > > 
> > > 他们不太可能继续只针对中国更新 R3nzSkin.
> > 
> > 
> > 市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了
> 
> 自己更新呗，短期内改几个偏移就行，你都找到这了，这还是问题吗？

不会啊，改偏移量不懂，我只会使用

**Comment by makabaka2869** [comment]
> > > > 期待中国继续的R3
> > > 
> > > 
> > > 他们不太可能继续只针对中国更新 R3nzSkin.
> > 
> > 
> > 市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了
> 
> 自己更新呗，短期内改几个偏移就行，你都找到这了，这还是问题吗？
你会更新吗？如果可以的话我可以付费

**Comment by SLJ2000** [comment]
> > > > 期待中国继续的R3
> > > 
> > > 
> > > 他们不太可能继续只针对中国更新 R3nzSkin.
> > 
> > 
> > 市场上也没有可以平替的，都是R3NZ的换壳！源码还是R3NZ，难顶，没R3NZ都不会玩游戏了
> 
> 自己更新呗，短期内改几个偏移就行，你都找到这了，这还是问题吗？

确实，如果你会改，我可以有偿

**Comment by SLJ2000** [comment]
> > 确实，如果你会改，我可以有偿
> 
> 付费换肤你直接去淘宝买不就行了，国服还防封

淘宝那种不行的，必封的

**Comment by 70805** [comment]
> > > 确实，如果你会改，我可以有偿
> > 
> > 
> > 付费换肤你直接去淘宝买不就行了，国服还防封
> 
> 淘宝那种不行的，必封的

你可以联系我 Q70805 我可以教你更新
