### ISSUE TITLE
后续中国大陆LOL还会更新吗？

### ISSUE THREAD

**Issue by liubo0203** [R3nzTheCodeGOD/R3nzSkin#1111]
后续中国大陆LOL还会更新吗？因为现在中国LOL使用的是TP检测，现在还可以使用，后续会有分支以用来支持 中国服吗？

**Comment by Pierreluc22** [comment]
但由于 Vanguard 在 14.9 补丁中在全球发布，他们不太可能继续仅针对中国进行更新 
![IMG_0189](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/63543e4b-d328-4f25-aa59-954896048fc7)

**Comment by ceryyyy** [comment]
希望能更新吧，

**Comment by Pierreluc22** [comment]
> 希望能更新吧，

R3nzSkin 不太可能只针对中国更新，下周将不再更新 
![IMG_0205](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/e4e88901-31b2-4f72-8d88-2a4f0f710392)
