### ISSUE TITLE
Vanguard doesn't ban custom skins

### ISSUE THREAD

**Issue by caerizu** [R3nzTheCodeGOD/R3nzSkin#1112]
It seems runeforge has been testing with vanguard on ph server and they aren't being banned so what are the chances of R3nzSkin being banned?

**Comment by Pierreluc22** [comment]
> It seems runeforge has been testing with vanguard on ph server and they aren't being banned so what are the chances of R3nzSkin being banned?

It not inject R3nzSkin with Vanguard 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/970f71bf-d425-4ed0-8b1c-6f93d719d27f)

**Comment by caerizu** [comment]
> > It seems runeforge has been testing with vanguard on ph server and they aren't being banned so what are the chances of R3nzSkin being banned?
> 
> R3nzSkin will not inject Tested on PBE with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/167087019/325781532-970f71bf-d425-4ed0-8b1c-6f93d719d27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODY1NDcsIm5iZiI6MTcxNDE4NjI0NywicGF0aCI6Ii8xNjcwODcwMTkvMzI1NzgxNTMyLTk3MGY3MWJmLWQ0MjUtNGVkMC04YjFjLTZmOTNkNzE5ZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzY5OTAxNGE4NjFlZGQ3NmM3MTk1YzY0MDkxM2Q1ZmZkNTIwZDY3NDBhODM3NGNmMTc4ZDczZDczMDhjMTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N88ImHbty46HKxG9cY8MvDI4Ugtu22lmz3nzUpm4Zys)

you updated the offsets?

**Comment by Pierreluc22** [comment]
> > > It seems runeforge has been testing with vanguard on ph server and they aren't being banned so what are the chances of R3nzSkin being banned?
> > 
> > 
> > R3nzSkin will not inject Tested on PBE with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/167087019/325781532-970f71bf-d425-4ed0-8b1c-6f93d719d27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODY1NDcsIm5iZiI6MTcxNDE4NjI0NywicGF0aCI6Ii8xNjcwODcwMTkvMzI1NzgxNTMyLTk3MGY3MWJmLWQ0MjUtNGVkMC04YjFjLTZmOTNkNzE5ZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzY5OTAxNGE4NjFlZGQ3NmM3MTk1YzY0MDkxM2Q1ZmZkNTIwZDY3NDBhODM3NGNmMTc4ZDczZDczMDhjMTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N88ImHbty46HKxG9cY8MvDI4Ugtu22lmz3nzUpm4Zys)
> 
> you updated the offsets?

Vanguard prevent all injection without a Vanguard bypass tested with a script tool in PH server with Vanguard 
![IMG_0185](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/167087019/661ceee8-4e8d-430b-a271-4c2e7c47b39f)

**Comment by Pierreluc23** [comment]
> > > It seems runeforge has been testing with vanguard on ph server and they aren't being banned so what are the chances of R3nzSkin being banned?
> > 
> > 
> > R3nzSkin will not inject Tested on PBE with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/167087019/325781532-970f71bf-d425-4ed0-8b1c-6f93d719d27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODY1NDcsIm5iZiI6MTcxNDE4NjI0NywicGF0aCI6Ii8xNjcwODcwMTkvMzI1NzgxNTMyLTk3MGY3MWJmLWQ0MjUtNGVkMC04YjFjLTZmOTNkNzE5ZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzY5OTAxNGE4NjFlZGQ3NmM3MTk1YzY0MDkxM2Q1ZmZkNTIwZDY3NDBhODM3NGNmMTc4ZDczZDczMDhjMTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N88ImHbty46HKxG9cY8MvDI4Ugtu22lmz3nzUpm4Zys)
> 
> you updated the offsets?

R3nzSkin work on PBE when Vanguard is uninstalled this confirm for good it Vanguard who prevent R3nzSkin to work 
![IMG_0219](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/ec7fa797-85f5-404b-ba6a-a08c3a2a3695)
