### ISSUE TITLE
Where does R3NZ go from here?

### ISSUE THREAD

**Issue by Gary-zy** [R3nzTheCodeGOD/R3nzSkin#1113]
Hello author, Mainland China has introduced the TP system. Will you continue to update it? Or is it only updated specifically for mainland China?

**Comment by mish20011** [comment]
sadly they have stopped the update permanently after vanguard has been introduced, there could be a way to bypass vanguard for this but it might result in account getting perma banned

**Comment by Pierreluc23** [comment]
> Hello author, Mainland China has introduced the TP system. Will you continue to update it? Or is it only updated specifically for mainland China?

![IMG_0226](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/01bc6c3e-3961-4144-be86-f72a90ca3a82)
