### ISSUE TITLE
Is this the end of the R3nz Skin Changer ? 

### ISSUE THREAD

**Issue by AJoKeRK** [R3nzTheCodeGOD/R3nzSkin#1114]
are they gonna fix it or no anyone knows something about the issue ?

**Comment by Y1ke888** [comment]
same, not able to use at the moment I think due to update

**Comment by AJoKeRK** [comment]
> same, not able to use at the moment I think due to update

yes i think cause of the update i guess, lets hope they can fix it. we really need it.

**Comment by Pierreluc23** [comment]
> > same, not able to use at the moment I think due to update
> 
> yes i think cause of the update i guess, lets hope they can fix it. we really need it.

Unlikely a fix

**Comment by AJoKeRK** [comment]
> > > same, not able to use at the moment I think due to update
> > 
> > 
> > yes i think cause of the update i guess, lets hope they can fix it. we really need it.
> 
> Unlikely a fix read the announcement ![IMG_0241](https://private-user-images.githubusercontent.com/168309875/327108782-e716f3cf-adc7-4ae8-bc06-eee2a3eec9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjI3MTMsIm5iZiI6MTcxNDU2MjQxMywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3MTA4NzgyLWU3MTZmM2NmLWFkYzctNGFlOC1iYzA2LWVlZTJhM2VlYzllNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTIwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTZiMDU2NGUxMzFjYmVhZTNkYTA3ODI2NWY0YjQ3M2U4OWRhZDA4YjY3M2FjNTc0NjlkZTdkMWUyMzVmNTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92fd3tDgor_NUph1OK24eHv3hLDHUbi7YMNfNNe4w80) And read 14.9 patch notes ![IMG_0234](https://private-user-images.githubusercontent.com/168309875/327108907-0b5aa0d6-9e9b-4f9e-906a-37bfc3a09a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjI3MTMsIm5iZiI6MTcxNDU2MjQxMywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3MTA4OTA3LTBiNWFhMGQ2LTllOWItNGY5ZS05MDZhLTM3YmZjM2EwOWE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTIwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODliODExZWJjN2VjMWZiYjlkODVkOWRmNWFhMzc2NWJiNDY4MTI3MzkxMTk4YmFhMmE0MTI5YzBhM2Q5Mjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN1GbPZFeTIFVcKAZTmYXmDI9UcldSFki1lPpOPjv44)

so it's the End sadly ?

**Comment by Pierreluc23** [comment]
> > > > same, not able to use at the moment I think due to update
> > > 
> > > 
> > > yes i think cause of the update i guess, lets hope they can fix it. we really need it.
> > 
> > 
> > Unlikely a fix read the announcement ![IMG_0241](https://private-user-images.githubusercontent.com/168309875/327108782-e716f3cf-adc7-4ae8-bc06-eee2a3eec9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjI3MTMsIm5iZiI6MTcxNDU2MjQxMywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3MTA4NzgyLWU3MTZmM2NmLWFkYzctNGFlOC1iYzA2LWVlZTJhM2VlYzllNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTIwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTZiMDU2NGUxMzFjYmVhZTNkYTA3ODI2NWY0YjQ3M2U4OWRhZDA4YjY3M2FjNTc0NjlkZTdkMWUyMzVmNTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92fd3tDgor_NUph1OK24eHv3hLDHUbi7YMNfNNe4w80) And read 14.9 patch notes ![IMG_0234](https://private-user-images.githubusercontent.com/168309875/327108907-0b5aa0d6-9e9b-4f9e-906a-37bfc3a09a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjI3MTMsIm5iZiI6MTcxNDU2MjQxMywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3MTA4OTA3LTBiNWFhMGQ2LTllOWItNGY5ZS05MDZhLTM3YmZjM2EwOWE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTIwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODliODExZWJjN2VjMWZiYjlkODVkOWRmNWFhMzc2NWJiNDY4MTI3MzkxMTk4YmFhMmE0MTI5YzBhM2Q5Mjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN1GbPZFeTIFVcKAZTmYXmDI9UcldSFki1lPpOPjv44)
> 
> so it's the End sadly ?

Cs-lol manager work with Vanguard 
![IMG_0242](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/6b6c9135-2d53-464c-8b64-b2ecef25ab68)

**Comment by AJoKeRK** [comment]
> Yesterday still usable tho just wait for the update i think

we don't think there will be an update i think. do you know something about that ?

**Comment by SpaceC0re** [comment]
> > Yesterday still usable tho just wait for the update i think
> 
> we don't think there will be an update i think. do you know something about that ?

He's smoking that pack, there indeed won't be an update. You can buy 1350RP skins for 5,4€ online if you look hard enough, though, so there's that.

**Comment by SpaceC0re** [comment]
> > > > Yesterday still usable tho just wait for the update i think
> > > 
> > > 
> > > we don't think there will be an update i think. do you know something about that ?
> > 
> > 
> > He's smoking that pack, there indeed won't be an update. You can buy 1350RP skins for 5,4€ online if you look hard enough, though, so there's that.
> 
> I really am curious on where you buy RP for that cheap on euw, tho haha

Stuff like https://www.elitepvpers.com/forum/league-legends-trading/5157403-league-legends-gifting-service-rp-top-up-ronaldinho.html

or https://www.elitepvpers.com/forum/league-legends-trading/5223645-league-choose-gift-service-instant-delivery-cheapest-price.html

**Comment by zippoooooo** [comment]
很遗憾，但还是很感谢你的工作

**Comment by eqfae** [comment]
我不希望这是R3的最后 因为所谓的反作弊软件

**Comment by discoveranytime** [comment]
so why are custom skins useable on runeforge but the skin changer is not. eventually there will be a new program or update

**Comment by Pierreluc23** [comment]
> so why are custom skins useable on runeforge but the skin changer is not. eventually there will be a new program or update

Unlikely a R3nzSkin update the op have said they will not fix it with Vanguard.

**Comment by longxa762** [comment]
> so why are custom skins useable on runeforge but the skin changer is not. eventually there will be a new program or update

Because CS-LoL Manager work by swapping files while R3nzSkin inject DLL into the game and change the code. Any old school method like swapping files may still work but injection is dead with Vanguard released.

**Comment by johan1357** [comment]
skin changer working here guys https://discord.gg/dXYcB8y3
