### ISSUE TITLE
     Remove DX9 Support and update IsLaneMinion offset.

### ISSUE THREAD

**Issue by Maruutu** [R3nzTheCodeGOD/R3nzSkin#1117]
How can i remove DX9 support and update IslaneMinion cuz i looked for a while and still have no clue how to do it

**Comment by Pierreluc23** [comment]
R3nzSkin removed dx9 support.

**Comment by Surcito** [comment]
Mee too

**Comment by Pierreluc23** [comment]
![IMG_0261](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/8e46d272-06e6-4dfe-b141-d43fc6f1180d)

**Comment by GIRAFEX** [comment]
me too. Did you manage to solve it?

**Comment by Pierreluc23** [comment]
> me too. Did you manage to solve it?

Like you have no see the photo ?

**Comment by GIRAFEX** [comment]
?????????, I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.

**Comment by GIRAFEX** [comment]
> > me too. Did you manage to solve it?
> 
> Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)

I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.

**Comment by Pierreluc23** [comment]
Read 14.9 patch notes and also it was also this when Vanguard was only in PBE 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/3d6c4918-d7ff-471b-8a6b-eb925e614907)

**Comment by Pierreluc23** [comment]
> > > me too. Did you manage to solve it?
> > 
> > 
> > Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)
> 
> I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.



> > > me too. Did you manage to solve it?
> > 
> > 
> > Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)
> 
> I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.

Read 14.9 patch notes and also it was also this when Vanguard was only in PBE 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/f56c51e5-74be-4b08-be84-0f3934374093)

**Comment by Pierreluc23** [comment]
> > > me too. Did you manage to solve it?
> > 
> > 
> > Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)
> 
> I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.

Read 14.9 patch notes and also it was also this when Vanguard was only in PBE 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/82b9ab85-bc4b-41e1-bfef-7a0a4bae52fc)

**Comment by GIRAFEX** [comment]
> > > > me too. Did you manage to solve it?
> > > 
> > > 
> > > Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)
> > 
> > 
> > I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.
> 
> Read 14.9 patch notes and also it was also this when Vanguard was only in PBE ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/327977406-82b9ab85-bc4b-41e1-bfef-7a0a4bae52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjAyMDIsIm5iZiI6MTcxNDg1OTkwMiwicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTc3NDA2LTgyYjlhYjg1LWJjNGItNDFlMS1iZmVmLTdhMGE0YmFlNTJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMTU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjViMWI0MGRiNzdhZjlmMzRmOTFjZjgyNWE0YTJiMjQ1MzY2YjYxMDQ3YjU3ODA0OTZkMWJmMDQ4OGI5MjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b_c16mTQMbo1eb4GDfKEh5yqoxRIZtyrvP8IVCMNrN0)

So does that mean the era of lol skins is over?

**Comment by Pierreluc23** [comment]
> > > > > me too. Did you manage to solve it?
> > > > 
> > > > 
> > > > Like you have no see this photo before your post ![IMG_0270](https://private-user-images.githubusercontent.com/168309875/327966664-fb173182-cdca-4e8f-bca5-24f7e7a231b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQ0NjcsIm5iZiI6MTcxNDg1NDE2NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTY2NjY0LWZiMTczMTgyLWNkY2EtNGU4Zi1iY2E1LTI0ZjdlN2EyMzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlMTMyYzk3ZWUyYTY5MWVkODRiMDNiOWU0ODM0Y2Y2OTI2NThkM2VmMDdiMjJiMWEwOTU1ZWNhZGRmNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnfz7P06pOFQioeuLBcVQJjb_psvEY7GpfqFiPSEPuQ)
> > > 
> > > 
> > > I saw it, but I didn't understand it. I already downloaded this version and when I click start, nothing happens.
> > 
> > 
> > Read 14.9 patch notes and also it was also this when Vanguard was only in PBE ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/327977406-82b9ab85-bc4b-41e1-bfef-7a0a4bae52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjAyMDIsIm5iZiI6MTcxNDg1OTkwMiwicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTc3NDA2LTgyYjlhYjg1LWJjNGItNDFlMS1iZmVmLTdhMGE0YmFlNTJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMTU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjViMWI0MGRiNzdhZjlmMzRmOTFjZjgyNWE0YTJiMjQ1MzY2YjYxMDQ3YjU3ODA0OTZkMWJmMDQ4OGI5MjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b_c16mTQMbo1eb4GDfKEh5yqoxRIZtyrvP8IVCMNrN0)
> 
> So does that mean the era of lol skins is over?

 No over this tool work with Vanguard 
![IMG_0271](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/ebc4a4e3-f86b-4656-b2bf-9d9bd61e24b9)
