### ISSUE TITLE
R3nzSkin Status not activating

### ISSUE THREAD

**Issue by Miessen** [R3nzTheCodeGOD/R3nzSkin#1118]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/146342800/729595f4-8baa-41df-9f79-03ce6ec1a2a8)
It doesnt work anymore

**Comment by Pierreluc23** [comment]
Read 14.9 patch notes and also it was also this when Vanguard was only in PBE
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/1afbe6f3-3630-46c5-832e-f3ba2ab0779a)
