### ISSUE TITLE
Will this get you banned?

### ISSUE THREAD

**Issue by Apole2** [R3nzTheCodeGOD/R3nzSkin#1119]
Does Vanguard ban this skin changer or does it not?

**Comment by Pierreluc23** [comment]
It not inject but it working if you uninstall Vanguard in game in control panel this work for few minutes
![IMG_0219](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/f3f7f528-d4cf-4f96-bc14-43bc1a79cf6a)

**Comment by Apole2** [comment]
ok so u cant use it without disabling vanguard?

**Comment by Pierreluc23** [comment]
> ok so u cant use it without disabling vanguard?
No for use it Vanguard need to be uninstall in control panel but it work only for few minutes because of the Vanguard check.

**Comment by K4D0R** [comment]
> > ok so u cant use it without disabling vanguard?
> 
> No for use it Vanguard need to be uninstall in control panel in game but it work only for few minutes because of the Vanguard check.

but will you get banned if you try ?

**Comment by Pierreluc23** [comment]
> > > ok so u cant use it without disabling vanguard?
> > 
> > 
> > No for use it Vanguard need to be uninstall in control panel in game but it work only for few minutes because of the Vanguard check.
> 
> but will you get banned if you try ?

No banned for uninstalling in game.

**Comment by Pierreluc23** [comment]
> > > ok so u cant use it without disabling vanguard?
> > 
> > 
> > No for use it Vanguard need to be uninstall in control panel in game but it work only for few minutes because of the Vanguard check.
> 
> but will you get banned if you try ?
R3nzSkin with Vanguard uninstalled in game  
![R3nzSkin with Vanguard uninstalled](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/bda41865-ddf8-4733-82af-91f8e9344ae1)

**Comment by K4D0R** [comment]
> > > > ok so u cant use it without disabling vanguard?
> > > 
> > > 
> > > No for use it Vanguard need to be uninstall in control panel in game but it work only for few minutes because of the Vanguard check.
> > 
> > 
> > but will you get banned if you try ?
> 
> R3nzSkin with Vanguard uninstalled in game but not a good fix because work only for few minutes. ![R3nzSkin with Vanguard uninstalled](https://private-user-images.githubusercontent.com/168309875/327880074-bda41865-ddf8-4733-82af-91f8e9344ae1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NzEzNzEsIm5iZiI6MTcxNDc3MTA3MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzI3ODgwMDc0LWJkYTQxODY1LWRkZjgtNDczMy04MmFmLTkxZjhlOTM0NGFlMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QyMTE3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjBiMTBlZTkzMmNkZWY1NDg5YmUxNjk5M2NiOTc4MDViY2JjMTNiZDAyNmRkZTcwNjMyYzc4ZjJhNTcwMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GYhxKeR_yzpsBzyi_ttcdrD6nfvUYDENff5KJ4aSbmE)

and if you try with vanguard installed ?

**Comment by Pierreluc23** [comment]
> > > > > ok so u cant use it without disabling vanguard?
> > > > 
> > > > 
> > > > No for use it Vanguard need to be uninstall in control panel in game but it work only for few minutes because of the Vanguard check.
> > > 
> > > 
> > > but will you get banned if you try ?
> > 
> > 
> > R3nzSkin with Vanguard uninstalled in game but not a good fix because work only for few minutes. ![R3nzSkin with Vanguard uninstalled](https://private-user-images.githubusercontent.com/168309875/327880074-bda41865-ddf8-4733-82af-91f8e9344ae1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NzEzNzEsIm5iZiI6MTcxNDc3MTA3MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzI3ODgwMDc0LWJkYTQxODY1LWRkZjgtNDczMy04MmFmLTkxZjhlOTM0NGFlMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QyMTE3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjBiMTBlZTkzMmNkZWY1NDg5YmUxNjk5M2NiOTc4MDViY2JjMTNiZDAyNmRkZTcwNjMyYzc4ZjJhNTcwMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GYhxKeR_yzpsBzyi_ttcdrD6nfvUYDENff5KJ4aSbmE)
> 
> and if you try with vanguard installed ?

![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/2f3852b2-f105-4a0a-9226-8c0e44bba369)

**Comment by ayhanyilmaz10** [comment]
So, can you use it or not?

**Comment by Pierreluc23** [comment]
> So, can you use it or not?

Not.
