### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bilibiliEmiya** [R3nzTheCodeGOD/R3nzSkin#112]
version:12.9
still not working with injector in chinese serve
please fix it
thank you!
ps:running without wegame

**Comment by FreeXMelody** [comment]
It works perfectly in the CN server, even with WeGame.
Anything wrong with ur operation?

**Comment by bilibiliEmiya** [comment]
> It works perfectly in the CN server, even with WeGame. Anything wrong with ur operation?

![image](https://user-images.githubusercontent.com/54109395/168485493-402b3b4c-7c58-45d3-82b1-d6235d36bd4a.png)

**Comment by bilibiliEmiya** [comment]
> It works perfectly in the CN server, even with WeGame. Anything wrong with ur operation?

I replaced the “LogitechLed.dll” manually, but the fourth option of the injector is still red
Of course, manual replacement can work normally,but I'm afraid it will block my account without injector
![image](https://user-images.githubusercontent.com/54109395/168486706-51decf3c-cc44-4bc1-832c-a9217ae93f94.png)
