### ISSUE TITLE
Any alternatives?

### ISSUE THREAD

**Issue by DaviJh** [R3nzTheCodeGOD/R3nzSkin#1120]
.-.

**Comment by Pierreluc23** [comment]
![IMG_0268](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/82deb41f-d3fe-4959-bddc-9a70c6067cd5)

**Comment by Mmmhghi** [comment]
> ![IMG_0268](https://private-user-images.githubusercontent.com/168309875/327956754-82deb41f-d3fe-4959-bddc-9a70c6067cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mzg3NDcsIm5iZiI6MTcxNDgzODQ0NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTU2NzU0LTgyZGViNDFmLWQzZmUtNDk1OS1iZGRjLTlhNzBjNjA2N2NkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNjAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTBhMjZjMWI1NTA0ZjM5NWYwYWUxM2RmOTY5NWI4OTQ2ZjU0MzQyMDc5MDllMmRjYjFkMGNhOGMxNWM5YjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTk7N6Q2aNgOzUa7Q933hHSKk0d8AogLXxnT-NZ6AdM)

we need a skin changer like r3nz not pooring ass customs

**Comment by Pierreluc23** [comment]
> > ![IMG_0268](https://private-user-images.githubusercontent.com/168309875/327956754-82deb41f-d3fe-4959-bddc-9a70c6067cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mzg3NDcsIm5iZiI6MTcxNDgzODQ0NywicGF0aCI6Ii8xNjgzMDk4NzUvMzI3OTU2NzU0LTgyZGViNDFmLWQzZmUtNDk1OS1iZGRjLTlhNzBjNjA2N2NkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNjAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTBhMjZjMWI1NTA0ZjM5NWYwYWUxM2RmOTY5NWI4OTQ2ZjU0MzQyMDc5MDllMmRjYjFkMGNhOGMxNWM5YjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTk7N6Q2aNgOzUa7Q933hHSKk0d8AogLXxnT-NZ6AdM)
> 
> we need a skin changer like r3nz not pooring ass customs

This is the only tool who work with Vanguard with R3nzSkin broken.

**Comment by Wafflecatus** [comment]
Is there an option to get skins from the game files and use them in cs lol manager?

**Comment by 0nlyb1nd** [comment]
not directly but I guess v can find files from internet
the problem is v need to convert them to a file format named ".fantome" or ".rar" archive which contains a ".wad.client" file
look for the example check out this link
https://drive.google.com/drive/folders/11fr3_4MIewpXalOG2fAhyTQdNVIxOrLR
It contains most of the skins but the problem is they r just unusable files in cs-lol-manager
there r few kinds of files type in these folders which is ".dds" ".SKL" ".SKN" and ".troybin"
so what then how can i use these files or actually let's say how can I convert these to a ".client" file?
![Capture](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/108167650/ba24ac8c-bd6b-4b72-a47f-c56af6d5dbcd)

**Comment by Wafflecatus** [comment]
All the guides use the obsidian program https://github.com/Crauzer/Obsidian/releases . And they just change the files they took out and change the textures and throw the new files into a new folder and then just throw that folder into cslolmanager and it works as a skin for example https://www.youtube.com/watch?v=yrWBEMLj-R8.

**Comment by Mmmhghi** [comment]
> All the guides use the obsidian program https://github.com/Crauzer/Obsidian/releases . And they just change the files they took out and change the textures and throw the new files into a new folder and then just throw that folder into cslolmanager and it works as a skin for example https://www.youtube.com/watch?v=yrWBEMLj-R8.
so u can now use skins files and convert them into wad to use them in cs.lol manager?

**Comment by Mmmhghi** [comment]
> not directly but I guess v can find files from internet the problem is v need to convert them to a file format named ".fantome" or ".rar" archive which contains a ".wad.client" file look for the example check out this link https://drive.google.com/drive/folders/11fr3_4MIewpXalOG2fAhyTQdNVIxOrLR It contains most of the skins but the problem is they r just unusable files in cs-lol-manager there r few kinds of files type in these folders which is ".dds" ".SKL" ".SKN" and ".troybin" so what then how can i use these files or actually let's say how can I convert these to a ".client" file? ![Capture](https://private-user-images.githubusercontent.com/108167650/327992371-ba24ac8c-bd6b-4b72-a47f-c56af6d5dbcd.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjI0MDIsIm5iZiI6MTcxNTAyMjEwMiwicGF0aCI6Ii8xMDgxNjc2NTAvMzI3OTkyMzcxLWJhMjRhYzhjLWJkNmItNGI3Mi1hNDdmLWM1NmFmNmQ1ZGJjZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxOTAxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDg2YzJhNzM2ZGE1NDI5NzU1NGFjYmI2NzEwYzU0ZWM0MTc3Y2IwZTNhNWY3MWJiNjUyYzYzMThkN2UxZmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WG8Zl_N5LdgXWSE_McxK3KNbzHOErgdi_Bq-BxVCvOc)

bro the skins link doesn't contain any files 
only names of the champs
