### ISSUE TITLE
hid.dll seems not work

### ISSUE THREAD

**Issue by moyuduo** [R3nzTheCodeGOD/R3nzSkin#1121]
I download r3nzskin and rename `R3nzSkin.dll` to `hid.dll` then put it into Game floder, but it seems not work.

I have two computers, one works, but another not effect, can everyone knows what happen?

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/59435134/30f0e80c-4884-4711-8b5d-679bff4a7107)

**Comment by 0nlyb1nd** [comment]
actually It's not going to work anymore
with this vanguard update

**Comment by 0nlyb1nd** [comment]
so try using .exe file

**Comment by moyuduo** [comment]
> so try using .exe file

what exactly it mean?

**Comment by ceryyyy** [comment]
这个放进去后，用exe的那个文件

**Comment by moyuduo** [comment]
> 这个放进去后，用exe的那个文件

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/59435134/539e4347-a86b-434d-8de2-0c3ff757ee88)
这个文件吗？具体点，thanks

**Comment by ceryyyy** [comment]
> > 这个放进去后，用exe的那个文件
> 
> ![image](https://private-user-images.githubusercontent.com/59435134/328015082-539e4347-a86b-434d-8de2-0c3ff757ee88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTAyNTYsIm5iZiI6MTcxNDkwOTk1NiwicGF0aCI6Ii81OTQzNTEzNC8zMjgwMTUwODItNTM5ZTQzNDctYTg2Yi00MzRkLThkZTItMGMzZmY3NTdlZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNGQ3MzY1ODNlNDQ4NWNiZjY1ZTU5ODAyNzBmOGNkNDllZjE1NTgwMDdhYmE2ODc0NDZkMDRiYmU3MzYyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbQdSHOwOsvFnJ6FnfqjdrEjagRmEs4q_7Wy2q6mq-8)这个文件吗？具体点，thanks

他压缩文件下载下来不是有一个.dll的文件跟一个exe文件吗
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/153993168/04913bfe-e2d3-4712-95ac-8a69c0958620)

**Comment by moyuduo** [comment]
> > > 这个放进去后，用exe的那个文件
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/59435134/328015082-539e4347-a86b-434d-8de2-0c3ff757ee88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTAyNTYsIm5iZiI6MTcxNDkwOTk1NiwicGF0aCI6Ii81OTQzNTEzNC8zMjgwMTUwODItNTM5ZTQzNDctYTg2Yi00MzRkLThkZTItMGMzZmY3NTdlZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNGQ3MzY1ODNlNDQ4NWNiZjY1ZTU5ODAyNzBmOGNkNDllZjE1NTgwMDdhYmE2ODc0NDZkMDRiYmU3MzYyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbQdSHOwOsvFnJ6FnfqjdrEjagRmEs4q_7Wy2q6mq-8)这个文件吗？具体点，thanks
> 
> 他压缩文件下载下来不是有一个.dll的文件跟一个exe文件吗 ![image](https://private-user-images.githubusercontent.com/153993168/328015303-04913bfe-e2d3-4712-95ac-8a69c0958620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTAzMTIsIm5iZiI6MTcxNDkxMDAxMiwicGF0aCI6Ii8xNTM5OTMxNjgvMzI4MDE1MzAzLTA0OTEzYmZlLWUyZDMtNDcxMi05NWFjLThhNjljMDk1ODYyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxMTUzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzFmNzMxMmMzYjhlMWJlOWNiMmVjZGZhMWUxYmMwNmJkZmZkYzc2ZmJlYTM3Mzk3OTFiMjdlNDgyNTU2NWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ktADskXqi8iWM4OIAS1Cx0XKdw9vWttBzTbzKEIKbuM)

就是那个注入器用不起我才直接把文件改为`hid.dll`，你在马服能用这个？

**Comment by ceryyyy** [comment]
> > > > 这个放进去后，用exe的那个文件
> > > 
> > > 
> > > ![图像](https://private-user-images.githubusercontent.com/59435134/328015082-539e4347-a86b-434d-8de2-0c3ff757ee88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTAyNTYsIm5iZiI6MTcxNDkwOTk1NiwicGF0aCI6Ii81OTQzNTEzNC8zMjgwMTUwODItNTM5ZTQzNDctYTg2Yi00MzRkLThkZTItMGMzZmY3NTdlZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNGQ3MzY1ODNlNDQ4NWNiZjY1ZTU5ODAyNzBmOGNkNDllZjE1NTgwMDdhYmE2ODc0NDZkMDRiYmU3MzYyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbQdSHOwOsvFnJ6FnfqjdrEjagRmEs4q_7Wy2q6mq-8)这个文件吗？具体点，thanks
> > 
> > 
> > 他压缩文件下载下来不是有一个.dll的文件跟一个exe文件吗![image](https://private-user-images.githubusercontent.com/153993168/328015303-04913bfe-e2d3-4712-95ac-8a69c0958620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTAzMTIsIm5iZiI6MTcxNDkxMDAxMiwicGF0aCI6Ii8xNTM5OTMxNjgvMzI4MDE1MzAzLTA0OTEzYmZlLWUyZDMtNDcxMi05NWFjLThhNjljMDk1ODYyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxMTUzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzFmNzMxMmMzYjhlMWJlOWNiMmVjZGZhMWUxYmMwNmJkZmZkYzc2ZmJlYTM3Mzk3OTFiMjdlNDgyNTU2NWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ktADskXqi8iWM4OIAS1Cx0XKdw9vWttBzTbzKEIKbuM)
> 
> 就是那个注入器用不起我才直接把文件改为，你在马服能用这个？`hid.dll`

对啊，TX上的我也是这样用的，昨天还用了，

**Comment by shimogezhelive** [comment]
顶着腾讯开换肤是吧 太猛了

**Comment by KomariVGC** [comment]
那就用那台能正常使用的电脑玩lol不就好了（
