### ISSUE TITLE
new sussy "r3nzskin"

### ISSUE THREAD

**Issue by Kaipo12313** [R3nzTheCodeGOD/R3nzSkin#1122]
Some new "R3nzskin" appeared, what do you guys think? Can someone with better knowledge than mine tell - is that a bait or is it safe?
https://www.youtube.com/watch?v=Tooz4jdyICU
https://r3nz.skin/

**Comment by Pierreluc23** [comment]
It the same R3nzSkin  
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/669d830e-09d4-41b3-b058-a1aa5f05cacc)

**Comment by bpham4869** [comment]
IIt r3nzskin but added Trojan-Downloader.Win32.PsDownload.gen( detected by Kaspersky), There are also a few other things but it also includes a backdoor trojan. Downloading from this Github itself, my device has never reported that there is a malware.

**Comment by mish20011** [comment]
nah thats too risky, they are using r3nz but they tampered with it, the youtube video is so freaking stupid full of warnings and imagine proceeding, if I am using a shit laptop then I would try, but never on this new one I got

**Comment by Maruutu** [comment]
i have 2 pcs and i downloaded it on the old and bad pc and it works but i wouldnt try it on my main one cuz this shit is risky

**Comment by Pierreluc23** [comment]
> i have 2 pcs and i downloaded it on the old and bad pc and it works but i wouldnt try it on my main one cuz this shit is risky

And how they inject.

**Comment by Pierreluc23** [comment]
> i have 2 pcs and i downloaded it on the old and bad pc and it works but i wouldnt try it on my main one cuz this shit is risky

No tested the R3nzSkin and and as the Real R3nzSkin iit not working 
![Suzzy R3nxSkin not working](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/994e4069-cc5e-4e1d-8b9f-49b1e29712d1)
