### ISSUE TITLE
ingame skins like custom cslolmanager?

### ISSUE THREAD

**Issue by urfavcromozom** [R3nzTheCodeGOD/R3nzSkin#1123]
is there any chance ingame skins to do .fantome so we can use the real skins at cslolmanager like custom skins maybe

**Comment by T9Jungler** [comment]
yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)

**Comment by urfavcromozom** [comment]
idk how to do but even if ik its take a lot effort for all skins so hope we can found an alternative like renz rip for renz it was a great journey:(

**Comment by urfavcromozom** [comment]
> yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)

can you lend me the discord sercer link?

**Comment by DaviJh** [comment]
> yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)

Can you send the discord link or tell tiktok name

**Comment by T9Jungler** [comment]
> > yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)
> 
> Can you send the discord link or tell tiktok name

https://www.tiktok.com/@n0xscape

**Comment by T9Jungler** [comment]
> > yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)
> 
> can you lend me the discord sercer link?

u got tiktok link there so you can join dc from tiktok but dont ask for real skins u gonna get banned like me

**Comment by T9Jungler** [comment]
> > yes, you can do that, but u need to know how. i see a guy on tiktok whos selling custom skins and he taking real skins from game and recoloring so i joined on his discord server and ask him to take real skins from game and give us fantome file so we can use it like r3nz and he say "hmm" and banned me from server (i tryed his BlueFire Yasuo (Nightbringer Yasuo) and it works just like in r3nz, hope someone will give as fantome files for real skins)
> 
> Can you send the discord link or tell tiktok name

you got there some free skins but you need to pay for skins with animations (you got only blue nightbringer yasuo with animations for free)

**Comment by T9Jungler** [comment]
it's stupid to pay 15 euros for a skin that no one else can see

**Comment by T9Jungler** [comment]
if i find something else i will tell you guys, im looking every day for something good

**Comment by T9Jungler** [comment]
https://discord.gg/customskins
 i got this one too

**Comment by DaviJh** [comment]
> if i find something else i will tell you guys, im looking every day for something good

i trying to find a way to use skins again too i tell if i find something

**Comment by meticulously-impeteous** [comment]
please keep us updated those who have the time to look into this 😭
