### ISSUE TITLE
Gang is this real?

### ISSUE THREAD

**Issue by WGPL777** [R3nzTheCodeGOD/R3nzSkin#1125]
So one member from my discord asked if this skin changer is legit. Im talking abt Pro version since its paid so I would be grateful if somoene who tested it could answer if its legit or nah

https://lol-skin.com

**Comment by meticulously-impeteous** [comment]
> So one member from my discord asked if this skin changer is legit. Im talking abt Pro version since its paid so I would be grateful if somoene who tested it could answer if its legit or nah
> 
> https://lol-skin.com

no this is fake crypto mining horseshit

**Comment by meticulously-impeteous** [comment]
only hope right now is to convert skin format to the one that's supported by cs lol manger other than that changing dll's and or injecting files is not feasible right now due o vanguard
