### ISSUE TITLE
R3nzskin Updated - Legit?

### ISSUE THREAD

**Issue by null15** [R3nzTheCodeGOD/R3nzSkin#1126]
https://www.youtube.com/watch?v=y4tJLbk2_5E

Anyone done this? Check comment section too

**Comment by Pierreluc23** [comment]
Patch 14.2 on the video

**Comment by J-EnJay** [comment]
DO NOT trust software that is not open source

**Comment by null15** [comment]
> DO NOT trust software that is not open source

Go take one for the team and test the software, let us know if it works

**Comment by Pierreluc23** [comment]
> > DO NOT trust software that is not open source
> 
> Go take one for the team and test the software, let us know if it works

It not patch 14.2 on the video

**Comment by J-EnJay** [comment]
> Patch 14.2 on the video not patch 14.9 ![IMG_0283](https://private-user-images.githubusercontent.com/168309875/329527397-49606520-e2b1-4851-bfe2-3ee835185d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjU1ODUsIm5iZiI6MTcxNTUyNTI4NSwicGF0aCI6Ii8xNjgzMDk4NzUvMzI5NTI3Mzk3LTQ5NjA2NTIwLWUyYjEtNDg1MS1iZmUyLTNlZTgzNTE4NWQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNDQ4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWU3Njk3ODBmMDY0MzU4NDI3N2JlNThhYzhkMGFhNGU3MzIzMjM0YmY2NTg3MGM3MDczNDM4ZWQ2OGU5MTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZyho8OBlbrNHrUz3tLXONN6L6BqSFYknmDyCOlqsP8)
> 
> ![IMG_0284](https://private-user-images.githubusercontent.com/168309875/329527479-a47c0a89-f6f6-40af-9936-e663123cc838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjU1ODUsIm5iZiI6MTcxNTUyNTI4NSwicGF0aCI6Ii8xNjgzMDk4NzUvMzI5NTI3NDc5LWE0N2MwYTg5LWY2ZjYtNDBhZi05OTM2LWU2NjMxMjNjYzgzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNDQ4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmY4NzVmNzg3YmNlOWVkMzE4MGRjNzkyODljMmI1MmM4MWMwNDk1YjhmZGM2Yjc4ZjhmMTNlOWZiZjAyYjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JUWrB768E1orcJTkvpp4GUIJOV2qDWrCxymLlstjdJQ)

so the video is fake and he wants you to download and use his so-called modskin to place a trojan virus on your computer.

**Comment by null15** [comment]
I mean it could be outdated video but the software is updated

**Comment by null15** [comment]
Im definitely not trying it though way too suspicious
