### ISSUE TITLE
Abt custom skins

### ISSUE THREAD

**Issue by dedddok** [R3nzTheCodeGOD/R3nzSkin#1127]
I tried to change base skin to other official skin using obsidian and cslol, but it didn't work. But as i understood you should change all dds, skn and skl files with "skinxx" (xx its skin number) to "basethe, create standard custom skin folder (you can find it in YouTube guide videos) add it into cslol. So, if someone can find solution pls dont be a dick and help us

**Comment by illitiratehobo** [comment]
uhh can you send me the yt link ill do it myself lol

**Comment by illitiratehobo** [comment]
did it but not even close lol https://pasteboard.co/iJtWe4gELMaB.png

**Comment by urfavcromozom** [comment]
> did it but not even close lol https://pasteboard.co/iJtWe4gELMaB.png

naah I tried but it was just like yours theres something we can change at files i think

**Comment by dedddok** [comment]
> did it but not even close lol https://pasteboard.co/iJtWe4gELMaB.png

Ye,  there's problems with skins higher than 950 RP or 1350 RP. Because they have some other animations. But it should be work if skin cost lesser

**Comment by dedddok** [comment]
> > did it but not even close lol https://pasteboard.co/iJtWe4gELMaB.png
> 
> naah I tried but it was just like yours theres something we can change at files i think

Btw, how did you do that? Because it didnt even change when i tried it

**Comment by dedddok** [comment]
> did it but not even close lol https://pasteboard.co/iJtWe4gELMaB.png

bro did you even do that, can you tell pls
im literally doing everything but still cant

**Comment by illitiratehobo** [comment]
https://www.youtube.com/watch?v=yrWBEMLj-R8 this tutorial but i tried it on dream dragon yasuo and rename the skin(number for example 55) i renamed it to base but it doesnt work

**Comment by illitiratehobo** [comment]
btw dream dragon yasuo is skin55

**Comment by illitiratehobo** [comment]
replaced all the files with skin 55 in them changed it to base

**Comment by dedddok** [comment]
> replaced all the files with skin 55 in them changed it to base

did you tried it with cheaper skins? Did it work?

**Comment by illitiratehobo** [comment]
will try later

**Comment by illitiratehobo** [comment]
still trying joined too many discord about custom skin and asking them how to replace base skin with official league skin but they are saying they don't support it
