### ISSUE TITLE
Does it work for anybody else? Mine keep crashing.

### ISSUE THREAD

**Issue by Sarmal3** [R3nzTheCodeGOD/R3nzSkin#113]
It just keep crashing after one second in the game.

**Comment by Obnoxygen** [comment]
Same here. I'm using garena btw. It used to work on patch 12.8 and below. Now, it just crashes a second after the game starts.

**Comment by Obnoxygen** [comment]
Nvm, it works now after reinstalling the tool. Thank you R3nzTheCodeGOD for this great software!

**Comment by Sarmal3** [comment]
It works after reinstalling?

**Comment by Obnoxygen** [comment]
Maybe try disabling your antivirus, or set the LoL game folder as an exclusion. Or maybe reinstalling the game itself.
