### ISSUE TITLE
Used on Tencent servers without any anomalies

### ISSUE THREAD

**Issue by EternallyH40** [R3nzTheCodeGOD/R3nzSkin#1134]

**Comment by Pierreluc23** [comment]
Will no longer work on patch 14.11 
![IMG_0302](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/fd2298a8-86d4-4199-a0ca-e8914c3b469b)

**Comment by Pierreluc23** [comment]
R3nzSkin will no longer work in patch 14.11 in 2 weeks it will show Failed to find pattern: 
![IMG_0302](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/7385c21d-89db-4283-9462-af2a9d7851e9)

**Comment by EternallyH40** [comment]
Riot server needs to find another way.
Tencent did not use Vanguard.

**Comment by Pierreluc23** [comment]
> Riot server needs to find another way. Tencent did not use Vanguard.

They will not fix R3nzSkin for Vanguard

**Comment by 70805** [comment]
Can contact me and I can teach you updates QQ 70805

**Comment by Maqpwa** [comment]
> Can contact me and I can teach you updates QQ 70805

please teach me how to update r3nzskin in china, what is your wechat I can't add you in QQ?

**Comment by Pierreluc23** [comment]
> > Can contact me and I can teach you updates QQ 70805
> 
> please teach me how to update r3nzskin in china, what is your wechat I can't add you in QQ?

I will clarify it only in patch 14.11 you will need to update it manually.
