### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by EzraelP** [R3nzTheCodeGOD/R3nzSkin#1135]
ive came to the "failed to find r3nzskin.dll in the current directory injector.auto update" issue i wonder if there's any solution to this?

**Comment by Pierreluc23** [comment]
For Riot server or Tencent server ?

**Comment by EzraelP** [comment]
I have this type of issue, I try to download it but it doesn’t work and it’s for league
![IMG_1195](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/164237649/3dcb519c-580f-41a7-a211-c329c0d41175)

**Comment by Pierreluc23** [comment]
> I have this type of issue, I try to download it but it doesn’t work and it’s for league ![IMG_1195](https://private-user-images.githubusercontent.com/164237649/331373900-3dcb519c-580f-41a7-a211-c329c0d41175.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTE0ODIsIm5iZiI6MTcxNTg5MTE4MiwicGF0aCI6Ii8xNjQyMzc2NDkvMzMxMzczOTAwLTNkY2I1MTljLTU4MGYtNDFhNy1hMjExLWMzMjljMGQ0MTE3NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMjAyNjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWViMmNkMjFkNTQzMzFkNTViNmE1OTBhNGQ2NzEzZjI3Yjc5ZjVhZTA0ZWNjMjY4YTAxZTg1ZjkxYTY5ZGFlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GSrqqKzWKE-WlU2AbhawNimyVnWaEUqcHp3776wXgdg)

For Riot server or Tencent server ?

**Comment by EzraelP** [comment]
Riot server

**Comment by Pierreluc23** [comment]
> Riot server

It broken.

**Comment by EzraelP** [comment]
bizzare because when i had windows 10 i was able to run it without any problem

**Comment by Pierreluc23** [comment]
> bizzare because when i had windows 10 i was able to run it without any problem

But before patch 14.9

**Comment by EzraelP** [comment]
oh yea true, but im sure there working on that right?

**Comment by Pierreluc23** [comment]
> oh yea true, but im sure there working on that right?

![IMG_0293](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/ca083cfb-a888-4a84-912f-0f2200531c84)

**Comment by EzraelP** [comment]
it's joever :(

**Comment by EzraelP** [comment]
any alternative?

**Comment by Pierreluc23** [comment]
> it's joever :(

R3nzSkin will stop working for good only on patch 14.11 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/b10231c6-b7ea-4a43-b845-6acc1dea5134)
And it still work 
![IMG_0219](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/30a74b02-9f93-43a9-be45-e6270080256f)
 If Vanguard is not running by exit in game the Vanguard app or uninstall Vanguard in control panel while in game but work only for few minutes

**Comment by Pierreluc23** [comment]
> any alternative?

This 
![IMG_0306](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/291ae859-84bb-406e-afba-9b98de836cff)

**Comment by EzraelP** [comment]
Is it as good as R3nz like you unlock every skin?

**Comment by Pierreluc23** [comment]
> Is it as good as R3nz like you unlock every skin?

![IMG_0307](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/6d6decbd-e096-475d-b775-a243c05c1e3b)
