### ISSUE TITLE
Anyone know how to update r3nzskin in china? because I still want to use it on patch 14.11 :( 

### ISSUE THREAD

**Issue by Maqpwa** [R3nzTheCodeGOD/R3nzSkin#1136]

**Comment by Pierreluc23** [comment]
You will need to update it yourself.

**Comment by ref4rain** [comment]
用不了，打了两局秒封

**Comment by ref4rain** [comment]
下个git clone下来生成就行了
但是我用了两把就被封了一周

**Comment by Maqpwa** [comment]
> 下个git clone下来生成就行了 但是我用了两把就被封了一周

How bro? Can you teach me how to update latest r3nzskin in china server?

**Comment by dcdb723** [comment]
国服还敢用?找死啊...人民币玩家都一样封

**Comment by Maqpwa** [comment]
> 国服还敢用?找死啊...人民币玩家都一样封

I will use it only in china server bro, do you know how to update it?

**Comment by ref4rain** [comment]
> > 下个git clone下来生成就行了 但是我用了两把就被封了一周
> 
> How bro? Can you teach me how to update latest r3nzskin in china server?

you can update ，but tencent ban your acount quickly

**Comment by Maqpwa** [comment]
> > > 下个git clone下来生成就行了 但是我用了两把就被封了一周
> > 
> > 
> > How bro? Can you teach me how to update latest r3nzskin in china server?
> 
> you can update ，but tencent ban your acount quickly

The thing is I don't know how to update, can you teach me?

**Comment by ref4rain** [comment]
download git and visual studio，after than you should git clone this repo and open .sln file with visual studio, then build this project 
you can get renz.dll

**Comment by Maqpwa** [comment]
> download git and visual studio，after than you should git clone this repo and open .sln file with visual studio, then build this project

bro how, I alr did that but the thing is I don't know how to update bro

**Comment by KIC22** [comment]
国服可以用的，把wegame卸载了，用联盟客户端登陆，没问题的

**Comment by 70805** [comment]
可以联系我QQ70805 我会更新

**Comment by Maqpwa** [comment]
> 国服可以用的，把wegame卸载了，用联盟客户端登陆，没问题的

Can you teach me how to do it?

**Comment by ymhzrzzz** [comment]
目前14.11版本 我还在使用
![screenshot-1716125604141](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/126318245/2161e1fd-d721-4760-912c-776136ead0cb)

**Comment by Maqpwa** [comment]
> 目前14.11版本 我还在使用

How bro, can you teach me ?

**Comment by SLJ2000** [comment]
> > 目前14.11版本 我还在使用
> 
> How bro, can you teach me, how did you update your r3nzskin?

We are a server in mainland China, and we don't have Valorant's anti-cheat, so we can use it. Other servers use Valorant's anti-cheat, so using R3NZSKIN will result in a ban.

**Comment by Maqpwa** [comment]
> > > 目前14.11版本 我还在使用
> > 
> > 
> > How bro, can you teach me, how did you update your r3nzskin?
> 
> We are a server in mainland China, and we don't have Valorant's anti-cheat, so we can use it. Other servers use Valorant's anti-cheat, so using R3NZSKIN will result in a ban.

I know bro. The thing I'm playing in China server and I want the r3nzskin latest verison but I don't know how to update.

**Comment by ref4rain** [comment]
> 国服可以用的，把wegame卸载了，用联盟客户端登陆，没问题的

我没用wegame啊，打着打着给我踢了

**Comment by ymhzrzzz** [comment]
> > > > 目前14.11版本 我还在使用
> > > 
> > > 
> > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > 
> > 
> > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> 
> 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。

你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过

**Comment by ref4rain** [comment]
> > > > > 目前14.11版本 我还在使用
> > > > 
> > > > 
> > > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > > 
> > > 
> > > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> > 
> > 
> > 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。
> 
> 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过

真没封啊？我号打一个封一个？机器码被锁了？

**Comment by ymhzrzzz** [comment]
> > > > > > 目前14.11版本 我还在使用
> > > > > 
> > > > > 
> > > > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > > > 
> > > > 
> > > > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> > > 
> > > 
> > > 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。
> > 
> > 
> > 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过
> 
> 真没封啊？我号打一个封一个？机器码被锁了？

不管你信不信 我反正是从用这个开始 接近2年 从没有因为这个被封过一次 哪怕是一小时
![screenshot-1716562900149](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/126318245/37a46753-d941-46eb-898b-1ee3f5acb2b8)

**Comment by ymhzrzzz** [comment]
> > > > > > > 目前14.11版本 我还在使用
> > > > > > 
> > > > > > 
> > > > > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > > > > 
> > > > > 
> > > > > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> > > > 
> > > > 
> > > > 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。
> > > 
> > > 
> > > 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过
> > 
> > 
> > 真没封啊？我号打一个封一个？机器码被锁了？
> 
> 不管你信不信 我反正是从用这个开始 接近2年 从没有因为这个被封过一次 哪怕是一小时 ![screenshot-1716562900149](https://private-user-images.githubusercontent.com/126318245/333636545-37a46753-d941-46eb-898b-1ee3f5acb2b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjM0MTIsIm5iZiI6MTcxNjU2MzExMiwicGF0aCI6Ii8xMjYzMTgyNDUvMzMzNjM2NTQ1LTM3YTQ2NzUzLWQ5NDEtNDZlYi04OThiLTFlZTNmNWFjYjJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTA1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDIwMzNjMGQxMjNjZTAyMDVjYjFhMzU2NTZjMzFjMmE5YzMzOTY0YzE2ZTc0YTY5NjcyN2FjNWVkOTA5MGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8-GZNBwAOTQgzGsYcSajr2lJeaXbFm9JQ8EkC2cP0g)

可以加我交流一下75911613 无偿

**Comment by Maqpwa** [comment]
> > > > > > > > 目前14.11版本 我还在使用
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > > > > > 
> > > > > > 
> > > > > > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> > > > > 
> > > > > 
> > > > > 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。
> > > > 
> > > > 
> > > > 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过
> > > 
> > > 
> > > 真没封啊？我号打一个封一个？机器码被锁了？
> > 
> > 
> > 不管你信不信 我反正是从用这个开始 接近2年 从没有因为这个被封过一次 哪怕是一小时 ![screenshot-1716562900149](https://private-user-images.githubusercontent.com/126318245/333636545-37a46753-d941-46eb-898b-1ee3f5acb2b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjM0MTIsIm5iZiI6MTcxNjU2MzExMiwicGF0aCI6Ii8xMjYzMTgyNDUvMzMzNjM2NTQ1LTM3YTQ2NzUzLWQ5NDEtNDZlYi04OThiLTFlZTNmNWFjYjJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTA1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDIwMzNjMGQxMjNjZTAyMDVjYjFhMzU2NTZjMzFjMmE5YzMzOTY0YzE2ZTc0YTY5NjcyN2FjNWVkOTA5MGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8-GZNBwAOTQgzGsYcSajr2lJeaXbFm9JQ8EkC2cP0g)
> 
> 可以加我交流一下75911613 无偿

bro, you can help me update the R3nzskin?

**Comment by ymhzrzzz** [comment]
> > > > > > > > > 目前14.11版本 我还在使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 兄弟，你能教我吗，你是怎么更新你的r3nzskin的？
> > > > > > > 
> > > > > > > 
> > > > > > > 我们是中国大陆的服务器，我们没有Valorant的反作弊功能，所以我们可以使用它。其他服务器使用 Valorant 的反作弊功能，因此使用R3NZSKIN将导致禁令。
> > > > > > 
> > > > > > 
> > > > > > 我知道兄弟。我正在中国服务器玩的东西，我想要 r3nzskin 最新版本，但我不知道如何更新。
> > > > > 
> > > > > 
> > > > > 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过
> > > > 
> > > > 
> > > > 真没封啊？我号打一个封一个？机器码被锁了？
> > > 
> > > 
> > > 不管你信不信 我反正是从用这个开始 接近2年 从没有因为这个被封过一次 哪怕是一小时![screenshot-1716562900149](https://private-user-images.githubusercontent.com/126318245/333636545-37a46753-d941-46eb-898b-1ee3f5acb2b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjM0MTIsIm5iZiI6MTcxNjU2MzExMiwicGF0aCI6Ii8xMjYzMTgyNDUvMzMzNjM2NTQ1LTM3YTQ2NzUzLWQ5NDEtNDZlYi04OThiLTFlZTNmNWFjYjJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTA1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDIwMzNjMGQxMjNjZTAyMDVjYjFhMzU2NTZjMzFjMmE5YzMzOTY0YzE2ZTc0YTY5NjcyN2FjNWVkOTA5MGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8-GZNBwAOTQgzGsYcSajr2lJeaXbFm9JQ8EkC2cP0g)
> > 
> > 
> > 可以加我交流一下75911613 无偿
> 
> 兄弟，你能帮我更新R3nzskin吗？

你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道

**Comment by Maqpwa** [comment]
> 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道

I am foreign but playing in china server, I want the r3nzskin latest version bro

**Comment by Pierreluc23** [comment]
> > > 目前14.11版本 我还在使用
> > 
> > 
> > How bro, can you teach me, how did you update your r3nzskin?
> 
> We are a server in mainland China, and we don't have Valorant's anti-cheat, so we can use it. Other servers use Valorant's anti-cheat, so using R3NZSKIN will result in a ban.

It not it just not inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/03b2275c-a7b0-45f7-819f-abaf88a2471f)

**Comment by Pierreluc23** [comment]
> > > > 目前14.11版本 我还在使用
> > > 
> > > 
> > > How bro, can you teach me, how did you update your r3nzskin?
> > 
> > 
> > We are a server in mainland China, and we don't have Valorant's anti-cheat, so we can use it. Other servers use Valorant's anti-cheat, so using R3NZSKIN will result in a ban.
> 
> I know bro. The thing I'm playing in China server and I want the r3nzskin latest verison but I don't know how to update.

Use R3nzSkin on Riot server do not ban it just not inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/26c8a1dc-6609-4995-a989-793377ccf179)

**Comment by Pierreluc23** [comment]
> 目前14.11版本 我还在使用 ![screenshot-1716125604141](https://private-user-images.githubusercontent.com/126318245/331875263-2161e1fd-d721-4760-912c-776136ead0cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU2MzAsIm5iZiI6MTcxNjgzNTMzMCwicGF0aCI6Ii8xMjYzMTgyNDUvMzMxODc1MjYzLTIxNjFlMWZkLWQ3MjEtNDc2MC05MTJjLTc3NjEzNmVhZDBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzRjY2FjODllOWE0NTZlZmNkYjRlNjMyNzY3MmJiOWZiODA1NWU5NmMxZmViM2M1NjVjNDE0OTU3MWMwZWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MqCjboeKI2uxD5RAcPtYSc7Y4dGAmP7_gJsL0SLmZhQ)

PBE Tencent version exist ?

**Comment by Pierreluc23** [comment]
> > 目前14.11版本 我还在使用
> 
> How bro, can you teach me, how did you update your r3nzskin?

I only know Riot who have PBE also any proof the photo is from a 14.11

**Comment by Pierreluc23** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> I am foreign but playing in china server, I want the r3nzskin latest version bro

Unlikely R3nzSkin release a update for china to fix this and 2 days before this error live on china server
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/73b2f96a-5fdd-4569-807e-bda501127189)

**Comment by Pierreluc23** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> I am foreign but playing in china server, I want the r3nzskin latest version bro

2 days before this error live on china server on patch 14.11 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/87395a22-fa37-4164-9a0a-1373a0de821a)

**Comment by Pierreluc23** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> I am foreign but playing in china server, I want the r3nzskin latest version bro

2-3 days before this error start to live in china and Riot server 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/6e28770c-90ff-49b0-a46c-330e9c75f22b)

**Comment by Pierreluc23** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> I am foreign but playing in china server, I want the r3nzskin latest version bro

R3nzSkin will not longer work in china in 2 days 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/41466896-10e6-4e25-a118-ffae96779675)

**Comment by Pierreluc23** [comment]
> 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过

Tested today on PBE and this show 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/9d9dabfa-a928-4cae-8534-90e62923fb20)

**Comment by Pierreluc23** [comment]
> 你不需要做任何修改，如果你之前会用的话 就是之前的使用方法下载文件 改名 复制进文件夹 切记不可玩云顶之弈 如果玩云顶之弈就把文件剪切出来再玩云顶之弈。目前为止我一直在玩未出现任何问题 包括封禁问题从未遇到过

R3nzSkin 不适用于补丁 14.11 
![IMG_0305](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/d77311c6-5558-434b-9adb-5037b14f38e1)

**Comment by ymhzrzzz** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> 我是外国人，但在中国服务器玩，我想要r3nzskin最新版本兄弟

为什么要来全世界最差的服务器玩，这个版本的R3已经停止更新了而且当前版本无法使用 最新的版本我不知道怎么分享给你

**Comment by J-EnJay** [comment]
> > 你是国人还是外国人？国人可以帮忙外国人或者外服我没玩过不知道
> 
> I am foreign but playing in china server, I want the r3nzskin latest version bro

you can get the hid.dll in my [resposity](https://github.com/J-EnJay/R3nzSkinCN)
