### ISSUE TITLE
R3nzskins sigue sirviendo 

### ISSUE THREAD

**Issue by Yashuuv** [R3nzTheCodeGOD/R3nzSkin#1139]
Intente abrir el r3nzskins en lol y cerrar el vanguard y funciona pero solo unos minutos por que te sale una noti de que lol no puede ejecutarse sin vanguard, entonces creen que si se pueda usar si le meten una actualización que deje a un lado el vanguard y funcione sin ningún problema ? No creo que sea tan difícil I

**Comment by lwlxsgnet** [comment]
>Intente abrir el r3nzskins en lol y cerrar el vanguard y funciona pero solo unos minutos por que te sale una noti de que lol no puede ejecutarse sin vanguard, entonces creen que si se pueda usar si le meten una actualización que deje a un lado el vanguard y funcione sin ningún problema ? No creo que sea tan difícil I

@Yashuuv  Can you help translate it into English? It’s hard for me to understand after translating it into Chinese.

**Comment by Pierreluc23** [comment]
R3nzSkin ya no recibe actualizaciones

**Comment by Pierreluc23** [comment]
R3nzSkin ya no recibe actualizaciones debido a Vanguard

**Comment by Pierreluc23** [comment]
R3nzSkin ya no recibe actualizaciones debido a Vanguard.
