### ISSUE TITLE
skin display error

### ISSUE THREAD

**Issue by Gasferr** [R3nzTheCodeGOD/R3nzSkin#114]
I wanted to tell you about an error that happens to me in some champions when I want to change the skin, game_character_display appears and it does not let me select said skin

imgur.com/n6H9b6w.png

**Comment by alphaaced** [comment]
I realized this too on viego but i dont think it does anything, it's just there and selects the default. All other skins work however.

**Comment by R3nzTheCodeGOD** [comment]
fixed
