### ISSUE TITLE
I can manage to run LOL client and play game with installed Vanguard on Secure Boot disabled.

### ISSUE THREAD

**Issue by truongvantuan** [R3nzTheCodeGOD/R3nzSkin#1140]
![Screenshot 2024-05-24 212559](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/22904956/143eea73-8e16-427d-a11a-8ab87e4f0f0c)
I have got play LOL on Secure Boot disabled. Is it possible to make R3nzSkin back again?

**Comment by urfavcromozom** [comment]
is it work?

**Comment by Pierreluc23** [comment]
> ![Screenshot 2024-05-24 212559](https://private-user-images.githubusercontent.com/22904956/333626132-143eea73-8e16-427d-a11a-8ab87e4f0f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTYyNzEsIm5iZiI6MTcxNjU5NTk3MSwicGF0aCI6Ii8yMjkwNDk1Ni8zMzM2MjYxMzItMTQzZWVhNzMtOGUxNi00MjdkLWExMWEtOGFiODdlNGYwZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTljYzk4ODAzYjRhYzk4MTYzNTFjNmMyOGM2MDk1YWYzOWJiOTJjZmE4NGQwMjZkMDNmZDVkMTBmZTUzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGv890exbF8MGXG_ygVDfs1kbjuam9IYa7ZEtmSh29k) I have got play LOL on Secure Boot disabled. Is it possible to make R3nzSkin back again?

No read the announcement R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by Mmmhghi** [comment]
> > ![Screenshot 2024-05-24 212559](https://private-user-images.githubusercontent.com/22904956/333626132-143eea73-8e16-427d-a11a-8ab87e4f0f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTYyNzEsIm5iZiI6MTcxNjU5NTk3MSwicGF0aCI6Ii8yMjkwNDk1Ni8zMzM2MjYxMzItMTQzZWVhNzMtOGUxNi00MjdkLWExMWEtOGFiODdlNGYwZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTljYzk4ODAzYjRhYzk4MTYzNTFjNmMyOGM2MDk1YWYzOWJiOTJjZmE4NGQwMjZkMDNmZDVkMTBmZTUzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGv890exbF8MGXG_ygVDfs1kbjuam9IYa7ZEtmSh29k) I have got play LOL on Secure Boot disabled. Is it possible to make R3nzSkin back again?
> 
> No read the announcement R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

ma guy u running every question with no mfker be positive for once !

**Comment by ConeDjordjic** [comment]
> > > ![Screenshot 2024-05-24 212559](https://private-user-images.githubusercontent.com/22904956/333626132-143eea73-8e16-427d-a11a-8ab87e4f0f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTYyNzEsIm5iZiI6MTcxNjU5NTk3MSwicGF0aCI6Ii8yMjkwNDk1Ni8zMzM2MjYxMzItMTQzZWVhNzMtOGUxNi00MjdkLWExMWEtOGFiODdlNGYwZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTljYzk4ODAzYjRhYzk4MTYzNTFjNmMyOGM2MDk1YWYzOWJiOTJjZmE4NGQwMjZkMDNmZDVkMTBmZTUzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGv890exbF8MGXG_ygVDfs1kbjuam9IYa7ZEtmSh29k) I have got play LOL on Secure Boot disabled. Is it possible to make R3nzSkin back again?
> > 
> > 
> > No read the announcement R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)
> 
> ma guy u running every question with no mfker be positive for once !

he is clueless as fuck just copy pasting shit when you can avoid vanguard lmao. you can just host a server with all custom skins for all champs and do what cslol is doing just detouring createfilea to put ur files

**Comment by Pierreluc23** [comment]
> ![Screenshot 2024-05-24 212559](https://private-user-images.githubusercontent.com/22904956/333626132-143eea73-8e16-427d-a11a-8ab87e4f0f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjQ2MDgsIm5iZiI6MTcxNjg2NDMwOCwicGF0aCI6Ii8yMjkwNDk1Ni8zMzM2MjYxMzItMTQzZWVhNzMtOGUxNi00MjdkLWExMWEtOGFiODdlNGYwZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAyNDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTQ2NmU4YzEyZjM3MTI3ZDc2MmNmZDM1MDUyMmQ0OTExN2RlZDkzZjU3YmRhYjQzODM1YjI4MjVkZjY3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpPo4NQ-SfAal3Pa-zk2l_4hkupCHzBiSK8ED_iLuYg) I have got play LOL on Secure Boot disabled. Is it possible to make R3nzSkin back again?

> why dont u guys change dll of skin changer like cslol did?

R3nzSkin is not working with Ring 0 anti cheat 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/2b9bc9e5-cac3-4c12-ac92-47a7ee1a4f7f)

![IMG_0330](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/400fcdf8-4e16-411d-ad70-3215be14bd18)

The photo is from this article in 2020 https://www.leagueoflegends.com/en-us/news/dev/dev-null-anti-cheat-kernel-driver/

**Comment by Pierreluc23** [comment]
> is it work?

Secure boot or TPM 2.0 change nothing about R3nzSkin because Vanguard run in Ring 0 
![IMG_0330](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/e411b0a6-1c23-4aa8-9681-72315a61a40a)
