### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by razee1** [R3nzTheCodeGOD/R3nzSkin#1141]
Will there be updates to new versions or will it not be possible due to vanguard?

**Comment by Pierreluc23** [comment]
Read the announcement  R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by Pierreluc23** [comment]
> Will there be updates to new versions or will it not be possible due to vanguard?

R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by Pierreluc23** [comment]
> Will there be updates to new versions or will it not be possible due to vanguard?

No read the announcement R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by Pierreluc23** [comment]
The answer on the main page 
![IMG_0331](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/ac90367e-353c-442e-8abf-8a3c242c2193)
