### ISSUE TITLE
cant this work?

### ISSUE THREAD

**Issue by 14fedora** [R3nzTheCodeGOD/R3nzSkin#1147]
why dont u  guys change dll of skin changer like cslol did?

**Comment by Pierreluc23** [comment]
> why dont u guys change dll of skin changer like cslol did?
DLL of Cslol-manager do not work with R3!nzSkin.

**Comment by Pierreluc23** [comment]
> why dont u guys change dll of skin changer like cslol did?

Because R3nzSkin is not longer supported read the announcement R3nzSkin is no longer supported due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)

**Comment by Pierreluc23** [comment]
> why dont u guys change dll of skin changer like cslol did?

Read the announcement 
![IMG_0325](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/48162df2-b767-420e-a3d2-86c67ddbca33)

**Comment by ConeDjordjic** [comment]
> why dont u guys change dll of skin changer like cslol did?

ignore the guy copy pasting. 
the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded

**Comment by Pierreluc23** [comment]
> > why dont u guys change dll of skin changer like cslol did?
> 
> ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded

Vanguard prevent injection it why it not working with Vanguard.

**Comment by ConeDjordjic** [comment]
> > > why dont u guys change dll of skin changer like cslol did?
> > 
> > 
> > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> 
> Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> 
> On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)

you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

**Comment by Pierreluc23** [comment]
> > > > why dont u guys change dll of skin changer like cslol did?
> > > 
> > > 
> > > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> > 
> > 
> > Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> > On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)
> 
> you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

I will clairfy again on the photo when Vanguard is running it not inject it show not injected 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/996c9335-eef9-473b-9e90-cfd186d1dbd7)

**Comment by Pierreluc23** [comment]
> > > > why dont u guys change dll of skin changer like cslol did?
> > > 
> > > 
> > > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> > 
> > 
> > Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> > On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)
> 
> you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

R3nzSkin inject only when Vanguard is not running 
![IMG_0219](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/f92ec27e-444e-4fee-87e2-8b6aa34766e8)

**Comment by Pierreluc23** [comment]
> > > > why dont u guys change dll of skin changer like cslol did?
> > > 
> > > 
> > > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> > 
> > 
> > Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> > On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)
> 
> you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

Vanguard prevent injection from a comment on zoomhack with Vanguard 
![IMG_0326](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/369cb061-3c85-415c-8485-e147a667afef)

**Comment by Pierreluc23** [comment]
> why dont u guys change dll of skin changer like cslol did?

Because R3nzSkin worked as ZoomHack and Vanguard have broken it 
![IMG_0326](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/ca14aa5a-4d7a-4c1e-99f0-c25dfa7251c1)

**Comment by Pierreluc23** [comment]
> > > > why dont u guys change dll of skin changer like cslol did?
> > > 
> > > 
> > > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> > 
> > 
> > Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> > On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)
> 
> you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

If it was the case it would inject 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/dc64d90e-c516-4750-a90d-f81884feb87e)

**Comment by Pierreluc23** [comment]
https://www.leagueoflegends.com/en-us/news/dev/dev-null-anti-cheat-kernel-driver/

**Comment by Pierreluc23** [comment]
> > why dont u guys change dll of skin changer like cslol did?
> 
> ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded

R3nzSkin do not work because of Vanguard who running in ring 0 
![IMG_0330](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/400fcdf8-4e16-411d-ad70-3215be14bd18)

**Comment by Pierreluc23** [comment]
> why dont u guys change dll of skin changer like cslol did?

R3nzSkin is not working with Ring 0 anti cheat 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/2b9bc9e5-cac3-4c12-ac92-47a7ee1a4f7f)

![IMG_0330](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/400fcdf8-4e16-411d-ad70-3215be14bd18)

The photo is from this article in 2020 https://www.leagueoflegends.com/en-us/news/dev/dev-null-anti-cheat-kernel-driver/

**Comment by Pierreluc23** [comment]
> > > > why dont u guys change dll of skin changer like cslol did?
> > > 
> > > 
> > > ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded
> > 
> > 
> > Vanguard prevent injection it why R3nzSkin is not working with Vanguard ![IMG_0079](https://private-user-images.githubusercontent.com/168309875/334187889-686f1287-8cc9-4c0b-a379-66de9a3bbc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg3ODg5LTY4NmYxMjg3LThjYzktNGMwYi1hMzc5LTY2ZGU5YTNiYmMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlMjVjZWUzNTIwZjBmNmY4OWI2NTFjMzE4MjA3N2YxNTY1OWY3OTg0ODgxMDBmYzlmOTJjYmVkMjFhZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4LkEVgFfwp8hEAiUyCmmQQgk_s_ApViwaOG9tnYzhe4)
> > On patch 14.10 R3nzSkin work when Vanguard is not running ![IMG_0219](https://private-user-images.githubusercontent.com/168309875/334188401-4e65bed2-d778-4660-9f3a-f59293e31580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3NjEsIm5iZiI6MTcxNjgzNTQ2MSwicGF0aCI6Ii8xNjgzMDk4NzUvMzM0MTg4NDAxLTRlNjViZWQyLWQ3NzgtNDY2MC05ZjNhLWY1OTI5M2UzMTU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjUzOTdiMGExY2JkZjg2ZDg5ZmJhNzZiYjQ4OTc1MmI5ZGMwMGIwNTBhZGIzZDExNzIwOTI5YWE5ZmQyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vf_EfH-QjM8aGRzJxxtZ1F7LoC_RyYjNqDWC_LN5p0Y)
> 
> you cannot prevent dll injections. what you can prevent is messing with game memory which is exactly what vanguard does

Not clear if Vanguard prevent dll injection but R3nzSkin is not working with Vanguard 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/9467eed6-8678-42bf-a6e0-10a6929369a8)

**Comment by Pierreluc23** [comment]
> > why dont u guys change dll of skin changer like cslol did?
> 
> ignore the guy copy pasting. the issue is that the way r3nz skin changes skins is directly through the memory which vanguard forbids and as of right now there are no public methods to avoid getting detected. however, cslol doesn't mess with the game memory, instead when the game calls createfilea to load ur skin, the hook detours and loads the skin you want instead of what it thinks it loaded

The problem is not the detection the problem is Vanguard who prevent R3nzSkin to work in memory 
![IMG_0079](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/7768b939-9503-4b47-93b2-ee3c4f3d9e18)
