### ISSUE TITLE
Anyone has UPDATE?

### ISSUE THREAD

**Issue by Alby2000** [R3nzTheCodeGOD/R3nzSkin#1148]
Hi,

Does anybody has update i know R3nzSkin'll not comeback since it loads in memory and vanguard block that, but maybe do you have any informations or discord/ about a future skin changer, thanks.

Btw don't use : GadzoSense, this guy is a pure scammer all his versions of skin changer are not working take care.

**Comment by SomethingSomethingDarkS** [comment]
If you find one let me know too
