### ISSUE TITLE
Failed to find pattern error after new update

### ISSUE THREAD

**Issue by kretcee** [R3nzTheCodeGOD/R3nzSkin#115]
![image](https://user-images.githubusercontent.com/58228910/170241190-26cb8025-e8c7-4e60-b5ae-9dd0dac11af0.png)

**Comment by alphaaced** [comment]
Was just about to post. I have the same issue.

**Comment by Salim-Bek** [comment]
Same

**Comment by Gasferr** [comment]
the same mistake

**Comment by yxngh** [comment]
just wait for update

**Comment by R3nzTheCodeGOD** [comment]
fixed
