### ISSUE TITLE
"failed to find pattern" does anyone know how to update r3nzskin, I wanna keep using it because there's no vanguard in china

### ISSUE THREAD

**Issue by Maqpwa** [R3nzTheCodeGOD/R3nzSkin#1150]

**Comment by Maqpwa** [comment]
![failed](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/156267450/36cfeb69-402a-4c3f-87e5-04ac1cadc76a)

**Comment by Pierreluc23** [comment]
Have the new offsets and compile the apps as on this tutorial https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2
