### ISSUE TITLE
I'm able to crack most of the skins myself and will do it one time for one of you

### ISSUE THREAD

**Issue by Shoush9** [R3nzTheCodeGOD/R3nzSkin#1157]
(SERIOUS)

Hello,

I managed to crack many of lol skins who work (even better) like r3nz but I will only share with one of you, ONE of the skins of your choice (that's automatically updated so dont worry about the patch) if you gift me 3 days xp boost (250 rp). 

I can only do it for one person because I need only one xp boost (i'm actually hand leveling a new acc) and dont want to make profit of the crack (bcz it's not legal). 

So if someone is seriously interested by getting a skin in exchange of 3 days xp boost just add me on discord : shoshondes_55278

If you want to know why  I dont make it available to everyone, it is because some people will want to use it to make profit by selling it to others (I saw some disc doing that) and to protect the method i'm using to crack.

**Comment by Pierreluc23** [comment]
With the crack you buy skin for free and everyone see it in game or it only a skin changer only you in game see it ?

**Comment by Shoush9** [comment]
> With the crack you buy skin for free and everyone see it in game or it only a skin changer only you in game see it ?

Its like skin changer mate, you only see it with how many accounts u want and it's completely safe

**Comment by Pierreluc23** [comment]
> > With the crack you buy skin for free and everyone see it in game or it only a skin changer only you in game see it ?
> 
> Its like skin changer mate, you only see it with how many accounts u want and it's completely safe

My question is if everyone see the skin or if only you see it.

**Comment by Shoush9** [comment]
> > > With the crack you buy skin for free and everyone see it in game or it only a skin changer only you in game see it ?
> > 
> > 
> > Its like skin changer mate, you only see it with how many accounts u want and it's completely safe
> 
> My question is if everyone in game see the skin or if only you see it.

As I said mate, you only see it

**Comment by Pierreluc23** [comment]
> > > > With the crack you buy skin for free and everyone see it in game or it only a skin changer only you in game see it ?
> > > 
> > > 
> > > Its like skin changer mate, you only see it with how many accounts u want and it's completely safe
> > 
> > 
> > My question is if everyone in game see the skin or if only you see it.
> 
> As I said mate, you only see it

On thank for the answer.

**Comment by Souplax1** [comment]
wdym , crack ? Bro u got .fantome files. Stop lying you did smth ,everyone knows from where u got it . Ainz said not to share files , so delete ur topic

**Comment by Valkyrrr** [comment]
Can i get the discord link for the ainz thing and is it paid

**Comment by Shoush9** [comment]
> wdym , crack ? Bro u got .fantome files. Stop lying you did smth ,everyone knows from where u got it . Ainz said not to share files , so delete ur topic

Hello,

I don't know who Ainz is btw but don't think that he's the only one who can crack the skins. Idk wich method he uses but mines work for sure and at the same time, don't judge people without having concrete proof.

Thanks for your understanding

**Comment by Shoush9** [comment]
For those who wish it the offer is still valid, only serious people, please and DM to my discord !



Little reminder : 

1) My skins are of very good quality, there are all the spells and recall animations. 

2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.

3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.

4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.

**Comment by Pierreluc23** [comment]
> For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> 
> Little reminder :
> 
> 1. My skins are of very good quality, there are all the spells and recall animations.
> 
> 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> 
> 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> 
> 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.

You send the skin in a gift ?

**Comment by Pierreluc23** [comment]
> For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> 
> Little reminder :
> 
> 1. My skins are of very good quality, there are all the spells and recall animations.
> 
> 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> 
> 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> 
> 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.

About this So if someone is seriously interested by getting a skin in exchange of 3 days xp boost just add me on discord : shoshondes_55278 you send the skin in a gift on the client or you send skin cracked files ?

**Comment by Pierreluc23** [comment]
> For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> 
> Little reminder :
> 
> 1. My skins are of very good quality, there are all the spells and recall animations.
> 
> 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> 
> 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> 
> 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.

For use your cracked skin it need to use cslol-manager ?

**Comment by Pierreluc23** [comment]
> I managed to crack many of lol skins who work (even better) like r3nz but I will only share with one of you, ONE of the skins of your choice (that's automatically updated so dont worry about the patch) 

How the cracked skin file do not broken on patch ?

**Comment by Shoush9** [comment]
> > For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> > Little reminder :
> > 
> > 1. My skins are of very good quality, there are all the spells and recall animations.
> > 
> > 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> > 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> > 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.
> 
> For use your cracked skin files it need to use cslol-manager ? ![IMG_0339](https://private-user-images.githubusercontent.com/168309875/335732020-9e7ec8c3-1702-489d-a8e1-813831c56526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI1MDgsIm5iZiI6MTcxNzE5MjIwOCwicGF0aCI6Ii8xNjgzMDk4NzUvMzM1NzMyMDIwLTllN2VjOGMzLTE3MDItNDg5ZC1hOGUxLTgxMzgzMWM1NjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTA1ZDI4ZDcxZmI2YWUwODI3ZDMwM2EyZDE0M2VlMWM3NDg4Y2MzMzFlN2ZiNjY0OWIyZTFlNTVjMWZhNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxXc39cO-HgSQQLh5FOQ92Jr7TOnt20vTx56eil3kJ8)

Hello you can use without or with it, it's your choice, but the second choice is easier for sure

**Comment by Shoush9** [comment]
> > I managed to crack many of lol skins who work (even better) like r3nz but I will only share with one of you, ONE of the skins of your choice (that's automatically updated so dont worry about the patch)
> 
> How the cracked skins files automatically update for future patch ?

I coded it in a way it still works even after update.

**Comment by Pierreluc23** [comment]
> > > For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> > > Little reminder :
> > > 
> > > 1. My skins are of very good quality, there are all the spells and recall animations.
> > > 
> > > 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> > > 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> > > 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.
> > 
> > 
> > For use your cracked skin files it need to use cslol-manager ? ![IMG_0339](https://private-user-images.githubusercontent.com/168309875/335732020-9e7ec8c3-1702-489d-a8e1-813831c56526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI1MDgsIm5iZiI6MTcxNzE5MjIwOCwicGF0aCI6Ii8xNjgzMDk4NzUvMzM1NzMyMDIwLTllN2VjOGMzLTE3MDItNDg5ZC1hOGUxLTgxMzgzMWM1NjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTA1ZDI4ZDcxZmI2YWUwODI3ZDMwM2EyZDE0M2VlMWM3NDg4Y2MzMzFlN2ZiNjY0OWIyZTFlNTVjMWZhNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxXc39cO-HgSQQLh5FOQ92Jr7TOnt20vTx56eil3kJ8)
> 
> Hello you can use without or with it, it's your choice, but the second choice is easier for sure

And what is the second choice ?

**Comment by Shoush9** [comment]
> > > > For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> > > > Little reminder :
> > > > 
> > > > 1. My skins are of very good quality, there are all the spells and recall animations.
> > > > 
> > > > 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> > > > 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> > > > 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.
> > > 
> > > 
> > > For use your cracked skin files it need to use cslol-manager ? ![IMG_0339](https://private-user-images.githubusercontent.com/168309875/335732020-9e7ec8c3-1702-489d-a8e1-813831c56526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI1MDgsIm5iZiI6MTcxNzE5MjIwOCwicGF0aCI6Ii8xNjgzMDk4NzUvMzM1NzMyMDIwLTllN2VjOGMzLTE3MDItNDg5ZC1hOGUxLTgxMzgzMWM1NjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTA1ZDI4ZDcxZmI2YWUwODI3ZDMwM2EyZDE0M2VlMWM3NDg4Y2MzMzFlN2ZiNjY0OWIyZTFlNTVjMWZhNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxXc39cO-HgSQQLh5FOQ92Jr7TOnt20vTx56eil3kJ8)
> > 
> > 
> > Hello you can use without or with it, it's your choice, but the second choice is easier for sure
> 
> And what is the second choice ?

1st is without it 
2nd is with it

**Comment by Pierreluc23** [comment]
> > > > > For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> > > > > Little reminder :
> > > > > 
> > > > > 1. My skins are of very good quality, there are all the spells and recall animations.
> > > > > 
> > > > > 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> > > > > 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> > > > > 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.
> > > > 
> > > > 
> > > > For use your cracked skin files it need to use cslol-manager ? ![IMG_0339](https://private-user-images.githubusercontent.com/168309875/335732020-9e7ec8c3-1702-489d-a8e1-813831c56526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI1MDgsIm5iZiI6MTcxNzE5MjIwOCwicGF0aCI6Ii8xNjgzMDk4NzUvMzM1NzMyMDIwLTllN2VjOGMzLTE3MDItNDg5ZC1hOGUxLTgxMzgzMWM1NjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTA1ZDI4ZDcxZmI2YWUwODI3ZDMwM2EyZDE0M2VlMWM3NDg4Y2MzMzFlN2ZiNjY0OWIyZTFlNTVjMWZhNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxXc39cO-HgSQQLh5FOQ92Jr7TOnt20vTx56eil3kJ8)
> > > 
> > > 
> > > Hello you can use without or with it, it's your choice, but the second choice is easier for sure
> > 
> > 
> > And what is the second choice ?
> 
> 1st is without it 2nd is with it

And without it copy paste file on the client ?

**Comment by Shoush9** [comment]
> > > > > > For those who wish it the offer is still valid, only serious people, please and DM to my discord !
> > > > > > Little reminder :
> > > > > > 
> > > > > > 1. My skins are of very good quality, there are all the spells and recall animations.
> > > > > > 
> > > > > > 2)I don't have all the skins (since I don't play all the champions) therefore, if you ask me for a skin that I don't have, I will come to you after cracking it. Feel free to ask the skin you really want to have.
> > > > > > 3)As I said, this service is only available for one person. I just need a 3 day experience boost in exchange. Maybe I'll apply again, if this boost isn't enough.
> > > > > > 4)I don't steal other people's files, skins are cracked from A-Z by me (I modified the game files) and are safe to use.
> > > > > 
> > > > > 
> > > > > For use your cracked skin files it need to use cslol-manager ? ![IMG_0339](https://private-user-images.githubusercontent.com/168309875/335732020-9e7ec8c3-1702-489d-a8e1-813831c56526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI1MDgsIm5iZiI6MTcxNzE5MjIwOCwicGF0aCI6Ii8xNjgzMDk4NzUvMzM1NzMyMDIwLTllN2VjOGMzLTE3MDItNDg5ZC1hOGUxLTgxMzgzMWM1NjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTA1ZDI4ZDcxZmI2YWUwODI3ZDMwM2EyZDE0M2VlMWM3NDg4Y2MzMzFlN2ZiNjY0OWIyZTFlNTVjMWZhNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxXc39cO-HgSQQLh5FOQ92Jr7TOnt20vTx56eil3kJ8)
> > > > 
> > > > 
> > > > Hello you can use without or with it, it's your choice, but the second choice is easier for sure
> > > 
> > > 
> > > And what is the second choice ?
> > 
> > 
> > 1st is without it 2nd is with it
> 
> Without use Cslol manager just copy paste the cracked skins files on the client ?

Hello, I think I have replied to enough of your questions. 

If you're interested to have a skin of your choice against 3 days xp boost, just dm me. Thx

**Comment by pingwinekZ** [comment]
rope

**Comment by Shoush9** [comment]
> rope
yourself ^^

**Comment by Shoush9** [comment]
Okay guys, I already made a deal with someone, so the offer is over.

**Comment by ZHA-TIAN-gang-yi-huan-zhao** [comment]
> wdym ， 裂纹 ？兄弟你得到了 .fantome 文件。别再撒谎了，你做了smth，每个人都知道你从哪里得到的。Ainz 说不要共享文件，所以删除你的主题
What you said is true, but in fact, this person’s skin fantome is unique, that is, he made it himself, and it is not someone else’s on the Internet, because I have not seen the same fantome on other fantome websites. Documentary
