### ISSUE TITLE
So how does this work exactly, canu release a tutorial or somekind of explanation or is not done yet? many thanks

### ISSUE THREAD

**Issue by T9Jungler** [R3nzTheCodeGOD/R3nzSkin#1163]
So how does this work exactly, canu release a tutorial or somekind of explanation or is not done yet? many thanks

_Originally posted by @ComplexQa in https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1162#issuecomment-2143449578_

you got on dc how it looks like, you got all skins in that program and you can just take wich you want and move to cslolmenager and run it like custom skin

**Comment by ComplexQa** [comment]
yea but how do i download the program or whatever is being used here, theres nothing in discord
