### ISSUE TITLE
Get available .fantom files 

### ISSUE THREAD

**Issue by keyg777** [R3nzTheCodeGOD/R3nzSkin#1172]
I get available .fantom files from Discord : shoshondes_55278 , 
he only do the same versus 3 days xp boost (260 rp) in euw server 
I got aatrox White dazzle ，I tried it and it worked great, it's real
His skins are completely clean.
Interested in going Discord : shoshondes_55278
Contact him

**Comment by Shoush9** [comment]
Hello Keyg777,


Thanks for your message,

Btw guys, I don't sell skins against money because it's not ethical for me (so please don't DM against money). Actually I just need xp boost because i'm leveling a new account. Without that need, I won't even crack you skins.

Regards,

Shoshondes_55278

**Comment by ZHA-TIAN-gang-yi-huan-zhao** [comment]
I found this guy in discord: Shoshondes, and after we communicated, I got a project called cslol from him. This project allows us to freely change skins in League of Legends. He gave me Yasuo’s Nightbringer skin for free.
This guy is completely trustworthy. As he said, he doesn't need us to give him money. He only needs a cheap experience accelerator card. This is to quickly upgrade his new account.
![Uploading image1.png…]()

**Comment by ZHA-TIAN-gang-yi-huan-zhao** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/171529353/fbaf4c00-cdc6-44d3-bd02-d52a9a50324d)
<img width="843" alt="15908934691cf522827aaa72346787e" src="https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/171529353/3f5a1874-22f5-47ef-986f-90386495e56b">

**Comment by ZHA-TIAN-gang-yi-huan-zhao** [comment]
![Uploading image.png…]()

**Comment by ZHA-TIAN-gang-yi-huan-zhao** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
