### ISSUE TITLE
Update when??

### ISSUE THREAD

**Issue by Alaric1st** [R3nzTheCodeGOD/R3nzSkin#1179]
are you guys not updating because of the new vangaurd for league or is it another issue? becuase i seriously miss this mod so much.

**Comment by Pierreluc23** [comment]
![IMG_0347](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/1b4ec457-2ceb-4cb5-8be1-a44198d7f441)

**Comment by Alaric1st** [comment]
ahh that's too bad, thanks anyways
