### ISSUE TITLE
Gun Goddess Miss Fortune bug 

### ISSUE THREAD

**Issue by HackPC** [R3nzTheCodeGOD/R3nzSkin#118]
Skin Gun Goddess Miss Fortune  bug with no VO no skill effect Q E and R 
![image](https://user-images.githubusercontent.com/20665028/170419623-fdeac683-10e6-4810-b40e-752fd0ee828f.png)
 R Ultimate
![image](https://user-images.githubusercontent.com/20665028/170419683-51e61e2a-9948-44c3-8ce6-0f05c216e2ec.png)

**Comment by Clownsw** [comment]
# 1

**Comment by Clownsw** [comment]
#1
