### ISSUE TITLE
新的源项目地址 New source project address

### ISSUE THREAD

**Issue by YCRyan** [R3nzTheCodeGOD/R3nzSkin#1181]
在这个源项目问题中有人使用偏移生成了400kb大小的dll文件，但是容易被中国服务器vac封禁，我提供了一个新的源项目地址，其中生成了700kb的dll文件，可能包含反vac封禁？
In this source project problem, someone used the offset to generate a 400kb dll file, but it was easy to be blocked by the Chinese server vac. I provided a new source project address, which generated 700kb dll file, may contain anti-VAC blocked?
源项目地址 Source item address：https://github.com/Xuemantou/R3nzSkin-For-China-Server
DLL/zip/tar.gz： https://github.com/Xuemantou/R3nzSkin-For-China-Server/releases/tag/3.3.3

**Comment by Zz291** [comment]
兄弟能测试一下会不会被封吗

**Comment by M1tsuha3** [comment]
在试了

**Comment by Zz291** [comment]
> 在试了

ok，等你消息

**Comment by M1tsuha3** [comment]
自定义和大乱斗都试了 目前还没封

**Comment by Pierreluc23** [comment]
> 在这个源项目问题中有人使用偏移生成了400kb大小的dll文件，但是容易被中国服务器vac封禁，我提供了一个新的源项目地址，其中生成了700kb的dll文件，可能包含反vac封禁？ In this source project problem, someone used the offset to generate a 400kb dll file, but it was easy to be blocked by the Chinese server vac. I provided a new source project address, which generated 700kb dll file, may contain anti-VAC blocked? 源项目地址 Source item address：https://github.com/Xuemantou/R3nzSkin-For-China-Server DLL/zip/tar.gz： https://github.com/Xuemantou/R3nzSkin-For-China-Server/releases/tag/3.3.3

This really work on Riot server ? 
![IMG_0352](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/168309875/0d838faa-2e3e-4274-9a9d-708c960930b8)

**Comment by KomariVGC** [comment]
腾讯服目前良好

**Comment by wiki9012** [comment]
不知道，然后呢

**Comment by J-EnJay** [comment]
> 不知道，然后呢

不知道就别拿这词不懂装懂了

**Comment by wiki9012** [comment]
vac是Valve反作弊技术，我经常玩cs，也经常去cs社区跟社区作者聊天，所以刚刚用vac是错误的，为你道歉，请你不要对我抱有恶意

**Comment by Agan-ippe** [comment]
多出来的300kb是怎么做的，我拉取项目自己生成还是400

**Comment by AmbitionKwils** [comment]
这个怎么使用

**Comment by YCRyan** [comment]
截止到目前还可以运行
使用和原来的方式一样，改名为hid.dll游戏内按下inside键
As of now it is working
Use the same way as the original, renamed hid.dll in-game press the inside key
提示：为防止意外，请不要在大厅长时间等待
Tip: To prevent accidents, please do not wait for a long time in the lobby

**Comment by Zz291** [comment]
到今天没有兄弟被封吗

**Comment by makabaka2869** [comment]
> 到今天没有兄弟被封吗

已经被封3年了，第三方软件加载，正在尝试减刑

**Comment by Tensor-king** [comment]
> > 到今天没有兄弟被封吗
> 
> 已经被封3年了，第三方软件加载，正在尝试减刑

shit

**Comment by Theo-ZYF** [comment]
> > 到今天没有兄弟被封吗
> 
> 已经被封3年了，第三方软件加载，正在尝试减刑

确定吗？用这个封了三年？没见封这么久的

**Comment by mandxy** [comment]
这个就是改了这个偏移量吗？这个我早改了，但是别人用我改的也说封号
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/43473135/b51810ff-989d-47ac-b8a5-df4bb62d714e)

**Comment by makabaka2869** [comment]
> > > 到今天没有兄弟被封吗
> > 
> > 
> > 已经被封3年了，第三方软件加载，正在尝试减刑
> 
> 确定吗？用这个封了三年？没见封这么久的

额，这有啥骗人的吗，没看其他问题底下也很多被封的吗，封就封了，都在国服用换肤了，怕就别用的心理

**Comment by mandxy** [comment]
删我评论了？

**Comment by YCRyan** [comment]
> > > > 到今天没有兄弟被封吗
> > > 
> > > 
> > > 已经被封3年了，第三方软件加载，正在尝试减刑
> > 
> > 
> > 确定吗？用这个封了三年？没见封这么久的
> 
> 额，这有啥骗人的吗，没看其他问题底下也很多被封的吗，封就封了，都在国服用换肤了，怕就别用的心理

你是怎么用这个生成的，改了me*.hpp  然后运行me*.cpp那个文件？
直接使用这个生成的可以用，大小只有400kb左右，容易被反查到
不封的版本有700kb，详情去我主问题的两个链接看看

**Comment by makabaka2869** [comment]
> > > > > 到今天没有兄弟被封吗
> > > > 
> > > > 
> > > > 已经被封3年了，第三方软件加载，正在尝试减刑
> > > 
> > > 
> > > 确定吗？用这个封了三年？没见封这么久的
> > 
> > 
> > 额，这有啥骗人的吗，没看其他问题底下也很多被封的吗，封就封了，都在国服用换肤了，怕就别用的心理
> 
> 你是怎么用这个生成的，改了me*.hpp 然后运行me*.cpp那个文件？ 直接使用这个生成的可以用，大小只有400kb左右，容易被反查到 不封的版本有700kb，详情去我主问题的两个链接看看

用的就是700多的，马服封号很正常，啥换肤到马服都得封，没事感谢分享，我号比较多，没事

**Comment by qw19696** [comment]
台服可以用吗

**Comment by suomia951** [comment]
黑屏

**Comment by Theo-ZYF** [comment]
> 黑屏

同样黑屏 您解决了吗？

**Comment by scy333666** [comment]
> > 黑屏
> 
> 同样黑屏 您解决了吗？

降级英伟达驱动

**Comment by BeginnerDone** [comment]
已经被封一周，然后申诉减罚了，以前的确实没有问题，从没被封过，用了这个直接G，慎重。

**Comment by TheNei** [comment]
家人们真封了嘛

**Comment by YCRyan** [comment]
> 已经被封一周，然后申诉减罚了，以前的确实没有问题，从没被封过，用了这个直接G，慎重。

是用的我链接里源代码那个dll吗，可以提供一下更详细的描述吗，比如开了什么对局（排位？匹配？训练？）做了什么事，还有就是有没有在大厅长时间挂机

**Comment by zreybn** [comment]
被封了七天

**Comment by zreybn** [comment]
排位模式就玩了两把，没有在大厅

**Comment by Zz291** [comment]
老哥现在这个版本还有 办法更新不

**Comment by YCRyan** [comment]
版本更新后dll版本进游戏闪退，删掉dll文件等待下次更新

**Comment by makabaka2869** [comment]
> 版本更新后dll版本进游戏闪退，删掉dll文件等待下次更新

这个版本进游戏，没有错误偏移量显示，好更新不兄弟
