### ISSUE TITLE
There is a guy who gives skins as .fantome archives 100% safe

### ISSUE THREAD

**Issue by theendofmanu** [R3nzTheCodeGOD/R3nzSkin#1184]
I found him here, I talked to him, he was really nice and he gave me the skin I was looking for, I recommend it. The files are totally secure. Discord: shoshondes_55278

**Comment by SomethingSomethingDarkS** [comment]
is it for free or paid?

**Comment by Boardock** [comment]
Its free and he is literally the goat of all time actually works you just have to be polite.

**Comment by JinkiraY** [comment]
add me on discord for fantome files zxytoxd6796
