### ISSUE TITLE
Is there a kind person who can update 14.12

### ISSUE THREAD

**Issue by AKINA-N** [R3nzTheCodeGOD/R3nzSkin#1194]
Or provide an offset

**Comment by 1065884693** [comment]
You can try this, I tried it and it works fine in version 14.12

https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1#
提取码：mpfj
![图片1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/67002017/f5cd98f3-57b0-4407-84dc-49505089c6fd)

**Comment by 1065884693** [comment]
You can try this, I tried it and it works fine in version 14.12

https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1#
提取码：mpfj
![QQ截图20240614104616](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/67002017/b6dcda2d-d10c-4fe6-814d-d22483478d15)

**Comment by kjohn10** [comment]
> You can try this, I tried it and it works fine in version 14.12
> 
> https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# Extraction code: mpfj ![QQ screenshot 20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE1MjYsIm5iZiI6MTcxODM0MTIyNiwicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjZjOTgwMTE4MWU3NzJjMTQ5Yzc3MGM5OWVlMDdjMmMwMmRhNWUzMzlkZDg2Zjk1YWMwOTM0ZmQ2ZWU2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfrYjGWU934kDBQF2Wjy_b0Kcg20raxCvwz3JDwb1jg)

Is this only for chinese server? or it works on riot server?

**Comment by 1065884693** [comment]
> > You can try this, I tried it and it works fine in version 14.12
> > https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# Extraction code: mpfj ![QQ screenshot 20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE1MjYsIm5iZiI6MTcxODM0MTIyNiwicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjZjOTgwMTE4MWU3NzJjMTQ5Yzc3MGM5OWVlMDdjMmMwMmRhNWUzMzlkZDg2Zjk1YWMwOTM0ZmQ2ZWU2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfrYjGWU934kDBQF2Wjy_b0Kcg20raxCvwz3JDwb1jg)
> 
> Is this only for chinese server or it works on riot server?



> > You can try this, I tried it and it works fine in version 14.12
> > https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# Extraction code: mpfj ![QQ screenshot 20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE1MjYsIm5iZiI6MTcxODM0MTIyNiwicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjZjOTgwMTE4MWU3NzJjMTQ5Yzc3MGM5OWVlMDdjMmMwMmRhNWUzMzlkZDg2Zjk1YWMwOTM0ZmQ2ZWU2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfrYjGWU934kDBQF2Wjy_b0Kcg20raxCvwz3JDwb1jg)
> 
> Is this only for chinese server or it works on riot server?

chinese server

**Comment by Xuemantou** [comment]
> You can try this, I tried it and it works fine in version 14.12
> 
> https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# 提取码：mpfj ![QQ截图20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDg5ODMsIm5iZiI6MTcxODM0ODY4MywicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA3MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTcyOTIwNzA2YjE0OWY1MDVlMDExZjE1MzM3NmYyMDQxNzUwYTBiOWM0YzZiYTc1Y2YzMzk2ZGE2MjRlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3JQ0bOxMeascOrHOH3UreJYlmelBrQJtv56FKqVyf4)

hey my friend , how did you repair it .

**Comment by xslzlccc** [comment]
> mpfj

兄弟，这个带steam盗号病毒，别下。

**Comment by xslzlccc** [comment]
> You can try this, I tried it and it works fine in version 14.12
> 
> https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# 提取码：mpfj ![QQ截图20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjAxOTIsIm5iZiI6MTcxODM1OTg5MiwicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwMTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMmVmZjBkZTI2YTlkODJlNzBmOTBiOTQ0NGFmMjRmOWI4YzFkM2YxODgxMTYyMjkxOTc5ODQ3ZTU0OTc2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBxo38NtQHsruR_VBjmCyy_3u4AZPRHescW8hEkeCIc)

艹你mother的，想骗你工人爷爷的steam账号？eat屎去吧

**Comment by xslzlccc** [comment]
> > You can try this, I tried it and it works fine in version 14.12
> > https://pan.xunlei.com/s/VO-JcfcPGuXv6_OEZC8K9WKoA1# 提取码：mpfj ![QQ截图20240614104616](https://private-user-images.githubusercontent.com/67002017/339615309-b6dcda2d-d10c-4fe6-814d-d22483478d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDg5ODMsIm5iZiI6MTcxODM0ODY4MywicGF0aCI6Ii82NzAwMjAxNy8zMzk2MTUzMDktYjZkY2RhMmQtZDEwYy00ZmU2LTgxNGQtZDIyNDgzNDc4ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA3MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTcyOTIwNzA2YjE0OWY1MDVlMDExZjE1MzM3NmYyMDQxNzUwYTBiOWM0YzZiYTc1Y2YzMzk2ZGE2MjRlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3JQ0bOxMeascOrHOH3UreJYlmelBrQJtv56FKqVyf4)
> 
> hey my friend , how did you repair it .

这不是你的friend，他这玩意带毒

**Comment by Jingzhenzxz** [comment]
> > mpfj
> 
> 兄弟，这个带steam盗号病毒，别下。

大神，请问你是怎么测出来的？

**Comment by xslzlccc** [comment]
360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去




1808486333
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R3nzTheCodeGOD/R3nzSkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月14日(星期五) 晚上6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R3nzTheCodeGOD/R3nzSkin] Is there a kind person who can update 14.12 (Issue #1194)





   
mpfj
  
兄弟，这个带steam盗号病毒，别下。
  
大神，请问你是怎么测出来的？

**Comment by xslzlccc** [comment]
> > > mpfj
> > 
> > 
> > 兄弟，这个带steam盗号病毒，别下。
> 
> 大神，请问你是怎么测出来的？

搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。

**Comment by Eneeeee** [comment]
> > > > mpfj
> > > 
> > > 
> > > 兄弟，这个带steam盗号病毒，别下。
> > 
> > 大神，请问你是怎么测出来的？
> 
> 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。

我不知道你是怎么测出来的，我也没太在意。

我下载完之后也是不敢贸然打开，我用沙盒运行之后把hid.dll提取出来了。国服14.12是可以用的。至于这个dll是不是同样有问题，我就不敢说了。不过看了你的评论我还是去注意了一下自己的各种账号。

你如果有确切的证据可以放出来，我目前还在用里面的hid.dll。

**Comment by Eneeeee** [comment]
> > > > mpfj
> > > 
> > > 
> > > 兄弟，这个带steam盗号病毒，别下。
> > 
> > 大神，请问你是怎么测出来的？
> 
> 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。

我看里面包含了dll还有一个搜狗的tools。猜测是用输入法注入来逃避检测。你如果不了解这一段可以跳过。

沙盒给出的行为是检测进程id获取英雄联盟目录，然后把hid.dll放进game目录。这和我们平常用的r3nzskin没有本质区别。

_**注意，我没有在给这种来路不明的文件洗白。我不确定其中是否包含其他确有恶意的代码。以上纯属我的个人见解。以及目前我还在使用其中的hid.dll。发现问题我会及时回来反馈**_

顺带一提这个hid.dll是修改过的，在r3nzskin的基础上添加了build时间和一些文字（xx专版和一个qq号） 。而且page down/up快速切换皮肤的功能有问题，无法使用。只能手动去选择。

**Comment by Sikeni** [comment]
不过他这个hid.dll不会导致封号吗？

**Comment by 1065884693** [comment]
> > > > > mpfj
> > > > 
> > > > 
> > > > 兄弟，这个带steam盗号病毒，别下。
> > > 
> > > 
> > > 大神，请问你是怎么测出来的？
> > 
> > 
> > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> 
> 我看里面包含了dll还有一个搜狗的tools。猜测是用输入法注入来逃避检测。你如果不了解这一段可以跳过。
> 
> 沙盒给出的行为是检测进程id获取英雄联盟目录，然后把hid.dll放进game目录。这和我们平常用的r3nzskin没有本质区别。
> 
> _**注意，我没有在给这种来路不明的文件洗白。我不确定其中是否包含其他确有恶意的代码。以上纯属我的个人见解。以及目前我还在使用其中的hid.dll。发现问题我会及时回来反馈**_
> 
> 顺带一提这个hid.dll是修改过的，在r3nzskin的基础上添加了build时间和一些文字（xx专版和一个qq号） 。而且page down/up快速切换皮肤的功能有问题，无法使用。只能手动去选择。

I don't know how the so-called account theft virus is detected. The tool is written in Python and its purpose is only to read the game's processes and install hid files. If you have any doubts about this software, please do not use it. You cannot satisfy someone who lacks security and wants to use the software!

**Comment by HUFENGXING** [comment]
> > > > > > MPFJ公司
> > > > > 
> > > > > 
> > > > > 兄弟，这个带steam盗号病毒，别下。
> > > > 
> > > > 
> > > > 大神，请问你是怎么测出来的？
> > > 
> > > 
> > > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> > 
> > 
> > 我看里面包含了dll还有一个搜狗的tools。猜测是用输入法注入来逃避检测。你如果不了解这一段可以跳过。
> > 沙盒给出的行为是检测进程ID获取英雄联盟目录，然后把hid.dll放进game目录。这和我们平常用的r3nzskin没有本质区别。
> > _**注意，我没有在给这种来路不明的文件洗白。我不确定其中是否包含其他确有恶意的代码。以上纯属我的个人见解。以及目前我还在使用其中的hid.dll。发现问题我会及时回来反馈**_
> > 顺带一提这个hid.dll是修改过的，在r3nzskin的基础上添加了build时间和一些文字（xx专版和一个qq号） 。而且page down/up快速切换皮肤的功能有问题，无法使用。只能手动去选择。
> 
> 我不知道所谓的帐户盗窃病毒是如何检测的。该工具是用 Python 编写的，其目的只是读取游戏的进程并安装隐藏文件。如果您对本软件有任何疑问，请不要使用它。您无法满足缺乏安全性并想使用该软件的人！

这个在国服封号概率大不大

**Comment by Eneeeee** [comment]
> > > > > > > MPFJ公司
> > > > > > 
> > > > > > 
> > > > > > 兄弟，这个带steam盗号病毒，别下。
> > > > > 
> > > > > 
> > > > > 大神，请问你是怎么测出来的？
> > > > 
> > > > 
> > > > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> > > 
> > > 
> > > 我看里面包含了dll还有一个搜狗的tools。猜测是用输入法注入来逃避检测。你如果不了解这一段可以跳过。
> > > 沙盒给出的行为是检测进程ID获取英雄联盟目录，然后把hid.dll放进game目录。这和我们平常用的r3nzskin没有本质区别。
> > > _**注意，我没有在给这种来路不明的文件洗白。我不确定其中是否包含其他确有恶意的代码。以上纯属我的个人见解。以及目前我还在使用其中的hid.dll。发现问题我会及时回来反馈**_
> > > 顺带一提这个hid.dll是修改过的，在r3nzskin的基础上添加了build时间和一些文字（xx专版和一个qq号） 。而且page down/up快速切换皮肤的功能有问题，无法使用。只能手动去选择。
> > 
> > 我不知道所谓的帐户盗窃病毒是如何检测的。该工具是用 Python 编写的，其目的只是读取游戏的进程并安装隐藏文件。如果您对本软件有任何疑问，请不要使用它。您无法满足缺乏安全性并想使用该软件的人！
> 
> 这个在国服封号概率大不大

也许我的账号比较特别，我从原版r3nzskin用到现在，一般都是手动把hid放在game目录，wegame不开荣誉截图，生涯等也都不公开。一直用到现在我连一天都没被封过。如果你要用的话还是建议你先用小号测试一下，或者干脆就用小号玩。我自己是大乱斗玩家，偶尔打一打召唤师峡谷匹配。

差不多就是，别人能察觉你开换肤的要素都给他解决掉。而且我一般很少跟别人“互动”，可能也会减少被举报然后连带封号的风险吧。

_上面说的可能无用的话比较多。总结一下，从我回复这些评论开始，一直到现在我仍在使用。目前没有发现问题_

**Comment by Sikeni** [comment]
> > > > > > > > MPFJ公司
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟，这个带steam盗号病毒，别下。
> > > > > > 
> > > > > > 
> > > > > > 大神，请问你是怎么测出来的？
> > > > > 
> > > > > 
> > > > > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> > > > 
> > > > 
> > > > 我看里面包含了dll还有一个搜狗的tools。猜测是用输入法注入来逃避检测。你如果不了解这一段可以跳过。
> > > > 沙盒给出的行为是检测进程ID获取英雄联盟目录，然后把hid.dll放进game目录。这和我们平常用的r3nzskin没有本质区别。
> > > > _**注意，我没有在给这种来路不明的文件洗白。我不确定其中是否包含其他确有恶意的代码。以上纯属我的个人见解。以及目前我还在使用其中的hid.dll。发现问题我会及时回来反馈**_
> > > > 顺带一提这个hid.dll是修改过的，在r3nzskin的基础上添加了build时间和一些文字（xx专版和一个qq号） 。而且page down/up快速切换皮肤的功能有问题，无法使用。只能手动去选择。
> > > 
> > > 
> > > 我不知道所谓的帐户盗窃病毒是如何检测的。该工具是用 Python 编写的，其目的只是读取游戏的进程并安装隐藏文件。如果您对本软件有任何疑问，请不要使用它。您无法满足缺乏安全性并想使用该软件的人！
> > 
> > 
> > 这个在国服封号概率大不大
> 
> 也许我的账号比较特别，我从原版r3nzskin用到现在，一般都是手动把hid放在game目录，wegame不开荣誉截图，生涯等也都不公开。一直用到现在我连一天都没被封过。如果你要用的话还是建议你先用小号测试一下，或者干脆就用小号玩。我自己是大乱斗玩家，偶尔打一打召唤师峡谷匹配。
> 
> 差不多就是，别人能察觉你开换肤的要素都给他解决掉。而且我一般很少跟别人“互动”，可能也会减少被举报然后连带封号的风险吧。
> 
> _上面说的可能无用的话比较多。总结一下，从我回复这些评论开始，一直到现在我仍在使用。目前没有发现问题_

请问这个hid,dll怎么提取出来

**Comment by oldzhg** [comment]
> > > > > mpfj
> > > > 
> > > > 
> > > > 兄弟，这个带steam盗号病毒，别下。
> > > 
> > > 
> > > 大神，请问你是怎么测出来的？
> > 
> > 
> > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> 
> 我不知道你是怎么测出来的，我也没太在意。
> 
> 我下载完之后也是不敢贸然打开，我用沙盒运行之后把hid.dll提取出来了。国服14.12是可以用的。至于这个dll是不是同样有问题，我就不敢说了。不过看了你的评论我还是去注意了一下自己的各种账号。
> 
> 你如果有确切的证据可以放出来，我目前还在用里面的hid.dll。

这个hid.dll在哪里，我用沙盒运行后查看释放的文件中，只有hid_v1.dll和hid_v2.dll，是这两个中的一个吗，还是说是其他名字的dll，但是我都没有找到。

**Comment by Eneeeee** [comment]
> > > > > > mpfj
> > > > > 
> > > > > 
> > > > > 兄弟，这个带steam盗号病毒，别下。
> > > > 
> > > > 
> > > > 大神，请问你是怎么测出来的？
> > > 
> > > 
> > > 搜360沙箱云、微步在线云沙箱、奇安信情报沙箱，把解压完的exe丢进去。
> > 
> > 我不知道你是怎么测出来的，我也没太在意。
> > 
> > 我下载完之后也是不敢贸然打开，我用沙盒运行之后把hid.dll提取出来了。国服14.12是可以用的。至于这个dll是不是同样有问题，我就不敢说了。不过看了你的评论我还是去注意了一下自己的各种账号。
> > 
> > 你如果有确切的证据可以放出来，我目前还在用里面的hid.dll。
> 
> 这个hid.dll在哪里，我用沙盒运行后查看释放的文件中，只有hid_v1.dll和hid_v2.dll，是这两个中的一个吗，还是说是其他名字的dll，但是我都没有找到。

我使用的是sandboxie，将程序放入沙盒中运行后点击该程序的安装按钮，在隔离目录中可以找到hid.dll，释放的文件本身名字就是hid.dll。在一个叫.hidden_dlls的文件夹中。
