### ISSUE TITLE
Fantome skins

### ISSUE THREAD

**Issue by T9Jungler** [R3nzTheCodeGOD/R3nzSkin#1196]
there is a lot of .fantome skins for free, im not guy who selling that shit xd

https://www.mediafire.com/folder/qk4uqjlbsy8v4/Skinsü

**Comment by GODGODGODOGDOGDOG** [comment]
thx bro but i want to add u discord can u give discord

**Comment by T9Jungler** [comment]
> thx bro but i want to add u discord can u give discord

a.d25110
