### ISSUE TITLE
Flagged as malicious

### ISSUE THREAD

**Issue by UwUbanana** [R3nzTheCodeGOD/R3nzSkin#12]
Ehm hello...
I installed the skin changer and my antivirus flag it as a Malware.
Also i have a Virustotal scan that flag 16 different viruses.
What can I do?
Thanks

**Comment by R3nzTheCodeGOD** [comment]
if you don't trust the ready-made source, clone the repository and compile it yourself we don't force anyone to use it

**Comment by UwUbanana** [comment]
I trust you (cuz i dont know how to compile) but If I install it, can you confirm that there are no viruses?
Thanks

**Comment by R3nzTheCodeGOD** [comment]
no there is no virus inside
