### ISSUE TITLE
Cannot modify menu to simplified Chinese

### ISSUE THREAD

**Issue by GCDOP** [R3nzTheCodeGOD/R3nzSkin#120]
Please tell me how to display simplified Chinese correctly, I encountered when modifying the menu, simplified Chinese changed to?? The problem of

**Comment by sonitaaaaa** [comment]
#88 
Just change the language code to match with your language

**Comment by GCDOP** [comment]
> 
I tried this, but it still didn't work, and I noticed that it had some original Chinese support, but seemed to only support displaying skin names
