### ISSUE TITLE
new skin changer just released

### ISSUE THREAD

**Issue by JinkiraY** [R3nzTheCodeGOD/R3nzSkin#1201]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/171052446/0c713529-d1e3-4331-ad87-c167fd7c6240)

https://discord.gg/Sw5HB5ZD

**Comment by mish20011** [comment]
Can you share the discord invite link again? I got kicked out for some reason (might be because I shared a GitHub link)
