### ISSUE TITLE
Working and Safe changer.

### ISSUE THREAD

**Issue by alphaaced** [R3nzTheCodeGOD/R3nzSkin#1210]
i will link the discord, the author has fixed some broken  particles in skins aswell, he can fix all what  r3nz couldnt fix but needs donation.
https://discord.gg/xkcP7Q9Kwa

**Comment by FraudeXx** [comment]
is it safe?

**Comment by alphaaced** [comment]
> is it safe?

yeah

**Comment by NAINTIN** [comment]
Not to mention refuses to update the skinchanger unless people donated lmao imagine that might as well buy legit skins

**Comment by mish20011** [comment]
> Not to mention refuses to update the skinchanger unless people donated lmao imagine that might as well buy legit skins

he deleted the server or what, I got kicked out of the server and the invite link is expired. Not really sad because some Chinese guy managed to make R3nzskin work again but it's kinda weird to kick me out (might be because I linked the GitHub r3nzskin revamp)

**Comment by lwlxsgnet** [comment]
> > Not to mention refuses to update the skinchanger unless people donated lmao imagine that might as well buy legit skins
> 
> he deleted the server or what, I got kicked out of the server and the invite link is expired. Not really sad because some Chinese guy managed to make R3nzskin work again but it's kinda weird to kick me out (might be because I linked the GitHub r3nzskin revamp)

me too, i did nothing

**Comment by johan1357** [comment]
Go to Ainz server and watch the discussion 😂😂

**Comment by asolezz** [comment]
> Go to Ainz server and watch the discussion 😂😂

what server? can you send the invite?

**Comment by johan1357** [comment]
discord.gg/ainzskins here

**Comment by longxa762** [comment]
> > Not to mention refuses to update the skinchanger unless people donated lmao imagine that might as well buy legit skins
> 
> he deleted the server or what, I got kicked out of the server and the invite link is expired. Not really sad because some Chinese guy managed to make R3nzskin work again but it's kinda weird to kick me out (might be because I linked the GitHub r3nzskin revamp)

Yeah he ban a bunch peoples then deleted his server after getting confronted about begging for $200 to release an update when his first release is a broken mess.
