### ISSUE TITLE
Offset errors in PBE

### ISSUE THREAD

**Issue by aLonelyNetu** [R3nzTheCodeGOD/R3nzSkin#124]

**Comment by senmao1994** [comment]
> ![image](https://user-images.githubusercontent.com/58574988/172461519-f0797092-828e-4d82-b911-a67d67f5951e.png)
> 
> Update the new **GetGoldRedirectTarget** model and recompile the project (for PBE)
> 
> ```c++
> "E8 ? ? ? ? 3B F8 5F 5E 5D 0F 94 C0 5B",
> "E8 ? ? ? ? 85 C0 74 09 8B CE"
> ```

I updated it, but the game crashed

**Comment by senmao1994** [comment]
![image](https://user-images.githubusercontent.com/50578587/172526722-2e65f471-5fab-4986-888f-3ed68ae8b8b7.png)

**Comment by aLonelyNetu** [comment]
**Still in PBE:**

![League_of_Legends_JcVXyThXok](https://user-images.githubusercontent.com/77209536/173182127-f350e9aa-bb3b-48fe-9564-8f969931baea.png)
![League_of_Legends_Kp2VEOBAD3](https://user-images.githubusercontent.com/77209536/173182128-f0ac27ea-4f08-409d-a964-00cb9acc114f.png)
![League_of_Legends_yjq8S1Maa0](https://user-images.githubusercontent.com/77209536/173182131-5cd87991-a597-4ee8-820f-a7e95a7ec203.png)

**Comment by R3nzTheCodeGOD** [comment]
## `Version 12.12.447.1390 [PUBLIC]`
@aLonelyNetu @senmao1994 
```cpp
// Patterns required for PBE
{
	{
		"8B 35 ? ? ? ? 8B 56 04 8D 4E 04 8B 41 04 8D 04 82",
		"A1 ? ? ? ? 55 57 8B 78 04 8B 40 08 8D 2C 87 3B FD"
	}, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
},
{
	{
		"A3 ? ? ? ? 6A 64 6A 00",
		"8B 35 ? ? ? ? FF 15 ? ? ? ? 3B C6 75 ? 8B 0D ? ? ? ? 85 C9 74 ? 8B 01"
	}, true, true, 0, &offsets::global::Riot__g_window
},
```

**Comment by senmao1994** [comment]
> ## `Version 12.12.447.1390 [PUBLIC]`
> @aLonelyNetu @senmao1994
> 
> ```c++
> // Patterns required for PBE
> {
> 	{
> 		"8B 35 ? ? ? ? 8B 56 04 8D 4E 04 8B 41 04 8D 04 82",
> 		"A1 ? ? ? ? 55 57 8B 78 04 8B 40 08 8D 2C 87 3B FD"
> 	}, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
> },
> {
> 	{
> 		"A3 ? ? ? ? 6A 64 6A 00",
> 		"8B 35 ? ? ? ? FF 15 ? ? ? ? 3B C6 75 ? 8B 0D ? ? ? ? 85 C9 74 ? 8B 01"
> 	}, true, true, 0, &offsets::global::Riot__g_window
> },
> ```

thank you so much，it`s running

**Comment by aLonelyNetu** [comment]
> ## `Version 12.12.447.1390 [PUBLIC]`
> 
> @aLonelyNetu @senmao1994
> 
> ```c++
> // Patterns required for PBE
> {
> 	{
> 		"8B 35 ? ? ? ? 8B 56 04 8D 4E 04 8B 41 04 8D 04 82",
> 		"A1 ? ? ? ? 55 57 8B 78 04 8B 40 08 8D 2C 87 3B FD"
> 	}, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
> },
> {
> 	{
> 		"A3 ? ? ? ? 6A 64 6A 00",
> 		"8B 35 ? ? ? ? FF 15 ? ? ? ? 3B C6 75 ? 8B 0D ? ? ? ? 85 C9 74 ? 8B 01"
> 	}, true, true, 0, &offsets::global::Riot__g_window
> },
> ```

Thanks man. Now it's working! <3 
How can i get them too?
