### ISSUE TITLE
patched

### ISSUE THREAD

**Issue by uzcre** [R3nzTheCodeGOD/R3nzSkin#125]
find pattern error in jp server
![image](https://user-images.githubusercontent.com/103557901/172492940-2786b215-8e0d-4d68-9d10-cabcad6c2359.png)

**Comment by 6oody** [comment]
same in eune server
![image](https://user-images.githubusercontent.com/42409047/172526891-cd1f24af-10b3-469e-b2b1-1a19d88b4244.png)

**Comment by discordtwilight** [comment]
Add the specific pattern like shown?
