### ISSUE TITLE
Issue and donate

### ISSUE THREAD

**Issue by 2uts** [R3nzTheCodeGOD/R3nzSkin#129]
Hello the new updated version doesnt seem to work on the NA server? It just crashes the game after loading instantly. Also i would like to know if you take donations?

**Comment by R3nzTheCodeGOD** [comment]
Can you give me a NA account so I can test R3nzSkin on NA server. Btw i don't need donations.

There may even be 3 level accounts that have completed the training. To give the account, you can write to me on [discord](https://discord.com/invite/cFkyzPKAgD) or send it via [e-mail](mailto:r3nzthecodegod@gmail.com).

**Comment by R3nzTheCodeGOD** [comment]
But first of all, you can try to use the cheat again by deleting **R3nzSkin.json**, which is in the same location as **League of Legends.exe**.
![image](https://user-images.githubusercontent.com/58574988/173209762-0d46da97-2d00-4bb8-a04a-b263d4df2d71.png)

**Comment by 2uts** [comment]
I have done that and now it works thank you very much for your work
