### ISSUE TITLE
Chinese service crashed after entering the game. Is there a way to solve it?

### ISSUE THREAD

**Issue by lm0x01** [R3nzTheCodeGOD/R3nzSkin#13]
Chinese service crashed after entering the game. Is there a way to solve it?

**Comment by R3nzTheCodeGOD** [comment]
Was the previous version working?

**Comment by R3nzTheCodeGOD** [comment]
Change the `SEE_ERROR` macro in `memory.cpp` to `1` and compile it and tell me the broken pattern.

**Comment by lm0x01** [comment]
> 将宏更改为并编译它，并告诉我已损坏的模式。`SEE_ERROR``memory.cpp``1`

Without messageboxa, the game crashed
