### ISSUE TITLE
Miss Fortune

### ISSUE THREAD

**Issue by KyoumiKyoko** [R3nzTheCodeGOD/R3nzSkin#13]
Miss Fortune Gun Goddess Skin has 4 versions

![2021-08-04 14_58_02-Miss Fortune_LoL_Cosmetics _ League of Legends Wiki _ Fandom - Opera](https://user-images.githubusercontent.com/88426288/128144130-37749ef9-e8c1-4091-8f13-bda8de6a9924.png)

Would be really awesome if you can add them, and really appreciate your work on this skin changer bud!

**Comment by R3nzTheCodeGOD** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/7#issuecomment-890404019
This skin is among the skins that are broken as I mentioned here.
