### ISSUE TITLE
Suggestion: Better injector

### ISSUE THREAD

**Issue by heryoff** [R3nzTheCodeGOD/R3nzSkin#131]
Hey, I really like your work so I thought why not suggest a few additions that would be cool to have.
Here is a list:
- Hide as a tray icon
- Make startup with windows

A cool thing would be to add an option to change the map skin. Would be dope!

**Comment by alphaaced** [comment]
the startup with windows would be nice

**Comment by pmetpmetpmet** [comment]
Use the Run command "shell:startup" and put the skin-changer in the folder.
