### ISSUE TITLE
Suggest:? Changing Size of champions ?

### ISSUE THREAD

**Issue by ClockworkBN** [R3nzTheCodeGOD/R3nzSkin#132]
Hey i have idea to change size of characters in LoL 
Like on practice tool when you give +100max hp to bot or dummy

Offset was mscaleskincoef.

Thanks

**Comment by R3nzTheCodeGOD** [comment]
@ClockworkBN 
I do not think to add something like this to the R3nzSkin. If you wish, you can add using this offset.

**Offset:** `GameObj + 0x1820`

![image](https://user-images.githubusercontent.com/58574988/175988259-c6a9ab7f-cc7d-4093-bfc9-5709954afd64.png)

**Comment by ClockworkBN** [comment]
@R3nzTheCodeGOD 
Thanks for replay :) !
I see you use IDA but i can’t remember how to do it i will be grateful if you can show how to do it.
I know its your free time.. to guide ;) 
Regards.
