### ISSUE TITLE
Suggest. Turret, nexus Skins 

### ISSUE THREAD

**Issue by Xarond12** [R3nzTheCodeGOD/R3nzSkin#134]
I think it would be nice to implement turret, nexus, inhibitors skins

**Comment by R3nzTheCodeGOD** [comment]
I can add turret skins, but I'm undecided whether or not to add them

it has some downsides
- Causes the image to disappear on the minimap showing how many plates are left in the turret.
- Not every turret skin has a plate so I need to give them a default plate.(a lot of shit code and loss of performance)

![image](https://user-images.githubusercontent.com/58574988/178136373-6e6a771c-0bcb-4261-bbad-be2871649578.png)

**Comment by Xarond12** [comment]
u can add it in pull requests with or without plates for me it didn't make diffrence
