### ISSUE TITLE
The programe in the game does not work！！

### ISSUE THREAD

**Issue by quqingfei** [R3nzTheCodeGOD/R3nzSkin#138]
![image](https://user-images.githubusercontent.com/16645035/176091770-a081a786-0f2d-41e8-b718-625c5b8af840.png)
press `Insert` ，but failed to pop up the interface. LOL version 12.12

can you please add `PageUp `or `PageDown` key,  Change the skin？

**Comment by R3nzTheCodeGOD** [comment]
Which server are you playing on?
I also see that it is not injected in the screenshot, is it not injected even though the game is open?

**Comment by plokm21** [comment]
Same i'm on the Garena server and it doesn't work after 12.12 now

**Comment by quqingfei** [comment]
> Which server are you playing on? I also see that it is not injected in the screenshot, is it not injected even though the game is open?

yes! I`m on the China server play.

**Comment by R3nzTheCodeGOD** [comment]
The anti cheat on these servers seems to be blocking our dll injection method.
Get hold of the logitechled.dll in the game or go down to the kernel level for the injector.
