### ISSUE TITLE
Cooldowns with resets are displayed incorrectly

### ISSUE THREAD

**Issue by caiiiok254** [R3nzTheCodeGOD/R3nzSkin#143]
Example: Fiora's Q, Irellia's Q etc..
They're always shown as on full cd even being reset.

**Comment by R3nzTheCodeGOD** [comment]
yes, spell cooldowns do not work correctly for spells that reset, have cooldown reduced, or cast 2 times. you need to handle these spells specifically in the code.

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/144#issuecomment-1173611488
