### ISSUE TITLE
Cooldowns bar [suggestion]

### ISSUE THREAD

**Issue by caiiiok254** [R3nzTheCodeGOD/R3nzSkin#144]
Cooldowns only shown when champs are visible, so how about a cooldown bar with all champs and their summoner cd's? Porofessor have a good one but without a "haram" options.

**Comment by R3nzTheCodeGOD** [comment]
I made the spell tracker feature as an example to show that this project can be developed.
The purpose of this project is skin change, it will not serve any other field.
If there is a feature you want, reverse the game and code it.

`Please do not create any more issues for the spell tracker I have made as an example.`
