### ISSUE TITLE
Kindred skin bug

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#146]
<img width="1280" alt="League of Legends Screenshot 2022 07 07 - 15 50 52 77" src="https://user-images.githubusercontent.com/50578587/177721194-82e9fe05-25cc-4eb1-9a76-bd0e9aebcefe.png">
<img width="1280" alt="League of Legends Screenshot 2022 07 07 - 15 51 00 92" src="https://user-images.githubusercontent.com/50578587/177721207-73916329-031e-45c9-a872-e06ba65b149e.png">
<img width="1280" alt="League of Legends Screenshot 2022 07 07 - 15 51 04 63" src="https://user-images.githubusercontent.com/50578587/177721212-7dccc6f8-be9c-4de4-933a-f0d3ef06d231.png">
Kindred skin is not change

**Comment by senmao1994** [comment]
> The wolf has to update. Use w and it will most likely fix itself

![League of Legends Screenshot 2022 07 10 - 01 23 43 68](https://user-images.githubusercontent.com/50578587/178116453-ba75ca1d-a2b7-4ca4-9deb-600eee9b4702.png)
![League of Legends Screenshot 2022 07 10 - 01 23 54 58](https://user-images.githubusercontent.com/50578587/178116457-f91b1eec-9512-492f-b642-19046b2cbbcc.png)

**Comment by R3nzTheCodeGOD** [comment]
I will look into this issue. #149
