### ISSUE TITLE
Suggestion. Set to default skins after a match

### ISSUE THREAD

**Issue by xtremepipe** [R3nzTheCodeGOD/R3nzSkin#147]
Skins remain changed after a match, even with enemy champs
A toggle to default skins would be great

**Comment by i1u5** [comment]
Yup, would love to also see maybe an exception dialog if the skins are used by you, so you get to keep the same ones while enemy/ally players don't.

**Comment by R3nzTheCodeGOD** [comment]
I did not understand what you mean. this may be due to my bad english.
