### ISSUE TITLE
Character Objects

### ISSUE THREAD

**Issue by R3nzTheCodeGOD** [R3nzTheCodeGOD/R3nzSkin#149]
While the side objects of characters such as teemo and gangplank change successfully, the side objects of some characters do not. Find the reason for this by reversing the game.

**if you know of another character with broken side objects, send it here**

![image](https://user-images.githubusercontent.com/58574988/178131404-293254c8-487a-4ffd-a1d0-48f1d8f0f410.png)

`currently known issues`
- Nunu SnowBall
- Kindred Wolf

**Comment by senmao1994** [comment]
Yone skins E
![League of Legends Screenshot 2022 07 10 - 22 05 39 54](https://user-images.githubusercontent.com/50578587/178148414-d2dae010-3fba-42d2-a0fc-4104935561ea.png)
![League of Legends Screenshot 2022 07 10 - 22 05 57 56](https://user-images.githubusercontent.com/50578587/178148417-5288cedd-759e-49bf-b3cc-0ff3231651fd.png)
![League of Legends Screenshot 2022 07 10 - 22 06 12 73](https://user-images.githubusercontent.com/50578587/178148421-c9dd6536-578b-43b0-9e3d-3bb1bf11ec1d.png)
![League of Legends Screenshot 2022 07 10 - 22 06 31 17](https://user-images.githubusercontent.com/50578587/178148424-d4d4d5f9-6161-47ac-be2d-1105e6cecf9c.png)
![League of Legends Screenshot 2022 07 10 - 22 06 48 53](https://user-images.githubusercontent.com/50578587/178148425-2f6d9f97-cab5-4ed6-8039-0f47986cd5aa.png)

**Comment by alphaaced** [comment]
Is this a possible future fix? I remember one of kayns skins not changing animation. This was the first issue uploaded for the bugged skins. I also am 100% sure that anivia W (ice wall) does not appear when changing skins

**Comment by alphaaced** [comment]
There is also chosen master yi skin sword not appearing.

**Comment by alphaaced** [comment]
Idk if this counts but with the miss fortune ultimate skin you cannot pick the other choices of that skin. Pulsefire ezreal, he doesnt evolve stays same as level 1. And spirit guard udyr skin, no animation for his abilities.

**Comment by VeryNais** [comment]
@alphaaced He wrote why spiritguard udyr and pulsefire dont work in #1

**Comment by alphaaced** [comment]
@VeryNais i know but he said to mention if there are any problems

**Comment by R3nzTheCodeGOD** [comment]
> Is this a possible future fix? I remember one of kayns skins not changing animation. This was the first issue uploaded for the bugged skins. I also am 100% sure that anivia W (ice wall) does not appear when changing skins

> Idk if this counts but with the miss fortune ultimate skin you cannot pick the other choices of that skin. Pulsefire ezreal, he doesnt evolve stays same as level 1. And spirit guard udyr skin, no animation for his abilities.

> @VeryNaisbiliyorum ama sorun olursa söylememi söyledi

You misunderstood, I'm talking about the unchanging skins of the sub-objects of the characters, such as nunu snowball, kindred wolf.

You are talking about broken particles and sounds in some skins of champions, I can't fix them. #1

**Comment by alphaaced** [comment]
> > Is this a possible future fix? I remember one of kayns skins not changing animation. This was the first issue uploaded for the bugged skins. I also am 100% sure that anivia W (ice wall) does not appear when changing skins
> 
> > Idk if this counts but with the miss fortune ultimate skin you cannot pick the other choices of that skin. Pulsefire ezreal, he doesnt evolve stays same as level 1. And spirit guard udyr skin, no animation for his abilities.
> 
> > @VeryNaisbiliyorum ama sorun olursa söylememi söyledi
> 
> You misunderstood, I'm talking about the unchanging skins of the sub-objects of the characters, such as nunu snowball, kindred wolf.
> 
> You are talking about broken particles and sounds in some skins of champions, I can't fix them. #1

Oh im sorry, if you mean like that. So the Anivia W and Chosen master yi are broken particles?

**Comment by R3nzTheCodeGOD** [comment]
> Oh im sorry, if you mean like that. So the Anivia W and Chosen master yi are broken particles?

yes it's just a problem with chosen masteryi skin also anivia wall works correctly on their first skin

**Comment by alphaaced** [comment]
> > Oh im sorry, if you mean like that. So the Anivia W and Chosen master yi are broken particles?
> 
> yes it's just a problem with chosen masteryi skin also anivia wall works correctly on their first skin
> 
> 

Oh okay. If you try the anivia skin paper craft and the recent one, it doesnt work(no wall visible only color). Is it also offset like the kayn and yaso and Zed issues?

**Comment by alphaaced** [comment]
> > Oh im sorry, if you mean like that. So the Anivia W and Chosen master yi are broken particles?
> 
> yes it's just a problem with chosen masteryi skin also anivia wall works correctly on their first skin
> 
> 

The anivia papercraft and latest skin, dont have wall. It doesnt appear (missing object) Is it also particles issue. Also is this future fix?

**Comment by R3nzTheCodeGOD** [comment]
> Syndra orbs. You need to press Ult till they refresh to the new skin.

After using the ultimate once, it updates itself. I don't need to update manually.

**Comment by alphaaced** [comment]
> > Syndra orbs. You need to press Ult till they refresh to the new skin.
> 
> After using the ultimate once, it updates itself. I don't need to update manually.

okay, thanks. What about chosen master yi sword and anivia wall for some skins like papercraft?

**Comment by senmao1994** [comment]
R3nzSkin 2.1.1 is so Good,thanks 
 Quinn R 
![League of Legends Screenshot 2022 07 13 - 15 59 46 49](https://user-images.githubusercontent.com/50578587/178682713-eb1a2365-145c-4a7d-9f71-3e9288a20463.png)
![League of Legends Screenshot 2022 07 13 - 16 00 10 39](https://user-images.githubusercontent.com/50578587/178682736-78a115cc-7868-4d33-a207-618397e0eb0c.png)
![League of Legends Screenshot 2022 07 13 - 16 00 27 20](https://user-images.githubusercontent.com/50578587/178682757-f34d68fa-51e2-4e43-9d46-e793bd83b74b.png)

**Comment by alphaaced** [comment]
> R3nzSkin 2.1.1 is so Good,thanks 
>  Quinn R 
> ![League of Legends Screenshot 2022 07 13 - 15 59 46 49](https://user-images.githubusercontent.com/50578587/178682713-eb1a2365-145c-4a7d-9f71-3e9288a20463.png)
> ![League of Legends Screenshot 2022 07 13 - 16 00 10 39](https://user-images.githubusercontent.com/50578587/178682736-78a115cc-7868-4d33-a207-618397e0eb0c.png)
> ![League of Legends Screenshot 2022 07 13 - 16 00 27 20](https://user-images.githubusercontent.com/50578587/178682757-f34d68fa-51e2-4e43-9d46-e793bd83b74b.png)
> 

I think its like syndra. You have to press R again. Can you send him a picture of the anivia wall on paper craft and new skins.

**Comment by VeryNais** [comment]
> okay, thanks. What about chosen master yi sword and anivia wall for some skins like papercraft?

@alphaaced  He already said that he wouldnt be able to fix those since they are broken particles
> You are talking about broken particles and sounds in some skins of champions, I can't fix them. #1

**Comment by alphaaced** [comment]
> 
>  
> > okay, thanks. What about chosen master yi sword and anivia wall for some skins like papercraft?
> 
> @alphaaced  He already said that he wouldnt be able to fix those since they are broken particles
> > You are talking about broken particles and sounds in some skins of champions, I can't fix them. #1 

whats the difference between anivias particle and nunu?

**Comment by WraithTrouble0** [comment]
It would be nice if Quinn R was fixed as written above :D

**Comment by 04255** [comment]
Some T2 skin lacks sound, and they belong to #1 ?

**Comment by masdb** [comment]
What should I do if your skinchanger doesn't work? Everything used to be fine, but now the injector itself is running and in the 'r3nzskin status' tab, the labels "injected" "not injected" are constantly flashing alternately. I tried to embed the dll myself through the injector, but it was not successful, it gave the error "failed to find pattern ....." The developer tell me how to fix this problem, please

**Comment by i1u5** [comment]
Anivia wall is invisible for some skins, I'd suggest maybe just making the base one show if it's not possible to add the per skin ones, for visual clarity.

**Comment by alphaaced** [comment]
> Anivia wall is invisible for some skins, I'd suggest maybe just making the base one show if it's not possible to add the per skin ones, for visual clarity.

if that is possible, it would be great +++.

**Comment by senmao1994** [comment]
Author your tool is too easy for me to use，Thank you for fixing Quinn R and 
spectator mode
#154 
#149
but R3nzSkin 2.12, Quinn R in Spectator mode remains unchanged
![League of Legends Screenshot 2022 07 17 - 19 46 22 83](https://user-images.githubusercontent.com/50578587/179396994-965d1d41-8936-4efa-a2d0-5a37f9cdc96b.png)

**Comment by R3nzTheCodeGOD** [comment]
@senmao1994 Actually, this is the intended behavior, this function is called before each frame rendering in lol, so if you are getting 144fps from the game this function will be called 144 times per second. If I check all champions' objects like this, the FPS will drop.

Currently, it will not work for champions on your team, opponent and spectator mode

I will write this code more efficiently when I am available.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/f099532cffa2ae70b162e83178e24d9f51d7e4c9/R3nzSkin/Hooks.cpp#L402-L409

**Comment by senmao1994** [comment]
> @senmao1994实际上，这是预期的行为，这个函数在每帧渲染之前调用 lol，所以如果你从游戏中获得 144fps，这个函数将每秒调用 144 次。如果我像这样检查所有冠军的对象，FPS 会下降。
> 
> 目前，它不适用于您的团队、对手和观众模式中的冠军
> 
> 当我有空时，我会更有效地编写这段代码。
> 
> https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/f099532cffa2ae70b162e83178e24d9f51d7e4c9/R3nzSkin/Hooks.cpp#L402-L409
thank you！

**Comment by senmao1994** [comment]
> @senmao1994 Actually, this is the intended behavior, this function is called before each frame rendering in lol, so if you are getting 144fps from the game this function will be called 144 times per second. If I check all champions' objects like this, the FPS will drop.
> 
> Currently, it will not work for champions on your team, opponent and spectator mode
> 
> I will write this code more efficiently when I am available.
> 
> https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/f099532cffa2ae70b162e83178e24d9f51d7e4c9/R3nzSkin/Hooks.cpp#L402-L409

thank you

**Comment by Pyleky** [comment]
Battle Queen Katarina knifes are invisible
![image](https://user-images.githubusercontent.com/109213744/179766991-348bce4e-042e-4990-955a-b2b8a37489e3.png)
![image](https://user-images.githubusercontent.com/109213744/179767141-b8f2646e-ac4a-4417-ae8a-f8c80ebc76e4.png)
![image](https://user-images.githubusercontent.com/109213744/179767184-b79dcc2c-cda9-4519-be56-7327e07902f0.png)

**Comment by R3nzTheCodeGOD** [comment]
> Battle Queen Katarina knifes are invisible

![image](https://user-images.githubusercontent.com/58574988/179768453-cd7b8d2a-5a60-403e-8f9a-8a69b0cc47d3.png)

**Comment by senmao1994** [comment]
Lulu W
![Uploading League of Legends Screenshot 2022.08.04 - 23.07.49.28.png…]()
![U
![League of Legends Screenshot 2022 08 04 - 23 07 58 86](https://user-images.githubusercontent.com/50578587/182882581-12c219ee-3e68-4121-ab60-deae2d1de98a.png)
ploading League of Legends Screenshot 2022.08.04 - 23.07.51.69.png…]()

**Comment by Gasferr** [comment]
all malphite skins appear as seen in the image the only one that does not do this is the dark star skin
[https://i.imgur.com/uXkcQrj.png](url)
