### ISSUE TITLE
High Noon Ashe

### ISSUE THREAD

**Issue by KyoumiKyoko** [R3nzTheCodeGOD/R3nzSkin#15]
Not sure if it can be fixed but there is some problem with high noon ashe skin

![Screen03](https://user-images.githubusercontent.com/88426288/128145944-d6e9e13c-b72d-40cc-8087-cd6983542d4d.png)

The correct one should be 
![2021-08-04 15_08_42-High Noon Ashe Skin Spotlight - League of Legends - YouTube - Opera](https://user-images.githubusercontent.com/88426288/128145996-f78311dd-2f6e-4c30-9b1b-8c55f1fe5857.png)

Then become this after using the ult
![2021-08-04 15_09_11-High Noon Ashe Skin Spotlight - League of Legends - YouTube - Opera](https://user-images.githubusercontent.com/88426288/128146031-cfd8dc38-d062-42a2-bdef-bedb7ae7396f.png)

It would be cool if it can be fixed!

**Comment by R3nzTheCodeGOD** [comment]
i don't think i can fix this

**Comment by KyoumiKyoko** [comment]
No problem, really appreciate the work!
