### ISSUE TITLE
ally and enemy's skins change by itself

### ISSUE THREAD

**Issue by seth007-moo** [R3nzTheCodeGOD/R3nzSkin#150]
I have issue when enter the game others champion's skin change to their own base skin by itself, 
And I noticed that it happen only when people use other skin that not base, 
eg: enemy's Master yi use Bloodmoon skin but when enter the game the injector set to Master yi.
and if Master yi use base skin the injector set to default like usual
This happen after I used "No Skin" option(I use only once and after that I never use it), and the issue continue happen every match

**Comment by R3nzTheCodeGOD** [comment]
delete `documents->R3nzSkin->R3nzSkin`

**Comment by seth007-moo** [comment]
> This is the purpose of the `No skin` feature. delete `documents->R3nzSkin->R3nzSkin`

fixed thank you
