### ISSUE TITLE
Voice Lines

### ISSUE THREAD

**Issue by WraithTrouble0** [R3nzTheCodeGOD/R3nzSkin#151]
Voice Lines of God King Darius, Galaxy Slayer Zed skins are mixed with normal skin, any chance to fix this?

**Comment by alphaaced** [comment]
i think yaso R also doesn't change voices with skins

**Comment by sakula6** [comment]
zed Many skins have no sound effect

**Comment by R3nzTheCodeGOD** [comment]
I'm really tired of closing the same issues broken particles and sounds of skins cannot be fixed #1

**Comment by CountryballsQer** [comment]
mythmaker irelia has a bug expect for ctrl s didnt have special voicelines
Efsanebaz ireliada ctrl hariç özel replikleri yok
