### ISSUE TITLE
performance issues causing fps drops of 100+

### ISSUE THREAD

**Issue by abud99** [R3nzTheCodeGOD/R3nzSkin#155]
usually I get 240 fps capped doesn't drop, but with the skin changer my fps hovers at around 100-150, can drop to 95 sometimes.

**Comment by alphaaced** [comment]
> usually I get 240 fps capped doesn't drop, but with the skin changer my fps hovers at around 100-150, can drop to 95 sometimes.

same

**Comment by R3nzTheCodeGOD** [comment]
I have a version of R3nzSkin that does almost 4-5x more processing in the back and when I inject it I lose a max of 10fps.
Also R3nzSkin is already an optimized program. Try compiling with technologies like SSE2, AVX2

![image](https://user-images.githubusercontent.com/58574988/179649461-da459afb-ddb3-405f-8e24-df7566ee2765.png)

**Comment by sakula6** [comment]
Will this (Ultimate) version be released in the near future?
