### ISSUE TITLE
Will this (Ultimate) version be released in the near future?

### ISSUE THREAD

**Issue by sakula6** [R3nzTheCodeGOD/R3nzSkin#158]
Will this (Ultimate) version be released in the near future
![1LXJT)$QB4UN98IWR1)JH_2](https://user-images.githubusercontent.com/93670933/179994684-c2e237ce-d001-410b-8b09-2eb2eaf56b4d.png)
?

**Comment by R3nzTheCodeGOD** [comment]
will not be released
