### ISSUE TITLE
GUI doesnt pop up

### ISSUE THREAD

**Issue by CrowVL** [R3nzTheCodeGOD/R3nzSkin#16]
i was using it a while ago without any issue but from last patch the gui doesnt pop up anymore and the script keep spamming "injected succesfully" let me know if there is anyway to fix it :)

**Comment by R3nzTheCodeGOD** [comment]
What server are you playing on and can you try injecting in training mode.

**Comment by CrowVL** [comment]
im on euw and i already tried to inject in training mode but same issue even there
