### ISSUE TITLE
Suggestion: add Korean font mod

### ISSUE THREAD

**Issue by pmetemp** [R3nzTheCodeGOD/R3nzSkin#162]
If you're able to add this mod as an option in your tool that would be cool. I'd rather have your tool than have to use another one to do this.

https://killerskins.com/frosted-fire/mods/fonts/uttumdotum-korean-font/

**Comment by alphaaced** [comment]
> If you're able to add this mod as an option in your tool that would be cool. I'd rather have your tool than have to use another one to do this.
> 
> https://killerskins.com/frosted-fire/mods/fonts/uttumdotum-korean-font/

you cannot use skin changer and change the font from a different source?

**Comment by pmetpmetpmet** [comment]
> you cannot use skin changer and change the font from a different source?

You can use both. I'd rather just have one tool to do everything than have to use multiple tools.

**Comment by alphaaced** [comment]
> > you cannot use skin changer and change the font from a different source?
> 
> You can use both. I'd rather just have one tool to do everything than have to use multiple tools.

Where can i find tutorial on how to use the font?

**Comment by pmetpmetpmet** [comment]
> Where can i find tutorial on how to use the font?

youtube
