### ISSUE TITLE
[Feature] Jungle timer tracker?

### ISSUE THREAD

**Issue by emlautarom1** [R3nzTheCodeGOD/R3nzSkin#171]
Similar to the extra features listed on #137, would it be possible to add timers for each jungle camp? I would really like to have this feature but I feel completely lost after spending ~5 hrs on unknowncheats so any hints would be appreciated.

**Comment by R3nzTheCodeGOD** [comment]
```cpp
// Version 12.15.458.1416 [PUBLIC]
constexpr auto NeutralMinionCampCommon__GetTimerExpiry{ 0x14E340 }; // E8 ? ? ? ? F3 0F 10 83 ? ? ? ? 0F 57 C9
using FnGetTimerExpiry = float(__thiscall*)(GameObject* ecx);
```

**Comment by Gasferr** [comment]
@R3nzTheCodeGOD in which part of the code would I go to place the times of the jungle, it seems to me a very good addition and thank you very much

**Comment by guyueyueshen** [comment]
同求(⊙﹏⊙)
