### ISSUE TITLE
anyone have updater?

### ISSUE THREAD

**Issue by 04255** [R3nzTheCodeGOD/R3nzSkin#173]
&offsets::functions::WorldToScreen
         //"83 EC 10 56 E8 ? ? ? ? 8B 08",
	//"E8 ? ? ? ? 8D 44 24 10 50 8B 44 24 54"
no work anymore.
i look for Unknow cheat but "8B CE E8 ? ? ? ? 83 7E 3C 00 75 17" no work for me, game  crash.
so, plz help for updater bot

**Comment by R3nzTheCodeGOD** [comment]
I have told you many times that I will not update that pull request. WorldToScreen method takes an ecx parameter after the new update. This indicates that the method is now called with the __thiscall calling convention and an instance must be passed to the method. Open the method in IDA and reverse it.

![image](https://user-images.githubusercontent.com/58574988/184548143-8c6b1627-cc83-468e-a571-0059a1305a5d.png)

When I look at the unknowncheats forum, I see that they have already shared the current type definition of the worltoscreen function. No one will give you a ready made code for this source.

learn c++, don't embarrass yourself on the forums
