### ISSUE TITLE
Can I add a Chinese interface

### ISSUE THREAD

**Issue by LeBlancei** [R3nzTheCodeGOD/R3nzSkin#175]
For many Chinese players, some of the functions are really incomprehensible.

**Comment by Clownsw** [comment]
可以参考[https://github.com/Clownsw/Open_LeagueSkin-Lite](https://github.com/Clownsw/Open_LeagueSkin-Lite)

**Comment by LeBlancei** [comment]
Thank you very much for your answer, but I haven't studied this kind of content. I really can't understand this kind of code file. Haha.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R3nzTheCodeGOD/R3nzSkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R3nzTheCodeGOD/R3nzSkin] Can I add a Chinese interface (Issue #175)





 
可以参考https://github.com/Clownsw/Open_LeagueSkin-Lite
