### ISSUE TITLE
All list Champion skin bug

### ISSUE THREAD

**Issue by CODENAME-SIGMA** [R3nzTheCodeGOD/R3nzSkin#179]
God-King Garen E Bug didn't have animation || https://imgur.com/a/J1nRlK3

Infernal Nasus All Skill Bug [Q,W,E,R] || https://imgur.com/a/HWCc2sh

Katarina Battle Queen knife invisible and all skills || https://imgur.com/a/Y1EIamW

Blackfrost Anivia Incorrect model Skills W
Festival Queen Anivia Incorrect model Skill W
Cosmic Flight Anivia Skill W disappear
Papercraft Anivia Skill W disappear
https://imgur.com/a/MjplTt5

Actually there is more. But I'll take a look at the major bugs first.

**Comment by alphaaced** [comment]
There's way more bugs. But they cannot be fixed according to #1.

**Comment by seth007-moo** [comment]
> God-King Garen E Bug didn't have animation || https://imgur.com/a/J1nRlK3
> 
> Infernal Nasus All Skill Bug [Q,W,E,R] || https://imgur.com/a/HWCc2sh
> 
> Katarina Battle Queen knife invisible and all skills || https://imgur.com/a/Y1EIamW
> 
> Blackfrost Anivia Incorrect model Skills W Festival Queen Anivia Incorrect model Skill W Cosmic Flight Anivia Skill W disappear Papercraft Anivia Skill W disappear https://imgur.com/a/MjplTt5
> 
> Actually there is more. But I'll take a look at the major bugs first.

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1
