### ISSUE TITLE
Can I add "rainbow fluft icon effect"?

### ISSUE THREAD

**Issue by rkdrlgh22** [R3nzTheCodeGOD/R3nzSkin#180]
Image:
![unknown](https://user-images.githubusercontent.com/99127548/185666436-d4b27b5b-209e-4267-9a1e-3cb5a6fe60c7.png)

I want to use the same effect as the image above using a different profile icon.
Can you add the above effects to the program

**Comment by R3nzTheCodeGOD** [comment]
It's pretty hard to find but if I find it, I will add R3nzSkin.
