### ISSUE TITLE
[SUGGESTION] Announcer Map Change

### ISSUE THREAD

**Issue by sonitaaaaa** [R3nzTheCodeGOD/R3nzSkin#181]
Change the Announcer of specific map

**[Wiki for the announcer](https://leagueoflegends.fandom.com/wiki/Announcer)** 

**Options:**
![image](https://user-images.githubusercontent.com/40225192/185705011-6a02ac62-6d2e-4940-a8d5-f89302dd154d.png)

![image](https://user-images.githubusercontent.com/40225192/185706009-4586917b-4670-474e-8347-0932141c13d2.png)

E.g. Star Guardians 2022 in **Summoner's Rift** is Ahri Announcer

**Comment by Th3Nigh7mare** [comment]
Woul be so cool that we could change the skin of the summoner's rift map!

**Comment by R3nzTheCodeGOD** [comment]
It's pretty hard to change something that's already loaded into memory. Use external software that modifies .wad files. like [KillerSkins](https://killerskins.com/)
