### ISSUE TITLE
Viego King is not in the tool

### ISSUE THREAD

**Issue by Th3Nigh7mare** [R3nzTheCodeGOD/R3nzSkin#185]
In the client PBE 12.17 it is not yet activated, but I went to see it in the practice tool (sandbox) and Viego King is not in the tool as a skin, a couple of patches ago with another skin it was when it was not really activated.

Edit: The new ones too: Zenith Games (Blitzcrank, Jayce and Lee Sin)

**Comment by Pxprl** [comment]
They arent out on the normal client. Go to pbe and try out the skins if you want to

**Comment by Th3Nigh7mare** [comment]
uhhh I wasn't talking about the "normal" but about the PBE, when they put patch 12.17, they weren't available.
