### ISSUE TITLE
[SUGGESTION] The possibility of changing the SKIN to the Summoner's Rift Map

### ISSUE THREAD

**Issue by Th3Nigh7mare** [R3nzTheCodeGOD/R3nzSkin#186]
It would be incredible if in the future you could implement in your tool the possibility of changing the skin of the summoner's rift.

Riot a couple of months ago added a new theme to the summoner's rift due to the introduction of the game mode "Speel Book" the ruined rift, it would be incredible that with the tool the design that the rift had was changed, this is interesting for when RIOT will add a new rift in the future so you can take a closer look at it in sandbox mode!

**Comment by wanwindwalker** [comment]
Th3Nigh7mare until he does you can use lcs manager from killerskins.com, there you can find all event skins for summoners rift as well as many custom ones like night rift and bilgewater rift.

**Comment by R3nzTheCodeGOD** [comment]
Quite difficult for an internal software
