### ISSUE TITLE
THE SCRIPT HAS A TROJAN !!!!

### ISSUE THREAD

**Issue by Abdullah2332** [R3nzTheCodeGOD/R3nzSkin#187]
the rar contains a trojan script !!! can you fix it !! it wasnt infected last month but now it has a virus

**Comment by Abdullah2332** [comment]
![Capture](https://user-images.githubusercontent.com/111985248/186421821-bd1eadd9-cbc9-4634-80f5-f8c534c312a5.PNG)

**Comment by seth007-moo** [comment]
lmao

**Comment by Clownsw** [comment]
code is open source

**Comment by Pxprl** [comment]
xD you are not serious

**Comment by Abdullah2332** [comment]
Can anyone download the file again , and scan it with windows defender make sure you have the latest windows update because the windows defender got updated and it might detect new threats ... can anyone tell me if you are having the same problem as me.

Note : Its not fake so if you dont have the issue then please dont accuse me

**Comment by Pxprl** [comment]
Just allow it. Its a false positive

**Comment by sonitaaaaa** [comment]
False positives (false alarms) are **harmless files or URLs that are incorrectly identified as malicious by the antivirus program**. Software programs that behave like malware or use identical file compression and protection techniques are susceptible to false alarms.

It's like you got scam and Paypal replied: "Lmao"

**Comment by R3nzTheCodeGOD** [comment]
?
