### ISSUE TITLE
all malphite skins appear as seen in the image, this happens when malphite's passive is deactivated

### ISSUE THREAD

**Issue by Gasferr** [R3nzTheCodeGOD/R3nzSkin#188]
all malphite skins appear as seen in the image, this happens when malphite's passive is deactivated
![image](https://user-images.githubusercontent.com/34402763/186790330-18c96817-b44e-471b-bf9c-5f3a9d9fe4b0.png)

**Comment by wanwindwalker** [comment]
Its not a bug its a feature
