### ISSUE TITLE
PBE 12.17 offset error

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#189]
![image](https://user-images.githubusercontent.com/50578587/187026292-278fee5c-4001-4496-944f-f8aa1389d09c.png)
![image](https://user-images.githubusercontent.com/50578587/187026296-cc3ef059-2117-49ab-88a1-bc04b175629f.png)
can you give me new offset

**Comment by R3nzTheCodeGOD** [comment]
```cpp
{
	{
		"A1 ? ? ? ? 55 57 8B 78 04 8B 40 08 8D 2C 87 3B FD",
		"8B 0D ? ? ? ? E8 ? ? ? ? EB 09"
	}, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
},
{
	{
		"0F B6 96 ? ? ? ? 88 4C 24 ? 33 C9 85 D2 74 ? 0F 1F 44 00 00"
	}, false, true, -1, &offsets::AIMinionClient::IsLaneMinion
},
```

**Comment by senmao1994** [comment]
> ```c++
> {
> 	{
> 		"A1 ? ? ? ? 55 57 8B 78 04 8B 40 08 8D 2C 87 3B FD",
> 		"8B 0D ? ? ? ? E8 ? ? ? ? EB 09"
> 	}, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
> },
> {
> 	{
> 		"0F B6 96 ? ? ? ? 88 4C 24 ? 33 C9 85 D2 74 ? 0F 1F 44 00 00"
> 	}, false, true, -1, &offsets::AIMinionClient::IsLaneMinion
> },
> ```

thanks，bro，it‘s running
