### ISSUE TITLE
Doesn't work after the last patch V11.16

### ISSUE THREAD

**Issue by 6oody** [R3nzTheCodeGOD/R3nzSkin#19]

**Comment by R3nzTheCodeGOD** [comment]
I will be out of town for 1.5 weeks. Compile the cheat with `#SEE_ERROR 1`
and find the broken pattern from forums like `UnknownCheats` try to solve
this problem yourself for now if you cant, I will update it in 1.5 weeks.

11 Ağu 2021 Çar 07:11 tarihinde 6oody ***@***.***> şunu yazdı:

**Comment by W0ksler** [comment]
1. Clone the repo
2. edit **memory.cpp** file with Visual Studio, 
3. find `83 EC 2C 53 56 57 8D 44 24 28` value under `CharacterDataStack_Update`
4. change it to `83 EC 1C 56 57 8D 44 24 20`
5.  Compile.

**Comment by player12145** [comment]
can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this

**Comment by aymoon4** [comment]
I have tried doing what @W0ksler has said but I never used Visual Studio before. But I did manage to get the .exe and .dll at the end. I did edit "83 EC 2C 53 56 57 8D 44 24 28" to > "83 EC 1C 56 57 8D 44 24 20" but this makes my game crash as soon as I start it

**Comment by aymoon4** [comment]
Please make a tutorial  (video or smth)

**Comment by W0ksler** [comment]
> can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this

[R3nzSkinsFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6971377/R3nzSkinsFixed.zip)

**Comment by aymoon4** [comment]
@W0ksler could u make a tutorial please?

**Comment by FeriStudent** [comment]
Actually this will be helpfully : https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/21

Good night all

**Comment by 6oody** [comment]
> > can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this
> 
> [R3nzSkinsFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6971377/R3nzSkinsFixed.zip)

doesn't work for me idk why

**Comment by W0ksler** [comment]
> > > can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this
> > 
> > 
> > [R3nzSkinsFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6971377/R3nzSkinsFixed.zip)
> 
> doesn't work for me idk why

Probably because ur CPU doesn't support AVX2, download the SSE2 version from latest release, then replace the .DLL with this one:  [R3nzSkinFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6976472/R3nzSkinFixed.zip)

![sse2](https://user-images.githubusercontent.com/88795092/129220412-7df9b59d-0bb1-4c46-97e3-b41c96dc6924.png)

**Comment by player12145** [comment]
> > > > can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this
> > > 
> > > 
> > > [R3nzSkinsFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6971377/R3nzSkinsFixed.zip)
> > 
> > 
> > doesn't work for me idk why
> 
> Probably because ur CPU doesn't support AVX2, download the SSE2 version from latest release, then replace the .DLL with this one: [R3nzSkinFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6976472/R3nzSkinFixed.zip)
> 
> ![sse2](https://user-images.githubusercontent.com/88795092/129220412-7df9b59d-0bb1-4c46-97e3-b41c96dc6924.png)

keeps crashing even if i use SSE2 version for me

**Comment by W0ksler** [comment]
I play on EUW server and works just fine, the offsets may be different for each server.

**Comment by FeriStudent** [comment]
W0ksler is right. He spotted the thing.
Before patch i was using version 1.3.
But in meanwhile (before the patch) admin change the version to 1.4 which was not oki for me.

What i did was - i went back for version which worked for me and updated the offset ...
![image](https://user-images.githubusercontent.com/79832303/129306863-205135ce-bbd7-4775-86d2-5fc610543b09.png)

and it's working!

+ do NOT forget to build yourself a new .exe file as well because maybe the one you have atm is from version 1.4 ... 

Enjoy

**Comment by 6oody** [comment]
> SSE2

+1

**Comment by 6oody** [comment]
> > > > > can anyone do this and give a download link? I don't know how to use VisualStudio and I don't know where to find the file where I need to edit this
> > > > 
> > > > 
> > > > [R3nzSkinsFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6971377/R3nzSkinsFixed.zip)
> > > 
> > > 
> > > doesn't work for me idk why
> > 
> > 
> > Probably because ur CPU doesn't support AVX2, download the SSE2 version from latest release, then replace the .DLL with this one: [R3nzSkinFixed.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6976472/R3nzSkinFixed.zip)
> > ![sse2](https://user-images.githubusercontent.com/88795092/129220412-7df9b59d-0bb1-4c46-97e3-b41c96dc6924.png)
> 
> keeps crashing even if i use SSE2 version for me

+1 It keep carshes for me after i replaced the dll

**Comment by FeriStudent** [comment]
Man it works 100% just do it yourself this time ... i am 100% you have v.1.4 exe and 1.3v .dll with updated offset ... it crashes ofc.

So go on : https://github.com/R3nzTheCodeGOD/R3nzSkin/archive/refs/tags/v1.3.zip

and then : 

![image](https://user-images.githubusercontent.com/79832303/129374872-148b777e-afdf-4eea-a7f3-c22f19bfcc34.png)

do not give up!

**Comment by 6oody** [comment]
> Man it works 100% just do it yourself this time ... i am 100% you have v.1.4 exe and 1.3v .dll with updated offset ... it crashes ofc.
> 
> So go on : https://github.com/R3nzTheCodeGOD/R3nzSkin/archive/refs/tags/v1.3.zip
> 
> and then :
> 
> ![image](https://user-images.githubusercontent.com/79832303/129374872-148b777e-afdf-4eea-a7f3-c22f19bfcc34.png)
> 
> do not give up!
man i don't have VS and i can't download it this month

**Comment by FeriStudent** [comment]
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6983871/R3nzSkin.zip)

Here you go

**Comment by FeriStudent** [comment]
Here you go : 
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6983893/R3nzSkin.zip)

**Comment by 6oody** [comment]
> Here you go :
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/6983893/R3nzSkin.zip)
> 
> To all guys out there :
> Please get yourself Visual Studio or wait for Admin. This is last time i share files.

Thanks man <3

**Comment by R3nzTheCodeGOD** [comment]
When I look at the conversations above, I see the same problem in all of you. You don't pay attention to SS2 and AVX2 technologies. I will turn these technologies off by default so everyone can compile and use the cheat themselves.

**Comment by R3nzTheCodeGOD** [comment]
aac7fa55f4604c4dad2e929e18db6c29155f0267 
You won't have any problems when you compile now
