### ISSUE TITLE
Can this get you banned?

### ISSUE THREAD

**Issue by clovdystackflow** [R3nzTheCodeGOD/R3nzSkin#190]
question. nothing to add

**Comment by Gasferr** [comment]
undetected

**Comment by Pxprl** [comment]
Most likely not though people have been banned for skin changers before. Have used this for like half a year no bans

**Comment by seth007-moo** [comment]
https://support-leagueoflegends.riotgames.com/hc/en-us/articles/225266848-Third-Party-Applications

**Comment by alphaaced** [comment]
> https://support-leagueoflegends.riotgames.com/hc/en-us/articles/225266848-Third-Party-Applications

Their stance is very weird. The skin changers/ custom skins literally do not affect other players only our screens. Why do they stand against it? Are they that money hungry ?

**Comment by W1nehazy** [comment]
> > https://support-leagueoflegends.riotgames.com/hc/en-us/articles/225266848-Third-Party-Applications
> 
> Their stance is very weird. The skin changers/ custom skins literally do not affect other players only our screens. Why do they stand against it? Are they that money hungry ?

Because it discourages players buying skins for themselves which subsequently bring less money into their pockets. 
If anything is weird here is the fact they even allow us to use such tools without getting banned.

**Comment by R3nzTheCodeGOD** [comment]
Yes, R3nzSkin can get you banned, although the probability is low.
