### ISSUE TITLE
R3nzSkin should be able to simulate ctrl + 5 feature

### ISSUE THREAD

**Issue by R3nzTheCodeGOD** [R3nzTheCodeGOD/R3nzSkin#193]
## About the problem
In League of legends, especially expensive skins also have ctrl+5 feature, this method changes something in skins. Since R3nzSkin changes all skins with the same method, it causes problems such as invisible objects in skins with ctrl + 5 feature. R3nzSkin needs to deal with this

## Skins that are broken due to this feature in League of Legends (what i know)
- Battle queen katarina daggers
- Gun goddess miss fortune guns and bullets
- Project Renekton head

## Images of manually corrected skins
- **Katarina**
![image](https://user-images.githubusercontent.com/58574988/188255699-1aaa131b-47c9-416c-9b38-ff2bf056d95b.png)  ![image](https://user-images.githubusercontent.com/58574988/188255734-580703cc-eacf-40c2-ac81-113440537942.png)

- **Renekton**
![image](https://user-images.githubusercontent.com/58574988/188255767-c64b3e4f-7b11-4455-a225-b9d396bbb103.png)

**Comment by alphaaced** [comment]
infernal nasus, chosen master yi sword, odyssey kayn.

**Comment by R3nzTheCodeGOD** [comment]
@alphaaced 
infernal nasus = animation issue (Same issue with Super Galaxy Rumble ult)
chosen master yi = server issue #1
odyssey kayn = server issue #1

for example pulsefire ezreal is related to this issue;

- **R3nzSkin Pulsefire Ezreal**
![image](https://user-images.githubusercontent.com/58574988/188262526-f740cf00-428c-4586-ac7b-05088f141828.png)

- **R3nzSkin users cannot change these gears of pulsefire ezreal by using ctrl + 5 keys.**

![image](https://user-images.githubusercontent.com/58574988/188262663-c2d2b454-5d27-4d13-af27-c8f2e59a5f38.png)![image](https://user-images.githubusercontent.com/58574988/188262553-e6abeaf0-8c51-4cd6-b934-c2b59e06d68f.png)![image](https://user-images.githubusercontent.com/58574988/188262587-f7fdaecf-34db-430f-afac-ac4399da979a.png)

**Comment by alphaaced** [comment]
> @alphaaced 
> infernal nasus = animation issue (Same issue with Super Galaxy Rumble ult)
> chosen master yi = server issue #1
> odyssey kayn = server issue #1
> 
> for example pulsefire ezreal is related to this issue;
> 
> - **R3nzSkin Pulsefire Ezreal**
> ![image](https://user-images.githubusercontent.com/58574988/188262526-f740cf00-428c-4586-ac7b-05088f141828.png)
> 
> - **R3nzSkin users cannot change these gears of pulsefire ezreal by using ctrl + 5 keys.**
> 
> ![image](https://user-images.githubusercontent.com/58574988/188262663-c2d2b454-5d27-4d13-af27-c8f2e59a5f38.png)![image](https://user-images.githubusercontent.com/58574988/188262553-e6abeaf0-8c51-4cd6-b934-c2b59e06d68f.png)![image](https://user-images.githubusercontent.com/58574988/188262587-f7fdaecf-34db-430f-afac-ac4399da979a.png)
> 
> 

Can these be fixed or are they server sided and locked?

**Comment by alphaaced** [comment]
> @alphaaced 
> infernal nasus = animation issue (Same issue with Super Galaxy Rumble ult)
> chosen master yi = server issue #1
> odyssey kayn = server issue #1
> 
> for example pulsefire ezreal is related to this issue;
> 
> - **R3nzSkin Pulsefire Ezreal**
> ![image](https://user-images.githubusercontent.com/58574988/188262526-f740cf00-428c-4586-ac7b-05088f141828.png)
> 
> - **R3nzSkin users cannot change these gears of pulsefire ezreal by using ctrl + 5 keys.**
> 
> ![image](https://user-images.githubusercontent.com/58574988/188262663-c2d2b454-5d27-4d13-af27-c8f2e59a5f38.png)![image](https://user-images.githubusercontent.com/58574988/188262553-e6abeaf0-8c51-4cd6-b934-c2b59e06d68f.png)![image](https://user-images.githubusercontent.com/58574988/188262587-f7fdaecf-34db-430f-afac-ac4399da979a.png)
> 
> 

how can we fix this issue?

**Comment by krukuhehe** [comment]
This is nice, I have suggestions. you can take your time :)

- R3nzSkin should be able to mute other VO (Overlapping VO when switching skins)
- R3nzSkins should be able to change other forms, there are other skins where the forms works (Nidalee/Elise, SG Ahri R etc.), but there are still that doesn't work (Coven Evelynn Demon Shade, SB Ahri R Fox etc. )
- R3nzSkin should be able to change skin music (All Seraphine skins, DJ Sona)
- R3nzSkin should be able to display legendary VFX borders (Sentinel/PROJECT Vayne R, BA Caitlyn R, SG Akali W etc.) 

These are just suggestions, feel free to ignore them.

**Comment by alphaaced** [comment]
Anivia  W not present on certain skins and God king garen E being normal walk.

**Comment by GuiSaiUwU** [comment]
R3nz, does the emulate cntrl 5 feature is a internal thing, or is related with the server?

**Comment by wisarius** [comment]
When I choose the Battle Queen Katarina skin, the daggers go on forever. Can't use another skins without battle queen daggers.

**Comment by DeadassDeaddack** [comment]
Is KDA Prestige Evelynn gonna be fixed, and if not is there a way we can fix it ourselves?
