### ISSUE TITLE
Can I add a language selection interface

### ISSUE THREAD

**Issue by LeBlancei** [R3nzTheCodeGOD/R3nzSkin#194]

**Comment by LeBlancei** [comment]
Because I am currently playing Japanese servers in China, I can't understand some words. If there is no way to optimize them, that's good. Thank you very much for your reply.

**Comment by pyleky11** [comment]
You can't, if you want to change your league language you should change some files in it. There are a lot of guides on youtube

**Comment by LeBlancei** [comment]
OK  thank you ~
