### ISSUE TITLE
This tool is not work for me, I don't know why.

### ISSUE THREAD

**Issue by tonydon140** [R3nzTheCodeGOD/R3nzSkin#195]
I opened this tool with administrator privilege, but it still shows that it is not injected when I enter the game.
And I have tried to wait for enough time, but it still doesn't work.
What should I do, could you please give me some advice?

**Comment by Yousazoe** [comment]
Chinese server doesn't work TT, you can try others.

**Comment by Th3Nigh7mare** [comment]
No one answered me, but is it normal that the 12.18 skins are not in the tool? I put a ticket to see if the developer takes it into account.
