### ISSUE TITLE
Legendary Skin Character Voiceline wrong

### ISSUE THREAD

**Issue by CODENAME-SIGMA** [R3nzTheCodeGOD/R3nzSkin#197]
Ezreal battle academia Still say voiceline in default 
Example :: When you press the Ctrl+3 it will said "Are you not intrigued?" It.. volice from default or epic skin
Or you just buy some item in the shop "Nice. You can send the bill to my uncle's museum." It wrong voiceline.

Ahri Legendary Still say voiceline in default too
Example ::  When you press the Ctrl+2 it will said "Should I make your pulse rise? Or... stop!" *Giggles* it a wrong one voiceline

Skin Legendary didn't say any voiceline Default, pls Fix it whenever you want
Take your time, love your skin mod so much.

If you want to see example program mod skin perfectly voliceline, hope it help
https://leagueskin.net/p/download-mod-skin-2020-chn

**Comment by seth007-moo** [comment]
lmao
