### ISSUE TITLE
[Feature Request]: Summoner Name Change Persistence

### ISSUE THREAD

**Issue by Lua0x0** [R3nzTheCodeGOD/R3nzSkin#198]
I think it would be ideal if the Summoner Name change feature persisted after a game. Currently, it resets after every game, and inputting a name can result in cooldowns being used at the start of a game by mistake (names containing the letter "F" being the most agregious for obvious reasons).

A simple method of avoiding this is to include a Summoner Name parameter in the configuration file, so that the name can be safely changed outside of the game.

**Comment by hotline1337** [comment]
Possible fix has been implemented by Riot to prevent local name changing
