### ISSUE TITLE
Can't use in 12.17

### ISSUE THREAD

**Issue by TDxir** [R3nzTheCodeGOD/R3nzSkin#203]
error: can't find pattern

**Comment by TenDominik** [comment]
Just wait for offets update.

**Comment by TDxir** [comment]
感谢你的来信，在我看到邮件后我会尽快地回复你，我对对你邮件回复的延迟感到十分抱歉，感谢你的理解！Thank
 you for your e-mail. I will reply as soon as I can if I can access to e-mails. I apologize for any delay in response to
 your e-mail. Thanks!
