### ISSUE TITLE
Failed to find pattern : 8B 35 ? ? ? ? 8B 56 04 8D 4E04 8B 41 04 8D 04 82

### ISSUE THREAD

**Issue by wxld12** [R3nzTheCodeGOD/R3nzSkin#204]
skinchanger was working for a few days now it says Failed to find pattern : 8B 35 ? ? ? ? 8B 56 04 8D 4E04 8B 41 04 8D 04 82 how can i fix it ?

**Comment by TenDominik** [comment]
Just wait for offets update.
