### ISSUE TITLE
Azir turrets Not changing

### ISSUE THREAD

**Issue by RafihYahya** [R3nzTheCodeGOD/R3nzSkin#207]
Azir turrets stay in base skin, applies to all his skins

**Comment by senmao1994** [comment]
Same problem
![League of Legends 2022-09-13 09-55-07-710](https://user-images.githubusercontent.com/50578587/189790365-1e3d7c3a-ddc0-4108-a7fe-dd5840862c49.png)

**Comment by lolkowicz** [comment]
things like teemo's mushrooms etc. it's probably server site or some shit, or if you change those you are most likely to be banned

**Comment by diyooor** [comment]
#1
