### ISSUE TITLE
Suggestion: Emotes

### ISSUE THREAD

**Issue by CodingAgent1337** [R3nzTheCodeGOD/R3nzSkin#209]
How to add or can you add emotes to use? Mastery and others

**Comment by alphaaced** [comment]
> How to add or can you add emotes to use? Mastery and others

I dont think this is possible.

**Comment by krukuhehe** [comment]
@alphaaced it's possible, the first version (b3akers) had emotes changer. he removed it because it conflicts afaik

**Comment by R3nzTheCodeGOD** [comment]
They are problematic and crash the game.
I'm having a hard time finding patterns and understanding how it works because I don't have old lol dumps.
