### ISSUE TITLE
can't be used in Chinese sever

### ISSUE THREAD

**Issue by xyzxyzfgdj** [R3nzTheCodeGOD/R3nzSkin#211]
it's been a long time, could you please do
something

**Comment by ZhangPF2000** [comment]
@xyzxyzfgdj 
I can use the R3nzSkin script.
You need to replace the file of `D:\LOL\英雄联盟\Game\LogitechLed.dll` with `R3nzSkin.dll`, and rename R3nzSkin.dll to LogitechLed.dll
Do not use R3NZSKIN_INjector, it does not work on the Chinese server
![image](https://user-images.githubusercontent.com/64509222/190586542-7db2b3e2-aa1f-4111-89c9-e78ed16870f8.png)
Check the author's reply: #51

**Comment by xyzxyzfgdj** [comment]
thanks

**Comment by zzw6776** [comment]
good it is work  very thanks

**Comment by xym15** [comment]
会被封号吗？
