### ISSUE TITLE
PBE 12.19 New offsets

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#213]
Can you give me new offset
![image](https://user-images.githubusercontent.com/50578587/191397697-f8514af9-417d-4075-b04d-1bc9bc35ab3e.png)

**Comment by R3nzTheCodeGOD** [comment]
Change PAD(0x48) to PAD(0x54) in the champion structure.

![image](https://user-images.githubusercontent.com/58574988/191460017-b31c08f1-cd51-4d26-b7c0-bf5a9faf7b37.png)

Secondly, delete the first pattern of AIMinionClient

```cpp
{
    {
        "8B 0D ? ? ? ? E8 ? ? ? ? EB 09"
    }, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
},


```

**Comment by senmao1994** [comment]
> 将冠军结构中的 PAD(0x48) 更改为 PAD(0x54)。
> 
> ![图片](https://user-images.githubusercontent.com/58574988/191460017-b31c08f1-cd51-4d26-b7c0-bf5a9faf7b37.png)
> 
> 其次，删除AIMinionClient的第一个模式
> 
> ```c++
> {
>     {
>         "8B 0D ? ? ? ? E8 ? ? ? ? EB 09"
>     }, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
> },
> ```

Thanks, I'll try

**Comment by senmao1994** [comment]
It ran successfully
![3~ U{OGVDM00P`147BYO)DO](https://user-images.githubusercontent.com/50578587/191477070-db1b943e-160c-4914-8286-88b7e9f9cc10.png)

**Comment by alphaaced** [comment]
> It ran successfully
> ![3~ U{OGVDM00P`147BYO)DO](https://user-images.githubusercontent.com/50578587/191477070-db1b943e-160c-4914-8286-88b7e9f9cc10.png)
> 

Will there be new update for the tool?

**Comment by senmao1994** [comment]
> > 它运行成功
> > ![3~ U{OGVDM00P`147BYO)DO](https://user-images.githubusercontent.com/50578587/191477070-db1b943e-160c-4914-8286-88b7e9f9cc10.png)
> 
> 该工具会有新的更新吗？

[R3nzSkin12.19.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/9615831/R3nzSkin12.19.zip)
You can try

**Comment by superminioncute** [comment]
> > > 它运行成功
> > > ![3~ U{OGVDM00P`147BYO)DO](https://user-images.githubusercontent.com/50578587/191477070-db1b943e-160c-4914-8286-88b7e9f9cc10.png)
> > 
> > 
> > 该工具会有新的更新吗？
> 
> [R3nzSkin12.19.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/9615831/R3nzSkin12.19.zip) You can try

I keep crashing. I edited what the dev said and built it, and I tried your copy too. I wasn't sure if that injector doesn't work and I never really injected via lol, so wasn't sure what to use. Not sure if I have the correct "region", I wasn't sure what the dev meant by that.

**Comment by senmao1994** [comment]
![image](https://user-images.githubusercontent.com/50578587/192916752-81c4fbc7-a38c-4cd0-913a-ecfd4fff1ec1.png)
Today,  it`s collapsed in PBE

**Comment by senmao1994** [comment]
> Change PAD(0x48) to PAD(0x54) in the champion structure.
> 
> ![image](https://user-images.githubusercontent.com/58574988/191460017-b31c08f1-cd51-4d26-b7c0-bf5a9faf7b37.png)
> 
> Secondly, delete the first pattern of AIMinionClient
> 
> ```c++
> {
>     {
>         "8B 0D ? ? ? ? E8 ? ? ? ? EB 09"
>     }, true, true, 0, &offsets::global::ManagerTemplate_AIMinionClient_
> },
> ```

![image](https://user-images.githubusercontent.com/50578587/192917169-7176a130-09a1-4360-acb5-09db39e4eb6d.png)

Today, it‘ss collapsed in PBE
