### ISSUE TITLE
 WorldToScreen 

### ISSUE THREAD

**Issue by Npc2017** [R3nzTheCodeGOD/R3nzSkin#215]
can someone share WorldToScreen offsets sig?  12.18

**Comment by R3nzTheCodeGOD** [comment]
```cpp
constexpr auto WorldToScreen = 0xA815D0; // 8B 11 8D 41 04 50
constexpr auto UnkInst = 0x24ED764;	 // 8B 0D ? ? ? ? 8B F0 F3 0F 10 0D ? ? ? ?
constexpr auto W2sInstance = 0x268;	 // 8D 8F ? ? ? ? E8 ? ? ? ? 8D 44 24 08

inline bool worldToScreen(Vector* in, Vector* out) noexcept
{
    static const auto w2s{ reinterpret_cast<bool(__thiscall*)(DWORD* ecx, Vector* in, Vector* out)>(::GetModuleHandle(nullptr) + WorldToScreen) };
    static const auto ecx{ reinterpret_cast<DWORD*>(*reinterpret_cast<DWORD*>(::GetModuleHandle(nullptr) + UnkInst) + W2sInstance) };
    return w2s(ecx, in, out);
}
```

I'm doing a experiment for myself. I think even this ready-made code will not be enough for you and you will not be able to run the cheat.

If you don't get it to work, come here and ask me why.

**Comment by Npc2017** [comment]
Thank you. I want to change the internal offset feature of Test Build v12.12 you shared, and then see the effect. However, the game still crashes. ha-ha

**Comment by R3nzTheCodeGOD** [comment]
I was expecting exactly this answer. Because you and people like you think you can keep a cheat updated just by updating the pattern.
