### ISSUE TITLE
[Request] Changing names of other players/bots

### ISSUE THREAD

**Issue by Evan-Younan** [R3nzTheCodeGOD/R3nzSkin#216]
I know that it is possible to modify your own name, how hard would it be to change other people's names (both enemies and allies)?

**Comment by alphaaced** [comment]
How do you change your own name?

TEST
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Evan-Younan ***@***.***>
Sent: Sunday, September 25, 2022 8:14:40 PM
To: R3nzTheCodeGOD/R3nzSkin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [R3nzTheCodeGOD/R3nzSkin] [Request] Changing names of other players/bots (Issue #216)


I know that it is possible to modify your own name, how hard would it be to change other people's names (both enemies and allies)?

**Comment by R3nzTheCodeGOD** [comment]
Use the heroList defined in R3nzSkin and make it.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/535de53a84aeb214b49dc1d579658f4b5b515990/R3nzSkin/GUI.cpp#L193-L194

## Example
```cpp
for (auto i{ 0u }; i < heroes->length; ++i) {
    const auto hero{ heroes->list[i] };
    std::string temp{ "Change Nick " + std::to_string(i) };
    ImGui::InputText(temp.c_str(), hero->get_name());
}
```
