### ISSUE TITLE
I'm banned!!!

### ISSUE THREAD

**Issue by xyzxyzfgdj** [R3nzTheCodeGOD/R3nzSkin#218]
I was banned for modifying game files, in Chinese sever!!

**Comment by boygoder** [comment]
倒霉倒霉倒霉

**Comment by Npc2017** [comment]
你用的劫持， 还是注入呐，

**Comment by R3nzTheCodeGOD** [comment]
There is a 100% chance that you were using the LogitechLed.dll method. If you stop being lazy and make yourself an injector, you won't be banned.
