### ISSUE TITLE
Game Crashing (After New Update, 11/3/2021)

### ISSUE THREAD

**Issue by SlimePlayz** [R3nzTheCodeGOD/R3nzSkin#22]
Hey, after the new update my game has been crashing. I assume its something to do with the offsets so just wondering does anyone have them?

**Comment by Volnetiks** [comment]
You can check/ask for them by yourself [https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-255.html](here) (cf. [https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2](issue #2) for more information about how to change them

**Comment by SlimePlayz** [comment]
> You can check/ask for them by yourself [here](https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-255.html) (cf. [issue #2](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2) for more information about how to change them)

They will never reply on that fourm.

**Comment by Volnetiks** [comment]
> > You can check/ask for them by yourself [here](https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-255.html) (cf. [issue #2](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2) for more information about how to change them)
> 
> They will never reply on that fourm.

It's a pretty active forum about league offsets. Asked on last patch and they answered in a day, just give them time

**Comment by R3nzTheCodeGOD** [comment]
I found the new offsets, but the offsets are not the only problem.
The game still keeps crashing, I think there is a build change in ChampionManager.

New ChampionManager: `89 1D ? ? ? ? 57 8D 4B 08`
New *GetGoldRedirectTarget: `E8 ? ? ? ? 85 C0 74 3A`

**Since I have exams and projects at university, I can't spare time for this project right now. Just be patient and wait for the update.**

**Comment by Volnetiks** [comment]
I can write a pull request for it if you wish

**Comment by Volnetiks** [comment]
I confirm the problem for the build change in ChampionManager, I'm gonna check if I can find a solution for it

**Comment by ReaperSN** [comment]
@Volnetiks

Any luck?

**Comment by Volnetiks** [comment]
> @Volnetiks
> 
> Any luck?

Still working on it, I ain't a master at c++ lmao
I will keep my repo updated if I find anything

**Comment by ReaperSN** [comment]
> > @Volnetiks
> > Any luck?
> 
> Still working on it, I ain't a master at c++ lmao I will keep my repo updated if I find anything

Sure, ty for being so helpful :)

**Comment by null15** [comment]
> > @Volnetiks
> > Any luck?
> 
> Still working on it, I ain't a master at c++ lmao I will keep my repo updated if I find anything

Thanks <3

**Comment by Luuycent** [comment]
> 
> 
> > @Volnetiks
> > Any luck?
> 
> Still working on it, I ain't a master at c++ lmao I will keep my repo updated if I find anything

appreciate it man <3

**Comment by wtfmiamia** [comment]
any updates?

**Comment by R3nzTheCodeGOD** [comment]
I asked for help from the UnknownCheats forum in hopes that they might help, but as I guessed, they didn't help, that forum is full of bullies🙂

**I'm going to sit down at the computer soon and reverse the game and update the cheat.**

**Comment by R3nzTheCodeGOD** [comment]
It was a quick update, there maybe bugs. df322a8bda992cb73435b80019cd89095baaa2f0

**Comment by W0ksler** [comment]
> I asked for help from the UnknownCheats forum in hopes that they might help, but as I guessed, they didn't help, that forum is full of bullies🙂
> 
> **I'm going to sit down at the computer soon and reverse the game and update the cheat.**

Thanks for your efforts on making this tool updated.  

I saw people blaming on you by saying u "copypasted" B3akers but if u didnt continued his project, we wouldn't have a functional skinchanger.

I feel like i speak for everyone that uses this tool when i say im really grateful for not giving up on the project. 
I dont know if you use it, but from my part, i use it daily, and it really makes League more fun when using shiny skins.

So a big thank you!
