### ISSUE TITLE
Help please , error x00007b

### ISSUE THREAD

**Issue by alphaaced** [R3nzTheCodeGOD/R3nzSkin#221]
![20221005_110232.jpg](https://user-images.githubusercontent.com/87904912/194010717-a656afb7-a548-4596-b385-90e6e17af20e.jpg)

**Comment by alphaaced** [comment]
@R3nzTheCodeGOD

**Comment by R3nzTheCodeGOD** [comment]
## The solutions to the error are clearly stated in google.
- Update [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).
- Update GPU drivers.
- Update [Microsoft .NET Framework](https://www.microsoft.com/en-US/download/details.aspx?id=30653).
- Update [DirectX](https://www.microsoft.com/en-us/download/confirmation.aspx?id=35)

Why not use google search engine to solve the error ?
