### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MrM4ciek** [R3nzTheCodeGOD/R3nzSkin#226]
please help
![image](https://user-images.githubusercontent.com/104386607/194716229-18144e75-5659-44dc-b4a8-ec06e91232b5.png)

**Comment by R3nzTheCodeGOD** [comment]
### If you examine the current Memory.hpp file, you can see that there is no such pattern. You are using an old version.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/7a997be7d28505713c52ba3b1b1395a965558011/R3nzSkin/memory.hpp#L48-L151
