### ISSUE TITLE
How to hide it in the taskbar or explorer0.0

### ISSUE THREAD

**Issue by guyueyueshen** [R3nzTheCodeGOD/R3nzSkin#228]
Thank the author for providing this software, and want to give some suggestions to the author
Is that the program can be hidden? Obsessive compulsive disorder means it can be hidden in the taskbar or resource manager, and then the game can not automatically call out the UI... I only use one skin
Your software is very good. It's the best skin I've ever seen
Of course, I know that the author wants to tell others that the software is made by the author, which is a bit inappropriate.. I'm sorry

**Comment by R3nzTheCodeGOD** [comment]
R3nzSkin can now be minimized to the system tray. #241
