### ISSUE TITLE
FPS DROP WHEN CAST ULT

### ISSUE THREAD

**Issue by GoldGhos** [R3nzTheCodeGOD/R3nzSkin#230]
when u cast ult R on sylas and illaoi an fps drop come

**Comment by RafihYahya** [comment]
same problem . atleast for sylas never picked illaoi.

**Comment by R3nzTheCodeGOD** [comment]
I can fix this problem for Sylas but there is not much that can be done for illaoi.

**Comment by RafihYahya** [comment]
Thanks, Appreciate it.
