### ISSUE TITLE
Anivia W works with bewitching skin but not others.

### ISSUE THREAD

**Issue by alphaaced** [R3nzTheCodeGOD/R3nzSkin#233]
If it works with a new skin, this means that it could work with the previous ones but needs an update similar to the nunu ball and yone E

**Comment by R3nzTheCodeGOD** [comment]
if that means please correct it

**Comment by alphaaced** [comment]
> if that means please correct it

i dont know if it can be fixed, just hoping you would know. if her walls can be fixed pls let us know. thx

**Comment by R3nzTheCodeGOD** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/206#issuecomment-1311788168
