### ISSUE TITLE
What is the reason for this ？

### ISSUE THREAD

**Issue by NIDIE2** [R3nzTheCodeGOD/R3nzSkin#235]
What is the reason for this ？

![QQ截图20221022164142](https://user-images.githubusercontent.com/116427924/197330242-ff15c327-fb9e-421b-9abc-d2a43190649f.png)
![QQ截图20221022164312](https://user-images.githubusercontent.com/116427924/197330243-0f102ada-73c9-462d-9981-acc6724bf39e.png)
![QQ截图20221022164327](https://user-images.githubusercontent.com/116427924/197330245-890ad36c-abdf-40e2-8697-0b6e98c94aad.png)

**Comment by R3nzTheCodeGOD** [comment]
It prevents you from injecting anti cheat dll. Go to ring0 or bypass.
