### ISSUE TITLE
I need help installing and using the program.

### ISSUE THREAD

**Issue by Sarmal3** [R3nzTheCodeGOD/R3nzSkin#24]
Im sorry but I really need help to use this i just dont understand. If you could make a little tutorial i would appreciate it. Step by step, or photos, or a video. Thanks.

**Comment by HighLevelCooler** [comment]
Step 1: Download the latest release (as of the time of this writing: https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v1.1.3).
Step 2: Extract the zip file and open the unzipped folder.
Step 3: Start LoL, hop into a match, make sure you are in-game and past the loading screen.
Step 4:  Run the 'R3nzSkin_Injector' exe file and you should be able to change the screens from here.

**Comment by Sarmal3** [comment]
When i try to open R3nzSkins.rar it says that it cant open because its damaged or corrupted. And I also dont see any .exe file once i extract the files.

**Comment by R3nzTheCodeGOD** [comment]
Turn off Windows Defender and any other virus programs if any and download the cheat again.

**Comment by lilvalishawty** [comment]
the game keeps crashing for me :(( even when i extract it to lol file and turn off windows defender

**Comment by R3nzTheCodeGOD** [comment]
Make sure the required C++ dependencies are installed on your computer.

![image](https://user-images.githubusercontent.com/58574988/140773359-367182c4-41d7-45a5-aaeb-c5152a3a0754.png)

If it still doesn't work sorry I have no other solution.
