### ISSUE TITLE
Its interface will be very small on 4k screen, please fix it!

### ISSUE THREAD

**Issue by Trump-Shuai** [R3nzTheCodeGOD/R3nzSkin#240]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/79371047/198173598-73ed9a24-9eca-4ee4-91e0-88bfb97ce3af.png">

**Comment by R3nzTheCodeGOD** [comment]
### Increase the font size.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/08637b738687ac82f5edd04f9640ee7232d94711/R3nzSkin/Hooks.cpp#L213-L216

**Comment by Trump-Shuai** [comment]
thk u,It would be better if the software was built in!
