### ISSUE TITLE
game crashing even after the update 11.22

### ISSUE THREAD

**Issue by lilvalishawty** [R3nzTheCodeGOD/R3nzSkin#25]
Hey there mates, i have an issue with the game crashing even after the latest update of the program. 
Doing everything correctly as i should just like with the last patch and version and suddenly it just doesnt work.
Everytime i inject it the game just freezes and crashes, reconnecting doesnt help.
Anyone having the same issue?
Please if so let me know and help me fixing it <33

**Comment by R3nzTheCodeGOD** [comment]
I tested it after updating and it should be working. Maybe you are making one of the common mistakes.

Things Forgotten To Do;
- Extracting the cheat from RAR
- Injecting the cheat before the game starts
- Turn off antivirus and windows defender, if they are on

**Comment by lilvalishawty** [comment]
still crashing ://

**Comment by R3nzTheCodeGOD** [comment]
Make sure the required C++ dependencies are installed on your computer.

![image](https://user-images.githubusercontent.com/58574988/140773359-367182c4-41d7-45a5-aaeb-c5152a3a0754.png)

If it still doesn't work sorry I have no other solution.
