### ISSUE TITLE
General question about the safety of this skin changer.

### ISSUE THREAD

**Issue by JustMaxExe** [R3nzTheCodeGOD/R3nzSkin#252]
Hey so i just wanted to really quickly ask about the general safety of the program as of viruses and such.
I know that antiviruses often detect game cheats as dangerous n stuff so i dont really mind it but the thing is that after using R3nzSkin there appears to be trojan spreading around (i didnt download anything else than the skinchanger in last week and i tried multiple times which always resulted in trojan appearing.) 
Soo what is this all about?

(to be more specific, if that matters it, was Trojan Win32/Tiggre!rfn)

**Comment by ScutWoolysocks** [comment]
Its a discord token grabber I've inspected it a while ago, it was I think at least legit when the changer was realeased, but now its just a virus, its not coincidental. Watch your discord account carefully.

**Comment by R3nzTheCodeGOD** [comment]
> Its a discord token grabber I've inspected it a while ago, it was I think at least legit when the changer was realeased, but now its just a virus, its not coincidental. Watch your discord account carefully, also visist Virustotal.com and that should let you know everything

### You must have received job offers from Marvel Comics and DC Comics.

https://user-images.githubusercontent.com/58574988/200997033-44b39f38-3cff-4d59-892c-58cd0cff4530.mp4

**Comment by ScutWoolysocks** [comment]
Haha right ;) 

💀💀💀💀💀💀💀💀

**Comment by hotline1337** [comment]
> Haha right ;) 💀💀💀💀💀💀💀💀
> 
> Also you literally haven't proven anything or answered the person... so not sure what is so bruh about scamming ppl this way and taking their shit cuz I know for a fact your code is filled with that shit, I use to use this and then shit like that started happening and I stopped instantly

you can literally view the source code.... and compile it urself?

**Comment by R3nzTheCodeGOD** [comment]
> Hey so i just wanted to really quickly ask about the general safety of the program as of viruses and such. I know that antiviruses often detect game cheats as dangerous n stuff so i dont really mind it but the thing is that after using R3nzSkin there appears to be trojan spreading around (i didnt download anything else than the skinchanger in last week and i tried multiple times which always resulted in trojan appearing.) Soo what is this all about?
> 
> (to be more specific, if that matters it, was Trojan Win32/Tiggre!rfn)

I reduced the false positives on VirusTotal site from 42 to 18 by making a few changes to injector compile settings. It should no longer be automatically deleted by windows defender.

**Comment by Pxprl** [comment]
> Its a discord token grabber I've inspected it a while ago, it was I think at least legit when the changer was realeased, but now its just a virus, its not coincidental. Watch your discord account carefully, also visist Virustotal.com and that should let you know everything

Big bruh moment right there
