### ISSUE TITLE
Syndra balls 

### ISSUE THREAD

**Issue by lordmintaro** [R3nzTheCodeGOD/R3nzSkin#256]
Syndra balls doesnt change. Vladimir shit in his hands too

**Comment by lordmintaro** [comment]
Syndra balls change but only after ultimate

**Comment by R3nzTheCodeGOD** [comment]
Syndra
- Fixed by the game when using the ulti.

Vladimir
- Fixed by the game when he casts his W ability.

**I have examined both characters, they are not suitable for manual correction.**
