### ISSUE TITLE
If the Chinese server uses "Wegame. exe", it will display bugs

### ISSUE THREAD

**Issue by maofeichao11** [R3nzTheCodeGOD/R3nzSkin#258]
If the Chinese server uses "Wegame. exe", it will display bugs

**Comment by maofeichao11** [comment]
"Wegame" is similar to Roitgameserver

**Comment by maofeichao11** [comment]
In the game, it can calculate the cooling time of "RedBuff"

**Comment by maofeichao11** [comment]
It should be "imgui"

**Comment by Yousazoe** [comment]
你把wegame设置为纯净模式就好了。

**Comment by rainzee** [comment]
The Chinese service was implemented by me together with the author, we spent a night Debug, looking for offsets, I guess this may be caused by draw hook competition, I try to fix the problem.

**Comment by maofeichao11** [comment]
> The Chinese service was implemented by me together with the author, we spent a night Debug, looking for offsets, I guess this may be caused by draw hook competition, I try to fix the problem.

dx11

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinnese Anti-Cheat
