### ISSUE TITLE
new release crashes!

### ISSUE THREAD

**Issue by NerfDoriftar** [R3nzTheCodeGOD/R3nzSkin#26]
played amumu, all was good until crash!
my actions: 
1. selected skin
2. set all skins for enemy to default
3. did q into team fight and boom - crash.
 
I think it's because i've changed enemy team skins to default.

**Comment by R3nzTheCodeGOD** [comment]
everything looks fine in the code, can you play a few more games and come back here?

**Comment by NerfDoriftar** [comment]
Sure, here is my analysis.

1.Custom game (practice tool) with 5 bots, game speed up (2 times by 10 minutes)
2. Changed all enemy team skins to random one.
3. After that i added lvl and gold 
4. And then i buy some items and i got crash.
5. Reconnect
6. Set all enemy skins to default
7. Crash after 1 min
8. Download version  v1.6
9. Reconnect
10. All works perfect

**Comment by R3nzTheCodeGOD** [comment]
Yes, based on what you said, the problem should certainly be in the method of changing the skin of other champions.

I created a training mode for my game to crash and I changed the skin of the bot, but unfortunately the game never crashed for 50 minutes, so I guess it's my luck.

Use the old version until I rectify this problem.

![image](https://user-images.githubusercontent.com/58574988/133643863-da4db82e-0603-4b45-b332-b4a1ae367974.png)

**Comment by NerfDoriftar** [comment]
I think you should create a game with 5 bots vs you, it will increase probability of crash, also every normal or ranked game is 5 vs 5, so we need to test this scenario for better results! :)

For creating a practice tool game with 5 bots vs you use this [github source link (click)](https://github.com/MManoah/league-practice-tool)

Anyway, for me new functions doesn't matter, btw thanks for you work!

**Comment by R3nzTheCodeGOD** [comment]
I tried 9 bot training mode, but still couldn't crash my game.

But I changed a part of the code that might crash, can you try the new version for me?

 [R3nzSkinDEBUG](https://cdn.discordapp.com/attachments/748413086083317811/888170324351402044/R3nzSkinDEBUG.rar)

**Comment by NerfDoriftar** [comment]
Tested now the version you sent, seems to be all is nice!
Didn't get any crash, tested two times with two different champs, maximum stress test, without any crash.
Thanks

**Comment by R3nzTheCodeGOD** [comment]
like you said it shouldn't crash anymore
