### ISSUE TITLE
Is the current version compatible with patch 12.22?

### ISSUE THREAD

**Issue by alphaaced** [R3nzTheCodeGOD/R3nzSkin#260]
just that or if needs update for offset.

**Comment by hazza3142** [comment]
For me it's working, but some bug pop out.

**Comment by hazza3142** [comment]
![x](https://user-images.githubusercontent.com/116691069/202283090-9743d62d-7650-4896-83a0-225559bec6c2.png)

**Comment by hazza3142** [comment]
I'm using the oldest version, I downloaded the newest and window still pop out
