### ISSUE TITLE
Kindred passive bug

### ISSUE THREAD

**Issue by Kientzyy** [R3nzTheCodeGOD/R3nzSkin#263]
Hello, Kindred's passive does not display correctly on the minimap when the software is activated.

**Comment by R3nzTheCodeGOD** [comment]
1765c2e1f5d5a7c93ba8e68455666ddd7a460d8f
The Problem should be solved. Test and give feedback

**Comment by Kientzyy** [comment]
> [1765c2e](https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/1765c2e1f5d5a7c93ba8e68455666ddd7a460d8f) The Problem should be solved. Test and give feedback

Yo, not fixed bro :/ This is what i see : 
![Screenshot_1](https://user-images.githubusercontent.com/118614748/202982351-5c27dc72-7c6e-417d-be3b-79fd0cb5def1.png)

**Comment by R3nzTheCodeGOD** [comment]
![image](https://user-images.githubusercontent.com/58574988/202998031-93378964-e434-4061-be0e-97731032ed67.png)

**Comment by Kientzyy** [comment]
I will try it this night but maybe it work in solo but not in normal/ranked games

**Comment by Kientzyy** [comment]
> ![image](https://user-images.githubusercontent.com/58574988/202998031-93378964-e434-4061-be0e-97731032ed67.png)

So, I tried it now on a new fresh pc to be sure it's not my pc the problem and no, it's not working :( . You can look at the screen :
![Sans titre](https://user-images.githubusercontent.com/118614748/203054412-87daece5-aaa1-480b-9a9f-a257c3729af3.png)

**Comment by R3nzTheCodeGOD** [comment]
@codexJoin It is doing exactly what you said, carefully examine the source code.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/9e5c08921c1e446d0a1056c03a1660a1028ef2e5/R3nzSkin/Hooks.cpp#L422-L427

**Comment by hotline1337** [comment]
#1
