### ISSUE TITLE
wards not appearing.

### ISSUE THREAD

**Issue by alphaaced** [R3nzTheCodeGOD/R3nzSkin#264]
The wards are invisible on my end, anyone else?

**Comment by cxy-yanggod** [comment]
同样看不到 r3未更新前可以

**Comment by alphaaced** [comment]
> [v2.3.1](https://github.com/R3nzTheCodeGOD/R3nzSkin/tree/v2.3.1) No problem 

yes old version has no problem with wards but swaps the jungle pets. New version fixed the pet issue but the wards dont appear now.

**Comment by cxy-yanggod** [comment]
Thanks
