### ISSUE TITLE
Battle Queen Katarina Audio bug

### ISSUE THREAD

**Issue by Exatio** [R3nzTheCodeGOD/R3nzSkin#266]
When ulting on katarina battle queen, even if you stop ulting, the sound effect will play until the normal full duration of ult

**Comment by alphaaced** [comment]
similar to kayn ult, it sticks after the ult and is very high. Doesnt go away till end of game.

**Comment by Exatio** [comment]
> similar to kayn ult, it sticks after the ult and is very high. Doesnt go away till end of game.

Personally it doesn't stick till end of game, just until maximum ult duration

**Comment by alphaaced** [comment]
> > similar to kayn ult, it sticks after the ult and is very high. Doesnt go away till end of game.
> 
> Personally it doesn't stick till end of game, just until maximum ult duration

weird, mine is very annoying. Idk why, did you try odyssey kayn? Its so damn loud.

**Comment by R3nzTheCodeGOD** [comment]
#1
