### ISSUE TITLE
this has virus

### ISSUE THREAD

**Issue by Pekora11** [R3nzTheCodeGOD/R3nzSkin#267]
this program is a Trojan, at first when I downloaded it the browser jumped warning me that it is some type of malicious file but I did not pay attention to it after that in a few days I did not know that my private accounts such as instagram, facebook etc had changed all the password and mail is not worth the risk and i almost lost my lol account too. Does anyone know how to report this project, I also did a test on the virustotal page and oh surprise it jumped like a Trojan, I did tests with other skin changers and they didn't jump as many alerts as this program.

**Comment by Legnatbird** [comment]
U can see the code bro wtf

**Comment by R3nzTheCodeGOD** [comment]
> this program is a Trojan, at first when I downloaded it the browser jumped warning me that it is some type of malicious file but I did not pay attention to it after that in a few days I did not know that my private accounts such as instagram, facebook etc had changed all the password and mail is not worth the risk and i almost lost my lol account too. Does anyone know how to report this project, I also did a test on the virustotal page and oh surprise it jumped like a Trojan, I did tests with other skin changers and they didn't jump as many alerts as this program.

### @Pekora11 better call Saul

https://user-images.githubusercontent.com/58574988/202965869-200a1ad5-7fb4-4185-8e71-57a98d829dac.mp4
