### ISSUE TITLE
Disable every skin except user's, scrolling

### ISSUE THREAD

**Issue by JakubCisowski** [R3nzTheCodeGOD/R3nzSkin#270]
Hi!

1) I would like to propose a button/checkbox similar to the 'No Skins' button, but instead it disables every skin except of the user's skin. 

I wonder if I'm alone with this issue - I want to disable all enemy/teammate skins to make spells more visible, but I don't want to disable my own. This leads to me clicking 'No Skins' at the start of each game, and then resetting my own skin to my own liking.

2) Also, could something be done so that when I scroll through a list of skins to choose (inside R3nzSKin window) my League camera doesn't zoom in or out? It's a bit annoying. The scrollbar on the right is really narrow and hard to click on.

3) Do i need to install new injector every new patch? If so, will my selected skins for champions reset? Where are they stored?

Thanks for creating this amazing app.

**Comment by R3nzTheCodeGOD** [comment]
1. The no skin feature no longer resets the appearance of the local player. 7111a4f270d96ae0e42418d212df0fab16387cb6
2. R3nzSkin cannot block user input.
3. You can use any injector you want with R3nzSkin. also the config file is located at `documents\R3nzSkin`.

**Comment by JakubCisowski** [comment]
Thanks! To be honest now that I think about it, wouldn't it be even better if that feature was a checkbox so it would be saved between games? So that user wouldn't need to click it every game (I assume if user clicks 'No skin', he does that every game)
