### ISSUE TITLE
No skin as a checkbox

### ISSUE THREAD

**Issue by JakubCisowski** [R3nzTheCodeGOD/R3nzSkin#271]
Thanks for the 'No skin' update I've requested.
To be honest now that I think about it, wouldn't it be even better if that feature was a checkbox so it would be saved between games? So that user wouldn't need to click it every game (I assume if user clicks 'No skin', he does that every game, so it would be much more convenient for people using this feature)

I don't mean that the button should be replaced by checkbox, just that it would be practical if there was an option to save that setting between games.

**Comment by R3nzTheCodeGOD** [comment]
it's already doing that.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/9e5c08921c1e446d0a1056c03a1660a1028ef2e5/R3nzSkin/GUI.cpp#L203-L207
