### ISSUE TITLE
running on linux

### ISSUE THREAD

**Issue by serekAlmette** [R3nzTheCodeGOD/R3nzSkin#272]
I think I tried every possible way to run this on arch linux. Can is there any way that I didn't tried if there is, can someone show me how?

**Comment by jabuxas** [comment]
did you find a method? isn't working for me

**Comment by I-Want-ToBelieve** [comment]
rename R3nzSkin.dll to /home/username/xxxx/xxxxx/league-of-legends/drive_c/Riot Games/League of Legends/Game/hid.dll

NixOS, Lutris , lutris-ge-lol-p8-12-x86_64

Work Well

**Comment by I-Want-ToBelieve** [comment]
The Taiwan server I played has been permanently blocked. 😭
