### ISSUE TITLE
Dawnbringer riven bugs

### ISSUE THREAD

**Issue by xaninhpudins** [R3nzTheCodeGOD/R3nzSkin#274]
The skin is mostly fine until she ults

1-her sword doest become long (ctrl 1 displays the long blade on the ground tho)
2-only the self ulting, standing and windslash animations show the gold character model, walking and using the other abilities causes her normal model to apear
3-although the game plays one of her voice lines when she ults the rest of the time the game is playing the base voice lines

**Comment by alphaaced** [comment]
#1
