### ISSUE TITLE
[Bug] Go fix animation legendary katarina

### ISSUE THREAD

**Issue by zeroyeap** [R3nzTheCodeGOD/R3nzSkin#275]
Animations of the Legendary Katarina skin remain when you swap for any other Katarina skin.
![image](https://user-images.githubusercontent.com/109529835/205282370-6b2f4744-f97d-4ad6-9646-2debd0efb8f6.png)

**Comment by zeroyeap** [comment]
Please fix this.

**Comment by xaninhpudins** [comment]
#257
