### ISSUE TITLE
infernal nasus issues

### ISSUE THREAD

**Issue by SrVulpes** [R3nzTheCodeGOD/R3nzSkin#278]
the Q has visual change but presents the same problem of the skin of the super galaxy rumble already the other skills have no change and end up buging certain textures like the R that gets very broken visually

1: how should the R
2: how it ends up getting
3: the problem of Q equal to the rumble (Do not know if this is something that can be fixed or is server problem so sorry if I'm talking about a problem that can not be fixed)

![Captura de tela 2022-12-04 110511](https://user-images.githubusercontent.com/119796211/205495506-5c70a68e-d917-40f3-b920-ce245478b82f.jpg)

anyway thank you for everything you've done   ^~^

**Comment by alphaaced** [comment]
This issue similar to many othere are server sided #1.

**Comment by SrVulpes** [comment]
> Este problema semelhante a muitos outros são do lado do servidor [# 1](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1).

ahhhhh okay then  :-:

**Comment by R3nzTheCodeGOD** [comment]
#1
