### ISSUE TITLE
High Noon Ashe texture popping 

### ISSUE THREAD

**Issue by BigBadBodyPillow** [R3nzTheCodeGOD/R3nzSkin#279]
Happens with all chromas
How it should look
![Screenshot 2022-12-06 101221](https://user-images.githubusercontent.com/119925640/205856450-a86cbac8-e786-4a9d-b81d-a61488bd03b7.jpg)

How it actually looks
![tr3PMGQL](https://user-images.githubusercontent.com/119925640/205856492-eb0ba81e-926c-4709-9b5a-014c96c43925.gif)

**Comment by R3nzTheCodeGOD** [comment]
#1
