### ISSUE TITLE
The application was unable to start correctly

### ISSUE THREAD

**Issue by Graydenn** [R3nzTheCodeGOD/R3nzSkin#28]
Was using this before I reset my computer, then I reset it and it stopped working. I set the computer up the exact same way as before, to my knowledge.

Basically, downloaded the latest version of the program, ran it, and got
"The application was unable to start correctly (0xc000007b). Click OK to close the application."

Not sure what's causing this.

**Comment by R3nzTheCodeGOD** [comment]
It looks like you haven't installed DirectX or Microsoft Visual C++ framework.

After doing the correct installations, the problem will be fixed.
