### ISSUE TITLE
Excuse me,could please tell me how can I change language?

### ISSUE THREAD

**Issue by xiangshuiyoudu** [R3nzTheCodeGOD/R3nzSkin#283]
Dear Sir
    I don't know if your  program is only English supported. I want to change language. But I did not find a button to change language. So I have to ask this question to you. I am looking forward to hearing from you soon.
    Best wishes！Best regards！

**Comment by icarss** [comment]
From my experience with this software, it doesn't have language change feature.

**Comment by R3nzTheCodeGOD** [comment]
The names of the skins are dependent on the language you are playing the game in, the interface is in English. If you want, you can modify the texts in your own language and compile them.
