### ISSUE TITLE
Anivia's wall is not displayed

### ISSUE THREAD

**Issue by Gasferr** [R3nzTheCodeGOD/R3nzSkin#284]
Anivia's wall is not displayed if the skin does not have the effect of the skin's wall by default, otherwise it is not visible

![anivia muro](https://user-images.githubusercontent.com/34402763/206855520-3311dfe2-0fc8-4506-a203-f0b1725ad021.png)

**Comment by alphaaced** [comment]
#1

**Comment by alphaaced** [comment]
#1

**Comment by diyooor** [comment]
#1
