### ISSUE TITLE
Suggestion: Add skins from killerskins or potential to add custom skin files

### ISSUE THREAD

**Issue by nivibilla** [R3nzTheCodeGOD/R3nzSkin#287]
Is it possible to add custom skins to the tool, for example skins from killer skins come in fantome format.

**Comment by R3nzTheCodeGOD** [comment]
It is possible but R3nzSkin does not have such a purpose.

**Comment by nivibilla** [comment]
hi, could you please let me know how I can add it myself. I don't have much experience in this
