### ISSUE TITLE
The voicelines for Cosmic Lux and Dark Cosmic Lux skins is bugged. 

### ISSUE THREAD

**Issue by ScarletFirefly** [R3nzTheCodeGOD/R3nzSkin#288]
These two skins have bugged voicelines and use the default Lux's skin voicelines. 
Bugged voicelines are when moving, attacking, casting abilities etc. Voicelines triggered by Ctrl + [1-4] seem unaffected.

**Comment by 1024191579** [comment]
i find the problem too!!!!!

**Comment by hotline1337** [comment]
#1
