### ISSUE TITLE
LoL crashes after patch 11.23 

### ISSUE THREAD

**Issue by ch0wi** [R3nzTheCodeGOD/R3nzSkin#29]
Apologies if this is not appropriate I was just wondering if it's on my end or the skin changer has not been updated yet. It crashes the game when injecting before and after the game starts, which it has not done before the most recent patch. Playing on EUNE live launcher.

**Comment by DushesS01** [comment]
It crashes if you try inject before game has loaded. Wait for fountain spawn first

**Comment by DushesS01** [comment]
On RU server works fine

**Comment by ch0wi** [comment]
I have since reinstalled the game which seems to have fixed the issue of crashing and the program works flawlessly now.
