### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by KaSock** [R3nzTheCodeGOD/R3nzSkin#291]
How do I uninstall the software and clean up its residue?

After I reinstall Windows, the software does not work. I need to uninstall it and clean up the residue.

**Comment by KaSock** [comment]
Unable to inject into the game, he will not always try to inject. He only injected once at the beginning of the game.

I don't know what the problem is.

![image](https://user-images.githubusercontent.com/56071624/211162813-be40d2cb-79ef-4bea-bd91-61ad080d9333.png)

**Comment by KaSock** [comment]
The game worked normally a few days ago, but it suddenly failed today. There was no update or hot patch for the game.

**Comment by KaSock** [comment]
Even if I reinstall the game, it will not work.

My runtime is complete.

![image](https://user-images.githubusercontent.com/56071624/211166505-b2cd7178-de9a-425e-b2b3-7e9147838e71.png)

**Comment by BariFL** [comment]
你系统是从WIN11退回WIN10了吗   
WIN10国服不能直接用  要替换一下文件  方法参阅R3NZ贴吧   有比较详细的教程

**Comment by KaSock** [comment]
> 你系统是从WIN11退回WIN10了吗 WIN10国服不能直接用 要替换一下文件 方法参阅R3NZ贴吧 有比较详细的教程

是的，我从win11回退到win10了，感谢你的答复，没有想过是系统差异带来的问题 ：）
