### ISSUE TITLE
 Wish I could switch skins with shortcuts

### ISSUE THREAD

**Issue by OHahaha** [R3nzTheCodeGOD/R3nzSkin#297]
Manually switching skins is a bit of a pain, I wish I could use shortcuts to switch them with one click😘😘😘

**Comment by alphaaced** [comment]
i think you already can.

**Comment by hotline1337** [comment]
you can do that

> Manually switching skins is a bit of a pain, I wish I could use shortcuts to switch them with one click😘😘😘
