### ISSUE TITLE
Unable to inject

### ISSUE THREAD

**Issue by afeer123** [R3nzTheCodeGOD/R3nzSkin#30]
![image](https://user-images.githubusercontent.com/86306447/145791079-9ae2f97a-4de2-4c10-a508-c703d0d48747.png)

**Comment by R3nzTheCodeGOD** [comment]
- Note that the **R3nzSkin.dll** and the injector are in the same folder.
- Make sure your anti virus is turned off.
- Make sure you download the version compatible with your own server.
   - if you are on china server make sure you start the game in DirectX9 mode.
