### ISSUE TITLE
Attention!

### ISSUE THREAD

**Issue by bilibiliEmiya** [R3nzTheCodeGOD/R3nzSkin#301]
It seems like chinese server  has been detected R3nzSkin,my friend and I have been banned.We don't use the injector, but directly replace the file.
![QQ图片20230126014252](https://user-images.githubusercontent.com/54109395/214641061-5afe88fd-a615-49a2-a192-689114514439.jpg)

**Comment by NeoZion** [comment]
Yes，The Tencent security team has taken note of the software。

**Comment by Aperodry** [comment]
you need to bypass 03/04 checks，It's about features

**Comment by NeoZion** [comment]
> you need to bypass 03/04 checks，It's about features

what is 03/04 checks？

**Comment by Aperodry** [comment]
> > you need to bypass 03/04 checks，It's about features
> 
> what is 03/04 checks？

TP ban time is 03 minutes or 04 minutes

**Comment by VINOWjp** [comment]
> > > you need to bypass 03/04 checks，It's about features
> > 
> > 
> > what is 03/04 checks？
> 
> TP ban time is 03 minutes or 04 minutes

If I disconnected network, then I replace the file,  like this, can I escape TP's check?

**Comment by good-and-more** [comment]
你有点憨吧，外服不管这事，你在国服开，真没尝过化腾的手段啊

**Comment by AquaCobell** [comment]
only on chinese servers or also europe and american?

**Comment by good-and-more** [comment]
> 

only tencent servers，u can use it in any other riot derectly servers

**Comment by good-and-more** [comment]
> only on chinese servers or also europe and american?

only tencent servers，u can use it in any other riot derectly servers

**Comment by AquaCobell** [comment]
thank you, hope you guys will find a way to not get banned on tencent servers.

**Comment by 213764** [comment]
现在还用吗

**Comment by zhougjstudy** [comment]
> > > you need to bypass 03/04 checks，It's about features
> > 
> > 
> > what is 03/04 checks？
> 
> TP ban time is 03 minutes or 04 minutes
Is it the 03 and 04 minutes of every hour？

**Comment by w004076** [comment]
I kown a idea,it can pass TP 03/04

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinese Anti-Cheat
