### ISSUE TITLE
The Monkey King's e-skill doppelganger shadow will become the original skin

### ISSUE THREAD

**Issue by 213764** [R3nzTheCodeGOD/R3nzSkin#303]
Ask the boss to fix this bug.

thankyou.🙂

**Comment by 213764** [comment]
Boss, there are still many skin holes. I beg you to fix these loopholes.😭

Finally, I wish you good military service and wait for you to come back.

**Comment by 213764** [comment]
Could you please fix the vulnerability of the Monkey King's e-skills? Asian players like to play the hero the Monkey King. If you can fix the bug of the Monkey King's e-skills, I believe your supporters will be more and more.😀😀😀

**Comment by 213764** [comment]
等你归来，兄弟

**Comment by 213764** [comment]
😀

**Comment by 213764** [comment]
Look at it every day

**Comment by pljjy** [comment]
He lives in Turkey, I don't think he has time or opportunity to fix it rn

**Comment by 213764** [comment]
When you come back, I wish you all the best, brother

**Comment by hotline1337** [comment]
#1
