### ISSUE TITLE
13.3版本更新后的使用方法        Note for 13.3

### ISSUE THREAD

**Issue by BariFL** [R3nzTheCodeGOD/R3nzSkin#304]
说明    仅适用于拳头直营服    马服换肤自行承担责任   
13.3版本更新后   使用R3NZSKIN进入游戏后会无限弹窗    且游戏内没有R3的软件界面
但是可以下载发布日期为  Nov 12, 2022 的v2.3版本    使用这个版本的软件只会在每局进游戏的时候弹窗一次    需要关闭弹窗   之后就可以正常换肤
至于为什么可以用    我不清楚     只是挨个试了以往发布版本   正好试出来这个能用
也希望作者服役顺利  早日平安归来

![1](https://user-images.githubusercontent.com/117833131/217726700-696768eb-7f8a-48ca-bc01-10a46bf1d164.png)

Get  [Releases]
Find [v2.3] updated in Nov 12, 2022
Click the pop-up every game

**Comment by baigu-147** [comment]
老哥可以，太感谢了！

**Comment by LiYunDong-bilibili** [comment]
可以可以！

**Comment by 1325266720** [comment]
希望服役顺利作者能平安回来
I hope the service goes well and the author returns safely.

**Comment by Neinndall** [comment]
I would like to use it for the PBE server... not for the LIVE server
I want to try things in the practice tool like the teaser of "firebuddy" the new champion milio, but it is not possible to use it in 13.4

**Comment by Gasferr** [comment]
[R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10701007/R3nzSkin-v13.3.zip)

**Comment by BariFL** [comment]
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10701007/R3nzSkin-v13.3.zip)
![QQ图片20230210095718](https://user-images.githubusercontent.com/117833131/217980943-0fc966de-d48b-495a-8956-c7df272c86cd.png)

**Comment by TheNei** [comment]
不行啊大哥

**Comment by TheNei** [comment]
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10701007/R3nzSkin-v13.3.zip)

发错了好兄弟，应该是这个

[R3nzSkin (1).zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10706686/R3nzSkin.1.zip)

or 
https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v2.3

**Comment by bigbigEden** [comment]
> > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10701007/R3nzSkin-v13.3.zip)
> 
> 发错了好兄弟，应该是这个
> 
> [R3nzSkin (1).zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10706686/R3nzSkin.1.zip)
> 
> or https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v2.3

可以用！感谢
