### ISSUE TITLE
Update for 13.3

### ISSUE THREAD

**Issue by Gasferr** [R3nzTheCodeGOD/R3nzSkin#305]
**dowload .zip and enjoy**
![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)

[R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)

`"8D 8B ? ? ? ? FF 74 24 54", "8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00" `   CharacterDataStack

**Comment by Tlhqdklii-S** [comment]
pls write here, if you can overcome this problem

**Comment by YuXinQaQ** [comment]
have same problem

**Comment by raskalc** [comment]
Need offset fix

**Comment by oMaikeru** [comment]
"8D 8E ? ? ? ? FF 74 24 4C",
				"8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00"
			}, false, true, 0, &offsets::AIBaseCommon::CharacterDataStack
			
			those are the lines that need to be updated does anyone know the updated one?

**Comment by raskalc** [comment]
in my opinion this pattern not correct

**Comment by Hecticism** [comment]
new patterns:

81 C1 A8 2D 00 00 E9 ?? ?? ?? ?? ?? ?? ?? ?? ?? 51
81 C1 A8 2D 00 00 E9 55 B4 FB FF ?? ?? ?? ?? ?? 81

**Comment by Gasferr** [comment]
> 

the game closes with these new compensations

**Comment by Gasferr** [comment]
> new patterns:
> 
> 81 C1 A8 2D 00 00 E9 ?? ?? ?? ?? ?? ?? ?? ?? ?? 51 81 C1 A8 2D 00 00 E9 55 B4 FB FF ?? ?? ?? ?? ?? 81

the game closes with these new compensations

**Comment by oMaikeru** [comment]
if anyone somehow make it work please post it here :)

**Comment by mobaiyan** [comment]
same problem

**Comment by Gasferr** [comment]
![image](https://user-images.githubusercontent.com/34402763/217848917-8ea806c1-4ed3-4de9-8a2d-dc7670875af2.png)
[Uploading R3nzSkin-2.3.zip…]()

**Comment by Gasferr** [comment]
> Guys we have to wait. The author is turkish and maybe something harmful happened after turkey earthquake.

We try to find a temporary solution between everything until the creator or collaborators can solve it

**Comment by alphaaced** [comment]
> > Guys we have to wait. The author is turkish and maybe something harmful happened after turkey earthquake.
> 
> We try to find a temporary solution between everything until the creator or collaborators can solve it

what u posted works? we just get error first game and then its gone?

**Comment by Gasferr** [comment]
> 

If it works, you just have to accept the error window and it works normally

**Comment by Tlhqdklii-S** [comment]
> throws pattern error once, but can then be used normally ![image](https://user-images.githubusercontent.com/34402763/217849962-78a538cc-c28e-46e8-8e7f-658c8e917adc.png) ![image](https://user-images.githubusercontent.com/34402763/217851066-70da93e3-dbfc-4cb9-a608-404bab4887f9.png)
> 
> [R3nzSkin-12.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10698534/R3nzSkin-12.3.zip)

i can use with ur link now, so firstly giving error then im approving and works. ty bro. its temporarily solution.

**Comment by Gasferr** [comment]
> Reference

You can now update with the compensations to the recent version so it will not throw the error

**Comment by Gasferr** [comment]
> > throws pattern error once, but can then be used normally ![image](https://user-images.githubusercontent.com/34402763/217849962-78a538cc-c28e-46e8-8e7f-658c8e917adc.png) ![image](https://user-images.githubusercontent.com/34402763/217851066-70da93e3-dbfc-4cb9-a608-404bab4887f9.png)
> > [R3nzSkin-12.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10698534/R3nzSkin-12.3.zip)
> 
> i can use with ur link now, so firstly giving error then im approving and works. ty bro. its temporarily solution.

You can now update with the compensations to the recent version so it will not throw the error

**Comment by alphaaced** [comment]
> **dowload .zip and enjoy**
> ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> 
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> 
> 

does it still give the error message or did u manage to fix?

**Comment by Gasferr** [comment]
> > **dowload .zip and enjoy**
> > ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> 
> does it still give the error message or did u manage to fix?

I managed to fix it, above the thread is to download it

**Comment by hazza3142** [comment]
@Gasferr legend

**Comment by DAsrinK** [comment]
> > > **dowload .zip and enjoy**
> > > ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> > 
> > 
> > does it still give the error message or did u manage to fix?
> 
> I managed to fix it, above the thread is to download it

This is working, you are really legend

**Comment by Darkaim63** [comment]
> > > **dowload .zip and enjoy**
> > > ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> > 
> > 
> > does it still give the error message or did u manage to fix?
> 
> I managed to fix it, above the thread is to download it

What were the offsets you used?

**Comment by Gasferr** [comment]
> > > > **dowload .zip and enjoy**
> > > > ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > > > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> > > 
> > > 
> > > does it still give the error message or did u manage to fix?
> > 
> > 
> > I managed to fix it, above the thread is to download it
> 
> What were the offsets you used?

`				"8D 8B ? ? ? ? FF 74 24 54",
				"8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00"`

**Comment by Darkaim63** [comment]
> > > > > **dowload .zip and enjoy**
> > > > > ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > > > > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> > > > 
> > > > 
> > > > does it still give the error message or did u manage to fix?
> > > 
> > > 
> > > I managed to fix it, above the thread is to download it
> > 
> > 
> > What were the offsets you used?
> 
> ` "8D 8B ? ? ? ? FF 74 24 54", "8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00"` CharacterDataStack

Hm, maybe I'm just a noob but I can't get this to build now.

**Comment by Neinndall** [comment]
> **dowload .zip and enjoy** ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> 
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)

for the 13.4 pbe, work? astronauts skins and firebuddy?

**Comment by Gasferr** [comment]
> > **dowload .zip and enjoy** ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> > [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> 
> for the 13.4 pbe, work? astronauts skins and firebuddy?

I did not try it, but surely they are different compensations

**Comment by Sheelia** [comment]
https://github.com/Sheelia/R3nzSkin-v13.3

**Comment by seth007-moo** [comment]
> https://github.com/Sheelia/R3nzSkin-v13.3

WE REALLY APPRECIATE YOUR HELP! 
and hope you can keep an update for the next patches.

**Comment by Gasferr** [comment]
> > https://github.com/Sheelia/R3nzSkin-v13.3
> 
> WE REALLY APPRECIATE YOUR HELP! and hope you can keep an update for the next patches.

We are going to leave this thread active to be able to post the update of the compensations, and the zip with the updated trick

**Comment by wxhecydxjj** [comment]
love you

**Comment by rainzee** [comment]
> > https://github.com/Sheelia/R3nzSkin-v13.3
> 
> WE REALLY APPRECIATE YOUR HELP! and hope you can keep an update for the next patches.

I can update all the time. I will update the offsets first time when next patch

**Comment by guajiguawai** [comment]
Thank you for your efforts. I hope you can continue to update it in the future. If you have time, can you update the tft version of the software?

**Comment by 213764** [comment]
The Monkey King's e-skill doppelganger shadow will become the original skin😀

**Comment by AndroidDeep** [comment]
Thank you guys

**Comment by 13476653157** [comment]
Thank you

**Comment by 13476653157** [comment]
Thank you

**Comment by Yousazoe** [comment]
who can tell me these fixed offset coming from? why must be:
```
8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00
```

**Comment by dothmeun** [comment]
> https://github.com/Sheelia/R3nzSkin-v13.3

is there something changed?

**Comment by sinuxyz** [comment]
> **dowload .zip e aproveite** ![image](https://user-images.githubusercontent.com/34402763/217909273-2e266fd5-cbbc-435a-819c-b63334be1246.png)
> 
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
> 
> `"8D 8B ? ? ? ? FF 74 24 54", "8D 8E ? ? 00 00 89 44 24 ? C7 44 24 ? 00 01 00 00" ` CharacterDataStack

thanks!

**Comment by sinuxyz** [comment]
> [R3nzSkin-v13.3.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10700720/R3nzSkin-v13.3.zip)
Thanks bro, good job! ❤️

**Comment by chloeprice1991** [comment]
thanks bro!!!!!!!!!!

**Comment by kaiyihuo** [comment]
> Guys we have to wait. The author is turkish and maybe something harmful happened after turkey earthquake.

He's thankfully okay, just mandatory military service. Read his announcement.

**Comment by 213764** [comment]
Hello, brother, can you fix the skin bug in the software? Everyone will thank you very much. There are many skin bugs, such as the Monkey King E skill, Nestor Cerberus Q skill, and many, many, brother, can you fix these bugs slowly? If you fix them, you will become the champion of SKIN author.😀😀😀

**Comment by alphaaced** [comment]
> Hello, brother, can you fix the skin bug in the software? Everyone will thank you very much. There are many skin bugs, such as the Monkey King E skill, Nestor Cerberus Q skill, and many, many, brother, can you fix these bugs slowly? If you fix them, you will become the champion of SKIN author.😀😀😀

We can wish but no body can fix those bugs, it's not issue from the app but from league files, these particles are hidden and cant be obtained.

**Comment by hotline1337** [comment]
Updated for the latest game update

**Comment by dkahdiuaha** [comment]
hey bro.Can you update R3nzskinTFT For 13.3？Thanks

**Comment by xiaoyuhaoda** [comment]
yes

**Comment by lilhalfuct98** [comment]
hi is there 13.4 comein?? :c

**Comment by OUYANG777** [comment]
The new version will change back to its original appearance after the character dies once
