### ISSUE TITLE
"failed to find pattern ....."

### ISSUE THREAD

**Issue by OsuHitsuji** [R3nzTheCodeGOD/R3nzSkin#307]

**Comment by dothmeun** [comment]
same mistake. After launching the R3nzSkin it constantly gives error failed to find pattern 8D 8E ? ? ? ? FF 74 24 4C etc

**Comment by binmus** [comment]
> same mistake. After launching the R3nzSkin it constantly gives error failed to find pattern 8D 8E ? ? ? ? FF 74 24 4C etc

maybe need update

**Comment by Gasferr** [comment]
[https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/305](url)

**Comment by Gasferr** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/305

**Comment by Eason10ve** [comment]
I have the disturbing problem too, can't fix it..

**Comment by Eason10ve** [comment]
> I have the disturbing problem too, can't fix it..

Hey bro , I find the solution to this problem, now I am playing in server CN TW..
Hope this can help you 
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/304

**Comment by binmus** [comment]
https://github.com/Sheelia/R3nzSkin-v13.3
