### ISSUE TITLE
Failed to find pattern:  8D 8E ? ? ? ? FF 74 24 4C

### ISSUE THREAD

**Issue by KinXandor** [R3nzTheCodeGOD/R3nzSkin#309]
Can you please help?
![image](https://user-images.githubusercontent.com/102000273/218189579-97757bf7-e3ad-4186-9846-266e1115c24d.png)

**Comment by daswareinfach** [comment]
cuz game has updated. change CharacterDataStack signature to 8D 8B ? ? ? ? FF 74 24 54 on memory.hpp file.

**Comment by KinXandor** [comment]
ill try, thanks for help :)

**Comment by KinXandor** [comment]
> cuz game has updated. change CharacterDataStack signature to 8D 8B ? ? ? ? FF 74 24 54 on memory.hpp file.

and where can i find the file to edit it ? sorry im not really like oriented in this

**Comment by kaiyihuo** [comment]
Use the version provided by Gasferr for a temporary solution

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/305

**Comment by Gasferr** [comment]
> Utilice la versión proporcionada por Gasferr para una solución temporal
> 
> #305

is the compiled version ready to use

**Comment by robotsplayer** [comment]
你解决掉这个问题了吗？

**Comment by robotsplayer** [comment]
did you solve this problem?

**Comment by KinXandor** [comment]
no ididnt

**Comment by KinXandor** [comment]
> did you solve this problem?

i did already, just download the edited version from gasferr, click at the #305 link and download that one, there are changed the patterns

**Comment by robotsplayer** [comment]
gasffer is a people or a websidt？ I find 37 versions but provided by one person



---Original---
From: "Jakub ***@***.***&gt;
Date: Sat, Feb 11, 2023 17:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [R3nzTheCodeGOD/R3nzSkin] Failed to find pattern:  8D 8E ? ? ? ?FF 74 24 4C (Issue #309)




  
did you solve this problem?
  
i did already, just download the edited version from gasferr, click at the #305 link and download that one, there are changed the patterns

**Comment by kaiyihuo** [comment]
> 

I've linked it on my original reply

**Comment by robotsplayer** [comment]
> 
wooooo! thank you!!!

**Comment by hotline1337** [comment]
Updated for the latest game update
