### ISSUE TITLE
Return Caitlyn's old default skin

### ISSUE THREAD

**Issue by Spanden** [R3nzTheCodeGOD/R3nzSkin#31]
How to return Caitlyn's old default skin?
![unknown](https://user-images.githubusercontent.com/25765730/145932716-42b940aa-edb6-40e3-9f62-76d2ccebcc05.png)

**Comment by R3nzTheCodeGOD** [comment]
Caitlyn's default skin has been changed by riot and the old model has been deleted from the game. This cheat cannot load a model that is not from the game.

Caitlyn Default Model: [CaitlynBase](https://raw.communitydragon.org/latest/game/assets/characters/caitlyn/skins/base)

**Comment by krukuhehe** [comment]
@Spanden I can actually revert since I do a lot of old champion restorations, however i'm kind of lazy, i'll probably do it next month or later with Old Ashe.

**Comment by Spanden** [comment]
also need return old Miss Fortune Waterloo skin
![waterloo-miss-fortune-miss-fortune-skins-miss-fortune-lol1](https://user-images.githubusercontent.com/25765730/146380578-2cab19a3-b41f-4815-9f84-0974b8df5661.png)

**Comment by krukuhehe** [comment]
> also need return old Miss Fortune Waterloo skin ![waterloo-miss-fortune-miss-fortune-skins-miss-fortune-lol1](https://user-images.githubusercontent.com/25765730/146380578-2cab19a3-b41f-4815-9f84-0974b8df5661.png)
You can checkout killerskins. They have Old Miss Fortune mod there.
