### ISSUE TITLE
天使换肤问题

### ISSUE THREAD

**Issue by xiwwqk** [R3nzTheCodeGOD/R3nzSkin#311]
天使换皮肤的时候，如果角色是六级，十一级，十六级，特效还是原本的一级特效，没有后续的成长特效。

**Comment by slivermaker** [comment]
现在🐎服能用了吗？

**Comment by slivermaker** [comment]
> 天使换皮肤的时候，如果角色是六级，十一级，十六级，特效还是原本的一级特效，没有后续的成长特效。

现在马服能用了吗

**Comment by xiwwqk** [comment]
我在国服用的（指tw）

**Comment by xiwwqk** [comment]
不晓得，一直在玩国服（指tw）

**Comment by haogaulle** [comment]
> > 天使换皮肤的时候，如果角色是六级，十一级，十六级，特效还是原本的一级特效，没有后续的成长特效。
> 
> 现在马服能用了吗

不能

**Comment by zcill** [comment]
马服要用老版本的吧？

**Comment by diyooor** [comment]
#1 

Closes #311 @hotline1337

**Comment by hotline1337** [comment]
#1
