### ISSUE TITLE
Dark cosmic jhin voiceline and Godking Garen E skill

### ISSUE THREAD

**Issue by mish20011** [R3nzTheCodeGOD/R3nzSkin#313]
Still uses the default Jhin voiceline

Garen E looks so scuffed that there is just circling effects around him and he is not spinning

**Comment by sokrateshayraniyim** [comment]
god king garen is bugged skin. this skin has the same issue no LoLSkin. I don't think they can solve it.

**Comment by sokrateshayraniyim** [comment]
@mish20011 god king garen is bugged skin. this skin has the same issue no LoLSkin. I don't think they can solve it.
