### ISSUE TITLE
Need an uptade for 13.4 it doesnt work anymore

### ISSUE THREAD

**Issue by Deaiman** [R3nzTheCodeGOD/R3nzSkin#318]
Need an uptade for 13.4 it doesnt work anymore

**Comment by LLTTYY1** [comment]
Yes,but writer doesnt seem to have time to update it.

**Comment by Gasferr** [comment]
> Need an uptade for 13.4 it doesnt work anymore

What do you mean it doesn't work anymore? I have no problem using it

**Comment by Deaiman** [comment]
> > Need an uptade for 13.4 it doesnt work anymore
> 
> What do you mean it doesn't work anymore? I have no problem using it

No it doesnt work anymore. It always says "object not set" when im trying to open it.

**Comment by haogaulle** [comment]
I used it yesterday and it was working normally.

**Comment by Kiana-da** [comment]
我的可以正常使用
