### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HoangDuong1310** [R3nzTheCodeGOD/R3nzSkin#322]
i got a few errors like " object reference not set to an instance an object" and " A critical error has occurred and the process must be terminated " how to fix it .
Thank u

**Comment by Kejiboy** [comment]
![image](https://user-images.githubusercontent.com/61222820/222944315-d02c643a-46d1-4187-9743-b632c0fa4969.png)

**Comment by Kejiboy** [comment]
Thanks, I ran it as administrator and it worked！

**Comment by Kejiboy** [comment]
> U should `Ctrl + Shift + F` on VS, then search for above strings and tracking errors, if you can copy those strings, I'll take a look

Thanks, I ran it as administrator and it worked
