### ISSUE TITLE
Request help

### ISSUE THREAD

**Issue by a984120978** [R3nzTheCodeGOD/R3nzSkin#325]
HI hotline1337:
        I'm from China, and many people in my country use this software
        
        I want to make this compatible with the Chinese version of LOL, and I want to translate it into local and compatible with the injection method
        
        But I'm not a c++developer. I'm a python developer, and I just learned c++
        
        What will happen now is to open the "sln" file with VS and import it for compilation
        
        ImGui:: Text ("Change Chinese Text") ->display garbled code, I don't understand what this is

thank you

**Comment by J-EnJay** [comment]
这个问题我遇到过，解决办法如下：
打开控制面板，搜索“更改日期、时间或数字格式”，在新窗口选择管理选项卡，点击下方“更改系统区域设置”按钮，选中下方“Beta版:使用Unicode UTF-8提供全球语言支持”选框。重启电脑后，再在vs中重新生成解决方案，即可解决。
注意：有些软件可能不支持此编码，可能导致一些软件文字不正常，建议在编译后还原设置。
我也fork了一个已经汉化了的仓库，你可以看下。

**Comment by SilentVastSky** [comment]
可惜现在作者不更新了，13.4用不了了，偏移也不知道上哪里找

**Comment by sjdvxssds** [comment]
请问这个现在国服和已使用吗？我也很喜欢这个辅助页面，可
