### ISSUE TITLE
when you die you lose the skin

### ISSUE THREAD

**Issue by Lorddrak69** [R3nzTheCodeGOD/R3nzSkin#328]
you lose skin when you die
same for your team

**Comment by CJackry** [comment]
me too

**Comment by fupan080735** [comment]
me too

**Comment by niuma0807** [comment]
me too

**Comment by blackclouds2810** [comment]
mee too

**Comment by blackclouds2810** [comment]
me too

**Comment by Francis-cpu-png** [comment]
me too

**Comment by phamlebaoanh123** [comment]
same here

**Comment by Elin-lin** [comment]
me too

**Comment by 19mengyanyan33** [comment]
me too,need a update for 13.5

**Comment by pyhabyss** [comment]
ditto

**Comment by 313063204** [comment]
me too

**Comment by LLTTYY1** [comment]
me too , hope the writer update it,Thank you!

**Comment by rainzee** [comment]
That because riot will resets character data stack when you die. So you will lose the skin.
I already fix that. but with some flaws

**Comment by ennnndme** [comment]
> 

really bro？could you send it for me？

**Comment by F-x-x-c** [comment]
if you fix it, you can upload it on your github, thanks bro love you😘

**Comment by ennnndme** [comment]
> 传到

bro,i can't fix it,i am freshman to the r3nzskin,but "rainzee" said he had fixed it ,i just want have it that  had fixed r3.

**Comment by ennnndme** [comment]
> 那是因为暴动会在你死后重置角色数据堆栈。所以你会失去皮肤。我已经解决了。但有一些缺陷

plz  update it

**Comment by 936270782** [comment]
> That because riot will resets character data stack when you die. So you will lose the skin. I already fix that. but with some flaws
Would you like to send out the modified one, and if so, that would be appreciated.

**Comment by evalexp** [comment]
> That because riot will resets character data stack when you die. So you will lose the skin. I already fix that. but with some flaws

Can you share your code? I want to how to detected the hero status, especially when the hero dired, thank you so much.

**Comment by cjd0901** [comment]
@evalexp There is a class called GameObject, which contains many functions to judge the object category, I guess we can use the same function, different enum values to get whether the player is dead, But how to find the correct enum value is a problem!

**Comment by WAY29** [comment]
me too

**Comment by evalexp** [comment]
> @evalexp There is a class called GameObject, which contains many functions to judge the object category, I guess we can use the same function, different enum values to get whether the player is dead, But how to find the correct enum value is a problem!

thank you so much, I have already fixed this problem.

**Comment by evalexp** [comment]
ok, I have fixed this problem, download and replace the dll.
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947718/R3nzSkin.zip)

**Comment by cjd0901** [comment]
@evalexp Can you open source your code,? I want to learn how you fixed this bug.

**Comment by evalexp** [comment]
> @evalexp Can you open source your code? I want to learn how you fixed this bug.

visit this: https://github.com/evalexp/R3nzSkin

**Comment by ariaabbasi** [comment]
> > @evalexp Can you open source your code? I want to learn how you fixed this bug.
> 
> visit this: https://github.com/evalexp/R3nzSkin

thanks evalexp , i appreciate it

**Comment by phamlebaoanh123** [comment]
> ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947718/R3nzSkin.zip)

Thank u so much, Sir @evalexp

**Comment by rainzee** [comment]
> > That because riot will resets character data stack when you die. So you will lose the skin. I already fix that. but with some flaws
> 
> Can you share your code? I want to how to detected the hero status, especially when the hero dired, thank you so much.

I read your solution, it's too heavy for me, you need to detect the player state and call the skinning function, which means, you will have a lot of stack->push, and stack->clear in the game, which will lead to unpredictable errors, and increase the risk of ban, actually there is a very simple solution here, it only requires one line of code change, and doesn't increase the potential risk, but there are still flaws, I'm testing it, and will merge it into this repository as soon as possible.

**Comment by evalexp** [comment]
> > > That because riot will resets character data stack when you die. So you will lose the skin. I already fix that. but with some flaws
> > 
> > 
> > Can you share your code? I want to how to detected the hero status, especially when the hero dired, thank you so much.
> 
> I read your solution, it's too heavy for me, you need to detect the player state and call the skinning function, which means, you will have a lot of stack->push, and stack->clear in the game, which will lead to unpredictable errors, and increase the risk of ban, actually there is a very simple solution here, it only requires one line of code change, and doesn't increase the potential risk, but there are still flaws, I'm testing it, and will merge it into this repository as soon as possible.

thank you so much, looking forward to your updates.

**Comment by rainzee** [comment]
See #337

**Comment by hotline1337** [comment]
Commit 9928813 fixes the problem.

**Comment by XhyMrr** [comment]
> ok

I found that the repaired skin will cause the game to flash back, and when using Kasha, the character will be transparent.
