### ISSUE TITLE
Issue with building on Visual Studios 

### ISSUE THREAD

**Issue by CoClanDeath** [R3nzTheCodeGOD/R3nzSkin#33]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4030	"Default" is an invalid value for the "ConformanceMode" parameter of the "CL" task. The "ConformanceMode" parameter is of type "System.Boolean".	R3nzSkin_Injector	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	653

**Comment by R3nzTheCodeGOD** [comment]
I'm using C++/CLI technology for the injector interface that I added to the cheat. install this in your visual studio

![image](https://user-images.githubusercontent.com/58574988/146219427-1347bb38-76b0-4771-ae71-feb691d5e893.png)
