### ISSUE TITLE
plz update for 13.5

### ISSUE THREAD

**Issue by Jh1n32** [R3nzTheCodeGOD/R3nzSkin#330]
plz update for 13.5 @hotline1337

**Comment by lilhalfuct98** [comment]
yeah bro please :(

**Comment by SilvanWu** [comment]
He is in the military service, as told in the announcement.
╮（╯＿╰）╭

**Comment by niuma0807** [comment]
but kind hotline1337 has  renewed 13.3，does he take GOD‘s work？

**Comment by SilvanWu** [comment]
dont know, but 13.4 hasnt been renewed yet-_-||

**Comment by evalexp** [comment]
it needs the sig of CharacterDataStack and CharacterDataStackUpdate, maybe more

**Comment by W18191868439** [comment]
+1

**Comment by plb111** [comment]
plz update it，(ง •̀_•́)ง @hotline1337

**Comment by evalexp** [comment]
ok, I have fixed this problem, download and replace the dll.
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)

**Comment by lilhalfuct98** [comment]
> ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)

Thank you so much bro :) works perfect and the new skins are there too uwu <3

**Comment by Jh1n32** [comment]
> ok, I have fixed this problem, download and replace the dll.
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)

Thx bro, will you be responsible for updating the next version, before god comes back?

**Comment by 1024191579** [comment]
> ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)

The skin bought by the remaining 9 people also shows the original skin.

**Comment by 1024191579** [comment]
> ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)

![image](https://user-images.githubusercontent.com/17799883/224469775-9ca2b037-c539-4fa1-8231-b8995be71830.png)

**Comment by evalexp** [comment]
> > ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)
> 
> The skin bought by the remaining 9 people also shows the original skin.

thank you, try this one
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10948016/R3nzSkin.zip)

**Comment by lilhalfuct98** [comment]
> > > ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)
> > 
> > 
> > The skin bought by the remaining 9 people also shows the original skin.
> 
> thank you, try this one [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10948016/R3nzSkin.zip)

now i have 20 fps ingameXD

**Comment by evalexp** [comment]
> 



> > ok, I have fixed this problem, download and replace the dll.
> > [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)
> 
> Thx bro, will you be responsible for updating the next version, before god comes back?

I'm sorry, but I don't have the energy to do the update at the moment

**Comment by erttispc** [comment]
> > > ok, I have fixed this problem, download and replace the dll. [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip)
> > 
> > 
> > The skin bought by the remaining 9 people also shows the original skin.
> 
> thank you, try this one [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10948016/R3nzSkin.zip)

thank you

**Comment by lilhalfuct98** [comment]
am i the only one with fps problems?

**Comment by evalexp** [comment]
> am i the only one with fps problems?

I haven't had this issue. I delete the useless code and rebuild it, try this:
https://github.com/evalexp/R3nzSkin/releases/download/v2.3.8/R3nzSkin.zip

**Comment by lilhalfuct98** [comment]
thanks

**Comment by rainzee** [comment]
See #337

**Comment by HoganAgnes** [comment]
> 好的，我已经解决了这个问题，下载并替换dll。 [R3nzSkin](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10947707/R3nzSkin.zip).zip上面的文件中有一个错误，请下载以下最新版本：[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/10948016/R3nzSkin.zip)

THANKS

**Comment by hotline1337** [comment]
Commit 9928813 fixes the problem.

**Comment by HoganAgnes** [comment]
> Commit [9928813](https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/9928813a0f6df66e232a1d8501a15ff3c7f99b2c) fixes the problem.
Will it be updated in the future？😘

**Comment by hotline1337** [comment]
> > Commit [9928813](https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/9928813a0f6df66e232a1d8501a15ff3c7f99b2c) fixes the problem.
> > Will it be updated in the future？😘

if i have time - yes
