### ISSUE TITLE
[solved] fix skin reset after the hero died

### ISSUE THREAD

**Issue by cjd0901** [R3nzTheCodeGOD/R3nzSkin#332]
I temporarily solved the problem of skin reset after the hero died, but there may be some bugs, you can download the zip from [v13.5.1](https://github.com/cjd0901/R3nzSkin/releases/tag/v13.5.1) if you encounter any problems, please contact me.
ps: When a game is over, you need to manually close the `League of Legends (TM) Client` in the task manager

**Comment by window8** [comment]
how did you solve it?

**Comment by cjd0901** [comment]
I optimized my code by learing [evalexp](https://github.com/evalexp)'s code, now you don't have to close it manually when game is over.

**Comment by youngman2000** [comment]
结束时有概率会未响应，大概3次有1次，

**Comment by cjd0901** [comment]
@youngman2000 你用的是我之前的版本吧，现在的应该不会有这个问题

**Comment by x1207349263** [comment]
而你我的朋友，是真正的英雄！

**Comment by lilhalfuct98** [comment]
hi sometimes when i take a skin my game just closes and i need to reconnect i dont have it every game aber some games somehow maybe there is a fix for that?

**Comment by cjd0901** [comment]
@lilhalfuct98 I haven't encountered this problem, but you can try the latest version to see if this problem still occurs.

**Comment by lilhalfuct98** [comment]
i have 13.5 already

**Comment by rainzee** [comment]
See #337

**Comment by hotline1337** [comment]
Commit 9928813 fixes the problem.
