### ISSUE TITLE
Potential blocking risks of the solution 当前的风险

### ISSUE THREAD

**Issue by rainzee** [R3nzTheCodeGOD/R3nzSkin#337]
我是该项目的早期贡献者，事实上，对于中国服务器的支持也是由我共同实现的 627e7e0，在13.5版本更新之后，我向社区指出了为什么在死亡时，换肤会失效，因为拳头在玩家重生后，会重置 `character_data_stack`。这似乎是13.5新增的。

I was an early contributor to the project, and in fact co-implemented the support for the Chinese servers(see commit 627e7e0). After the 13.5 update, I pointed out to the community that why the software was disabled on reborn, because riot will resets the `character_data_stack`

目前我看到社区的结局方案都是类似的，他们检测玩家的状态，并在重生时，调用函数，这么做首先会导致性能问题，和奇怪的BUG，你会在重生时候有卡顿，其次更严重的问题是，这将导致你频繁修改内存中的位置，不断覆盖和重写，这会导致一系列风险，导致客户端崩溃（已经看到有人反馈在游戏结束时候客户端崩溃），极大的增加了封号的风险，尤其是中国服务器。

The solutions I've seen from the community so far are similar in that they detect the state of the player and, on reborn, call the change skin function. Doing this will firstly cause performance issues, you will have small lag during reborn, and secondly a more serious issue is that this will cause you to frequently modify locations in memory, constantly overwriting and rewriting, which will lead to a series of risks that will cause the client to crash(already seen the problems in the issues when game end client will crash) and greatly increase the risk of blocking.

这是因为，拳头会在每次游戏客户端崩溃的时候，或者发生性能问题的时候，Dump整个游戏内存并且上报到服务器，这会极大的增加你的封号风险，这也是我跟作者早期在Discord的讨论，其实拳头并不是每次都会重置内存，我已经做了很多测试，其实这里存在一个一个简单的解决方案，只需要修改一行代码，就能完美运行，也不需要在局内频繁读写，但是还需要更多的测试。

This is because the riot will be in each game client crash, or when performance problems occur, Dump the entire game memory and reported to the server, which will greatly increase your risk of ban, this is also the author and I early discussion in Discord, in fact, the riot does not always reset the memory, I have done a lot of testing, in fact, here exists a simple solution, only need to modify one line of code, you can run perfectly, and do not need to read and write frequently in  gameing, but there also needs more testing.

![proof](https://user-images.githubusercontent.com/4585440/224478772-5a44e7aa-ab5a-4d8f-b3c7-324ae3358b00.png)

我在实现中国服务器支持的时候跟作者的交流
My discussion with the author

**Comment by x1207349263** [comment]
感谢！

**Comment by 19mengyanyan33** [comment]
thank you so much!

**Comment by cjd0901** [comment]
Indeed, when debugging the code, my game crashed dozens of times, I modified the code to only update the player's own skin, and minimized the interaction between tools and game memory. 

waiting for your better solution!

**Comment by haogaulle** [comment]
Thanks!

**Comment by Democles85** [comment]
Let's say hypothetically I decide to implement @cjd0901 solution, would that risk my account being banned, or is it just a normal fix that could be better?

**Comment by yaobaimiao** [comment]
thanks

**Comment by rainzee** [comment]
> Let's say hypothetically I decide to implement @cjd0901 solution, would that risk my account being banned, or is it just a normal fix that could be better?

Greatly increase the risk of being ban

**Comment by Democles85** [comment]
> > Let's say hypothetically I decide to implement @cjd0901 solution, would that risk my account being banned, or is it just a normal fix that could be better?
> 
> Greatly increase the risk of being ban

So @hotline1337 just uploaded an update, and is not that much different from the fix @cjd0901 had. Even that would greatly increase the chance of a ban?

**Comment by Refeain** [comment]
thanks

**Comment by rainzee** [comment]
As I mentioned before, more and more side effects have started to be exposed recently, as the extra state detection, and frequent function calls, can make a mess of your memory, and the detection functions can cause a lot of errors and crashes. Currently getting community feedback, FPS lag issues, game client crash issues, playback system crash issues, skin disappearance issues. And so on.

These are all caused by the side effects of extra detection and frequent function calls, and prove that the current solution is immature, I am sure that frequent crashes will lead to your account being banned, so we need to work together to find a better solution.

正如我之前提到的那样，最近越来越多的副作用开始暴露，因为额外的状态检测，和频繁调用函数，会让你的内存变得一团糟，检测函数会导致大量的错误和崩溃。目前得到的社区反馈，FPS卡顿问题，游戏客户端崩溃问题，回放系统崩溃问题，皮肤消失问题。等等。

这些都是由于额外的检测和频繁的调用函数的副作用所导致的，也证明了当前的解决方案是不成熟的，我相信，频繁的崩溃一定会导致您的帐号被封禁，所以，我们需要努力一起找到更优的解决方案。

**Comment by Democles85** [comment]
Understandable, in my experience dealing with these type of "changes" it's going to be hard to find the "perfect" solution, before like patch 13.6 comes out, but that is my experience, this could be different. I hope that this does not mean the end for R3nz skins as it is a very nice tool to be experiment on, for myself at least, also for the community.

**Comment by WAY29** [comment]
waiting for your better solution

**Comment by BariFL** [comment]
Appreciate your selfless spirit.
Salute!

**Comment by r3nzskin-bazhu** [comment]
感谢您！中国有很多lol玩家受益于你们的工作，希望r3nzskin可以继续下去。

**Comment by KLzfyn520** [comment]
Thanks
Salute! 🙏

**Comment by rainzee** [comment]
注意，中国服务器仍然会在很长一段时间内使用X86架构，我也有能力在64架构到来之后继续维护更新。这里没什么可担心的。

**Comment by zxcvbnm3057** [comment]
我怎么觉得，干脆hook掉他内存上报更简单一点。。。崩溃大不了重启嘛，他上报了对这局游戏也无关紧要。而且有点纳闷没注意过崩溃后出现异常流量啊，还是说他不是立即上传的。全部进程内存上传肯定不现实，只上传堆栈的话，也许可以hook皮肤加载函数换肤来避免被检测？
