### ISSUE TITLE
Is this a virus

### ISSUE THREAD

**Issue by dancethemo** [R3nzTheCodeGOD/R3nzSkin#340]
my antivirus detected the skin changer is in my roaming appdata in my windows folder.  So i'm assuming it a virus because it in my windows folder. I have never seen it get flagged before.

**Comment by pljjy** [comment]
шеЫ ъф

**Comment by pljjy** [comment]
If you think its a virus, you can check the source code. There are also a lot of issues opened and closed which means people use it so no reasons to doubt.

**Comment by giovannilol** [comment]
virus sure me also im hack
