### ISSUE TITLE
this spectator mode will crash in v2.3.8（13.5）

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#342]
I try to use the new [v2.3.8]（ https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v2.3.8 ）Go to turn on the spectator mode,
Every time it starts to run, the game crashes. 
This is in [v2.3.7]（ https://github.com/R3nzTheCodeGOD/R3nzSkin/tree/v2.3.7 ）This problem will not exist in the version

 what happened. help me

![image](https://user-images.githubusercontent.com/50578587/224539801-da553533-c880-47bb-bdd3-c549b21adb85.png)
![image](https://user-images.githubusercontent.com/50578587/224539819-411a91f8-27c9-4308-9cea-7f528bb438c1.png)

**Comment by senmao1994** [comment]
In v2.3.7
![image](https://user-images.githubusercontent.com/50578587/224539961-e37ebb1d-2aca-40d8-8efd-38ab1a65cf73.png)

**Comment by cjcnms001** [comment]
他妈的你不会把它关了自己再观战啊？白嫖免费的B事还多

**Comment by senmao1994** [comment]
> 他妈的你不会把它关了自己再观战啊？白嫖免费的B事还多

请你好好说话，我反馈问题是因为这个项目之前有支持回放系统。

**Comment by senmao1994** [comment]
After the test, it was found that the implementation was caused by the risk described by #337
