### ISSUE TITLE
[BUG]Display abnormalities under higher resolution

### ISSUE THREAD

**Issue by kinghoo666** [R3nzTheCodeGOD/R3nzSkin#344]
When the computer is set to a resolution of 2k or 4k, the UI of the R3 will become smaller. Even if the font size is 2, the UI is still very small  after each entering the game.
This problem is available in the previous version, and the new version still exists.

**Comment by hotline1337** [comment]
you can edit the code on your own to increase the size
https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/9928813a0f6df66e232a1d8501a15ff3c7f99b2c/R3nzSkin/GUI.cpp#L239
