### ISSUE TITLE
R3nz13.5 Will not be available in playback mode and the playback process will crash.

### ISSUE THREAD

**Issue by changdao98** [R3nzTheCodeGOD/R3nzSkin#345]
Sorry,I translated English in Chinese. Maybe you can't understand what I said.

**Comment by changdao98** [comment]
I translated English in Chinese. Maybe you can't understand what I said.

**Comment by changdao98** [comment]
But R3NZ 13.3 can

**Comment by rainzee** [comment]
This is because the new fix patch introduces additional detect that causes a lot of unpredictable problems, as I pointed out in #337, and this is one of the side effects, with more waiting to be exposed.

**Comment by LeBlancei** [comment]
我的是在游戏读取界面的时候会直接崩溃掉，电脑死机。
