### ISSUE TITLE
is a virus guys

### ISSUE THREAD

**Issue by giovannilol** [R3nzTheCodeGOD/R3nzSkin#346]
It's a virus change all your password and uninstall this its hotline1337 the hacker, I received an email from a guy asking me for a ransom of 800 because he filmed all my activities on my pc pls trust me

**Comment by breezeCJ** [comment]
really?let me look the  picture

**Comment by hotline1337** [comment]
you can build the source on your own if you do not want to download the release, the injector is made in c# so you can even view the compiled source in dnSpy, league of legends is not an elevated process so the "ransomware" won't be even able to encrypt most of the files.

**Comment by giovannilol** [comment]
fuck you bro viens a grigny tu vas vas espèce de pd
