### ISSUE TITLE
Seraphine Passive Music

### ISSUE THREAD

**Issue by miyuishere** [R3nzTheCodeGOD/R3nzSkin#347]
I just made an account to ask, is there possibility for her passive music to change on every skin she has? Because she always has default no matter which skin

**Comment by giovannilol** [comment]
its a virus guy unnistall this and change your password .

**Comment by hotline1337** [comment]
> its a virus guy unnistall this and change your password .

you can see the source code on your own

**Comment by miyuishere** [comment]
> its a virus guy unnistall this and change your password .

It's not a virus, I've been suing this for long time, windows thinks its virus because it wasn't downloaded for much times. I can assure you nothing happened and nothing will happen to my pc ^^

**Comment by diyooor** [comment]
#1 @hotline1337
