### ISSUE TITLE
你好，我之前看到代码说，国服其实也是可以用这个软件的，请问需要如何设置修改代码呢，能给一下 吗

### ISSUE THREAD

**Issue by sjdvxssds** [R3nzTheCodeGOD/R3nzSkin#348]
能教一下怎么修改代码吗？

**Comment by sjdvxssds** [comment]
我自行研究啦很久都没有头绪，能叫我一下这个怎么修改吗，感谢，您可以用英文答复，麻烦啦，请一定要回复

**Comment by BariFL** [comment]
腾讯服务器的使用方法去贴吧看    有教程   
不用修改代码   替换一下原有文件就可以
腾讯的检测力度非常大      封号是大概率事件      不建议用

**Comment by assasqd** [comment]
把R3nzSkin.dll改成LogitechLed.dll直接替换到国服的游戏目录就行了，但是国服的封号力度你懂的，不如直接玩台服

**Comment by a984120978** [comment]
修改win hook把R3nzSkin.dll注入到LogitechLed.dll即可

**Comment by kinghoo666** [comment]
> 把R3nzSkin.dll改成LogitechLed.dll直接替换到国服的游戏目录就行了，但是国服的封号力度你懂的，不如直接玩台服

这个方法对直营服有效吗，这样的话就不用每次都打开注入器了

**Comment by toString122** [comment]
You should not use this software on the CN server, or you will be banned!!

**Comment by BaiFeng666** [comment]
> 您不应该在CN服务器上使用此软件，否则您将被禁止！！

万恶的狗屎CN服务器
