### ISSUE TITLE
Changable open key

### ISSUE THREAD

**Issue by JeesusKrisostoomus** [R3nzTheCodeGOD/R3nzSkin#35]
Button to change the open key for people who do not have the insert key for example my friend has 60% keyb and doesn't have insert key for whatever reason so he can't close the menu. I will try doing a pr but im not sure if it will come anytime soon as i don't have that much experience with c++ yet

**Comment by R3nzTheCodeGOD** [comment]
All you have to do is change 1 parameter.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/d2be79235a87341943a969a4603068c397285495/R3nzSkin/Hooks.cpp#L32

**Comment by JeesusKrisostoomus** [comment]
ye but i meant as ingame button. Maybe some people dont understand how it works or dont want to compile the project themselves

**Comment by R3nzTheCodeGOD** [comment]
Now you can change the menu key
