### ISSUE TITLE
Hello，Daughter of the Void（Kai’Sa）BUG

### ISSUE THREAD

**Issue by class-qingfeng** [R3nzTheCodeGOD/R3nzSkin#351]
#350 Daughter of the Void（Kai’Sa）After death, it becomes transparent and the character cannot be displayed, can you fix this bug?

**Comment by kendinecodder** [comment]
#338

**Comment by class-qingfeng** [comment]
> #338

谢谢

**Comment by ve9Opx** [comment]
13.5.2修復了嗎
