### ISSUE TITLE
The Font Scale setting does not take effect when new match starts

### ISSUE THREAD

**Issue by LeeG4ng** [R3nzTheCodeGOD/R3nzSkin#353]
The **Font Scale** setting does not take effect (i.e. Font Scale=1) when new match starts. 
The **Font Scale** setting will take effect only after the last tab (**Extras**) is clicked. Looks like the  **Font Scale** setting is not loaded before opening the **Extras** tab.
Please help fix it.

**Comment by hotline1337** [comment]
Fix https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/cb55f10a89f26d74f639dc7a237c164adb97484b
