### ISSUE TITLE
dawnbringer riven

### ISSUE THREAD

**Issue by ghost** [R3nzTheCodeGOD/R3nzSkin#357]
skin does not change when using r1
![Screenshot_1](https://user-images.githubusercontent.com/128435586/226494555-136fa7fe-5930-4e43-a36b-695496a4284f.png)

**Comment by loveandlies** [comment]
how it should be:
![Screenshot_2](https://user-images.githubusercontent.com/128435586/226497772-bc86b000-13c6-4d38-af05-e0a7619368ff.png)
