### ISSUE TITLE
ImGui显示中文的问题

### ISSUE THREAD

**Issue by BaiFeng666** [R3nzTheCodeGOD/R3nzSkin#358]
如图所示
我看了里面加载字体里是有msyh.ttc的 说明是支持中文
但是imgui控件依旧显示乱码

已尝试过的操作：
项目改成多字节符集
字符串前+u8 (会报错)

**Comment by good-ideal** [comment]
中文版本看我Fork的版本，我已经做了汉化：[R3nzSkin/good-ideal](https://github.com/good-ideal/R3nzSkin)

**Comment by J-EnJay** [comment]
#325 看这个解决方法

**Comment by BaiFeng666** [comment]
> #325 看这个解决方法

有一个更优解 (Const char*)(u8"中文")

**Comment by yeruilin** [comment]
> > #325 看这个解决方法
> 
> 有一个更优解 (Const char*)(u8"中文")

这个方法真的是有用的，首先要准备好微软雅黑字体，再这样才可以显示中文。
