### ISSUE TITLE
Can someone help me adding a pause-code into this program？能否帮我添加一个暂缓的代码？

### ISSUE THREAD

**Issue by jkwtbmyz** [R3nzTheCodeGOD/R3nzSkin#359]
I am using r3nz and cslol, also a lol plug-in that adds map's mod, downloaded from here: https://killerskins.com/

Both of them will do something when the game starts, and then conflict, causing error. 

Then I find that r3nz can be injected and effective anytime during the game, so I am thinking to let cslol operate first, r3nz waits several seconds, then let r3nz do its code.  

To be percise, when r3nz knows that "leaguegame status" turns “FOUND”, it pauses 10 seconds, then continues.

Code maybe added here
![image](https://user-images.githubusercontent.com/17421620/226572978-0acc2bd8-d83e-4961-8190-d410fe7f717e.png)

Can someone be so kind to add a line and complie the code for me? Thank you so much!

我同时还在用cslol，一个修改地图的插件，两个插件都会在游戏启动的时候注入信息，此时会冲突报错；
我发现r3nz在游戏开启后任何时刻注入都能有效，于是我想让r3nz检测到游戏开始的时候，暂停10s，等待cslol完成注入，再执行它自己的注入，可能问题就解决了
具体来说，在leaguegame status 从not found变成found 的时候，等10s，再继续
可能是这里
![image](https://user-images.githubusercontent.com/17421620/226573040-580a91c7-fe70-44ad-94e7-7c9ef379c8ea.png)

能否帮助我加入这一行代码并编译成程序呢？谢谢！

**Comment by evalexp** [comment]
```cpp
std::this_thread::sleep_for(std::chrono::seconds(10));
```

**Comment by jkwtbmyz** [comment]
> ```c++
> std::this_thread::sleep_for(std::chrono::seconds(10));
> ```

Thanks, but I cannot compile injecter app with vs and am not sure where exactly to put this line that will work. 
Would you be so kind to upload the exe file pls?

**Comment by jkwtbmyz** [comment]
> ```c++
> std::this_thread::sleep_for(std::chrono::seconds(10));
> ```

Thanks, but I cannot compile injecter app with vs and am not sure where exactly to put this line that will work. 
Would you be so kind to upload the exe file pls?

**Comment by good-ideal** [comment]
等我下班我给你编译一份吧，我仓库Fork了汉化过的版本

**Comment by jkwtbmyz** [comment]
> 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本

谢谢hxd
你仓库里的是没有exe还是我没找到？

**Comment by good-ideal** [comment]
> > 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本
> 
> 谢谢hxd 你仓库里的是没有exe还是我没找到？

这是最新的中文版本：[releases/13.6](https://github.com/good-ideal/R3nzSkin/releases/tag/13.6)

**Comment by good-ideal** [comment]
> > 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本
> 
> 谢谢hxd 你仓库里的是没有exe还是我没找到？

这是按照你的问题构建暂缓10秒后注入[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11068054/R3nzSkin.zip)

**Comment by jkwtbmyz** [comment]
> > > 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本
> > 
> > 
> > 谢谢hxd 你仓库里的是没有exe还是我没找到？
> 
> 这是按照你的问题构建暂缓10秒后注入[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11068054/R3nzSkin.zip)

谢谢老哥，运行良好；
如果你还会继续更新的话，要不干脆就按照延迟10s的版本来做？反正就算延迟了，加载界面也要许久，基本上也能在游戏开始或者开始作战之前完成注入；我这个换地图的插件用的人也有一些的，尤其是越来越多的人拿来换大乱斗屠夫之桥地图；如果还有其他插件也能避开冲突；
另外汉化也很好，就是防御塔换肤，不是“敌方我方”是“蓝红”；
“给所有人随机皮肤”功能原版就有bug，重生后会恢复，有计划修复吗？若修复，能否让他勾选后接下来的对局都启用呢？我每局都愿意打开这个功能
再次感谢~

**Comment by good-ideal** [comment]
> > > > 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本
> > > 
> > > 
> > > 谢谢hxd 你仓库里的是没有exe还是我没找到？
> > 
> > 
> > 这是按照你的问题构建暂缓10秒后注入[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11068054/R3nzSkin.zip)
> 
> 谢谢老哥，运行良好； 如果你还会继续更新的话，要不干脆就按照延迟10s的版本来做？反正就算延迟了，加载界面也要许久，基本上也能在游戏开始或者开始作战之前完成注入；我这个换地图的插件用的人也有一些的，尤其是越来越多的人拿来换大乱斗屠夫之桥地图；如果还有其他插件也能避开冲突； 另外汉化也很好，就是防御塔换肤，不是“敌方我方”是“蓝红”； “给所有人随机皮肤”功能原版就有bug，重生后会恢复，有计划修复吗？若修复，能否让他勾选后接下来的对局都启用呢？我每局都愿意打开这个功能 再次感谢~

1、延迟10s的情况可能后续不会，因为绝大部分人不会有这种需求.
2、汉化问题“敌方我方”为“蓝红”目前已知晓，后续修复.
2、给所有人随机皮肤功能问题，等待源repo修复，你可以提一个新issues
4、后续此仓库版本更新后，汉化放库依然会Sync fork

**Comment by jkwtbmyz** [comment]
> > > > > 等我下班我给你编译一份吧，我仓库Fork了汉化过的版本
> > > > 
> > > > 
> > > > 谢谢hxd 你仓库里的是没有exe还是我没找到？
> > > 
> > > 
> > > 这是按照你的问题构建暂缓10秒后注入[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11068054/R3nzSkin.zip)
> > 
> > 
> > 谢谢老哥，运行良好； 如果你还会继续更新的话，要不干脆就按照延迟10s的版本来做？反正就算延迟了，加载界面也要许久，基本上也能在游戏开始或者开始作战之前完成注入；我这个换地图的插件用的人也有一些的，尤其是越来越多的人拿来换大乱斗屠夫之桥地图；如果还有其他插件也能避开冲突； 另外汉化也很好，就是防御塔换肤，不是“敌方我方”是“蓝红”； “给所有人随机皮肤”功能原版就有bug，重生后会恢复，有计划修复吗？若修复，能否让他勾选后接下来的对局都启用呢？我每局都愿意打开这个功能 再次感谢~
> 
> 1、延迟10s的情况可能后续不会，因为绝大部分人不会有这种需求. 2、汉化问题“敌方我方”为“蓝红”目前已知晓，后续修复. 2、给所有人随机皮肤功能问题，等待源repo修复，你可以提一个新issues 4、后续此仓库版本更新后，汉化放库依然会Sync fork

谢谢回复，我说了cslol这个插件也有一定的用户啊，其他插件要在游戏开始加载也可能导致冲突；延迟10s依旧能保证在游戏开始前完成注入；
或者老哥方便说一下在哪里加代码+如何编译？我下载了vs2022但是原版的injector都无法编译一堆错误。。。

**Comment by jkwtbmyz** [comment]
> vs2019 ![image](https://user-images.githubusercontent.com/41094378/227935440-bfde0d2a-d02a-4c93-8dc5-f5048aab9e08.png)

换了2019 
是这里编译injector吗 
![image_60](https://user-images.githubusercontent.com/17421620/227988454-f31d29a6-1bb3-403d-992d-207e7148177f.png)

报错呢
![image_61](https://user-images.githubusercontent.com/17421620/227988483-0372c71a-f936-45d5-ba41-d7ad500f5fef.png)

**Comment by jkwtbmyz** [comment]
> 编译的地方是正确的，这个C++安装了吗？ ![image](https://user-images.githubusercontent.com/41094378/227990470-dc9ec48b-c662-4462-bd09-97b06959076b.png)
![image](https://user-images.githubusercontent.com/17421620/228399103-3dfa3a0e-b32a-415d-b33d-eb7bab62bb8f.png)
![image](https://user-images.githubusercontent.com/17421620/228399153-f9c7ca48-acd3-4f29-84ca-5053a2e22091.png)

**Comment by good-ideal** [comment]
加v，83727128
&nbsp;


&nbsp;&nbsp;admin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 上午8:57
收件人: ***@***.***&gt;; 
抄送: "  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [R3nzTheCodeGOD/R3nzSkin] Can someone help me adding a pause-code into this program？能否帮我添加一个暂缓的代码？ (Issue #359)





  
编译的地方是正确的，这个C++安装了吗？
