### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by LeeeSe** [R3nzTheCodeGOD/R3nzSkin#360]
MacOS 13
M1 aarch64

**Comment by LeeeSe** [comment]
I do not know if it is difficult to change the platform to achieve skin

**Comment by kaiyihuo** [comment]
Will certainly not happen anytime soon as the main developer is doing his military service.

**Comment by LeeeSe** [comment]
Okay, maybe I should wait for the author to come back and reopen this issue.
