### ISSUE TITLE
禁用tp程序启动LOL

### ISSUE THREAD

**Issue by ZhangPF2000** [R3nzTheCodeGOD/R3nzSkin#368]
# 使用火绒的`程序执行控制功能`添加程序禁止某些exe的启动

## LOL安装目录
`"D:\LOL"`

## 禁用程序名单
- D:\LOL\英雄联盟\Game\ACE-Helper.exe
- D:\LOL\英雄联盟\LeagueClient\ACE-Helper.exe
- D:\LOL\英雄联盟\LeagueClient\NetworkAssist\xunyou\yxqxunyou.exe
- D:\LOL\英雄联盟\TCLS\ACE-Helper.exe
- D:\LOL\英雄联盟\TCLS\TenProtect\TenSafe.exe
- D:\LOL\英雄联盟\TCLS\TenProtect\TenSafe_1.exe
- D:\LOL\英雄联盟\TCLS\TenProtect\TP\TPHelper.Installer.exe
- D:\LOL\英雄联盟\TCLS\TenProtect\TP\TPHelper\TPHelper.exe
- D:\LOL\英雄联盟\TCLS\TP3Helper.exe
- D:\LOL\英雄联盟\TCLS\TPSvc.exe
- D:\LOL\英雄联盟\WeGameLauncher\bugreport.exe
- D:\LOL\英雄联盟\WeGameLauncher\launcher.exe

## 注意事项
- 使用qq快速登录（注：没用微信登录，不知道会不会屏蔽掉）
- 不要使用wegame开启lol
- 不要禁止以下程序，会无法启动(已验证)
  - D:\LOL\英雄联盟\TCLS\WGTinyDL.exe
  - D:\LOL\英雄联盟\TCLS\TenProtect\Ten\Ten.exe
  - D:\LOL\英雄联盟\TCLS\TenProtect\TASLogin.exe

## 优化
- 删除`D:\LOL\英雄联盟\Cross`文件夹下所有内容，保留文件夹`Cross`
- 删除`D:\LOL\英雄联盟\LeagueClient\FeedBack`文件夹下所有内容，保留文件夹`FeedBack`
- 可以删除`D:\LOL\英雄联盟\WeGameLauncher`文件夹下所有内容，保留文件夹`WeGameLauncher`
  - 看情况，有些人删了就不行了，我的可以删除后启动

## 纯净版LOL下载
- B站搜索

**Comment by kahuixiansheng** [comment]
禁用后马服就可以使用R3了么兄弟

**Comment by ZhangPF2000** [comment]
我今天才刚开的，不清楚，先玩几天就知道了，不过我之前被封过，封了7天

**Comment by nOBS1** [comment]
各位勇士，可以不 马服能玩不

**Comment by hkhgggg** [comment]
> 各位勇士，可以不 马服能玩不

马服可以用r3

**Comment by zskm01** [comment]
you are trying to open the league of legends game client in an invaild way. to successfully open the game cilent,click on the play button and join a quene or create a  custom game.大佬这个怎么处理

**Comment by zskm01** [comment]
> you are trying to open the league of legends game client in an invaild way. to successfully open the game client,click on the play button and join a quene or create a custom game.大佬这个怎么处理

解决了,应该是启动tcls下的client.exe
