### ISSUE TITLE
China can't use it

### ISSUE THREAD

**Issue by 1678895471** [R3nzTheCodeGOD/R3nzSkin#37]
All of its options are correct, but it can't be used

**Comment by Clownsw** [comment]
> 它的所有选项都正确，但不能使用

Please try my Chinese version [](https://www.smilex.cn/archives/63abb1qrtwnogxtahfwai5u5cx2d7zb5)

**Comment by 1678895471** [comment]
> > 它的所有选项都正确，但不能使用
> 
> 请试试我的中文版（代码来自R3nzTheCodeGOD）[下载地址](https://www.smilex.cn/archives/63abb1qrtwnogxtahfwai5u5cx2d7zb5)

谢谢，但是我仍然无法使用

**Comment by Clownsw** [comment]
> > > 它的所有选项都正确，但不能使用
> > 
> > 
> > 请试试我的中文版（代码来自R3nzTheCodeGOD）[下载地址](https://www.smilex.cn/archives/63abb1qrtwnogxtahfwai5u5cx2d7zb5)
> 
> 谢谢，但是我仍然无法使用

您是否尝试使用我博客中的注入器加载?

**Comment by 1678895471** [comment]
> 

是的，但是游戏内依旧无法通过按键显示窗口

**Comment by 1678895471** [comment]
> > > > 它的所有选项都正确，但不能使用
> > > 
> > > 
> > > 请试试我的中文版（代码来自R3nzTheCodeGOD）[下载地址](https://www.smilex.cn/archives/63abb1qrtwnogxtahfwai5u5cx2d7zb5)
> > 
> > 
> > 谢谢，但是我仍然无法使用
> 
> 您是否尝试使用我的博客中注入器加载？

是的但游戏内依然无法通过显示窗口

**Comment by lcl124252** [comment]
按作者的方法替换合法的dll，比如 LogitechLed.dll ，将 R3nzSkin.dll 改名然后替换前面那个dll，虽然仍显示未注射，但是可以正常在游戏中使用，按insert就可以了，但是作者不推荐这种办法应该是容易封号（自己感觉），我用着是没什么问题的，因为作者制作的程序会自动变化名称的，应该就是为了防检测的，自己考虑风险吧

**Comment by namekkozZ** [comment]
> 你这个方法可以

**Comment by namekkozZ** [comment]
> 按作者的方法替换合法的dll，比如 LogitechLed.dll ，将 R3nzSkin.dll 改名然后替换前面那个dll，虽然仍显示未注射，但是可以正常在游戏中使用，按insert就可以了，但是作者不推荐这种办法应该是容易封号（自己感觉），我用着是没什么问题的，因为作者制作的程序会自动变化名称的，应该就是为了防检测的，自己考虑风险吧

我试了也可以  你用了这么久有封号吗

**Comment by bigbigEden** [comment]
> > 按作者的方法替换合法的dll，比如 LogitechLed.dll ，将 R3nzSkin.dll 改名然后替换前面那个dll，虽然仍显示未注射，但是可以正常在游戏中使用，按insert就可以了，但是作者不推荐这种办法应该是容易封号（自己感觉），我用着是没什么问题的，因为作者制作的程序会自动变化名称的，应该就是为了防检测的，自己考虑风险吧
> 
> 我试了也可以 你用了这么久有封号吗

可以尝试下这个
在这个评论地址：https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/47
有人写了一个中文替换exe文件

**Comment by bigbigEden** [comment]
> > 按作者的方法替换合法的dll，比如 LogitechLed.dll ，将 R3nzSkin.dll 改名然后替换前面那个dll，虽然仍显示未注射，但是可以正常在游戏中使用，按insert就可以了，但是作者不推荐这种办法应该是容易封号（自己感觉），我用着是没什么问题的，因为作者制作的程序会自动变化名称的，应该就是为了防检测的，自己考虑风险吧
> 
> 我试了也可以 你用了这么久有封号吗

@namekkozZ 
可以尝试下这个
在这个评论地址：https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/47
有人写了一个中文替换exe文件

**Comment by 1678895471** [comment]
> 按作者的方法替换合法的dll，比如LogitechLed.dll，将R3nzSkin.dll名然后替换前面的dll，虽然仍然显示未注射的那个，但是正常在游戏中使用，按插入就可以改了，但是不推荐这个种办法应该是容易封号（自己觉得），我用着是问题的，因为作者制作的程序不会自动改变名称的，应该是为了防检测的，自己考虑冒险吧

谢谢你。看到了回复但是找不到这个界面，今天发现可以打开了才回复
