### ISSUE TITLE
Reference Object Issue

### ISSUE THREAD

**Issue by isabellaguillen** [R3nzTheCodeGOD/R3nzSkin#372]
hi guys i need some help here
everytime i run the program i just get the message "object reference not defined to an instance of an object"
if someone could help me i would be just so so grateful S2
![print erro r3nzskin](https://user-images.githubusercontent.com/129638052/229328213-6e734035-21fb-4a6f-8712-d307df3c9b3c.png)

i'll attach a screenshot of the issue so u guys see it clearly, just wanna advise y'all it's portuguese

ps: i have w11 and a friend of mine told me it could be the issue

**Comment by TheNei** [comment]
Unpacke The file again and opne the new 
but The R3nzSkin didn't work in 13.6 patch😭
