### ISSUE TITLE
update for 13.7 plz！

### ISSUE THREAD

**Issue by Jason1111111** [R3nzTheCodeGOD/R3nzSkin#376]
The game updated  last night, and the dll
 wasn't work!

**Comment by CrazyDavee** [comment]
The author said he went to fulfill his mandatory military service, I do not know if he will update...

**Comment by Jason1111111** [comment]
> The author said he went to fulfill his mandatory military service, I do not know if he will update...

yeah,but someone has find the signature code in last issues,i do not know how to find it ,so i ask for help here...

**Comment by Answer111222** [comment]
please fix it ！even dont want play game！！

**Comment by XNeSizzzz** [comment]
Updating to 13.7 software is no longer available

**Comment by Jason1111111** [comment]
> Updating to 13.7 software is no longer available

Why？Has the game been updated to 64 bit？

**Comment by bigbigEden** [comment]
pls pls

**Comment by lll1483579** [comment]
plz thx

**Comment by 350845110** [comment]
plz thx

**Comment by ZuiTaiPing** [comment]
please fix it ！even dont want play game too !!

**Comment by 17725952283** [comment]
Please fix it as soon as possible, thanks a lot~

**Comment by trmessi** [comment]
Failed at last injection

**Comment by MRevenger** [comment]
Failed at lat injection, plz update!!!!

**Comment by minazuki522** [comment]
is it working now?

**Comment by fpy030205** [comment]
i really need this

**Comment by MRevenger** [comment]
> is it working now?

After the version update, it cannot be used anymore. Wait for the author to update it
