### ISSUE TITLE
x86 Deprecation

### ISSUE THREAD

**Issue by hotline1337** [R3nzTheCodeGOD/R3nzSkin#379]
### Best regards, hotline1337.

**Comment by Dejvi-Z** [comment]
Can someone point to any alternative programs?

**Comment by harlequinmutant** [comment]
Thank you, hotline1337 and also R3nzTheCodeGOD.


> Can someone point to any alternative programs?

I know MOD Skin LOL does a similar thing, but the program is significantly worse than this and I don't know if they'll be updating it for 13.7.

**Comment by uzcre** [comment]
> Thank you, hotline1337 and also R3nzTheCodeGOD.
> 
> > Can someone point to any alternative programs?
> 
> I know MOD Skin LOL does a similar thing, but the program is significantly worse than this and I don't know if they'll be updating it for 13.7.

can i ask the MOD if not bothering u tnx

**Comment by harlequinmutant** [comment]
> can i ask the MOD if not bothering u tnx

I believe it's this link: https://leagueskin.net/p/download-mod-skin-2020-chn

The current version is for 13.6.1 though and doesn't work with new patch.

**Comment by Mitakagated** [comment]
It was good while it lasted. Thanks for having it going ♥

**Comment by Rommewelo** [comment]
Guess we gotta wait for R3nz to come back now

**Comment by azp5211314** [comment]
作者感谢你做出的贡献，这个有人接手吗，还是必须等到原作者回来才能转手

**Comment by yussui-nino** [comment]
Its crazy and so sad man i  literally started using it on half 13.6 was so happy with it and out of all patches the next patch its done and project is closed for now riot is literally just targeting me at this point i hope u do update it man and gl <3

**Comment by disconunuxd** [comment]
much love <3

**Comment by minazuki522** [comment]
so... RIP r3nzskins?

**Comment by tr3xz** [comment]
why........ now i need another program, and lolskin is awful because of bugged skins and chormos...

**Comment by UncertA1n1** [comment]
Thanks to the author for everything also I want to ask when he will come back from his military service

**Comment by seth007-moo** [comment]
> ### The [x86 Architecture of the game has been deprecated](https://www.leagueoflegends.com/en-us/news/game-updates/patch-13-7-notes/). The project doesn't support x64 Architecture, and it is not that easy to "quickly update" the project to the new architecture. I will not provide an update to the new arch, therefore the project is getting discontinued as of now. R3nzTheCodeGOD will decide whether to keep it updated or to discontinue it fully after he fulfills his mandatory military service.
> ### Thanks to everyone that reported bugs, contributed to the project, and even used the project on the daily basis.
> ### Best regards, hotline1337.

We thank you for your all contributes you've made for this far, We really appreciated your help man!!

**Comment by j434861038** [comment]
感谢作者大大的贡献，以后还有机会更新吗，我愿意付费支持

**Comment by fernbacher** [comment]
It was great, best of its kind while it lasted. Every other software that did the same thing was just horrible, thank you.

**Comment by qinglvding** [comment]
Thank you for the author's previous update, it's really great

**Comment by ucrsneakers** [comment]
如果你有时间继续更新我相信有很大一部分的中国玩家愿意众筹支持你(｡•ˇ‸ˇ•｡)

**Comment by chfens** [comment]
感谢一直以来的更新！(Ｔ▽Ｔ)

**Comment by Jason1111111** [comment]
The game does not seem to be updated to x64, but it no longer supports 32-bit systems

**Comment by good-ideal** [comment]
Thank you for your efforts！🥰

**Comment by rainzee** [comment]
> 如果你有时间继续更新我相信有很大一部分的中国玩家愿意众筹支持你(｡•ˇ‸ˇ•｡)

中国服务器是可用的，在未来一段时间内

**Comment by miyuishere** [comment]
Kinda sad, started using it 2-3 months ago and I loved it, it was the best and had all chromas I needed. Thank you for your time that you used into developing this program

**Comment by yz-hongchen** [comment]
We thank you for your all contributes you've made for this far, We really appreciated your help man!!

**Comment by x1207349263** [comment]
TAT

**Comment by pljjy** [comment]
Thanks for your job

**Comment by mewhz** [comment]
Thank you for your contribution！！

**Comment by Xinqingdianti01** [comment]
I loved this project since the first time I used it. Thanks for all the contributions you made, really appreciate it. As a Chinese player, R3nzTheCodeGod is the best one I've ever used. Hope you all the best in the future

**Comment by LeBlancei** [comment]
thank  you

**Comment by cdchs99** [comment]
anyway, thanks you. good bless to R3nzTheCodeGOD.

**Comment by pawinka** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/130150176/230599334-4903fc64-42a3-4575-a42c-6d8a7efe8194.jpg)


I saw something like that. But I dont undertsand anything. Is it possible, can someone help?

**Comment by IAKILL** [comment]
@pawinka Where did you find it? in what yt video

**Comment by pawinka** [comment]
> @pawinka Where did you find it? in what yt video

its a video about this cheat, [League of Legends Skin Changer | R3nzSkin]

**Comment by IAKILL** [comment]
@pawinka link or smth? cant find it

**Comment by pawinka** [comment]
> @pawinka link or smth? cant find it

https://www.youtube.com/watch?v=mzBLAPkmqJM on this video

**Comment by qinglvding** [comment]
> 
This is in the comments section

**Comment by AIS3N** [comment]
> > @pawinka link or smth? cant find it
> 
> https://www.youtube.com/watch?v=mzBLAPkmqJM on this video

It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html

**Comment by pawinka** [comment]
> > > @pawinka link or smth? cant find it
> > 
> > 
> > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> 
> It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html

I just want to know if its really possible to make it work like that because I have no idea about coding

**Comment by lukazhao** [comment]
I have used it for several months, it was really great, thanks for your contribution. good luck to you

**Comment by iGoodLife** [comment]
Thanks for your long-term efforts!!!  I'm willing to pay if it will be updated later.

**Comment by Alby2000** [comment]
if theres any update pls contact me on discord Alby#5555 need it asap

**Comment by miqheil** [comment]
> > > > @pawinka link or smth? cant find it
> > > 
> > > 
> > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > 
> > 
> > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> 
> I just want to know if its really possible to make it work like that because I have no idea about coding

Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.

Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.

**Comment by pawinka** [comment]
> > > > > @pawinka link or smth? cant find it
> > > > 
> > > > 
> > > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > > 
> > > 
> > > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> > 
> > 
> > I just want to know if its really possible to make it work like that because I have no idea about coding
> 
> Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.
> 
> Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.

sonucunu burdan da haber verir misin hocam

**Comment by alphaaced** [comment]
Someone please find a new way

**Comment by KevnDuta** [comment]
sad! I do appreciate for your work and your contribute! have used it for few days notwithstanding, it is the best skin changer I've ever used.

**Comment by KevnDuta** [comment]
sad! I do appreciate for your work and your contribution! have used it for few days notwithstanding, it is the best skin changer I've ever used.

**Comment by kaiyihuo** [comment]
I'm willing to pay too if anyone finds a way to update it.

**Comment by Mrzhousang** [comment]
it is so pity, i hope there one will update it to use ,please

**Comment by miqheil** [comment]
> > > > > > @pawinka link or smth? cant find it
> > > > > 
> > > > > 
> > > > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > > > 
> > > > 
> > > > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> > > 
> > > 
> > > I just want to know if its really possible to make it work like that because I have no idea about coding
> > 
> > 
> > Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.
> > Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.
> 
> sonucunu burdan da haber verir misin hocam

hotline [fixlenemeyeceğini](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/388#issuecomment-1500548933) söylüyor. Öte yandan forumda fixlediğini [iddia eden](https://www.unknowncheats.me/forum/league-of-legends/578125-skinchangers-x64.html) ama bir şey paylaşmayan da var. Şu an skin hilesi için tek yol, halihazırda 64 bit'de çalışan scriptlerdeki skin changer'lar.

**Comment by alphaaced** [comment]
> > > > > > > @pawinka link or smth? cant find it
> > > > > > 
> > > > > > 
> > > > > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > > > > 
> > > > > 
> > > > > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> > > > 
> > > > 
> > > > I just want to know if its really possible to make it work like that because I have no idea about coding
> > > 
> > > 
> > > Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.
> > > Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.
> > 
> > sonucunu burdan da haber verir misin hocam
> 
> hotline [fixlenemeyeceğini](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/388#issuecomment-1500548933) söylüyor. Öte yandan forumda fixlediğini [iddia eden](https://www.unknowncheats.me/forum/league-of-legends/578125-skinchangers-x64.html) ama bir şey paylaşmayan da var. Şu an skin hilesi için tek yol, halihazırda 64 bit'de çalışan scriptlerdeki skin changer'lar.  

Do you any free ones for x64 bit? People are gatekeeping to make money off of it.

**Comment by Willianxian** [comment]
thank

**Comment by puzzlemax** [comment]
谢谢，期待您的再次更新。

**Comment by 8824PPZ** [comment]
Thanks for your job

**Comment by jinxx0** [comment]
> > > > > > > @pawinka link or smth? cant find it
> > > > > > 
> > > > > > 
> > > > > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > > > > 
> > > > > 
> > > > > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> > > > 
> > > > 
> > > > I just want to know if its really possible to make it work like that because I have no idea about coding
> > > 
> > > 
> > > Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.
> > > Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.
> > 
> > 
> > sonucunu burdan da haber verir misin hocam
> 
> hotline [fixlenemeyeceğini](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/388#issuecomment-1500548933) söylüyor. Öte yandan forumda fixlediğini [iddia eden](https://www.unknowncheats.me/forum/league-of-legends/578125-skinchangers-x64.html) ama bir şey paylaşmayan da var. Şu an skin hilesi için tek yol, halihazırda 64 bit'de çalışan scriptlerdeki skin changer'lar.

Bir tanesinden atman mümkün mü skin changer bulamıyorum

**Comment by jinxx0** [comment]
> > > > > > > > @pawinka link or smth? cant find it
> > > > > > > 
> > > > > > > 
> > > > > > > https://www.youtube.com/watch?v=mzBLAPkmqJM on this video
> > > > > > 
> > > > > > 
> > > > > > It comes from here originally : https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-445.html
> > > > > 
> > > > > 
> > > > > I just want to know if its really possible to make it work like that because I have no idea about coding
> > > > 
> > > > 
> > > > Issues'in en üstünde "[Tutorial : How to change offsets by yourself](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)" diye bir yer var orada anlatıyor şu an visual studio'ya cpp yüklüyorum denicem.
> > > > Aslında Github oto compile da edebiliyor ama nasıl çalıştığını hiç bilmiyorum bilsem hiç yüklemeye de gerek kalmaz hemen değiştirir denerdik.
> > > 
> > > 
> > > sonucunu burdan da haber verir misin hocam
> > 
> > 
> > hotline [fixlenemeyeceğini](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/388#issuecomment-1500548933) söylüyor. Öte yandan forumda fixlediğini [iddia eden](https://www.unknowncheats.me/forum/league-of-legends/578125-skinchangers-x64.html) ama bir şey paylaşmayan da var. Şu an skin hilesi için tek yol, halihazırda 64 bit'de çalışan scriptlerdeki skin changer'lar.
> 
> Do you any free ones for x64 bit? People are gatekeeping to make money off of it.

Did u find it?

**Comment by l9dson-wq** [comment]
> is there any working skin changer left?

Can use this one: 

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/393

IDK use it on your own risk, the problem is that you can't use DX9 and it's all in chinese, but I tested in a VM to see what happen with a new account and it worked.

**Comment by 394510288** [comment]
感谢，辛苦了

**Comment by alphaaced** [comment]
https://discord.gg/leagueplus
join for the updated r3nz tool.

**Comment by xnrheh** [comment]
> https://discord.gg/leagueplus join for the updated r3nz tool.

Cringe edgelord developers made the program print swastikas ingame, regular n-words in discord etc.

Insanely cringy server.
