### ISSUE TITLE
Hello, 1337

### ISSUE THREAD

**Issue by sakula6** [R3nzTheCodeGOD/R3nzSkin#380]
When the original author asked who had the ability to update the R3nzskin project and handed it over to you, why did you act like a cockroach, unable to even update an address feature code, but needing someone else to submit it! After the x64 update, you have to stop R3skinx86. Have you done anything?

**Comment by Snob345** [comment]
Did you fix it?

**Comment by hotline1337** [comment]
> When the original author asked who had the ability to update the R3nzskin project and handed it over to you, why did you act like a cockroach, unable to even update an address feature code, but needing someone else to submit it! After the x64 update, you have to stop R3skinx86. Have you done anything?

I have contributed to the project way before i've gotten a push access.
