### ISSUE TITLE
Nothing to worry about

### ISSUE THREAD

**Issue by rainzee** [R3nzTheCodeGOD/R3nzSkin#381]
Note that the China server will still be using the X86 architecture for a long time, and I can afford to continue maintaining it after the X64 architecture is updated, as I see that someone on the forum has already completed Clean Dump, and there is nothing to worry about here, and I have completed a completely side-effect free implementation.

The current problem is that it is very difficult to Dump the Chinese server, my usual workflow is to Dump the Taiwanese service and then port it, initially I let the project support the Chinese service when Windows 11 was just released, at that time it was possible to use League Dumper on the new system, but now it is not possible at all, if you have the ability to do kernel Dump you can contact me (QQ1004529162).

There's really nothing to worry about at the moment, above.

注意，中国服务器仍然会在很长一段时间内使用 X86架构，并且我也有能力在X64架构更新后继续维护，因为我看到论坛已经有人完成了Clean Dump，这里没什么需要担心的，我也完成了完全无副作用的实现。

目前的问题是，中国服务器的Dump很困难，我通常的工作流都是Dump台服然后进行移植，最初我让该项目支持中国服的时候，Windows 11刚刚发布，那个时候在新系统上可以使用League Dumper，但是现在已经完全不行了，如果有能力进行内核Dump的可以联系我（QQ1004529162）。

目前真的没有什么需要担心的，以上。

**Comment by DyroS3** [comment]
非常感谢您的付出努力，精神上支持

**Comment by yuehuangsheng** [comment]
感谢！

**Comment by timi0809** [comment]
感谢您的努力 支持

**Comment by yyyfffccc** [comment]
那么除中国以外的x64架构目前是不是没有可用的呢？感谢你的努力！！

**Comment by Frostmourn2234** [comment]
I can not appreciate it more.Grateful for your updating!

**Comment by supremecool1** [comment]
感谢你的贡献

**Comment by a1029602653** [comment]
玩台服的可以用嘛？

**Comment by niuma0807** [comment]
谢谢你好兄弟，而你，才是真正的英雄！

**Comment by rainzee** [comment]
> 那么除中国以外的x64架构目前是不是没有可用的呢？感谢你的努力！！

只有中国服务器开始更改到X64架构后，我才会着手研究，目前没有支持X64的计划。

**Comment by rainzee** [comment]
> 玩台服的可以用嘛？

不行，台服已经实装X64客户端

**Comment by AndroidDeep** [comment]
按国服的尿性应该不会那么快更新X64架构

**Comment by flyingpangpang** [comment]
谢谢你，因为有你，温暖了四季~~~QAQ

**Comment by yyyfffccc** [comment]
> 

好吧，多谢。不过国服用不会封号么，貌似国服对这个查的很严

**Comment by a1029602653** [comment]
> 

总之还是感谢，就等适配x64了

**Comment by HoganAgnes** [comment]
有没有可能提前更新适配X64，现在已经不玩国服了，究极感谢大佬！！

**Comment by rainzee** [comment]
> 有没有可能提前更新适配X64，现在已经不玩国服了，究极感谢大佬！！

国服更新架构后我才会适配，因为我只玩国服。

**Comment by HoganAgnes** [comment]
> > 有没有可能提前更新适配X64，现在已经不玩国服了，究极感谢大佬！！
> 
> 国服更新架构后我才会适配，因为我只玩国服。

好的😭只能暂时裸奔了

**Comment by lukazhao** [comment]
thank you for your contribution

**Comment by iGoodLife** [comment]
> > 有没有可能提前更新适配X64，现在已经不玩国服了，究极感谢大佬！！
> 
> 国服更新架构后我才会适配，因为我只玩国服。

麻烦问一下，您是在国服使用R3nz吗？在国服这个好像是被禁用的，很可能存在封号的风险

**Comment by rainzee** [comment]
> 

国服就是最初我实现的，我维护自己的分叉版本，特征不同，可以放心用

**Comment by yooinsung** [comment]
> > 
> 
> 国服就是最初我实现的，我维护自己的分叉版本，特征不同，可以放心用

那么哪里可以玩到你的分支呢

**Comment by yigei12138** [comment]
x64结构还能看到你来更新维护嘛

**Comment by rainzee** [comment]
> x64结构还能看到你来更新维护嘛

段时间内，国服不会更新架构。

**Comment by yigei12138** [comment]
确实好像还可以用，但是关于使用后疯狂掉帧，请问你对此有解决的办法吗？

> > x64结构还能看到你来更新维护嘛
> 
> 段时间内，国服不会更新架构。

**Comment by LLTTYY1** [comment]
确实最近换肤后会一直掉帧。

**Comment by rainzee** [comment]
> 确实最近换肤后会一直掉帧。

因为检测的原因导致的，我维护的版本不存在这个问题。

**Comment by yigei12138** [comment]
> > 确实最近换肤后会一直掉帧。
> 
> 因为检测的原因导致的，我维护的版本不存在这个问题。

那请问那里可以下载到你所维护的版本呢？万分感谢

**Comment by xl495** [comment]
> 

+1

**Comment by ZhangPF2000** [comment]
+1

**Comment by gptCN** [comment]
+1

**Comment by gptCN** [comment]
国服现在有用的版本吗。万分感谢。

**Comment by rainzee** [comment]
> 国服现在有用的版本吗。万分感谢。

13.5的Release

**Comment by ZhangPF2000** [comment]
@rainzee 你好，十分感谢你做出的贡献，根据你的提示，我使用13.5版本的release。
我是使用替换LogitechLed.dll文件的方式，注入器的方式没办法使用。
我刚刚测试了一下，在自定义模式和训练模式中，它是有效的，可以使用，但是当我打大乱斗模式时，选择玩英雄进入加载界面之后，就会直接卡死，等个几秒后，会强制退出，要求重新连接。我主要是打大乱斗的。
我根据这个项目中的isuue #427 中的内容，修改我的Logitech G HUB时，
![image](https://user-images.githubusercontent.com/64509222/235426889-6e899e66-7781-4abc-9caa-26e289a4916b.png)
我不知道为什么鼠标会和fps之间扯上了关系。。。
再次打开游戏时，是可以进去的，而且也能完成换肤，但是会出现fps下降的问题，大概就是降到10fps左右，十分的难玩，没办法使用。 
在无限火力中是可以使用的，但是fps会下降，很严重也是没法打，而且修改Logitech G HUB没用，匹配不经常打，没测试。
![image](https://user-images.githubusercontent.com/64509222/235429172-40408616-341d-4eed-be8a-2d295ca8e167.png)
如果你也遇到这个问题的话，请考虑开个分支修复该问题，感谢

**Comment by yigei12138** [comment]
> 

大佬能发一个改良版嘛.3245851996@qq.com节日快乐！谢谢大佬！

**Comment by rainzee** [comment]
> @rainzee 你好，十分感谢你做出的贡献，根据你的提示，我使用13.5版本的release。 我是使用替换LogitechLed.dll文件的方式，注入器的方式没办法使用。 我刚刚测试了一下，在自定义模式和训练模式中，它是有效的，可以使用，但是当我打大乱斗模式时，选择玩英雄进入加载界面之后，就会直接卡死，等个几秒后，会强制退出，要求重新连接。我主要是打大乱斗的。 我根据这个项目中的isuue #427 中的内容，修改我的Logitech G HUB时， ![image](https://user-images.githubusercontent.com/64509222/235426889-6e899e66-7781-4abc-9caa-26e289a4916b.png) 我不知道为什么鼠标会和fps之间扯上了关系。。。 再次打开游戏时，是可以进去的，而且也能完成换肤，但是会出现fps下降的问题，大概就是降到10fps左右，十分的难玩，没办法使用。 在无限火力中是可以使用的，但是fps会下降，很严重也是没法打，而且修改Logitech G HUB没用，匹配不经常打，没测试。 ![image](https://user-images.githubusercontent.com/64509222/235429172-40408616-341d-4eed-be8a-2d295ca8e167.png) 如果你也遇到这个问题的话，请考虑开个分支修复该问题，感谢

这个问题我很早就修复了，我在13.5的时候就指出目前社区的解决方案有很大的副作用，包括卡顿等，这是因为需要不断检测状态，我当时就已经实现了完全无副作用的，但是鉴于国内的环境，我并没有打算开源，如果你需要，我可以告诉你解决方案，具体你找一下我联系方式。

**Comment by ZhangPF2000** [comment]
@rainzee 大佬gmail邮箱已联系你，不方便也可以qq邮箱`2812827294@qq.com`，感谢，祝大佬节日快乐!!!

**Comment by xl495** [comment]
> > @rainzee 你好，十分感谢你做出的贡献，根据你的提示，我使用13.5版本的release。 我是使用替换LogitechLed.dll文件的方式，注入器的方式没办法使用。 我刚刚测试了一下，在自定义模式和训练模式中，它是有效的，可以使用，但是当我打大乱斗模式时，选择玩英雄进入加载界面之后，就会直接卡死，等个几秒后，会强制退出，要求重新连接。我主要是打大乱斗的。 我根据这个项目中的isuue #427 中的内容，修改我的Logitech G HUB时， ![image](https://user-images.githubusercontent.com/64509222/235426889-6e899e66-7781-4abc-9caa-26e289a4916b.png) 我不知道为什么鼠标会和fps之间扯上了关系。。。 再次打开游戏时，是可以进去的，而且也能完成换肤，但是会出现fps下降的问题，大概就是降到10fps左右，十分的难玩，没办法使用。 在无限火力中是可以使用的，但是fps会下降，很严重也是没法打，而且修改Logitech G HUB没用，匹配不经常打，没测试。 ![image](https://user-images.githubusercontent.com/64509222/235429172-40408616-341d-4eed-be8a-2d295ca8e167.png) 如果你也遇到这个问题的话，请考虑开个分支修复该问题，感谢
> 
> 这个问题我很早就修复了，我在13.5的时候就指出目前社区的解决方案有很大的副作用，包括卡顿等，这是因为需要不断检测状态，我当时就已经实现了完全无副作用的，但是鉴于国内的环境，我并没有打算开源，如果你需要，我可以告诉你解决方案，具体你找一下我联系方式。

是要付费吗 ? 能否发一个购买链接呢大佬?

**Comment by rainzee** [comment]
不需要啊，你联系我，我告诉你怎么解决就完事了。

**Comment by CharledKoh** [comment]
@rainzee 作者你好，请问你维护的版本可以分享使用吗

**Comment by XIKIDER** [comment]
> 不需要啊，你联系我，我告诉你怎么解决就完事了。

你好，请问可以付费使用你的产品吗?
