### ISSUE TITLE
There might be a way to create skin changer with WAD files?

### ISSUE THREAD

**Issue by IAKILL** [R3nzTheCodeGOD/R3nzSkin#383]
Well i tried something with custom skins and got these results 
![Bez názvu](https://user-images.githubusercontent.com/70193108/230384930-99c0b41d-3143-4750-be76-c2bf452b269b.png)
![Bez názvasdu](https://user-images.githubusercontent.com/70193108/230385108-ece2b38d-1d36-4e7f-a8c7-0554264e1f67.png)
![qweqewqewqew](https://user-images.githubusercontent.com/70193108/230385257-3017bbbb-ed78-46f6-9f24-b30a17d18903.png)
![weqewqweqwqew](https://user-images.githubusercontent.com/70193108/230385265-7f02942c-28ff-4778-9f65-ee7a840c7b39.png)

but as you can see i only somehow got the model skin the effects are not from Battle Queen Qiyana, When I tried to also upload bin with the animations my league went black screen. 
I didnt code anything just simply downloaded WAD file of qiyana and renamed skin number to base skin. So I am sure there is a way to create new modskin, if someone is good at coding or good at working with models etc it is possible. Sadly I am not capable of that I tried quite a lot of ways to try fix the effects and it didnt work. Spent around 8 hours fixing.

**Comment by 9qlys** [comment]
Can u to reach me

**Comment by IAKILL** [comment]
> Can u to reach me

What do you mean?

**Comment by 9qlys** [comment]
I want to know how you did it can you reach me via instagram or message

**Comment by IAKILL** [comment]
@9qlys Well its quite simple i extracted the WAD file of Qiyana, which contains all effects,models etc on each skin. Then I substracted the skin i choose to diff folder, and uploaded to lolcsmanager (custom skin program). Sadly when i tried to do full clean skin league was black seen and lolcsmanager access denied so it has some anticheat propably but someone who can code can bypass it imo this is just non coding custom skin basically. But I guess this is how modskinlol might work simply changing wad files. If you want you can dm me on DC huya 572329#5702

**Comment by Fiethsings** [comment]
@IAKILL 
Hey, just letting you know that to get the effects (particles) to show up you have to play around with the .bin files.
It's not as simple as changing skin15.bin to skin0.bin, but it's not rocket science either. You can probably figure it out by looking through the tutorials on killerskins.com .

**Comment by GuiSaiUwU** [comment]
well, there is another better way to do wad skin hacking, and I'm developping a app for that, it even lets you copy skins from PBE [with effects]
![Screen482](https://user-images.githubusercontent.com/107002177/230787979-d3f9d3f6-5ddb-4500-ab40-bf66621e9e4f.png)

**Comment by austenseo** [comment]
> well, there is another better way to do wad skin hacking, and I'm developping a app for that, it even lets you copy skins from PBE [with effects] ![Screen482](https://user-images.githubusercontent.com/107002177/230787979-d3f9d3f6-5ddb-4500-ab40-bf66621e9e4f.png)

that's great how wil it work like R3nzSkin Or LOL mod skin?

**Comment by alphaaced** [comment]
> well, there is another better way to do wad skin hacking, and I'm developping a app for that, it even lets you copy skins from PBE [with effects]
> ![Screen482](https://user-images.githubusercontent.com/107002177/230787979-d3f9d3f6-5ddb-4500-ab40-bf66621e9e4f.png)
> 

Wow that's amazing. Will it be free?
Will it also fix the issues and broken particles r3nz skin had?
