### ISSUE TITLE
中国玩家的心声

### ISSUE THREAD

**Issue by azp5211314** [R3nzTheCodeGOD/R3nzSkin#384]
我是一名中国玩家，我非常喜欢这个，我们不想看到这么好的东西被弃用，所以有好心人想要重启该项目的话我们中国玩家可以给你众筹，就是捐款来支持你开发新的架构。

**Comment by gavin189518** [comment]
是的

**Comment by SuShuiNB** [comment]
> 
本人好像参军去了，他这源码公开的，要是有人维护就好了1

**Comment by Yang7h** [comment]
支持

**Comment by sakula6** [comment]
It's not that you don't want to see such a good thing abandoned, but that they gave up and affected your interests! But I don't have the ability to update myself

**Comment by xiangshuiyoudu** [comment]
I have reached printf("hello world!")! Wait me to update this!😭

**Comment by TheNei** [comment]
有无英雄登场  可以众筹点的

**Comment by SuShuiNB** [comment]
有没有人能去继续搞一下这个项目，可以众筹

**Comment by rainzee** [comment]
最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？

**Comment by HoganAgnes** [comment]
> 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有"弃用"一说呢？

大佬 现在国服安全吗😅

**Comment by xiangshuiyoudu** [comment]
> > 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有"弃用"一说呢？
> 
> 大佬 现在国服安全吗😅

我就外服用 国服就算能用也不敢用 封号太快 我就国服本地改个血的颜色就封了七天

**Comment by xiangshuiyoudu** [comment]
> 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？

我就外服用 国服就算能用也不敢用 封号太快 我就国服本地改个血的颜色就封了七天

**Comment by UncertA1n1** [comment]
> 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？

我希望其他服的玩家也可以感谢你

**Comment by XNeSizzzz** [comment]
> 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？

大佬还能再用吗？这个换肤真的很好用，大伙愿意众筹求更新

**Comment by zhang1997518** [comment]
I have completed the update of this project Need some sponsorship to use Need contact me Q9700782

**Comment by rainzee** [comment]
> > 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有"弃用"一说呢？
> 
> 大佬 现在国服安全吗😅

直接用肯定是封号的，因为特征早都上去了，我自己的版本肯定是不封号了，已经用了很多年了

**Comment by rainzee** [comment]
> > 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？
> 
> 大佬还能再用吗？这个换肤真的很好用，大伙愿意众筹求更新

本身就是可以用的，国服还会使用很久的X86架构

**Comment by rainzee** [comment]
> Dont send anything to this guy lol @zhang1997518 he try to scam for sure

That's for sure lol

**Comment by IAKILL** [comment]
@rainzee btw I have found this on one forum

0x1ea9b0 // 0F B6 41 48 4C

comepare object type flag (ishero, isminion...)

translateStringUNSAFE 0xc5c650 // not unsafe, just name
fnCharacterDataStack_Push 0x188380 // E8 ?? ?? ?? ?? 48 8D 8D B0 11 00 00 E8 ?? ?? ?? ?? 48 85 C0
fnCharacterDataStack_Update 0x172840 // 88 54 24 10 53 55 56 57 41 54 41 55 41 56 41
oCharacterDataStack 0x3628

for skinchanger

**Comment by minazuki522** [comment]
what is this?

**Comment by zhang1997518** [comment]
I have indeed managed to get this project working. I didn't cheat anyone, you can contact me if you need it You can test it

> 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗



> 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗



> 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗

I have indeed managed to get this project working. I didn't cheat anyone, you can contact me if you need it You can test it

**Comment by minazuki522** [comment]
> I have indeed managed to get this project working. I didn't cheat anyone, you can contact me if you need it You can test it
> 
> > 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗
> 
> > 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗
> 
> > 不要向这家伙发送任何东西，哈哈，@zhang1997518他肯定会试图欺骗
> 
> I have indeed managed to get this project working. I didn't cheat anyone, you can contact me if you need it You can test it

just lend some proof then. No one will believe otherwise

**Comment by NightNightDream** [comment]
> > > 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？
> > 
> > 
> > 大佬还能再用吗？这个换肤真的很好用，大伙愿意众筹求更新
> 
> 本身就是可以用的，国服还会使用很久的X86架构

你怎么知道国服还会用很久的X86架构

**Comment by a984120978** [comment]
那你拿出诚意来去学C++啊

**Comment by rainzee** [comment]
> > > > 最初支持中国服务器是我跟作者实现的，你要感谢也应该是感谢我，另外最奇怪的是，现在国服并没有更新架构和Sig，依旧是可用的，未来也会持续可用。哪里有“弃用”一说呢？
> > > 
> > > 
> > > 大佬还能再用吗？这个换肤真的很好用，大伙愿意众筹求更新
> > 
> > 
> > 本身就是可以用的，国服还会使用很久的X86架构
> 
> 你怎么知道国服还会用很久的X86架构

就像我知道如何让R3最初支持国服一样，我当然知道
