### ISSUE TITLE
I have reached printf("hello world!")! Wait me to update this!😭

### ISSUE THREAD

**Issue by xiangshuiyoudu** [R3nzTheCodeGOD/R3nzSkin#386]
![image](https://user-images.githubusercontent.com/81700585/230555530-136d5ab0-77a6-48f3-931c-279d0d27c537.png)

### **Who can tell me what level I need to reach to update this or what I need to learn next？**

**Comment by 9qlys** [comment]
With a cynical attitude, there's not much you can learn here

**Comment by szworld1** [comment]
When you update, this game is gone

**Comment by zhj123169** [comment]
lol hahaha

**Comment by castorwong** [comment]
代码构成大部分是C++，你这是C的语法  ;-)

**Comment by TheNei** [comment]
不是
std::cout << "Hello World" << endl;
??????
