### ISSUE TITLE
这个代码是C++还是？

### ISSUE THREAD

**Issue by Kimmichcoder** [R3nzTheCodeGOD/R3nzSkin#387]
他的源码在哪里？

> 我的天哪

**Comment by Kimmichcoder** [comment]
话说有没有其他能用的修改器？

**Comment by qingqingweiran** [comment]
没有 #define mian main 我不是很认可

**Comment by minazuki522** [comment]
Lol skin is one of those that works, but youll have to wait for an update (within 2 or 3 days from now)

**Comment by Kimmichcoder** [comment]
> 没有 #define mian main 我不是很认可
int mian()是吧

**Comment by Kimmichcoder** [comment]
哈哈哈

**Comment by TheNei** [comment]
什么C语言大佬

**Comment by Kimmichcoder** [comment]
> 什么C语言大佬

再说mihoyo把腾讯源码给你爬下来
