### ISSUE TITLE
THIS CODE SHOULD FIX IT, CAN SOMEONE RECODE IT? I DONT KNOW HOW TO CODE

### ISSUE THREAD

**Issue by IAKILL** [R3nzTheCodeGOD/R3nzSkin#388]
translateStringUNSAFE 0xc5c650 // not unsafe, just name
fnCharacterDataStack_Push 0x188380 // E8 ?? ?? ?? ?? 48 8D 8D B0 11 00 00 E8 ?? ?? ?? ?? 48 85 C0
fnCharacterDataStack_Update 0x172840 // 88 54 24 10 53 55 56 57 41 54 41 55 41 56 41
oCharacterDataStack 0x3628

**Comment by Papryczekk** [comment]
Where did you get it?

**Comment by MihaiTheAwsm** [comment]
doesn't work by simply changing these offsets i tried it

**Comment by hotline1337** [comment]
The game has switched the architecture, just changing the offsets won't fix anything.

![obraz](https://user-images.githubusercontent.com/32012110/230662255-3a7ba2c4-2de5-4aa6-a2b1-57dab9157e2f.png)
