### ISSUE TITLE
How to get those function sign coded in memory.hpp

### ISSUE THREAD

**Issue by zxcvbnm3057** [R3nzTheCodeGOD/R3nzSkin#391]
Did you guys just locate them with ida base on your experience or there's some tools better? And will this repo keep updating if there's a new injector and x64 disassembler provided?

**Comment by zxcvbnm3057** [comment]
@hotline1337 maybe little information about this?

**Comment by MihaiTheAwsm** [comment]
The game has switched the architecture, just changing the offsets won't fix anything.
![230662255-3a7ba2c4-2de5-4aa6-a2b1-57dab9157e2f](https://user-images.githubusercontent.com/47987723/230746701-c7482ee9-07dd-4a2a-907f-f613967da0e4.png)

**Comment by zxcvbnm3057** [comment]
Yeah, I got it. I can make the injector support x64 but this patch doesn't seem like rely on function signature but address offset. Unfortunately, it is too complex for me to relocate them from game memory dump. So please post a ref if there is  tutorial about it.

**Comment by IAKILL** [comment]
So you made injector supporting x64 already? if so good work! Keep it up, tons of people would aprecciate your job, lets hope hotline will help you with the game memory dump, i hope its not something hard, I love this app propably best that have been made

**Comment by zxcvbnm3057** [comment]
No, I haven't done it yet. But I make a patch to replace the x64 embedded LUA engine in DST earlier this year. So I think I can get it done. But I can use known export api function address to generate the function signature in that envirenment. So it still a problem to locate skin load function address in LOL.

**Comment by IAKILL** [comment]
Oh well i dont understand anything about that one hopefgully some will help you i seen couple ppl talking it should be easy to make it work for x64 but seems like none of them actually trying

**Comment by minazuki522** [comment]
> Oh well i dont understand anything about that one hopefgully some will help you i seen couple ppl talking it should be easy to make it work for x64 but seems like none of them actually trying

its actually kinda hard, because you have to change a lot of things. Its pretty messed up lmao

**Comment by quangchung2002** [comment]
I think this version https://leagueskin.net/p/download-mod-skin-2020-CHN contains old data. Someone can change the data in it

**Comment by JUstZot** [comment]
https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-450.html
perhaps someone here can help

**Comment by HGYHGX** [comment]
If you use the "lolskin" files does not help?

**Comment by zxcvbnm3057** [comment]
> https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-450.html perhaps someone here can help

Thanks for that. So does that mean I don't need to worry about "offset" cause those guys have done it.

**Comment by zxcvbnm3057** [comment]
I think this can prove that my injection was successful. And now I really need some help about relocate those function address
![(T$GCJ`$Z`PCL)M }5`J5PJ](https://user-images.githubusercontent.com/48760372/233630922-bdddfd97-607c-4bb3-9500-d5203f2a7624.png)

**Comment by zxcvbnm3057** [comment]
All codes have been pushed to my fork, on branch x64-develop.

@hotline1337 Little help?

**Comment by zxcvbnm3057** [comment]
#428

**Comment by vinacf001** [comment]
![image](https://user-images.githubusercontent.com/12063920/233827277-bd5f4000-2ef5-4cf8-b9e3-612371e10dfa.png)


invoker.invokeThiscall<__int64>(__int64(this), (DWORD64)(cheatManager.memory->base + offsets::functions::CharacterDataStack__Update), change);

It crash not work ! Please show me new Solution !

**Comment by zxcvbnm3057** [comment]
@vinacf001 yeah, the version now is still not working. I make the injecter and hook handler support x64 only. But the signs in memory.hpp are still for old version, which is not correct. And there is nothing I can do.

**Comment by vinacf001** [comment]
@zxcvbnm3057 i will share memory.hpp with offset.hpp newest version ! 13.8 now

**Comment by vinacf001** [comment]
offset.hpp 13.8 some offset not update !

`#pragma once

#include <cstdint>

namespace offsets {
	namespace GameObject {
		namespace VTable {//i do not update here
			enum {
				IsLaneMinion = 0xDA,
				IsEliteMinion = IsLaneMinion + 0x1,
				IsEpicMinion = IsEliteMinion + 0x1,
				IsMinion = IsEpicMinion + 0x4,
				IsJungle = IsMinion + 0x1
			};
		};
		enum {//updated 13.8
			Team = 0x003C,
			Name = 0x0060,
			Health = 0x1058,
			MaxHealth = 0x1070
		};
	};

	namespace global {
		inline std::uint32_t Player{ 0x518aad8 };
		inline std::uint32_t ChampionManager{ 0x392B8C8 };
		inline std::uint32_t Riot__g_window{ 0x518aaf0 };
		inline std::uint32_t ManagerTemplate_AIMinionClient_{ 0x392b8a0 };
		inline std::uint32_t ManagerTemplate_AIHero_{ 0x20d0fa0 };
		inline std::uint32_t ManagerTemplate_AITurret_{ 0x5179250 };
		inline std::uint32_t GameClient{ 0x392b8d8 };
		inline std::uint32_t retSpoofGadget{ 0x0FFECE6 };//not sure
	};

	namespace AIBaseCommon {
		inline std::uint32_t CharacterDataStack{ 0x3620 };
		inline std::uint32_t SkinId{ 0x3658 };
	};

	namespace MaterialRegistry {
		inline std::uint32_t D3DDevice{ 0x2b0 };
		inline std::uint32_t SwapChain{ 0x1c0 };
	};

	namespace functions {
		inline std::uint32_t Riot__Renderer__MaterialRegistry__GetSingletonPtr{ 0xdc84d0 };
		inline std::uint32_t translateString_UNSAFE_DONOTUSE{ 0xc58d20 };
		inline std::uint32_t CharacterDataStack__Push{ 0x18ac00 };
		inline std::uint32_t CharacterDataStack__Update{ 0x174ef0 };
		inline std::uint32_t GetGoldRedirectTarget{ 0x1e44b0 };//not sure
	};
};
`

**Comment by vinacf001** [comment]
offset.hpp 13.8 some offset not update !

`#pragma once

#include <cstdint>

namespace offsets {
	namespace GameObject {
		namespace VTable {//i do not update here
			enum {
				IsLaneMinion = 0xDA,
				IsEliteMinion = IsLaneMinion + 0x1,
				IsEpicMinion = IsEliteMinion + 0x1,
				IsMinion = IsEpicMinion + 0x4,
				IsJungle = IsMinion + 0x1
			};
		};
		enum {//updated 13.8
			Team = 0x003C,
			Name = 0x0060,
			Health = 0x1058,
			MaxHealth = 0x1070
		};
	};

	namespace global {
		inline std::uint32_t Player{ 0x518aad8 };
		inline std::uint32_t ChampionManager{ 0x392B8C8 };
		inline std::uint32_t Riot__g_window{ 0x518aaf0 };
		inline std::uint32_t ManagerTemplate_AIMinionClient_{ 0x392b8a0 };
		inline std::uint32_t ManagerTemplate_AIHero_{ 0x20d0fa0 };
		inline std::uint32_t ManagerTemplate_AITurret_{ 0x5179250 };
		inline std::uint32_t GameClient{ 0x392b8d8 };
		inline std::uint32_t retSpoofGadget{ 0x0FFECE6 };//not sure
	};

	namespace AIBaseCommon {
		inline std::uint32_t CharacterDataStack{ 0x3620 };
		inline std::uint32_t SkinId{ 0x3658 };
	};

	namespace MaterialRegistry {
		inline std::uint32_t D3DDevice{ 0x2b0 };
		inline std::uint32_t SwapChain{ 0x1c0 };
	};

	namespace functions {
		inline std::uint32_t Riot__Renderer__MaterialRegistry__GetSingletonPtr{ 0xdc84d0 };
		inline std::uint32_t translateString_UNSAFE_DONOTUSE{ 0xc58d20 };
		inline std::uint32_t CharacterDataStack__Push{ 0x18ac00 };
		inline std::uint32_t CharacterDataStack__Update{ 0x174ef0 };
		inline std::uint32_t GetGoldRedirectTarget{ 0x1e44b0 };//not sure
	};
};
`

**Comment by zxcvbnm3057** [comment]
@vinacf001 Thank you for sharing this. But it seem like still not working.... Perhaps because memory.hpp is still not updated.

**Comment by zxcvbnm3057** [comment]
@VAGUE000 Almost all items in [memory.hpp](https://github.com/zxcvbnm3057/R3nzSkin/blob/x64-develop/R3nzSkin/memory.hpp) need to be updated. And I can't continue to fix this utill all sign is corrent.

**Comment by zxcvbnm3057** [comment]
> @zxcvbnm3057 could you check this one? https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-460.html (not good at coding but seems like the guy posted updated 13.8 offsets) P.S. hope it could help by any chance

They are posting address not sign. I'm not sure if I should change r3nzskin from locate with sign to locate by address.
