### ISSUE TITLE
leagueskin.net https://leagueskin.net/p/download-mod-skin-2020-chn

### ISSUE THREAD

**Issue by gulle1337** [R3nzTheCodeGOD/R3nzSkin#392]
When i open mod skin from leagueskin.net newest patch it doesnt work

When i open the app, it opens another app that said its last edited in 2021 and doesnt work anymore, what should i do.

**Comment by ariaabbasi** [comment]
its for chnia only

**Comment by gulle1337** [comment]
> 

what...
usually its for every region

**Comment by Fiethsings** [comment]
> @ariaabbasi what... usually its for every region

Likely because they haven't updated to work on x64 architecture yet. I believe China Server is still using x86, but they will likely have to update to x64 eventually as well, so we will see whether anyone adapts R3nz or modskin in the future.
