### ISSUE TITLE
How to deinstall?

### ISSUE THREAD

**Issue by switchblade0003** [R3nzTheCodeGOD/R3nzSkin#394]
How to deinstall? Tried to click right button instead left but doesnt change anything :D ![image](https://user-images.githubusercontent.com/130502821/231267165-bf83c876-7f01-4765-aac2-b4cc7a99a7b3.png)

**Comment by alphaaced** [comment]
You just press this, finish your game and next game nothing should be there.

**Comment by minazuki522** [comment]
> You just press this, finish your game and next game nothing should be there.

I did it and yet it still there

**Comment by tianya0529** [comment]
> > You just press this, finish your game and next game nothing should be there.
> 
> I did it and yet it still there



The radio box on the left is for hijacking injection, while the radio box on the right is for driver injection. The left button at the bottom is for opening, and the right button is for closing. Opening requires opening in the game hall, and closing requires closing after the game is closed

**Comment by miyuishere** [comment]
I clicked the right button two times when there was something wrote about logitech.dll file or whatever the name was lol

**Comment by hotline1337** [comment]
Issue not associated with the current project.
