### ISSUE TITLE
I have created a discord

### ISSUE THREAD

**Issue by tianya0529** [R3nzTheCodeGOD/R3nzSkin#395]
#393 
I have created a discord
There will be updates in English in the future, and I will post them in the [discord](https://discord.gg/aTMj4kbT8Q)

**Comment by dungpham1785** [comment]
it says invite invalid can u send another invite

**Comment by minazuki522** [comment]
thank you very much!

**Comment by hotline1337** [comment]
Issue not associated with the current project.
