### ISSUE TITLE
R3nzSkin Outer13.7 外服13.7版本

### ISSUE THREAD

**Issue by zhang1997518** [R3nzTheCodeGOD/R3nzSkin#396]
我创造了一个英文版本，在[R4nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11207048/R4nzSkin.zip)在这里学到了很多知识和技术。
我会在以后的时间持续更新这个项目，但是并不会开源因为这个Skin只是我项目中的其中一个。并且我的项目还在使用中
可能以后我项目不再使用了，我会开源我的项目，那些说有病毒的人希望你们不要使用我的项目。我并没有找到如何注入新版本X64位的游戏的注入器，如果有人有这个注入器可以私信发我一下谢谢。
把 LogitechLed.dll 放到游戏目录Game文件下面 然后登陆游戏进入游戏即可使用

I created an English version and learned a lot of knowledge and techniques here at R3nzSkin.
I'll keep updating this project in the future, but it won't be open source because this Skin is just one of my projects. And my project is still in use
Maybe in the future my project is no longer used, I will open source my project, those who say there is a virus hope that you will not use my project. I didn't find how to inject the injector into the new version of the X64-bit game, if anyone has this injector can send me a private message thank you. Put LogitechLed.dll under the game directory Game file, then log in to the game and enter the game to use

**Comment by Ertugrul-salih** [comment]
it works thanks

**Comment by gan-liliang** [comment]
非常好用，感谢大佬

**Comment by alphaaced** [comment]
> 我创造了一个英文版本，在[R4nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11207048/R4nzSkin.zip)在这里学到了很多知识和技术。
> 我会在以后的时间持续更新这个项目，但是并不会开源因为这个Skin只是我项目中的其中一个。并且我的项目还在使用中
> 可能以后我项目不再使用了，我会开源我的项目，那些说有病毒的人希望你们不要使用我的项目。我并没有找到如何注入新版本X64位的游戏的注入器，如果有人有这个注入器可以私信发我一下谢谢。
> 把 LogitechLed.dll 放到游戏目录Game文件下面 然后登陆游戏进入游戏即可使用
> 
> I created an English version and learned a lot of knowledge and techniques here at R3nzSkin.
> I'll keep updating this project in the future, but it won't be open source because this Skin is just one of my projects. And my project is still in use
> Maybe in the future my project is no longer used, I will open source my project, those who say there is a virus hope that you will not use my project. I didn't find how to inject the injector into the new version of the X64-bit game, if anyone has this injector can send me a private message thank you. Put LogitechLed.dll under the game directory Game file, then log in to the game and enter the game to use
> 

Will it be possible to fix particles that r3nz could not? Anivia W, Kayn R, Godking garen?

**Comment by iwilltry7** [comment]
Where do i have to put the file for the eng version ? thanks.

**Comment by lesingebleu** [comment]
CN only?

**Comment by DAsrinK** [comment]
I didn't understand how to use.

**Comment by DAsrinK** [comment]
> it works thanks

Usta nasıl çalıştırdın ?

**Comment by minazuki522** [comment]
Does it work for all servers?

**Comment by HoganAgnes** [comment]
Where to download LogitechLed.dll🙇

**Comment by IAKILL** [comment]
Something is in english but the skin names still arent 
![image](https://user-images.githubusercontent.com/70193108/231473903-9e443091-04f7-428c-981b-77390a7dc966.png)

**Comment by derrishas** [comment]
_luv u <3_

**Comment by minazuki522** [comment]
how can I minimize the program in the game?

**Comment by gan-liliang** [comment]
> CN only?all servers except cn

**Comment by gan-liliang** [comment]
> CN only?

All servers except cn

**Comment by gan-liliang** [comment]
> Does it work for all servers?

Yes

**Comment by gan-liliang** [comment]
> Does it work for all servers?

Except CN

**Comment by gan-liliang** [comment]
> how can I minimize the program in the game?

Press ins

**Comment by billysyt** [comment]
@zhang1997518 Could you share the offset to me privately? Really thanks!

**Comment by lesingebleu** [comment]
It does work but it makes me drop frames.

**Comment by slowloriss** [comment]
> It does work but it makes me drop frames.

same prb
you should try without inject version(English version)

**Comment by IAKILL** [comment]
@lesingebleu try decreasing your mouse refresh rate

**Comment by c0neee** [comment]
dont understand how to use it do need to inject it or just  put the dll file in league of legends game folder and start the game help?

**Comment by wiinders** [comment]
how can i use

**Comment by slowloriss** [comment]
> dont understand how to use it do need to inject it or just put the dll file in league of legends game folder and start the game help?

just put LogitechLed.dll to Riot Games\League of Legends\Game\
then in-game press insert key to display GUI
PG Up & PG Down key allow you quick skin change

**Comment by blaphomew** [comment]
Can you add a button that changes everyone else's skins to default/classic? R3nzSkin used to have this function, but your R4nz does not

thanks for your work

**Comment by quangchung2002** [comment]
cảm ơn bạn, tôi đã thử và thành công

**Comment by austenseo** [comment]
> 我创造了一个英文版本，在[R4nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11207048/R4nzSkin.zip)在这里学到了很多知识和技术。 我会在以后的时间持续更新这个项目，但是并不会开源因为这个Skin只是我项目中的其中一个。并且我的项目还在使用中 可能以后我项目不再使用了，我会开源我的项目，那些说有病毒的人希望你们不要使用我的项目。我并没有找到如何注入新版本X64位的游戏的注入器，如果有人有这个注入器可以私信发我一下谢谢。 把 LogitechLed.dll 放到游戏目录Game文件下面 然后登陆游戏进入游戏即可使用
> 
> I created an English version and learned a lot of knowledge and techniques here at R3nzSkin. I'll keep updating this project in the future, but it won't be open source because this Skin is just one of my projects. And my project is still in use Maybe in the future my project is no longer used, I will open source my project, those who say there is a virus hope that you will not use my project. I didn't find how to inject the injector into the new version of the X64-bit game, if anyone has this injector can send me a private message thank you. Put LogitechLed.dll under the game directory Game file, then log in to the game and enter the game to use

hi it didn't work for me pleas can you help me  and thank you for ur effort <3 ^-^

**Comment by IAKILL** [comment]
> > 我创造了一个英文版本，在[R4nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11207048/R4nzSkin.zip)在这里学到了很多知识和技术。 我会在以后的时间持续更新这个项目，但是并不会开源因为这个Skin只是我项目中的其中一个。并且我的项目还在使用中 可能以后我项目不再使用了，我会开源我的项目，那些说有病毒的人希望你们不要使用我的项目。我并没有找到如何注入新版本X64位的游戏的注入器，如果有人有这个注入器可以私信发我一下谢谢。 把 LogitechLed.dll 放到游戏目录Game文件下面 然后登陆游戏进入游戏即可使用
> > I created an English version and learned a lot of knowledge and techniques here at R3nzSkin. I'll keep updating this project in the future, but it won't be open source because this Skin is just one of my projects. And my project is still in use Maybe in the future my project is no longer used, I will open source my project, those who say there is a virus hope that you will not use my project. I didn't find how to inject the injector into the new version of the X64-bit game, if anyone has this injector can send me a private message thank you. Put LogitechLed.dll under the game directory Game file, then log in to the game and enter the game to use
> 
> hi it didn't work for me pleas can you help me and thank you for ur effort <3 ^-^

https://www.youtube.com/watch?v=qceSPJ9-YFQ&t=4s&ab_channel=qwqq 
Try watch this 
Make sure you unchecked DX9 in league settings

**Comment by Romeobv** [comment]
Funciona c:

**Comment by dzopix** [comment]
It works perfectly fine for me - no trojan either, but for my friend the windows antivirus keeps deleting the file.. He even added it to excluded items, both folder and file in virus settings and still when he pastes it into lol game folder a virus threat pops up and it deletes the file even after he checks the "allow on device" box. Any solutions to this? I guess he could disable antivirus as a whole but hes sceptical about doing that (idk why he is windows antivirus is bad af)

**Comment by slowloriss** [comment]
> It works perfectly fine for me - no trojan either, but for my friend the windows antivirus keeps deleting the file.. He even added it to excluded items, both folder and file in virus settings and still when he pastes it into lol game folder a virus threat pops up and it deletes the file even after he checks the "allow on device" box. Any solutions to this? I guess he could disable antivirus as a whole but hes sceptical about doing that (idk why he is windows antivirus is bad af)

windows defender whitelist add two folders
1. download files folder location
2. you want put where (unzip to)

when you download from browser choese keep file and then unzip to folder of whitelist (only need R4.exe)
maybe windows defender still notification something just allow them because never anti-virus allow we put private files to windows resource folder
When you don't want to use it anymore find 111.dll and wegamedrive.sys in C:\Windows\ you can delete them by youself
The other two files can also be deleted
C:\R3nzSkin
X:\Riot Games\League of Legends\Game\imgui.ini

second way just use LogitechLed.dll
It might be better if you have a lot of concerns

**Comment by Pulinpuli** [comment]
感谢大佬

**Comment by halilefe4228** [comment]
It works but even before choosing any skins, my character movement becomes weird it kind of teleports to the direction it wants to go. I don't know how to explain it better, can provide video in case its not a known issue. How to fix?

**Comment by dzopix** [comment]
> > > It works perfectly fine for me - no trojan either, but for my friend the windows antivirus keeps deleting the file.. He even added it to excluded items, both folder and file in virus settings and still when he pastes it into lol game folder a virus threat pops up and it deletes the file even after he checks the "allow on device" box. Any solutions to this? I guess he could disable antivirus as a whole but hes sceptical about doing that (idk why he is windows antivirus is bad af)
> > 
> > 
> > windows defender whitelist add two folders
> > 
> > 1. download files folder location
> > 2. you want put where (unzip to)
> > 
> > when you download from browser choese keep file and then unzip to folder of whitelist (only need R4.exe) maybe windows defender still notification something just allow them because anti-virus never allow we put private files to windows resource folder When you don't want to use it anymore find 111.dll and wegamedrive.sys in C:\Windows\ you can delete them by youself The other two files can also be deleted C:\R3nzSkin X:\Riot Games\League of Legends\Game\imgui.ini
> > second way just use LogitechLed.dll It might be better if you have a lot of concerns and dx11 works good no drop fps
> 
> Yes, we are both using LogitechLed.dll but as soon as he extracts logitechled.dll and pastes it into lol game folder it gets deleted by antivirus. Thats what i was trying to explain. Even tho we put it as excluded item in virus threat protection


I found a way, you need to exclue File Type.... Just write dll in File Type exclusion

**Comment by davidvn001** [comment]
The kindred marks do not show up clearly, it just shows a small blue dot in the map.

**Comment by JohanLiebert10** [comment]
sure isnt not bannable ?

**Comment by moStartIn2019** [comment]
666

**Comment by lastmonarchy** [comment]
you are my best bro

**Comment by gyuuki77** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/130842156/232224070-6856b3ec-6852-4c13-a482-b542737fd128.png) thanks! everything works

**Comment by ilyablaut** [comment]
mb u can say me how to fix default voicy lines on legendery skins for lux. soraka and etc

**Comment by alphaaced** [comment]
> mb u can say me how to fix default voicy lines on legendery skins for lux. soraka and etc 

You cannot. Its from riot not the tool

**Comment by CountAlucard99** [comment]
Thanks u saved my life!

**Comment by OUYANG777** [comment]
我只能說你是我的神I can only say that you are my god

**Comment by Pandikas** [comment]
Ahhh, can someone help. It's my second time testing this, and the same thing is happening, by starting to use it, my fps caps around 100, and it starts lagging, can someone help to fix this?

**Comment by Doodler8** [comment]
can you please fix the bug on khazix skins , lunar guardian and odessey are not available

**Comment by hotline1337** [comment]
Issue not associated with the current project. No binaries are allowed to be shared here.
