### ISSUE TITLE
Let's find an actual solution.

### ISSUE THREAD

**Issue by Ilyessssss** [R3nzTheCodeGOD/R3nzSkin#397]
Since the project is not gonna get updated anymore because of x86 deprecation let's all try to find an actual solution.The only thing we have access to rn is that chinese version which first of all is not safe , second of all is filled with glitches.i've also seen somoene saying you could use .wad files and custom skins with cs lol but no developpement to that.Ik it's already been asked but if anyone has a solution or even just an idea please post it here so we can gather them and hopefully give birth to a new skin changer.

**Comment by minazuki522** [comment]
There is a program that works already

**Comment by yuukiqa** [comment]
can you tell me the name of the program?

**Comment by wowimsoretarded** [comment]
> There is a program that works already

whicih one? please tell us

**Comment by alphaaced** [comment]
> > There is a program that works already
> 
> whicih one? please tell us

the chinese version.

**Comment by minazuki522** [comment]
> > There is a program that works already
> 
> whicih one? please tell us

the one created by tiyana

**Comment by Ali229** [comment]
Link for that version?

**Comment by SeeN150** [comment]
link?

**Comment by alphaaced** [comment]
discord.gg/leagueplus 
youll find everything u need here.
