### ISSUE TITLE
"?" with russian language.

### ISSUE THREAD

**Issue by wnglsss** [R3nzTheCodeGOD/R3nzSkin#399]
hello. im playing on a russian server, and I ran into a problem "?". i am far from programming, i tried to change it myself according to the instructions for the vietnamese language, but nothing happened. as i understand it, its in unicode. 
![image](https://user-images.githubusercontent.com/130900437/232293025-fad6cd80-3dd4-438f-b675-d0754850a2f1.png)

i will be grateful for your help.

**Comment by ilyablaut** [comment]
Челик не будет открывать проект для общего использования и для открытого кода, поэтому довольствуемся тем чем есть

**Comment by hotline1337** [comment]
Issue not associated with the current project.
