### ISSUE TITLE
The last version release my antivirus detects it as VIRUS.

### ISSUE THREAD

**Issue by Th3Nigh7mare** [R3nzTheCodeGOD/R3nzSkin#40]
I'd like you to check it for viruses.

**Comment by discordtwilight** [comment]
It has no viruses it's litterly open source...

**Comment by Clownsw** [comment]
> 我希望你检查它是否有病毒。

I think if you don't worry about binary distribution, you can compile it yourself

**Comment by ViralVirusCap** [comment]
Same, trojan warning. Do all of them have viruses fr?

**Comment by Th3Nigh7mare** [comment]
Window Defender detects it, but maybe it's my antivirus.

**Comment by R3nzTheCodeGOD** [comment]
It's funny that you open an issue thread like this while the source code is here.
