### ISSUE TITLE
Skin sounds in the new skin changer version

### ISSUE THREAD

**Issue by VojtisCZ** [R3nzTheCodeGOD/R3nzSkin#400]
Hi, I just wanted to ask if there's any way to get the skin sounds like Aatrox Q or Pyke R sounds into the game with the new version of r3nzskin from the chinese people. I know theres a whole issue opened for this but i dont really know if the owner found a solution for this or if he didnt. 
Thanks

**Comment by alphaaced** [comment]
> Hi, I just wanted to ask if there's any way to get the skin sounds like Aatrox Q or Pyke R sounds into the game with the new version of r3nzskin from the chinese people. I know theres a whole issue opened for this but i dont really know if the owner found a solution for this or if he didnt. 
> Thanks

Nope, no solution

**Comment by VojtisCZ** [comment]
Alright, thanks.

**Comment by lpszcpa** [comment]
雷神加速器可以的，有个中文转换，语音包也会换成中文
