### ISSUE TITLE
Any update for 13.8 version yet?

### ISSUE THREAD

**Issue by nsthanh1307** [R3nzTheCodeGOD/R3nzSkin#403]

**Comment by W18191868439** [comment]
Not found yet,.

**Comment by dzopix** [comment]
Why doesn't 13.7 work with 13.8 patch? whats the difference i never understood why it has to be patched along the lol client

**Comment by jesus1241232132145** [comment]
> Why doesn't 13.7 work with 13.8 patch? whats the difference i never understood why it has to be patched along the lol client

probably because the game files update so the skin changer has to update too its just what i think tho

**Comment by dzopix** [comment]
> 

what is this?

**Comment by dzopix** [comment]
> [Release.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11273510/Release.zip) how to use: 1)make sure you are on Dx11 (client settings->game -> Dx9 legacy is not checked) 2)go ingame 3)run the exe 4)use left-right arrow keys on ur keyboard to change skin (im too lazy to add menu lol)

whats this?

**Comment by dzopix** [comment]
> > > [Release.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11273510/Release.zip) how to use: 1)make sure you are on Dx11 (client settings->game -> Dx9 legacy is not checked) 2)go ingame 3)run the exe 4)use left-right arrow keys on ur keyboard to change skin (im too lazy to add menu lol)
> > 
> > 
> > whats this?
> 
> my skin changer

how can i know its not a scam xd im sceptic about this stuff but many people been using r3nzskin so i decided to do it too

**Comment by nnxs13** [comment]
> > > [Release.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11273510/Release.zip) how to use: 1)make sure you are on Dx11 (client settings->game -> Dx9 legacy is not checked) 2)go ingame 3)run the exe 4)use left-right arrow keys on ur keyboard to change skin (im too lazy to add menu lol)
> > 
> > 
> > whats this?
> 
> my skin changer

crazy shuriken brah

**Comment by dzopix** [comment]
aight it was trojan but i hope ur not trynna fk me up

**Comment by rainzee** [comment]
> Why doesn't 13.7 work with 13.8 patch? whats the difference i never understood why it has to be patched along the lol client

The skin change principle is done by modifying a specific address in the game's memory, after each version upgrade the address may be slightly different and we need to get the new address offset, it's that simple.

**Comment by Hecticism** [comment]
> aight it was trojan but i hope ur not trynna fk me up

its not lol and if u dont trust me run it on  a Virtual machine

**Comment by Hecticism** [comment]
> 



> i dont even know what virtual machine is bro but anyways it works, btw why cant u add menu from r3nzskin? wasnt there like code on the thing where we download? curious, its good like this either way thanks

i can but i dont have time i simply made this in a couple of hours for you guys to have

**Comment by dzopix** [comment]
ye ye, thanks mate, works pretty good, i just hold space and hold left or right arrow so my camera doesnt move - quick tip for anyone who decides to use it too :P thanks again

**Comment by m0rf1sadok** [comment]
> 13.8 Релиз смены скинов[.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11273510/Release.zip) как использовать: 1)убедитесь, что вы находитесь на Dx11 (настройки клиента->игра -> Dx9 legacy не отмечен) 2) Зайдите в игру 3) Запустите exe 4) Используйте клавиши со стрелками влево-вправо на клавиатуре, чтобы изменить скин (мне лень добавлять меню, лол)

this dll file causes the game to crash (directx 9 is turned off), tell me what to do?

**Comment by rainzee** [comment]
> > 
> 
> > i dont even know what virtual machine is bro but anyways it works, btw why cant u add menu from r3nzskin? wasnt there like code on the thing where we download? curious, its good like this either way thanks
> 
> i can but i dont have time i simply made this in a couple of hours for you guys to have

Can you open source?

**Comment by NOBODYLOVED** [comment]
@Hecticism Like ye bro, could you please make it open source? I don't think you are scamming like other ppl in other threads but for learning and safety. ^^

**Comment by Nineta1es** [comment]
@Hecticism cool but why the fkn swastika? stop being cringe

**Comment by hotline1337** [comment]
Do not promote or share any binaries in this repository.
