### ISSUE TITLE
New temporary skin changer (Use on your own risk) 

### ISSUE THREAD

**Issue by OkashiWantavi** [R3nzTheCodeGOD/R3nzSkin#404]
https://gofile.io/d/Imm8im

1. Open league

2. Go into a game & inject

3. insert to open & close

**Comment by saypppro** [comment]
virus

**Comment by OkashiWantavi** [comment]
> virus

No, its not. Try it out buddy lmfao

**Comment by erttispc** [comment]
joined github 30 mins ago ehh

**Comment by Portralitos** [comment]
https://www.virustotal.com/gui/file/07e46b21afc4ab1bef8fc293db0daf6a5440c59584617b52c1c348d6e83655b3
its a HEAVY virus

**Comment by Nineta1es** [comment]
Can u stop calling virus everytime ? Anything that's an injection is a virus to an antivirus or Windows. The original skin changer by R3nz was also flagged as a virus but it's not

**Comment by Portralitos** [comment]
> Can u stop calling virus everytime ? Anything that's an injection is a virus to an antivirus or Windows. The original skin changer by R3nz was also flagged as a virus but it's not

ok, but did you use it?

**Comment by Abedbaydoun** [comment]
> @Portralitos the skin changer from @OkashiWantavi ? no i don't use it. better safe than sorry. I'm using this one. btw if anyone knows how to remove the swastika that'd be nice [#403 (comment)](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/403#issuecomment-1514728123)

Bro its not working for me when i enter game i click on the release and it just disappears and my webcam was on for some reason

**Comment by hotline1337** [comment]
Do not promote or share any binaries in this repository.
