### ISSUE TITLE
New Discord Server

### ISSUE THREAD

**Issue by Azagarialol** [R3nzTheCodeGOD/R3nzSkin#405]
our server provides best support, removes @everyone/@here pings, we have faq and information on how to install certain changers. people also send the changers.

https://discord.gg/QhSsahfR
https://discord.gg/QhSsahfR

**Comment by Snob345** [comment]
I like this post because now I know how to use skin changer and I have no intensions of harming myself!!#!#!.

**Comment by hotline1337** [comment]
Do not promote or share any binaries in this repository.
