### ISSUE TITLE
Why can't we discuss alternative skin changers here?

### ISSUE THREAD

**Issue by Nineta1es** [R3nzTheCodeGOD/R3nzSkin#406]
I keep seeing this guy cockblock us of any alternative as if there's a better place to ask for it

**Comment by hkthomas** [comment]
No one is stopping you from using it, even if there is no guarantee that its source is legitimate.

**Comment by Nineta1es** [comment]
? All skin changers that aren’t the original R3nz app are getting removed. So yes there is someone stopping us

**Comment by Hecticism** [comment]
ye they removed my super epic swastika skinchanger

**Comment by hotline1337** [comment]
Issues are not a discussion board, do not open the issues if they are not related to bug reporting or feature requesting.
