### ISSUE TITLE
Does not show Elise's Spider form Skin (Withered Rose New Skin)

### ISSUE THREAD

**Issue by Th3Nigh7mare** [R3nzTheCodeGOD/R3nzSkin#41]
![12](https://user-images.githubusercontent.com/66384195/148138128-1c6e011b-9f12-4475-99ca-0d89024d8a39.PNG)
This is the skin of the spider form should be shown as in the next image that I will attach.
![elisespider](https://user-images.githubusercontent.com/66384195/148138164-0b8cb4fb-fe14-40d0-abf1-577ee510d979.png)

**Comment by R3nzTheCodeGOD** [comment]
Same problem with the nidale's tiger not being seen. I don't think I can fix it
