### ISSUE TITLE
 R4Skin Skinchanger 13.8 

### ISSUE THREAD

**Issue by Galactaknit** [R3nzTheCodeGOD/R3nzSkin#410]
-redacted-

**Comment by nsthanh1307** [comment]
it's worked! Tks bro

**Comment by harleyxu-xhl** [comment]
does't work

**Comment by Galactaknit** [comment]
it work for me

**Comment by z2wHkaa** [comment]
it doesn't work for CH version

**Comment by Hentai-yukino** [comment]
Thank you, it works on JP too

**Comment by tuanhobbit123** [comment]
> it's worked! Tks bro

dùng thế nào bro, chỉ tôi với

**Comment by 5kitu** [comment]
Nice. Thanks for share.

**Comment by nsthanh1307** [comment]
Duplicate of #

> > it's worked! Tks bro
> 
> dùng thế nào bro, chỉ tôi với

Tải về rồi chép file đó vào thư mục game trong thư mục lol là được bro

**Comment by HimuL-Phsam** [comment]
That's good, TW can use.I hope it won't be deleted

**Comment by Galactaknit** [comment]
To use it drag into

**Comment by Zaghi1107** [comment]
> found this, it work on EUW
> 
> https://mega.nz/file/EVNT2CiI#Ks8UssdSD3AuMtqC2jPJLDaRKyC2Yo4oaxokPq0JE1k

it works for me thx bro (im on eune)

**Comment by danivagyoksia** [comment]
thanks man!

**Comment by danivagyoksia** [comment]
> C:\Riot Games\League of Legends\Game




> how to use it bro

**Comment by tuanhobbit123** [comment]
> Duplicate of #
> 
> > > it's worked! Tks bro
> > 
> > 
> > dùng thế nào bro, chỉ tôi với
> 
> Tải về rồi chép file đó vào thư mục game trong thư mục lol là được bro

có thể ib chỉ mình được ko, mình chép vào thư mục game rồi nma ko thấy hiện skin, https://www.facebook.com/minhh.tuann.00/

**Comment by tuanhobbit123** [comment]
> > found this, it work on EUW
> > https://mega.nz/file/EVNT2CiI#Ks8UssdSD3AuMtqC2jPJLDaRKyC2Yo4oaxokPq0JE1k
> 
> how to use it bro

place it on Game and press Insert

**Comment by pjapoduck** [comment]
It works on LAS!! <333 thxxx

**Comment by GolloChad** [comment]
work on LAN thanks!!

**Comment by GolloChad** [comment]
they put a micro
 patch and it stopped working

**Comment by veenx** [comment]
crashes the game rn

**Comment by quangchung2002** [comment]
Can't connect to the match

**Comment by ezJosque** [comment]
new update game :/

**Comment by suxcess-1337** [comment]
not worked update game :(

**Comment by hotline1337** [comment]
Do not promote or share any binaries in this repository.
