### ISSUE TITLE
R3nz skinchager crashing newest update

### ISSUE THREAD

**Issue by Abujas** [R3nzTheCodeGOD/R3nzSkin#416]
I downloaded the logitechled.dll, therefore yesterday it was working but today it started to crash, any idea why?

**Comment by Abujas** [comment]
https://ufile.io/8msnyhi0
Sorry for the link. i hope its okay :D

**Comment by Abujas** [comment]
just tell me if its working or not.

**Comment by maciekxpp** [comment]
nah its crashing for me too :/ we have to wait for the new update to be posted

**Comment by Abujas** [comment]
thanks, at least i know that im not the only one lol

**Comment by scrapz24** [comment]
yeah it's crashing my game too

**Comment by Abujas** [comment]
Update: My game keeps crashing even without skinchanger, which is weird.
guess rito is just stupid to code their game correctly

**Comment by scrapz24** [comment]
> Update: My game keeps crashing even without skinchanger, which is weird. guess rito is just stupid to code their game correctly

Have you deleted the dll file from game folder? 

I had this problem too, I fixed it by downloading hextech repair tool and choosing force repatch. If it still doesn't work then try again and choose clean reinstall.

**Comment by Abujas** [comment]
yea i alr deleted it, i forgot to do it. thanks for the advice.
