### ISSUE TITLE
请更新13.8

### ISSUE THREAD

**Issue by SuShuiNB** [R3nzTheCodeGOD/R3nzSkin#417]
我们可以赞助作者，请求更新

**Comment by Jejfn** [comment]
> 我们可以赞助作者，请求更新

there is new version https://wwi.lanzoup.com/b01em26zg
password is edbp

**Comment by maciekxpp** [comment]
can u tell how to make it work?

**Comment by Abujas** [comment]
there is a password right as you enter at the website.

**Comment by collenns** [comment]
vt results https://www.virustotal.com/gui/file/d0ce64f0f4c7c2bcf9740e954427f7e007c98ca1bc6f4c0900bd445ffc23fd53

**Comment by Abujas** [comment]
game keeps crashing efter i launched it. so virus it is.
