### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by krukuhehe** [R3nzTheCodeGOD/R3nzSkin#42]
It used to work fine but a few days ago, when it got injected it crashed. it's not a immediate crash anyways. After the loading screen, when the game begins, it crashes. I also tried injecting in game after the loading screen, it also crashed. I also use Garena, so maybe a seperate version of garena?

**Comment by yxngh** [comment]
Game got updated, thats reason of crashes

**Comment by InnovationFlash** [comment]
> 

So do you find a new version which can work, dude

**Comment by eucascada** [comment]
update plz

**Comment by R3nzTheCodeGOD** [comment]
If you send me the dumped file of the Garena server I can update it.

**Comment by krukuhehe** [comment]
It works already!
