### ISSUE TITLE
Heres the dll guys have fun i found it and it works zero crashes and i think zero frames drops have fun again:))

### ISSUE THREAD

**Issue by TheonlyJok3r** [R3nzTheCodeGOD/R3nzSkin#420]
redacted

**Comment by LeTrukinutil** [comment]
SEEMS TO BE A TROJAN 5.6 MB

**Comment by LeTrukinutil** [comment]
nvm seems to work fine...

**Comment by LeTrukinutil** [comment]
still a bit laggy tho

**Comment by collenns** [comment]
the site is not opening

**Comment by maciekxpp** [comment]
how do i use it?

**Comment by Abujas** [comment]
Works Fine. Aprooving

**Comment by Abujas** [comment]
i dont have any fps drops.
it seems to work really fine. Again thanks for ur work

**Comment by maciekxpp** [comment]
put ddl in game folder?

**Comment by collenns** [comment]
site says Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.

**Comment by maciekxpp** [comment]
> > there is no need to use any injector?
> 
> nope i think so but just start the game and press insert to see if it works if not then i do not know sorry hehe im not that smart with these kind of things

its not working for me maybe this isnt working on euw

**Comment by GuiSaiUwU** [comment]
> > site says Dangerous File Blocked
> > 
> > The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.
> 
> I don't know why it says that tbh it's not actually a virus or anything it's just a DLL nothing more then that 

Its pretty common media fire blocking any third party software or dll, happen to me a lot with .exe files made with python

**Comment by maciekxpp** [comment]
> > > > > > there is no need to use any injector?
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > nope i think so but just start the game and press insert to see if it works if not then i do not know sorry hehe im not that smart with these kind of things
> > > > 
> > > > 
> > > > its not working for me maybe this isnt working on euw
> > > 
> > > 
> > > I don't know then, I think I am on eune that's maybe why it works don't know then.
> > 
> > 
> > unlucky thanks anyway
> 
> did u put it in the right folder?

C:\Riot Games\League of Legends\Game

**Comment by FishB0nes98** [comment]
yep, thats the correct one, then idk sorry :(

**Comment by maciekxpp** [comment]
> yep, thats the correct one, then idk sorry :(

idk too i logged on my eune acc and it still dosent work i might try reinstall lol

**Comment by scrimrist** [comment]
https://www.virustotal.com/gui/file/e6242e92688937e653f727217867a0cbf1b05bb0d3755866b945891c085ae26d

THAT TROJAN, so sad

**Comment by 14fedora** [comment]
a lot of fps drops any solutions?
