### ISSUE TITLE
Hi again this is the updated version that i found on my other pc that i first downloaded it on but i get fps drops on my  main pc sadly 

### ISSUE THREAD

**Issue by TheonlyJok3r** [R3nzTheCodeGOD/R3nzSkin#422]
redacted

**Comment by xxade2q** [comment]
TROJAN

**Comment by maciekxpp** [comment]
https://www.virustotal.com/gui/url/dd7e86c4431270d3f379803041766649447824eca44024fcf906e55ede819b24?nocache=1

virus scan ^

**Comment by maciekxpp** [comment]
> 

this isnt trojan atleast ill give it a try 
maybe this one will work

**Comment by maciekxpp** [comment]
yes! finnaly it works ty so much

**Comment by 14fedora** [comment]
> yes! finnaly it works ty so much

still lags

**Comment by maciekxpp** [comment]
> > yes! finnaly it works ty so much
> 
> still lags

not for me tho

**Comment by dopamine00** [comment]
still laging

**Comment by LeTrukinutil** [comment]
APPARENTLY fps drops came from mouse refresh rate

**Comment by nickxpremium** [comment]
WORKS FOR MEEE

**Comment by sugiharaxo** [comment]
> https://www.virustotal.com/gui/url/dd7e86c4431270d3f379803041766649447824eca44024fcf906e55ede819b24?nocache=1
> 
> virus scan ^

This is not the correct scan, seems like you are trying to lie about something. don't donwload it
This is the real scan
https://www.virustotal.com/gui/file/07487eca043a9e4a544db9c492de5d5b801235fe8928b2a7022e152d068ce4eb
