### ISSUE TITLE
fps drops

### ISSUE THREAD

**Issue by 14fedora** [R3nzTheCodeGOD/R3nzSkin#424]
i think i found a solution,you have to reduce you mouse refresh rate from its program but idk if that gonna impact your gameplay i just tried it

**Comment by flagzy77** [comment]
i downloaded the modskin yesterday but today when i launch a game i crash down. How can i find a solution ?

**Comment by LeTrukinutil** [comment]
> i think i found a solution,you have to reduce you mouse refresh rate from its program but idk if that gonna impact your gameplay i just tried it

HOW JUST TELL ME HOW

**Comment by nsthanh1307** [comment]
> i downloaded the modskin yesterday but today when i launch a game i crash down. How can i find a solution ?

just delete dll file you copy to Game folder

**Comment by 14fedora** [comment]
> i downloaded the modskin yesterday but today when i launch a game i crash down. How can i find a solution ?

idk know about that sorry

**Comment by xiao-baia** [comment]
> i think i found a solution,you have to reduce you mouse refresh rate from its program but idk if that gonna impact your gameplay i just tried it

How to adjust mouse refresh rate in a program?
