### ISSUE TITLE
Solution Drop FPS

### ISSUE THREAD

**Issue by scrimrist** [R3nzTheCodeGOD/R3nzSkin#427]
hanging the frequency rate from 1000hz to 500hz was able to fix the error

**Comment by dopamine00** [comment]
doesnt work for me

**Comment by LeTrukinutil** [comment]
It works perfectly just make sure by testing on a specialized website that u are under 500hz

**Comment by Asujdau** [comment]
Can you upload a working version of the skin changer?

**Comment by Edassap** [comment]
> doesnt work for me

doesn't work for me too

**Comment by Saber1u** [comment]
perfectly worked for me！i use dll that someone upload.

**Comment by lakinjo-1** [comment]
how do u do that

**Comment by Saber1u** [comment]
> how do u do that

DL G HUB, if u use logitech mouse
