### ISSUE TITLE
Unable to reconnect for a whole game

### ISSUE THREAD

**Issue by VJanabia** [R3nzTheCodeGOD/R3nzSkin#43]
at japan servers

**Comment by yxngh** [comment]
not updated yet

**Comment by pmetpmetpmet** [comment]
That will never get fixed cause JP servers suck. If you have AHK in the background it will do the same thing. Programs that work in other regions will fail on the JP servers. It's the region's anti cheat probably.

**Comment by R3nzTheCodeGOD** [comment]
send me dumped game file of japan server

**Comment by VJanabia** [comment]
> send me dumped game file of japan server

I don't know how to do it

**Comment by VJanabia** [comment]
> send me dumped game file of japan server
[GameLogs.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/8010321/GameLogs.zip)
this is my gamelogs

**Comment by R3nzTheCodeGOD** [comment]
[this](https://www.unknowncheats.me/forum/league-of-legends/320116-dump-lol-addresses-guide.html) guide will help you

**Comment by VJanabia** [comment]
ty
