### ISSUE TITLE
Is there a new update guys? after the mini patch riot did?

### ISSUE THREAD

**Issue by ilikeleaguesomuch1234** [R3nzTheCodeGOD/R3nzSkin#430]

**Comment by alphaaced** [comment]
> 

https://discord.gg/leagueplus
This server contains the new updated safe tools.

**Comment by 14fedora** [comment]
> > 
> 
> https://discord.gg/leagueplus This server contains the new updated safe tools.

should we trust this guy?

**Comment by alphaaced** [comment]
> > > 
> > 
> > https://discord.gg/leagueplus This server contains the new updated safe tools.
> 
> should we trust this guy?
> 

you can join and see for yourself.

**Comment by Saify7** [comment]
invite doesnt work

**Comment by alphaaced** [comment]
> invite doesnt work 

https://discord.gg/leagueplus
