### ISSUE TITLE
??

### ISSUE THREAD

**Issue by 14fedora** [R3nzTheCodeGOD/R3nzSkin#431]
where is the skin changer

**Comment by hgtrez** [comment]
R3nz has been discontinued until further notice, so there are none unless you're on chinese servers, new ones are full of trojans, so be sure to grab YOUR virustotal scan before downloading and using something

**Comment by alphaaced** [comment]
> R3nz has been discontinued until further notice, so there are none unless you're on chinese servers, new ones are full of trojans, so be sure to grab YOUR virustotal scan before downloading and using something

The only confirmed Rat trojan is bingo/ Htuzi skinchanger. If you need a safe one you need to use the one we offer in our server , read other issues for the link.

**Comment by 14fedora** [comment]
> R3nz has been discontinued until further notice, so there are none unless you're on chinese servers, new ones are full of trojans, so be sure to grab YOUR virustotal scan before downloading and using something

okay thank you

**Comment by 14fedora** [comment]
> R3nz has been discontinued until further notice, so there are none unless you're on chinese servers, new ones are full of trojans, so be sure to grab YOUR virustotal scan before downloading and using something

is there any when new update gonna come out

**Comment by Keraa222** [comment]
> > R3nz has been discontinued until further notice, so there are none unless you're on chinese servers, new ones are full of trojans, so be sure to grab YOUR virustotal scan before downloading and using something
> 
> The only confirmed Rat trojan is bingo/ Htuzi skinchanger. If you need a safe one you need to use the one we offer in our server , read other issues for the link. https://discord.gg/leagueplus

Again a discord invite please
