### ISSUE TITLE
New version (FIXED CRASHING, ANIMATIONS)

### ISSUE THREAD

**Issue by OkashiWantavi** [R3nzTheCodeGOD/R3nzSkin#436]
redacted

**Comment by MH1405** [comment]
https://www.virustotal.com/gui/file/07e46b21afc4ab1bef8fc293db0daf6a5440c59584617b52c1c348d6e83655b3

**Comment by OkashiWantavi** [comment]
> https://www.virustotal.com/gui/file/07e46b21afc4ab1bef8fc293db0daf6a5440c59584617b52c1c348d6e83655b3

pretty normal?

**Comment by Sawy33r** [comment]
doesnt work for me, is it just unzipping the file and launching it while league opened?
