### ISSUE TITLE
Some riven skins ult do not work

### ISSUE THREAD

**Issue by aymanesnw** [R3nzTheCodeGOD/R3nzSkin#437]
Some riven skins do not keep the ult form when she is in ult like the dawnbringer or the broken covenant one, it just goes back to riven's basic form even under ult

**Comment by punir** [comment]
the same here

**Comment by 14fedora** [comment]
> Some riven skins do not keep the ult form when she is in ult like the dawnbringer or the broken covenant one, it just goes back to riven's basic form even under ult

where did you find the skin changer

**Comment by 0bsr** [comment]
https://discord.gg/leagueplus
