### ISSUE TITLE
Injector 

### ISSUE THREAD

**Issue by SeyDow** [R3nzTheCodeGOD/R3nzSkin#440]
Hello, 

When i click start the R3nzSkin injector, - The injector status : Working
                                                                - League Client Status : Found
                                                                - LeagueGame Status : Found
                                                                - R3nzSkin Status : Not injected 

Someone can help me to understand why the injector won't work :( ?

**Comment by Galactaknit** [comment]
> Hello,
> 
> When i click start the R3nzSkin injector, - The injector status : Working - League Client Status : Found - LeagueGame Status : Found - R3nzSkin Status : Not injected
> 
> Someone can help me to understand why the injector won't work :( ?

not updated

**Comment by 0bsr** [comment]
https://discord.gg/leagueplus check here, 2 versions that work

**Comment by LeBlanCXYX** [comment]
Hello,I meet the same problem,have you solved it?
