### ISSUE TITLE
Update R3nzSkin from x86 to x64

### ISSUE THREAD

**Issue by R3nzTheCodeGOD** [R3nzTheCodeGOD/R3nzSkin#442]
To-do list:

- [x] Add x64 configuration to the project
- [x] Make the pattern scanning function x64 compatible
- [x] Update the patterns
- [x] Update the offsets
- [x] Update the game structures
- [x] Remove x86retspoof from the project and call its functions without ret spoof
- [x] Update the injector
- [x] Remove the solution 9928813a0f6df66e232a1d8501a15ff3c7f99b2c from the project. -> `Note: if the character's model is reset after death, it means the skinId pattern is broken`.

**Comment by Souplax1** [comment]
you are back ?

**Comment by Xiao3314** [comment]
Can you also update the new version of x86,it's drop fps and no one fix it.THX from Chinese guys

**Comment by 9qlys** [comment]
hoş geldin kral iMac içinde yaparsan sevinirim

**Comment by xnrheh** [comment]
HOLYYYYYY, R3NZ IS BACK

WELCOME BACK!

**Comment by fpy030205** [comment]
welcome ！！！！！！！！！！！！！so  excited i am！！！

**Comment by yangtaoer** [comment]
wait u for so long time! welcome

**Comment by harleyxu-xhl** [comment]
The God is  COMNG BACK! Could you please continue to update x86 architecture? since the LOL CN server is still x86. Thanks!

**Comment by LLTTYY1** [comment]
Welcome back !!!

**Comment by nopde** [comment]
welcome back mate!

**Comment by DUC1233** [comment]
welcome backkkk

**Comment by Lorddrak69** [comment]
king is back

**Comment by Sapphire-e** [comment]
I couldn't see better news. Welcome back man, and hope your ramadan, Eid and military service went very well 🙏

**Comment by Capo1337** [comment]
can anybody assemble this because i dont know how to update it

**Comment by NOBODYLOVED** [comment]
Wow, amazing work. Waiting for compilled version.

**Comment by R3nzTheCodeGOD** [comment]
### I made a quick update. I tested it on the training mode on TR server, and everything seems to be working fine.

![image](https://user-images.githubusercontent.com/58574988/234407031-12021769-df86-4bdc-8f5b-2f5f4ef3a3c9.png)

**Comment by lesingebleu** [comment]
It's working. Welcome back, mate.

**Comment by changxingduomeyaoyan** [comment]
thanks for all your work to skin changer, by the way, could you help to update CN server's dll? We are suffering that we can't use new skin changer!

**Comment by xiaokonglongya** [comment]
welcome back and hope everything goes well with you。

**Comment by thegizobizo** [comment]
Thankyou VERY MUCH!!! welcome back brother!

**Comment by icode0698** [comment]
Thank you for your effort. It's exciting. Welcome back

**Comment by good-ideal** [comment]
good！

**Comment by pjapoduck** [comment]
Love u god

**Comment by x1207349263** [comment]
THX! Ur a real hero!

**Comment by rainzee** [comment]
> thanks for all your work to skin changer, by the way, could you help to update CN server's dll? We are suffering that we can't use new skin changer!

我尝试在DC上跟他联系一下吧，之前就是我跟他一起做的国服，但是现在国服的架构还是86，维护两个架构是有点困难的，

**Comment by gptCN** [comment]
Thank you for all the work you have done for the skincare machine. Can you help update the DLL of the CN server? We are experiencing the pain of not being able to use a new skincare device!

**Comment by Weltolk** [comment]
> > thanks for all your work to skin changer, by the way, could you help to update CN server's dll? We are suffering that we can't use new skin changer!
> 
> 我尝试在DC上跟他联系一下吧，之前就是我跟他一起做的国服，但是现在国服的架构还是86，维护两个架构是有点困难的，

或许可以临时fork一个版本，以后国服升级到x64架构时就archive掉

**Comment by wyhtt** [comment]
> > thanks for all your work to skin changer, by the way, could you help to update CN server's dll? We are suffering that we can't use new skin changer!
> 
> 我尝试在DC上跟他联系一下吧，之前就是我跟他一起做的国服，但是现在国服的架构还是86，维护两个架构是有点困难的，

辛苦老哥了，国服一直用不了呜呜呜

**Comment by wyhtt** [comment]
> > thanks for all your work to skin changer, by the way, could you help to update CN server's dll? We are suffering that we can't use new skin changer!
> 
> 我尝试在DC上跟他联系一下吧，之前就是我跟他一起做的国服，但是现在国服的架构还是86，维护两个架构是有点困难的，

辛苦老哥了，国服13.8之后用不了最新的r3版本。之前版本是一直掉帧

**Comment by wyhtt** [comment]
please help cn server,13.8 version can't  use r3,thanks!

**Comment by wyhtt** [comment]
Thank you for all the work you have done for the skincare machine. Can you help update the DLL of the CN server? We are experiencing the pain of not being able to use a new skincare device!

**Comment by wyhtt** [comment]
&nbsp;Thank you, my god. When I saw this news, I was extremely excited and excited. When I come home from work, I will definitely try the new version of R3 first. Please allow me to express my gratitude on behalf of all the players who love R3 on CN servers!!!








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R3nzTheCodeGOD/R3nzSkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 凌晨2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R3nzTheCodeGOD/R3nzSkin] Update R3nzSkin from x86 to x64 (Issue #442)





 
Closed #442 as completed.

**Comment by wyhtt** [comment]
My god, I downloaded the latest version 13.9 after work tonight, but I still cannot change skin on the CN server. If you have time, you can try to fix it as much as possible. Thank you, my god





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R3nzTheCodeGOD/R3nzSkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 凌晨2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R3nzTheCodeGOD/R3nzSkin] Update R3nzSkin from x86 to x64 (Issue #442)





 
Closed #442 as completed.

**Comment by gptCN** [comment]
Hello, the author's Chinese server is currently unable to use due to severe or ineffective frame dropout. Can we maintain it for the Chinese server? If it is well maintained, I hope you can download the instructions on your homepage. Thank you

**Comment by wyhtt** [comment]
My god, I don't quite understand what it means, but it's okay. I'll wait for you to fix the Chinese server, and I'll always be waiting for you. If there's anything I can help with, you can let me know, and I'll cooperate fully to fix it. We R3 Chinese players will be waiting for you! Also, I am not very sure how to download the instructions on the homepage





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R3nzTheCodeGOD/R3nzSkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R3nzTheCodeGOD/R3nzSkin] Update R3nzSkin from x86 to x64 (Issue #442)





 
Hello, the author's Chinese server is currently unable to use due to severe or ineffective frame dropout. Can we maintain it for the Chinese server? If it is well maintained, I hope you can download the instructions on your homepage. Thank you
