### ISSUE TITLE
What is the hotkey to change skins?

### ISSUE THREAD

**Issue by Ali229** [R3nzTheCodeGOD/R3nzSkin#445]
Thanks for the x64 update things are working fine now :).
How to change skins using hotkeys? Where do I designate a hotkey? I've searched everywhere in readme and issues as well can't find the answers.

**Comment by slowloriss** [comment]
Form menu choice Extras->Quick Skin Change
then you can use Page Up&Page Down change it

**Comment by Ali229** [comment]
Thanks for the info
