### ISSUE TITLE
Is it useful for China?

### ISSUE THREAD

**Issue by Zcaic** [R3nzTheCodeGOD/R3nzSkin#448]

**Comment by LLTTYY1** [comment]
I download the file and replace the .dll in my game, but nothing happened.

**Comment by Xiao3314** [comment]
NO

**Comment by BNO1GLEAM** [comment]
NO，not work

**Comment by xiao-baia** [comment]
The speed of updating x64 on CN is slower than in other regions, so CN needs to be patient and wait

**Comment by BNO1GLEAM** [comment]
这是来自QQ邮箱的自动回复邮件。你好，邮件已收到。

**Comment by rainzee** [comment]
X64更新实施之后就不再能够在国服工作了，因为国服依旧是X86架构

**Comment by xiao-baia** [comment]
但是国服很快也会改为X86架构，因为国服更新速度慢，所以现在还是X64架构

**Comment by xiao-baia** [comment]
国服很快就会改为X64架构，因为国服更新慢，所以现在还是X86架构

**Comment by rainzee** [comment]
> 国服很快就会改为X64架构，因为国服更新慢，所以现在还是X86架构

据我所知不会很快，甚至会很久。

**Comment by NightNightDream** [comment]
> 

我想知道为啥国服不赶紧更新X64架构？

**Comment by NightNightDream** [comment]
> > 国服很快就会改为X64架构，因为国服更新慢，所以现在还是X86架构
> 
> 据我所知不会很快，甚至会很久。

为啥国服不更新X64架构呢？

**Comment by rainzee** [comment]
因为国服本身有大量的工具，例如WeGame等等，更新架构需要很多时间

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinese Anti-Cheat.

**Comment by xiao-baia** [comment]
> R3nzSkin doesn't support Chinese Anti-Cheat.

I am using it by hid.dll
