### ISSUE TITLE
Nothing is happening 

### ISSUE THREAD

**Issue by STROMAIN** [R3nzTheCodeGOD/R3nzSkin#449]
![Снимок экрана (1652)](https://user-images.githubusercontent.com/131904265/234655111-88420a54-f81d-4d14-b15c-3cd25abb62ee.png)

Injector status working 
everything else not found 
i have waited nothing is happening
does anyone know how i can inject the dll myself?

**Comment by hotline1337** [comment]
Launch the game and go play.
