### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by WraithTrouble** [R3nzTheCodeGOD/R3nzSkin#45]
Still Working in patch 12.2?

**Comment by JeppeX** [comment]
![image](https://user-images.githubusercontent.com/29777790/151213914-551f3b1b-2563-4a56-b9a0-8ba4c0f50bb3.png)
The injector tells that everything is okay but I cannot open the in-game interface by pressing insert.
Although I am playing on linux through wine so I would like if somebody on windows would test this.

**Comment by R3nzTheCodeGOD** [comment]
it should work

**Comment by AndersonVilela** [comment]
> ![image](https://user-images.githubusercontent.com/29777790/151213914-551f3b1b-2563-4a56-b9a0-8ba4c0f50bb3.png) O injetor informa que está tudo bem, mas não consigo abrir a interface do jogo pressionando inserir.
> 
> Mas vale ressaltar que estou jogando no Linux (através do Wine), então gostaria que alguém no Windows pudesse testar.

How did you get it to run on wine?

**Comment by JeppeX** [comment]
> > ![image](https://user-images.githubusercontent.com/29777790/151213914-551f3b1b-2563-4a56-b9a0-8ba4c0f50bb3.png) O injetor informa que está tudo bem, mas não consigo abrir a interface do jogo pressionando inserir.
> > Mas vale ressaltar que estou jogando no Linux (através do Wine), então gostaria que alguém no Windows pudesse testar.
> 
> How did you get it to run on wine?

By using Lutris. Here's a couple of links:
[instructions](https://leagueoflinux.gitlab.io/install/lutris/)
[lutis page](https://lutris.net/games/league-of-legends/)

totally not intoxicated at the moment

- [ ] task

**Comment by AndersonVilela** [comment]
> 
> 
> 
> By using Lutris. Here's a couple of links:
> 
> [instructions](https://leagueoflinux.gitlab.io/install/lutris/)

> 
> [lutis page](https://lutris.net/games/league-of-legends/)
> 
> 
> 
> totally not intoxicated at the moment
> 
> 
> 
> - [ ] task

I'm referring to the mod skin

**Comment by JeppeX** [comment]
> > By using Lutris. Here's a couple of links:
> > [instructions](https://leagueoflinux.gitlab.io/install/lutris/)
> 
> > [lutis page](https://lutris.net/games/league-of-legends/)
> > totally not intoxicated at the moment
> > 
> > * [ ]  task
> 
> I'm referring to the mod skin

In lutris:
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/29777790/6271a1df-f533-48ce-9ad5-9ca299043f58)

**Comment by helioLJ** [comment]
> By using Lutris. Here's a couple of links:

I get this error when I try to run the R3nzSkin_Injector.exe

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/42224962/40f5766b-cfdd-47a7-b91f-c377effcf717)

**Comment by AndersonVilela** [comment]
I'm having this same mistake
