### ISSUE TITLE
Mythmaker Irelia has base voicelines

### ISSUE THREAD

**Issue by F1rePowered** [R3nzTheCodeGOD/R3nzSkin#456]
Mythmaker Irelia has base voicelines despite being a legendary skin, it would be nice to see it fixed if it's possible, could be a wrong address/offset or something I highly doubt it's due to voicelines being pushed serverside. Thanks for all the effort that goes into making this!
It also would be nice to see the vfx on Project Vayne's helmet, probably a ctrl+5 issue, but also could be a serverside pushed effect, I'm really not sure about that one.

**Comment by rainzee** [comment]
There are a lot of skins with effects, assets, and voices that are controlled on the server side, with server-delivered events that can't be helped locally.

**Comment by diyooor** [comment]
#1
