### ISSUE TITLE
Crash offset issue

### ISSUE THREAD

**Issue by ghost** [R3nzTheCodeGOD/R3nzSkin#459]
Can someone tell me if the offset fix tutorial still has the crash issues ? I want to fix the riven ult bugs since it is quite misleading during games, and idk if it worth it or not since on the pinned tutorial says it makes the game crash and is unplayable. Any help is appreciated, thanks.

**Comment by slowloriss** [comment]
I think just opcode got change.
It's makes not work properly in ARAM mode.
We'll need update memorry.hpp
