### ISSUE TITLE
can u please address that the fileof the skin changer comes up as 4 different viruses in virustotal.com

### ISSUE THREAD

**Issue by meatydangle** [R3nzTheCodeGOD/R3nzSkin#46]
can u explain if its a false positive or what its about please and ty
used the program for a while since malwarebytes  didnt opick it up but windows antivirus did so it scared me and then i went to virsutotal and saw that and deleted it out of fear
really love the program just would like an explanation

**Comment by R3nzTheCodeGOD** [comment]
The only explanation I will make is
# BRUHH
