### ISSUE TITLE
Failed to find pattern: 8D 8E ? ? ? ? FF 74 24 4C 

### ISSUE THREAD

**Issue by Roooockstar** [R3nzTheCodeGOD/R3nzSkin#464]
![image](https://user-images.githubusercontent.com/98254188/235857338-2ebcec58-1414-4030-bbee-651a4b91c045.png)

What is should do

**Comment by AszNo1** [comment]
me too

**Comment by nsthanh1307** [comment]
> ![image](https://user-images.githubusercontent.com/98254188/235857338-2ebcec58-1414-4030-bbee-651a4b91c045.png)
> 
> What is should do

Because it only work on 13.8

**Comment by ugurkesk** [comment]
bı kac gune gunceller admın

**Comment by meeezaezaa** [comment]
thank god i thought i was the issue plz somebody tell me when 13.9 is live

**Comment by meeezaezaa** [comment]
so they update their apps right?

**Comment by burakender** [comment]
can you find 13.9 update?

**Comment by hollatheray** [comment]
Still waiting 13.9

**Comment by i4TsU** [comment]
> ![image](https://user-images.githubusercontent.com/98254188/235857338-2ebcec58-1414-4030-bbee-651a4b91c045.png)
> 
> What is should do

when was the last time you built the .dll ? that looks like a pattern from before x64 update lmao

there is a sig that needs updating for 13.9, though not the one in your screenshot - try changing MaterialRegistry::D3DDevice from "48 8D 8D ? ? ? ? 48 03 CB E8" to **"48 8B 8F ? ? ? ? BA 37 00 00"**

**Comment by meeezaezaa** [comment]
if you guys find the nenw patch plz let us know

**Comment by xDaffy** [comment]
> > ![image](https://user-images.githubusercontent.com/98254188/235857338-2ebcec58-1414-4030-bbee-651a4b91c045.png)
> > What is should do
> 
> when was the last time you built the .dll ? that looks like a pattern from before x64 update lmao
> 
> there is a sig that needs updating for 13.9, though not the one in your screenshot - try changing MaterialRegistry::D3DDevice from "48 8D 8D ? ? ? ? 48 03 CB E8" to **"48 8B 8F ? ? ? ? BA 37 00 00"**

Working!

**Comment by trunghm88888** [comment]
> 

Thanks. Could you also share how to get the new patterns? Would really appreciate that!

**Comment by Siden-0** [comment]
> > > ![image](https://user-images.githubusercontent.com/98254188/235857338-2ebcec58-1414-4030-bbee-651a4b91c045.png)
> > > What is should do
> > 
> > 
> > when was the last time you built the .dll ? that looks like a pattern from before x64 update lmao
> > there is a sig that needs updating for 13.9, though not the one in your screenshot - try changing MaterialRegistry::D3DDevice from "48 8D 8D ? ? ? ? 48 03 CB E8" to **"48 8B 8F ? ? ? ? BA 37 00 00"**
> 
> Working!

When I change the pattern to the one mentioned above it keeps injecting incompletely, any idea why this happens?

**Comment by KXJTN** [comment]
can someone show how to fix it please?

**Comment by R3nzTheCodeGOD** [comment]
The pattern shown in the image belongs to the x86 architecture.
