### ISSUE TITLE
where is 13.9

### ISSUE THREAD

**Issue by burakender** [R3nzTheCodeGOD/R3nzSkin#466]

**Comment by Awesomekda** [comment]
+

**Comment by xDaffy** [comment]
in memory.hpp
```
search for "48 8D 8D ? ? ? ? 48 03 CB E8"
moddify with "48 8B 8F ? ? ? ? BA 37 00 00"
at - offsets::MaterialRegistry::D3DDevice
```

**Comment by hvoyya** [comment]
in which application can I change that code?

**Comment by dzopix** [comment]
i dont even understand whats he talking about LOL

**Comment by Vincoz** [comment]
> in memory.hpp
> 
> ```
> search for "48 8D 8D ? ? ? ? 48 03 CB E8"
> moddify with "48 8B 8F ? ? ? ? BA 37 00 00"
> at - offsets::MaterialRegistry::D3DDevice
> ```

doesn't work, still can't find offset

**Comment by jaques1232** [comment]
This way doesn't work, the skin cant upload the status keeps going from injected to not injected and nothing appears in the game

**Comment by raskalc** [comment]
fix

**Comment by raskalc** [comment]
[13.9.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11384494/13.9.zip)
Fix fo 13.9

**Comment by synzxd** [comment]
> [13.9.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11384494/13.9.zip) Fix fo 13.9

does it work is it safe any1 can vouch?

**Comment by s21247** [comment]
i put it in game folder and scanner with virustotal seems legit but doesnt work

**Comment by zdaryss** [comment]
> [13.9.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11384494/13.9.zip) Fix fo 13.9
Bruv it doesnt work

**Comment by HOwTODie222** [comment]
is not working

**Comment by icikxyz** [comment]
> 

it does, open the folder where your injector is and delete the .dll which has it, and put the one from the 13.9 zip

**Comment by Vincoz** [comment]
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11384773/R3nzSkin.zip)

https://www.virustotal.com/gui/file/6247f71c5e5918c3c0af3a139e0c79794c5317fa53655b6fefc6c775a84a2309 (zip)

https://www.virustotal.com/gui/file/acdc86e56710b3734d3e935959d6b92d98e88bd091e39f690c16a84f1e22467e (dll inside), just replace this with the one in r3nz folder

**Comment by zdaryss** [comment]
Bro I downloaded R3nzskin.zip with that old dll I also replaced it with dll from 13.9 and it doesnt fucking work

**Comment by Keiha1** [comment]
can someone explain to me how to install it pls

**Comment by Dalideye** [comment]
> 有人可以向我解释如何安装它吗？

no installation required, just replace the dll file in the previous r3nz file

**Comment by scrimrist** [comment]
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11384773/R3nzSkin.zip)
> 
> https://www.virustotal.com/gui/file/6247f71c5e5918c3c0af3a139e0c79794c5317fa53655b6fefc6c775a84a2309 (zip)
> 
> https://www.virustotal.com/gui/file/acdc86e56710b3734d3e935959d6b92d98e88bd091e39f690c16a84f1e22467e (dll inside), just replace this with the one in r3nz folder

explain to me how to install it pls

**Comment by Papryczekk** [comment]
All you have to do is change one thing, and more specifically this one:
`{
			{
				"48 8B 8F ? ? ? ? BA 37 00 00" 
			}, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice
		},
`
It is changed offset with memory.hpp you can do it yourself or download a ready fix.
If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one.
[R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)

**Comment by Keiha1** [comment]
idk why i put the R3nzSkin.dll in my Riot Games > League of Legends > Game
(first time i touch a R3nz skin changer so idk if i have to do something other to install it)

**Comment by Papryczekk** [comment]
> idk why i put the R3nzSkin.dll in my Riot Games > League of Legends > Game (first time i touch a R3nz skin changer so idk if i have to do something other to install it)

You don't have to put it in Riot Games > League of Legends > Game

**Comment by Keiha1** [comment]
so where i have to put it

**Comment by ilikeleaguesomuch1234** [comment]
> > idk why i put the R3nzSkin.dll in my Riot Games > League of Legends > Game (first time i touch a R3nz skin changer so idk if i have to do something other to install it)
> 
> You don't have to put it in Riot Games > League of Legends > Game

how u edit it btw after u edit the memory hpp, i mean how u make the new dll file

**Comment by Papryczekk** [comment]
> > > idk why i put the R3nzSkin.dll in my Riot Games > League of Legends > Game (first time i touch a R3nz skin changer so idk if i have to do something other to install it)
> > 
> > 
> > You don't have to put it in Riot Games > League of Legends > Game
> 
> how u edit it btw after u edit the memory hpp, i mean how u make the new dll file

![xd](https://user-images.githubusercontent.com/123909104/235987744-5624880e-0d3d-4e06-ad66-b57c20a8d753.png)
By clicking this

**Comment by Papryczekk** [comment]
> so where i have to put it

Wherever you want

**Comment by Papryczekk** [comment]
> what are you using to modify it

visual studio

**Comment by ilikeleaguesomuch1234** [comment]
there is no build option for me tho when i right click it

**Comment by mainmansam** [comment]
Is it possible to use this skinchanger without the injector?

**Comment by Papryczekk** [comment]
> there is no build option for me tho when i right click it

So instead of playing around with it, maybe just download what I've shared

**Comment by Papryczekk** [comment]
> okay thank you i only download the .zip that us gave to me and nothing more did i have to dl something other ?

All you have to do is delete the previous .dll and replace it with a new one

**Comment by mainmansam** [comment]
how do i install this skinchanger? where do i have to put this dll file

**Comment by mainmansam** [comment]
where can i find this injector?

**Comment by Papryczekk** [comment]
> where can i find this injector?

In releases

**Comment by phamlebaoanh123** [comment]
> All you have to do is change one thing, and more specifically this one: `{ { "48 8B 8F ? ? ? ? BA 37 00 00" }, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice }, ` It is changed offset with memory.hpp you can do it yourself or download a ready fix. If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one. [R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)

but in ARAM it don't work

**Comment by aymanesnw** [comment]
> All you have to do is change one thing, and more specifically this one: `{ { "48 8B 8F ? ? ? ? BA 37 00 00" }, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice }, ` It is changed offset with memory.hpp you can do it yourself or download a ready fix. If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one. [R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)

Thanks boss, I hope there's no chinese guy mining his family's legacy on my pc tho.

**Comment by Papryczekk** [comment]
> > All you have to do is change one thing, and more specifically this one: `{ { "48 8B 8F ? ? ? ? BA 37 00 00" }, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice }, ` It is changed offset with memory.hpp you can do it yourself or download a ready fix. If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one. [R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)
> 
> Thanks boss, I hope there's no chinese guy mining his family's legacy on my pc tho.

You can do it yourself and the result will be the same, a ready-made solution is simply an addition

**Comment by Siden-0** [comment]
> > > All you have to do is change one thing, and more specifically this one: `{ { "48 8B 8F ? ? ? ? BA 37 00 00" }, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice }, ` It is changed offset with memory.hpp you can do it yourself or download a ready fix. If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one. [R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)
> > 
> > 
> > Thanks boss, I hope there's no chinese guy mining his family's legacy on my pc tho.
> 
> You can do it yourself and the result will be the same, a ready-made solution is simply an addition

Thanks for updating it, do you have any idea why it's not functioning on ARAM?

**Comment by Papryczekk** [comment]
> > > > All you have to do is change one thing, and more specifically this one: `{ { "48 8B 8F ? ? ? ? BA 37 00 00" }, false, true, false, 0, &offsets::MaterialRegistry::D3DDevice }, ` It is changed offset with memory.hpp you can do it yourself or download a ready fix. If you want to download a ready-made solution, all you have to do is delete the old .dll file and replace it with a new one. [R3nzSkinFix.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11385032/R3nzSkinFix.zip)
> > > 
> > > 
> > > Thanks boss, I hope there's no chinese guy mining his family's legacy on my pc tho.
> > 
> > 
> > You can do it yourself and the result will be the same, a ready-made solution is simply an addition
> 
> Thanks for updating it, do you have any idea why it's not functioning on ARAM?

Nah idk about aram

**Comment by R3nzTheCodeGOD** [comment]
1b757588e663bc3de5d36a21a116318c6fc004ce

**Comment by Dysterx** [comment]
bro iwant to know how to do this memory.hpp thing
