### ISSUE TITLE
China Server Not Injected

### ISSUE THREAD

**Issue by Yx-2** [R3nzTheCodeGOD/R3nzSkin#47]
# China server Not Injected
It happened recently, after testing https://github.com/nieatty/TrustedInjector Modified it can be successfully injected at the beginning of the game

**Comment by Clownsw** [comment]
> # 中国服务器未注入
> 最近发生的事情，经过测试https://github.com/nieatty/TrustedInjector修改后可以在游戏开始时成功注入

The Chinese server is protected by TP and cannot be injected by conventional injectors

**Comment by Yx-2** [comment]
![image](https://user-images.githubusercontent.com/97827402/151372807-91b61dd8-63d6-4f97-95e7-ab0241be18ba.png)
After a successful injection, the injector still does not detect its work.

**Comment by Yx-2** [comment]
[dll_ConsoleApplication1.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/7976338/dll_ConsoleApplication1.zip)
Use this injector to inject the Chinese version
## How to use it
- Rename the injected dll file to **one.dll** and place it in the injector's folder
- Run

**Comment by ShiedaYoung** [comment]
still cannot work

**Comment by Yx-2** [comment]
> still cannot work

I update the attachment in the comments.
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/47#issuecomment-1026517908
Now the injector works as expected

**Comment by ShiedaYoung** [comment]
> > still cannot work
> 
> I update the attachment in the comments. [#47 (comment)](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/47#issuecomment-1026517908) Now the injector works as expected

I mean the status is still “not rejected “ in my injector after using the code above. Where should I put them or how can I solve this problem?

**Comment by Yx-2** [comment]
> > > still cannot work
> > 
> > 
> > I update the attachment in the comments. [#47 (comment)](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/47#issuecomment-1026517908) Now the injector works as expected
> 
> I mean the status is still “not rejected “ in my injector after using the code above. Where should I put them or how can I solve this problem?




> The Chinese server is protected by TP and cannot be injected by conventional injectors

**Comment by 04255** [comment]
> 

Sir, can you share its source code?
I want to make an automatic injector instead of manually injecting it every time I start. Therefore, I need to know the injected code. Please

**Comment by ShiedaYoung** [comment]
Sorry sir, I am new here, and i have no idea which file I should send to you.
I don't have this file in my game folder.([dll_ConsoleApplication1.zip])
Just tech me please.

**Comment by KaSock** [comment]
寄
![image](https://user-images.githubusercontent.com/56071624/213187656-3bdc2d15-a877-4d0f-8e74-a512ce3311be.png)


> [dll_ConsoleApplication1.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/7992754/dll_ConsoleApplication1.zip) 使用此喷油器注入中文版
> 
> ## 如何使用它
> * 将注入的 dll 文件重命名为 **one.dll**并将其放在注入器的文件夹中
> * 跑
