### ISSUE TITLE
source for 13.9 version + copy of dll for clueless ppl

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#471]
https://github.com/i4TsU/R3nzSkin-13.9

fork of main branch, only change is to the sig for dx9 device that i posted earlier (just hurts my soul seeing all the dodgy dlls ppl r downloading). also uploaded a copy of the dll for those that are too lazy to build it or dont know how - just download the R3nzSkin.dll file and replace the .dll you use currently with this one

**Comment by dzopix** [comment]
how do i use this? i downloaded r3nzskin.dll only and put it into /game but it doesnt work - do i need to download everything or?

**Comment by dzopix** [comment]
also on main "r3nzskin" one it says "13.9" update so i guess they're updating it now regularly or?

**Comment by dzopix** [comment]
nevermind, the main one works too so i guess ill be using that but i still dont understand - when they said they will stop with the updates bcs the guy went on military duty, when random people were posting their own .dll files, i could just put that dll in /game and it would pop up, but with main one i have to open injector, click start and then wait for it to open in game - bcs when i put the .dll file from main one it didnt work
