### ISSUE TITLE
SUPER GALAXY RUMBLE Q AND R BUG

### ISSUE THREAD

**Issue by IAW2020** [R3nzTheCodeGOD/R3nzSkin#472]
super galaxy rumble's q ability flame is coming out from the right side and the r ability animation is not visible can you fix this

**Comment by IAW2020** [comment]
![image](https://user-images.githubusercontent.com/132498728/236019564-0106667d-f006-4d9d-85ce-e970274501d1.png)

**Comment by IAW2020** [comment]
![image](https://user-images.githubusercontent.com/132498728/236020121-ae007b7d-89b4-411f-8052-72e7815eec00.png)

**Comment by lanlanshuai** [comment]
+1

**Comment by pilusoyyo** [comment]
+1 :C

**Comment by diyooor** [comment]
#1
