### ISSUE TITLE
Failed To Find Pattern

### ISSUE THREAD

**Issue by wizvrdoh** [R3nzTheCodeGOD/R3nzSkin#473]
I just downloaded the newest version the one from 1 hour ago or smth like that and i get this in the match 

" Failed to find pattern: 48 8B 05 ? ? ? ? 45 33 E4 0F 57 C0 " 

and it alt tabs me permanently 

Please help me !

**Comment by phamlebaoanh123** [comment]
same here, are you play ARAM?

**Comment by wizvrdoh** [comment]
> same here, are you play ARAM?

Yeah i am in ARAM

**Comment by phamlebaoanh123** [comment]
I also play aram and r3nzskin doesn't work, seems at this lol patch it can only work on Summoner rift map

**Comment by wizvrdoh** [comment]
Uff... i really play just ARAM those days especially if i try to level up an account i dont know how to fix it i read the tutorial but it beats me

**Comment by LycheeClone** [comment]
Guys, the 13.9 patch has arrived. The program will not work until it is updated and as for the Alt + tab problem, go back to league of legends without saying ok to the error message, you won't get errors again until the match is over. You can return to the game by using Alt + tab or by clicking on the icon on the taskbar.

**Comment by LycheeClone** [comment]
Erdem Hocam selamün aleyküm.

Hocam askerlik göreviniz devam ediyor mu? Ediyorsa Allah kolaylık versin.

İbrahim Halil Demir

4 May 2023 Per 20:02 tarihinde Erdem Yılmaz ***@***.***> şunu
yazdı:

**Comment by R3nzTheCodeGOD** [comment]
> Erdem Hocam selamün aleyküm. Hocam askerlik göreviniz devam ediyor mu? 
> Ediyorsa Allah kolaylık versin. 
> İbrahim Halil Demir.

Ediyor, kuzey ırakda pençe kilit harekatında görevliyim.

**Comment by prtty6c** [comment]
How to fix it plss cause my version is updated, plss help me fix it
