### ISSUE TITLE
Pattern Problem in ARAM

### ISSUE THREAD

**Issue by phamlebaoanh123** [R3nzTheCodeGOD/R3nzSkin#474]
It's show "Failed to find pattern: 48 8B 05 ? ? ? ? 45 33 E4 0F 57 C0". The game continues normally but I can't back in Match screen, btw r3nz in Summoner rift map still work

**Comment by R3nzTheCodeGOD** [comment]
I'll look again tomorrow night

**Comment by AnasAbdulatif** [comment]
same problem

**Comment by AnasAbdulatif** [comment]
im intrested in this software 
maybe i can help u a little 
contact me if u have enough time

**Comment by Maooookai** [comment]
same problem

**Comment by R3nzTheCodeGOD** [comment]
should work now

**Comment by phamlebaoanh123** [comment]
> should work now

thank u <3, Sir
