### ISSUE TITLE
renzskin.dll detected as trojan by microsoft defender?

### ISSUE THREAD

**Issue by shijisan** [R3nzTheCodeGOD/R3nzSkin#475]
I noticed in task manager that everytime i run the renzskin.exe, vanguard usermode interface runs multiple instances and consumes 90% of my cpu. What does it mean?

![1](https://user-images.githubusercontent.com/115002067/236049778-8e40ef06-6bdb-49db-9f2b-ac74e620e287.PNG)
![0](https://user-images.githubusercontent.com/115002067/236049790-37b1da3c-d1c0-47cf-a49e-110566c33833.PNG)

**Comment by esdeathq** [comment]
every release seems to have some sort of virus rn

**Comment by phamlebaoanh123** [comment]
u can download sourcecode to check and build it yourself

**Comment by Legnatbird** [comment]
Retard issue of the month
