### ISSUE TITLE
How can I directly inject the dll into the game files without using the injector? 

### ISSUE THREAD

**Issue by mish20011** [R3nzTheCodeGOD/R3nzSkin#477]
the one made by tianya doesn't need an injector, I just added the logitech dll something to the game folder of league and it worked and what's better is it doesn't crash the game also, is there a workaround for this?

**Comment by bixrynn** [comment]
Yeah I second this. The injector does not work for me no matter how many times I've tried. I used the tianya version before and it worked fine. It's frustrating.

**Comment by SapoTurco** [comment]
> Yeah I second this. The injector does not work for me no matter how many times I've tried. I used the tianya version before and it worked fine. It's frustrating.

Where i can install the tianya's version?

**Comment by R3nzTheCodeGOD** [comment]
What are you talking about? Do you think tianya wrote a magic code? Rename the `R3nzSkin.dll` file to `LogitechLed.dll` and put it in the `Riot Games\League of Legends\Game` folder. let the game handle the rest, lol It will mistake the LogitechLed.dll file as its own dll file and inject it into the game.

But I don't recommend this method because you will get a chain ban wave when riot fixes this vulnerability.

**Comment by Yoezzz** [comment]
> What are you talking about? Do you think tianya wrote a magic code? Rename the `R3nzSkin.dll` file to `LogitechLed.dll` and put it in the `Riot Games\League of Legends\Game` folder. let the game handle the rest, lol It will mistake the LogitechLed.dll file as its own dll file and inject it into the game.
> 
> But I don't recommend this method because you will get a chain ban wave when riot fixes this vulnerability.

roit should have fixed this bug by now,because I tried it just now and it didn't work

**Comment by hotline1337** [comment]
Make a dll called `Hid.dll` in `Riot Games\League of Legends\Game `

**Comment by moyuduo** [comment]
> Make a dll called `Hid.dll` in `Riot Games\League of Legends\Game `

I have two computer this way in one computer works, but in another computer seems not work, some help will be appreciate
