### ISSUE TITLE
Inject .dll

### ISSUE THREAD

**Issue by MIKUZIKASHI** [R3nzTheCodeGOD/R3nzSkin#478]
Can u inject the .dll with another injector or u can only use it with the r3nzinjector?

**Comment by R3nzTheCodeGOD** [comment]
You can use any injector you want.

**Comment by MIKUZIKASHI** [comment]
i tried with 2 different injectors, they arent't working
i tried with "AlisaAlis Manual Map DLL Injector" and "CheatSquad Injector v2.1"
