### ISSUE TITLE
How to run R3 on a Chinese server

### ISSUE THREAD

**Issue by TieShuHua** [R3nzTheCodeGOD/R3nzSkin#486]
I would like to know how to run r3 on x86 in China

**Comment by bluefyren** [comment]
its when u build you can chose chinaserver

**Comment by KedowsWu** [comment]
能不能说的详细一点

**Comment by gaoweijun2018** [comment]
> 能不能说的详细一点

他的意思是自己打包的时候可以选择中国服务器和x86架构
但是,我尝试打包的时候项目直接报错了
不会c++

**Comment by KedowsWu** [comment]
谢谢


------------------ 原始邮件 ------------------

发 件 人：gaoweijun2018 ***@***.***>

发送时间：2023-05-11 13:56:47

收 件 人：R3nzTheCodeGOD/R3nzSkin ***@***.***>

抄 送："吴阁" ***@***.***>,Comment ***@***.***>

主 题：Re: [R3nzTheCodeGOD/R3nzSkin] How to run R3 on a Chinese server (Issue #486)







能不能说的详细一点

他的意思是自己打包的时候可以选择中国服务器和x86架构
但是,我尝试打包的时候项目直接报错了
不会c++

**Comment by r3nzskin-bazhu** [comment]
https://tieba.baidu.com/p/8443538288
