### ISSUE TITLE
why r3 status  is not injected in chinese server?

### ISSUE THREAD

**Issue by zskm01** [R3nzTheCodeGOD/R3nzSkin#487]

**Comment by zskm01** [comment]
![微信截图_20230506035805](https://user-images.githubusercontent.com/125043027/236557811-72243f64-0edc-4b21-8274-8c596cb9aab8.png)

**Comment by hkthomas** [comment]
Chinese servers are still using the x86 platform.

**Comment by VONOROOM** [comment]
台湾也是吗/

**Comment by Postroggy** [comment]
> 

is that to say, if we compile the tool as x86. We can use it in Chinese Server?

**Comment by zskm01** [comment]
> 台湾也是吗/
台湾可以的，只有国服是x86版本

**Comment by zskm01** [comment]
> 

Earlier versions of the plugin appeared to be x86, but with the update of the LOL server, the plugin appears to have been updated to x64

**Comment by zskm01** [comment]
> > 
> 
> is that to say, if we compile the tool as x86. We can use it in Chinese Server?

Earlier versions of the plugin appeared to be x86, but with the update of the LOL server, the plugin appears to have been updated to x64

**Comment by VONOROOM** [comment]
但是台服用不了，在LOL文件夹中，不见之前那个Logitech.all的文件了，没这个文件怎么替换呢?

---Original---
From: ***@***.***&gt;
Date: Sun, May 21, 2023 21:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [R3nzTheCodeGOD/R3nzSkin] why r3 status  is not injected inchinese server? (Issue #487)




  
台湾也是吗/
 台湾可以的，只有国服是x86版本

**Comment by zskm01** [comment]
> 

不用替换啊，插件下载下来直接用就行了，替换文件只是相当于自动启动了，而且作者也不建议替换文件容易封

**Comment by zskm01** [comment]
> 但是台服用不了，在LOL文件夹中，不见之前那个Logitech.all的文件了，没这个文件怎么替换呢?
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, May 21, 2023 21:05 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [R3nzTheCodeGOD/R3nzSkin] why r3 status is not injected inchinese server? (Issue #487) 台湾也是吗/ 台湾可以的，只有国服是x86版本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不用替换啊，下载下来直接用就行了，替换文件只是相当于自动启动了，而且作者也不建议替换文件，容易被封

**Comment by VONOROOM** [comment]
不行呀，解压文件那个exe我开了没有，他第四个选项不亮，说找不到注入文件之类的，不明白我可以截图给你看

**Comment by zskm01** [comment]
> 不行呀，解压文件那个exe我开了没有，他第四个选项不亮，说找不到注入文件之类的，不明白我可以截图给你看

那我就不清楚了，没遇见过，你翻翻其他的issue看有没有碰见类似问题的吧

**Comment by VONOROOM** [comment]
![Uploading Desktop Screenshot 2023.05.21 - 22.04.15.47.png…]()

**Comment by httpsColon** [comment]
解决了吗，cn体验服无法注入

**Comment by hotline1337** [comment]
> Has it been solved? The cn experience server cannot be injected.

R3nzSkin doesn't support Chinese Anti-Cheat

**Comment by Postroggy** [comment]
已经收到您发送的邮件，有空处理了再联系您。郭跃琪
