### ISSUE TITLE
Hello, I have some suggestions

### ISSUE THREAD

**Issue by AbrnYa** [R3nzTheCodeGOD/R3nzSkin#49]
Can you add a skin avatar like this

![image](https://user-images.githubusercontent.com/77602247/151810787-f7436b82-323d-45df-a60e-08e72bd6ae6d.png)

**Comment by Clownsw** [comment]
A good suggestion

**Comment by serekAlmette** [comment]
I think it's not hard to remember how skin looks or overall look of skin
