### ISSUE TITLE
it says its a virus

### ISSUE THREAD

**Issue by Ax4o** [R3nzTheCodeGOD/R3nzSkin#490]
when i start the program my windows defender says there is a virus in my pc from the program as the name: defenseevasion.a ml

**Comment by sus2240** [comment]
there is virus in last version

**Comment by Ax4o** [comment]
> there is virus in last version

but i dont think theres a virus

**Comment by hotline1337** [comment]
Disable your antivirus or add the injector to the exclusion in your antivirus.
