### ISSUE TITLE
Failed to find pattern: 8D 8E ? ? ? ? FF 74 24 4C

### ISSUE THREAD

**Issue by burakender** [R3nzTheCodeGOD/R3nzSkin#492]
what's the solution 
![235857338-2ebcec58-1414-4030-bbee-651a4b91c045](https://user-images.githubusercontent.com/132440888/236679142-1864ef8f-5aba-4dd5-bf99-fa01b1b945a5.png)

**Comment by Capo1337** [comment]
i have the issue too

**Comment by Saber1u** [comment]
me too

**Comment by Cuiyim** [comment]
我也遇到了

**Comment by AspirinEny** [comment]
更新到最新版本。

**Comment by failure1975** [comment]
我怎样才能更新到最新版本？

**Comment by sansbruhgaming** [comment]
> 我怎样才能更新到最新版本？

https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/latest
