### ISSUE TITLE
How to run r3nzskin  Chinese server

### ISSUE THREAD

**Issue by ajihua** [R3nzTheCodeGOD/R3nzSkin#498]
I tried to compile the Chinese server x86 but failed, compiling the Chinese server x64 succeeded
![-6e0239f2f3d3e867](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/24368848/0299c27b-5625-4886-95c2-3903629b9057)

**Comment by slowloriss** [comment]
setting up platform to Visual Studio 2019 (v142)

**Comment by gaoweijun2018** [comment]
just wait for china server x64
or u code yourself

**Comment by ajihua** [comment]
Thank your for the answer, I don't know c++, I'll wait for the Chinese server to update x64.



---Original---
From: ***@***.***&gt;
Date: Mon, May 15, 2023 14:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [R3nzTheCodeGOD/R3nzSkin] How to run r3nzskin  Chinese server(Issue #498)




 
just wait for china server x64
 or u code yourself

**Comment by ajihua** [comment]
Already set,But the compilation still fails，Whether you want to modify the source code,

I don't know C++,I'm still waiting for the Chinese server to update x64


---Original---
From: ***@***.***&gt;
Date: Mon, May 15, 2023 01:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [R3nzTheCodeGOD/R3nzSkin] How to run r3nzskin  Chinese server(Issue #498)




 
setting up platform to Visual Studio 2019 (v142)
