### ISSUE TITLE
malvare 

### ISSUE THREAD

**Issue by Rivest11** [R3nzTheCodeGOD/R3nzSkin#499]
Hello i don't know how this program has 2 malwares in it,but my anti-virus "Hitman pro" says that both of the fails is malware and when i start to use it. A lot of my emails get hack so yeah it make sense!

**Comment by WitheredRose7** [comment]
False positives

**Comment by Rivest11** [comment]
https://prnt.sc/stfAICQs2Tf9

**Comment by Rivest11** [comment]
Ur tried closing issues like that? Yeah sure may it be a lot but now days the hackers are a lot, and i'am choosing the safest option for my pc and my date in it. I like the skin changer a lot, it's great but in Youtube you can see a lot of videos about the program and half and most of them  are with malwares and viruses. So i don't see a problem with complaining. It's human to ask.

**Comment by hotline1337** [comment]
> 

Download the release from the original repository or compile the source code yourself if you are worried about getting a virus, just don't download anything from youtube videos, etc.
