### ISSUE TITLE
still have crashes

### ISSUE THREAD

**Issue by khelito** [R3nzTheCodeGOD/R3nzSkin#5]
it seems i still have crash after 3-5 mins on the game, is there some files that are from the bak3rs skin changer who made it?

**Comment by 6oody** [comment]
> it seems i still have crash after 3-5 mins on the game, is there some files that are from the bak3rs skin changer who made it?

![image](https://user-images.githubusercontent.com/42409047/127472229-1b8e0bb0-d298-4d06-98a7-a9b7c08649b7.png)

**Comment by khelito** [comment]
cringe

**Comment by DxxxxY** [comment]
im also having crashes 1-3 mins into the game

**Comment by 6oody** [comment]
ig it depends on the skin u use, i mean like some skins have bugs like rammus when he just hit an enemy player and use w it crashes the whole game.
i didn't know that after it crashed like 6 times in the game

**Comment by R3nzTheCodeGOD** [comment]
Now there should be instant crashes, if you are experiencing crashes near the end of the game, use the unhook method.

**Comment by R3nzTheCodeGOD** [comment]
I think the problem is in DirectX11, I would appreciate it if you write here whether you get a crash after playing the game in DirectX9 for a while.

**Comment by daswareinfach** [comment]
i tried with DirectX9 but still have crashes.

**Comment by R3nzTheCodeGOD** [comment]
Which skin did you play with? @daswareinfach

**Comment by R3nzTheCodeGOD** [comment]
Yes, the crash has nothing to do with DirectX11, it's time to eliminate it

I wonder if using the `CharacterDataStack__Push` method for all skins will solve this problem? I really don't understand what is causing the crashe.

**Comment by DxxxxY** [comment]
> Yes, the crash has nothing to do with DirectX11, it's time to eliminate it
> 
> 
> 
> I wonder if using the `CharacterDataStack__Push` method for all skins will solve this problem? I really don't understand what is causing the crashe.

Maybe you can try to directly inject from Visual Studio to get the error in the debug console?

**Comment by khelito** [comment]
will try it, thanks for updating it !

**Comment by NerfDoriftar** [comment]
Game crashes - > ryze skin (aram) 
next game - > illaoi skin (aram)

**Comment by R3nzTheCodeGOD** [comment]
We've already eliminated dx9, it's definitely not caused by him

**Comment by R3nzTheCodeGOD** [comment]
I think I solved the crash, I'll be sure after I play a few more matches

**Comment by R3nzTheCodeGOD** [comment]
I played 3 games of ARAM and 2 games normally and I didn't get any crashes. I'm waiting for your feedback. If it crashes again, send a message here.

**Comment by siegjan6** [comment]
https://lol.qq.com/ 
Do you support it?

**Comment by R3nzTheCodeGOD** [comment]
I do not support

**Comment by DxxxxY** [comment]
> https://lol.qq.com/
> Do you support it?

what is this?

**Comment by R3nzTheCodeGOD** [comment]
problem solved
