### ISSUE TITLE
Super Galaxy Rumble (Q)

### ISSUE THREAD

**Issue by akDKi1saf** [R3nzTheCodeGOD/R3nzSkin#503]
R3nz skin changer - 
![Screen23](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/100109715/820c0438-f66b-4d2a-8339-7ee532d17635)

Original - 
![Screenshot_4](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/100109715/9672fbcb-bc48-4dfa-99b8-ec461bdbb1c9)

**Comment by Pxprl** [comment]
#1

**Comment by diyooor** [comment]
#1

**Comment by diyooor** [comment]
#1 @hotline1337
