### ISSUE TITLE
fix for 13.10

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#504]
FYI - to fix for new 13.10 patch, just change signature for CharacterDataStack__Push to "E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0" (previously "E8 ? ? ? ? 48 8D 8D B0 11 00 00 E8 ? ? ? ? 48 85 C0") and rebuild

**Comment by slowloriss** [comment]
TY

**Comment by J-EnJay** [comment]
nice

**Comment by Hypeliox** [comment]
Sorry,I really don't understand what to do

**Comment by Yueby** [comment]
Thanks bro, it work!

**Comment by iwilltry7** [comment]
How to do it pls ?

**Comment by Yueby** [comment]
> How to do it pls ?

Just download the project and open with VisualStudio, and do my bro said (ctrl+shift+f to search that string). Then rebuild solution. If you're using VisualStudio2022, it will auto open environment install page when you open the porject, and download c++.

**Comment by Hypeliox** [comment]
> > How to do it pls ?
> 
> Just download the project and open with VisualStudio, and do my bro said (ctrl+shift+f to search that string). Then rebuild solution. If you're using VisualStudio2022, it will auto open environment install page when you open the porject, and download c++.

I seriously don't understand which file to open, sorry about that, can you explain a little more

**Comment by Yueby** [comment]
> > > How to do it pls ?
> > 
> > 
> > Just download the project and open with VisualStudio, and do my bro said (ctrl+shift+f to search that string). Then rebuild solution. If you're using VisualStudio2022, it will auto open environment install page when you open the porject, and download c++.
> 
> I seriously don't understand which file to open, sorry about that, can you explain a little more
Firs click "R3nzSkin.sln" file to open project solution, and press "ctrl+shift+f" to search "E8 ? ? ? ? 48 8D 8D B0 11 00 00 E8 ? ? ? ? 48 85 C0", replace it and on toolbar build to rebuild solution,

**Comment by Yueby** [comment]
> > > > How to do it pls ?
> > > 
> > > 
> > > Just download the project and open with VisualStudio, and do my bro said (ctrl+shift+f to search that string). Then rebuild solution. If you're using VisualStudio2022, it will auto open environment install page when you open the porject, and download c++.
> > 
> > 
> > I seriously don't understand which file to open, sorry about that, can you explain a little more
> > Firs click "R3nzSkin.sln" file to open project solution, and press "ctrl+shift+f" to search "E8 ? ? ? ? 48 8D 8D B0 11 00 00 E8 ? ? ? ? 48 85 C0", replace it and on toolbar build to rebuild solution,

Builded file in Release folder

**Comment by ozcan0** [comment]
There is no release option only (china server and riot server) and when I build I get errors

**Comment by desmond315** [comment]
can someone do a in-depth tutorial lol, usually how long would the updated version be released

**Comment by clashyboy1only** [comment]
So I changed the characterdatastack but it still gives the same error. I clicked rebuilt and that was it. Am i meant to do something more after?

**Comment by Hypeliox** [comment]
> So I changed the characterdatastack but it still gives the same error. I clicked rebuilt and that was it. Am i meant to do something more after?

How do you open the file? , I have numbers and letters in different formats, I can't change them

**Comment by Stan2525** [comment]
> 

yea i also don't understand, any tutorial on how to build this ? i have no knowledge in coding lol

**Comment by clashyboy1only** [comment]
> > So I changed the characterdatastack but it still gives the same error. I clicked rebuilt and that was it. Am i meant to do something more after?
> 
> How do you open the file? , I have numbers and letters in different formats, I can't change them

You need to open it with visual studio (may need to download) then go into memories which you will see in the right hand tab and look for characterdatastack, you should be able to change the numbers from there.

**Comment by Skeley01** [comment]
> > How to do it pls ?
> 
> Just download the project and open with VisualStudio, and do my bro said (ctrl+shift+f to search that string). Then rebuild solution. If you're using VisualStudio2022, it will auto open environment install page when you open the porject, and download c++.

I think it would be easier for all if u just upload ur edited file but thanks anyways for trying ^^

**Comment by Hypeliox** [comment]
> 

Yea I think too ^^

**Comment by desmond315** [comment]
sorry if i am acting dumb, but the file u guys been talking about, is that the .dll file that comes with the injector app

**Comment by Stan2525** [comment]
> sorry if i am acting dumb, but the file u guys been talking about, is that the .dll file that comes with the injector app

don't worry brother we're in the same boat ;)) but no, they are not talking about that file

**Comment by Backprop1** [comment]
I just dont get it. Should upgrade the project to VS2022? Or should I download a VSCPP2019? I have change the code and try to rebuild but it shows this
Error	TRK0005	Failed to locate: "CL.exe". 系统找不到指定的文件。	R3nzSkin

**Comment by desmond315** [comment]
> ![sadsaadas](https://user-images.githubusercontent.com/133955679/239186385-39f0f630-cd4e-40e7-aee3-797af6e75945.PNG)

am I in the right place, why is it empty lol

**Comment by clashyboy1only** [comment]
> ![sadsaadas](https://user-images.githubusercontent.com/133955679/239186385-39f0f630-cd4e-40e7-aee3-797af6e75945.PNG)

you are on the chinese server there, look at the top tab

**Comment by 22saint** [comment]
Love u man, it works :D

**Comment by clashyboy1only** [comment]
> Love u man, it works :D

what did you do after rebuilding?

**Comment by desmond315** [comment]
![ewqewqe](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/133955679/67a43f72-a263-466b-a9b0-1c194149bd5b)
what i do next

**Comment by clashyboy1only** [comment]
source files then memory

**Comment by isak102** [comment]
> ![ewqewqe](https://user-images.githubusercontent.com/133955679/239187863-67a43f72-a263-466b-a9b0-1c194149bd5b.PNG) what i do next

You should search for the string `E8 ? ? ? ? 48 8D 8D B0 11 00 00 E8 ? ? ? ? 48 85 C0` and replace it with `E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0` and then right click on the solution and rebuild. But I get some errors when building

**Comment by Backprop1** [comment]
> > ![ewqewqe](https://user-images.githubusercontent.com/133955679/239187863-67a43f72-a263-466b-a9b0-1c194149bd5b.PNG) what i do next
> 
> You should search for the string `E8 ? ? ? ? 48 8D 8D B0 11 00 00 E8 ? ? ? ? 48 85 C0` and replace it with `E8 ? ? ? ? 48 8D 8D ? ? ? ? E8 ? ? ? ? 48 85 C0` and then right click on the solution and rebuild. But I get some errors when building

I got errors too

**Comment by Hypeliox** [comment]
I wonder if someone who edits the file shares the file, we can use it ?

**Comment by desmond315** [comment]
after u replace the string what do u do ...

**Comment by desmond315** [comment]
![Capturegtdfd](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/133955679/7dc955f4-19f3-4e82-89fc-f81f4ed89342)
i cant find the application here

**Comment by aderuu** [comment]
what we do after changing the string ?

**Comment by Stan2525** [comment]
> ![sadsaadas](https://user-images.githubusercontent.com/133955679/239186385-39f0f630-cd4e-40e7-aee3-797af6e75945.PNG)

how did u get to here?

**Comment by i4TsU** [comment]
https://github.com/i4TsU/R3nzSkin-updated/blob/668353fabc9665a29b96a0060a8bee68e799b811/R3nzSkin.dll

link to 13.10 dll file if u dont know how to build it yourself ^^

**Comment by isak102** [comment]
> https://github.com/i4TsU/R3nzSkin-updated/blob/668353fabc9665a29b96a0060a8bee68e799b811/R3nzSkin.dll
> 
> link to 13.10 dll file if u dont know how to build it yourself ^^

Thanks! Worked perfectly

**Comment by jakubrusek** [comment]
what windows sdk version is this supposed to be built on

**Comment by Hypeliox** [comment]
> https://github.com/i4TsU/R3nzSkin-updated/blob/668353fabc9665a29b96a0060a8bee68e799b811/R3nzSkin.dll
> 
> link to 13.10 dll file if u dont know how to build it yourself ^^

thx It workss ^^

**Comment by slowloriss** [comment]
> what windows sdk version is this supposed to be built on

I build it at Platform Toolset = 'v142'

**Comment by johngay123** [comment]
> https://github.com/i4TsU/R3nzSkin-updated/blob/668353fabc9665a29b96a0060a8bee68e799b811/R3nzSkin.dll
> 
> link to 13.10 dll file if u dont know how to build it yourself ^^


Im kinda confused, after I download the dll do I insert it into the game folder or do I use the injector

**Comment by hkthomas** [comment]
> 

Replace the old R3nzSkin.dll in the.exe folder。

**Comment by xiyangbaofengxu** [comment]
Hello, can you explain how to find the correct offset？
