### ISSUE TITLE
There is a R3nzskin for 13.10

### ISSUE THREAD

**Issue by MikasaCat** [R3nzTheCodeGOD/R3nzSkin#505]
Thank you for the guidance from the previous bro. This is the file I have regenerated and it can works.

OneDrive to download-->[R3nzskin for 13.10](https://1drv.ms/u/s!AhNrpSF-NG9YgTrIcYpQBZArW4ju?e=HwkjVp)
Github to download-->[R3nzskin for 13.10](https://github.com/MikasaCat/R3nzskin-for-13.10)

**Comment by a1029602653** [comment]
Thank you!!

**Comment by Skeley01** [comment]
> Thank you for the guidance from the previous leader. This is the file I have regenerated and tested for use.
> 
> [R3nzskin for 13.10](https://1drv.ms/u/s!AhNrpSF-NG9YgTrIcYpQBZArW4ju?e=HwkjVp)

yep it works thanks buddy :3

**Comment by 983706057** [comment]
it works ,thanks bro

**Comment by ChocolateFirmLover** [comment]
Thanks, it works.

**Comment by Stan2525** [comment]
Thanks bro

**Comment by thnsz** [comment]
thanks bro works for eune

**Comment by GGbond66666** [comment]
谢谢兄弟，但是我下载时会跳转到OneDrive的网站，可不可以分享一个直接下载的链接呢。

**Comment by MikasaCat** [comment]
好 等会我发一个百度网盘> 谢谢兄弟，但是我下载时会跳转到OneDrive的网站，可不可以分享一个直接下载的链接呢。

**Comment by nhockan** [comment]
big thank, it work for VN sever

**Comment by skyywh** [comment]
why does it say the program has trojan? is it safe to download? im very unsure

**Comment by aymoon4** [comment]
all comments here are made by new accounts i would not download it guys

**Comment by MikasaCat** [comment]
OneDrive 进不去的点第二个链接下载

**Comment by MikasaCat** [comment]
> 

it is safe

**Comment by GGbond66666** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/133966655/ef55725e-4455-4192-8e67-c65f5c39ff11)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/133966655/ed62c254-98d0-4c68-a818-51aa6cdc660c)

**Comment by GGbond66666** [comment]
已解决，是我电脑配置有问题

**Comment by therlsm** [comment]
请问打不开链接如何解决

**Comment by HuaJieHappy** [comment]
多谢，完美使用

**Comment by xiaokonglongya** [comment]
谢谢你，分享侠

**Comment by therlsm** [comment]
已解决
