### ISSUE TITLE
Chinese Server Not Inject

### ISSUE THREAD

**Issue by ShiedaYoung** [R3nzTheCodeGOD/R3nzSkin#51]
In Chinese server, R3nz kin status is red 'not inject' while other 3 is found. How can I deal with this?

**Comment by R3nzTheCodeGOD** [comment]
You can hijack a legitimate dll.

For example, you can replace LogitechLed.dll with R3nzSkin.dll in the game's files, so that every time you enter the game, the cheat is injected automatically. (I do not recommend this method, but you do not need an injector in this method.)

**Comment by ShiedaYoung** [comment]
> You can hijack a legitimate dll.
> 
> For example, you can replace LogitechLed.dll with R3nzSkin.dll in the game's files, so that every time you enter the game, the cheat is injected automatically. (I do not recommend this method, but you do not need an injector in this method.)

Still “Not Inject” 😭

**Comment by ShiedaYoung** [comment]
Please solve it! We cannot use it!

**Comment by lcl124252** [comment]
按作者的方法替换合法的dll，比如 LogitechLed.dll ，将 R3nzSkin.dll 改名然后替换前面那个dll，虽然仍显示未注射，但是可以正常在游戏中使用，按insert就可以了，但是作者不推荐这种办法应该是容易封号（自己感觉），因为作者制作的程序会自动变化名称的，应该就是为了防检测的，自己考虑风险吧
