### ISSUE TITLE
Viego's passive

### ISSUE THREAD

**Issue by Fausterz** [R3nzTheCodeGOD/R3nzSkin#511]
There is a bug when i play Viego that it doeesn't matter if i change the skin with the program that the passive stills the same when i take the champion that i've killed. If i had pentakill viego selected before the game starts and in the program i select edg viego when i take a body it has the pentakill crown and all that stuff, but when u ult with ur passive it's ok with ur skin u've selected in the program. Hope u can fix it! :)

**Comment by eienjdn** [comment]
need this

**Comment by hotline1337** [comment]
#1
