### ISSUE TITLE
关于英雄联盟的问题，本人不会英语，请大佬机翻

### ISSUE THREAD

**Issue by VONOROOM** [R3nzTheCodeGOD/R3nzSkin#520]
我想问台服也是x86吗，注入不了吗，现在我在英雄联盟文件夹里都找不到那个LOL都找不到那个LogitecheLed.all 文件，就说现在没有这个文件所有就换不了是吗

**Comment by a491363060** [comment]
台服是x64的，现在只有国服是x86

**Comment by VONOROOM** [comment]
我知道，可是这次版本更新那个Logitech.all那个文件没有了，然后就替换不了嘞，你用那个注入，不会说找不到注入对象之类的吗，我选完英雄，进游戏久弹出来，用不了。以前我都是自己改名称替换，现在那个文件直接没了



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年5月22日(週一) 上午9:08
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [R3nzTheCodeGOD/R3nzSkin] 关于英雄联盟的问题，本人不会英语，请大佬机翻 (Issue #520)




 
台服是x64的，现在只有国服是x86

**Comment by a491363060** [comment]
> 我知道，可是这次版本更新那个Logitech.all那个文件没有了，然后就替换不了嘞，你用那个注入，不会说找不到注入对象之类的吗，我选完英雄，进游戏久弹出来，用不了。以前我都是自己改名称替换，现在那个文件直接没了
> [...](#)
> ---原始郵件--- 寄件人： ***@***.***> 傳送時間： 2023年5月22日(週一) 上午9:08 收件人： ***@***.***>; 抄送： ***@***.******@***.***>; 主旨： Re： [R3nzTheCodeGOD/R3nzSkin] 关于英雄联盟的问题，本人不会英语，请大佬机翻 （Issue #520） 台服是x64的，现在只有国服是x86 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了线程。消息 ID： ***@***.***>

改成hid.dll就行，也会有弹窗但是功能正常

**Comment by slowloriss** [comment]
> 我知道，可是这次版本更新那个Logitech.all那个文件没有了，然后就替换不了嘞，你用那个注入，不会说找不到注入对象之类的吗，我选完英雄，进游戏久弹出来，用不了。以前我都是自己改名称替换，现在那个文件直接没了
> […](#)
> ---原始郵件--- 寄件人： ***@***.***&gt; 傳送時間： 2023年5月22日(週一) 上午9:08 收件人： ***@***.***&gt;; 抄送： ***@***.******@***.***&gt;; 主旨： Re: [R3nzTheCodeGOD/R3nzSkin] 关于英雄联盟的问题，本人不会英语，请大佬机翻 (Issue #520) 台服是x64的，现在只有国服是x86 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

實際情況是 13.7開始已經不使用這個文件(並且已經移除) 但是客戶端仍然會嘗試加載LogitechLed.dll 甚至並不檢測LogitechLed.dll的MD5/CRC 無條件加載 直到13.8移除了客戶端加載LogitechLed.dll的代碼

**Comment by mincident** [comment]
> > 我知道，可是这次版本更新那个Logitech.all那个文件没有了，然后就替换不了嘞，你用那个注入，不会说找不到注入对象之类的吗，我选完英雄，进游戏久弹出来，用不了。以前我都是自己改名称替换，现在那个文件直接没了
> > [...](#)
> > ---原始郵件--- 寄件人： _**@**_._**> 傳送時間： 2023年5月22日(週一) 上午9:08 收件人： _**@**_.**_>; 抄送： _**@**_._**_**@**_.**_>; 主旨： Re： [R3nzTheCodeGOD/R3nzSkin] 关于英雄联盟的问题，本人不会英语，请大佬机翻 （Issue #520） 台服是x64的，现在只有国服是x86 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了线程。消息 ID： _**@**_.***>
> 
> 改成hid.dll就行，也会有弹窗但是功能正常

是不是意思就是，把dll文件改成hid.dll 放在game目录里就行了？请教

**Comment by ld0714** [comment]
> > > 我知道，可是这次版本更新那个Logitech.all那个文件没有了，然后就替换不了嘞，你用那个注入，不会说找不到注入对象之类的吗，我选完英雄，进游戏久弹出来，用不了。以前我都是自己改名称替换，现在那个文件直接没了
> > > [...](#)
> > > ---原始郵件--- 寄件人： _**@**_._**> 傳送時間： 2023年5月22日(週一) 上午9:08 收件人： _**@**_.**_>; 抄送： _**@**_._**_**@**_.**_>; 主旨： Re： [R3nzTheCodeGOD/R3nzSkin] 关于英雄联盟的问题，本人不会英语，请大佬机翻 （Issue #520） 台服是x64的，现在只有国服是x86 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了线程。消息 ID： _**@**_.***>
> > 
> > 
> > 改成hid.dll就行，也会有弹窗但是功能正常
> 
> 是不是意思就是，把dll文件改成hid.dll 放在game目录里就行了？请教

用x64架构编译，文件名改成hid.dl放在game下就行了
