### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by VONOROOM** [R3nzTheCodeGOD/R3nzSkin#522]
no that all replaces that
![Desktop Screenshot 2023 05 22 - 00 26 37 22](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/123545527/5e8ca839-3583-408e-ab66-dde2574c473f)
![Desktop Screenshot 2023 05 22 - 00 26 37 22](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/123545527/79a9d95b-3fa9-4547-936d-d9526cd053b3)
logith。。。。。not

**Comment by hotline1337** [comment]
We suggest using the R3nzSkin Injector for the safety since the Logitech method might get patched and flagged by Riot which may endanger your account.
