### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Apocfel** [R3nzTheCodeGOD/R3nzSkin#529]
- Add auto-update/update-check feature
- Add option for closing not to minimize to tray
- Chromas separate from skins

**Comment by hotline1337** [comment]
> Add option for closing not to minimize to tray

This is already a "feature", just close the window instead of minimizing it.

**Comment by Apocfel** [comment]
> This is already a "feature", just close the window instead of minimizing it.

No. When minimized, the application should also not be minimized to the tray if this option is enabled. 

Personally, it's inconvenient for me that sometimes the application just ends up in the tray and I forget about it, which would not happen if it didn't collapse there at all.

**Comment by hotline1337** [comment]
> No. When minimized, the application should also not be minimized to the tray if this option is enabled.
Personally, it's inconvenient for me that sometimes the application just ends up in the tray and I forget about it, which would not happen if it didn't collapse there at all.

Ah, I understand now. Will add this feature honestly.

**Comment by hotline1337** [comment]
> > No. When minimized, the application should also not be minimized to the tray if this option is enabled.
> > Personally, it's inconvenient for me that sometimes the application just ends up in the tray and I forget about it, which would not happen if it didn't collapse there at all.
> 
> Ah, I understand now. Will add this feature honestly.

https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/f160848c5a5f2d6539a195a237915aee61e34379
