### ISSUE TITLE
Automatically enter "/mute all" at game start

### ISSUE THREAD

**Issue by Yoezzz** [R3nzTheCodeGOD/R3nzSkin#532]
When I was playing games recently, I always encountered quarrels with my teammates, so I had to input commands frequently to block everyone. Is there any well-meaning boss who can guide me how to add code to R3nzSkin to achieve this function, thank you very very very much👻👻👻

**Comment by rainzee** [comment]
off topic

**Comment by rtj563etn36h4h** [comment]
just disable the chat and emotes you monkey

**Comment by whiteday13jin** [comment]
You can disable receiving messages in the settings
