### ISSUE TITLE
Dude, please update the China server, thank you very much!

### ISSUE THREAD

**Issue by class-qingfeng** [R3nzTheCodeGOD/R3nzSkin#536]
Dude, please update the China server, thank you very much!

**Comment by xiyangbaofengxu** [comment]
It's ready to use now

**Comment by class-qingfeng** [comment]
> 现在可以使用了

The injector does not start

**Comment by class-qingfeng** [comment]
> 现在可以使用了

The injector cannot be injected

**Comment by hellozhangzheng** [comment]
Rename the dll to hid.dll and copy it to the GAME folder in the lol directory

**Comment by r3nzskin-bazhu** [comment]
https://tieba.baidu.com/p/8443538288

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinese Anti-Cheat
