### ISSUE TITLE
High noon Ashe texture overlap

### ISSUE THREAD

**Issue by JuleZ085** [R3nzTheCodeGOD/R3nzSkin#538]
There's bug with High noon Ashe, as I know, she changes her textures after ult, but this is not happening in skinchaged version of skin, instead she has 2 types of textures overlapping eachother. Can you split both versions, or fix that issue? I suppose my framerate drops because of this. Thank you.

**Comment by hotline1337** [comment]
Issue already known: https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1
