### ISSUE TITLE
Has anyone explained how to find the correct offset?

### ISSUE THREAD

**Issue by xiyangbaofengxu** [R3nzTheCodeGOD/R3nzSkin#539]
I encountered this error when using R3nzSkin.(Failed to find pattern:48 8B 05 ? ? ? ? 8B 58 0C)
Has anyone explained how to find the correct offset?

**Comment by I-Want-ToBelieve** [comment]
me too, but close the error window, still work.

**Comment by diyooor** [comment]
> I encountered this error when using R3nzSkin.(Failed to find pattern:48 8B 05 ? ? ? ? 8B 58 0C) Has anyone explained how to find the correct offset?



> me too, but close the error window, still work.

In my comment in this issue https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/760#issuecomment-1721908678 I explain how to fix this. Reply if it still doesn't work with error dialogs.
