### ISSUE TITLE
Broken when started from batch file

### ISSUE THREAD

**Issue by diniamo** [R3nzTheCodeGOD/R3nzSkin#54]
So basically I'm trying to run R3nzSkin from a batch file with the `start` command, but it doesn't work.
The window opens, but when I get into a game it just spams the injected successfully message, but does nothing.

**Comment by R3nzTheCodeGOD** [comment]
Server ?

**Comment by diniamo** [comment]
No, normal windows, it works if I open it with a double click.

**Comment by diniamo** [comment]
Oh you meant game server, I play on EUNE.
