### ISSUE TITLE
The injector does not support Chinese servers

### ISSUE THREAD

**Issue by class-qingfeng** [R3nzTheCodeGOD/R3nzSkin#540]
Dude, the injector cannot support Chinese servers, please update to support Chinese servers, thank you!

**Comment by Aperodry** [comment]
China server has tprotect,you need to inject using other methods

**Comment by r3nzskin-bazhu** [comment]
https://tieba.baidu.com/p/8443538288教程·

**Comment by TheNei** [comment]
it's supprot look at me 
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/112568042/a44215e8-5945-4fde-bf9c-a951dccdae96)
如果在国服，则是将解压出来的另一个文件R3nzSkin.dll改名为hid.dll，然后将其复制到英雄联盟安装路径下的Game 文件夹中，进游戏即可。无需运行R3nzSkin_Injector.exe程序文件

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinese Anti-Cheat
