### ISSUE TITLE
About China service 

### ISSUE THREAD

**Issue by TheNei** [R3nzTheCodeGOD/R3nzSkin#544]
实际上，是可以用的，方法和之前一样改名，不过不是改为以前那个，而是改为hid然后和之前一样复制到Game 文件夹里去，游戏加载自动运行
可参考：https://zhuanlan.zhihu.com/p/634545213
https://tieba.baidu.com/p/8443538288

**Comment by class-qingfeng** [comment]
So insecure, I need a secure stream

**Comment by wuchenc1** [comment]
请问TFT的文件替换名称是什么呢

**Comment by hotline1337** [comment]
R3nzSkin doesn't support Chinese Anti-Cheat
