### ISSUE TITLE
Refer to Code Injector for Personal DLL Injection

### ISSUE THREAD

**Issue by vacnex** [R3nzTheCodeGOD/R3nzSkin#549]
Hello, I would like to ask if I can refer to your code injector to create my own injector and inject my own DLL? 
I'm not very familiar with DLL injection, so I think referring to your injector is a safe approach and also helps me avoid detection.
I also want to ask if there are any issues with using LoadLibrary in League, as I've heard that LoadLibrary is a commonly detected injection method.

**Comment by MrTsud0** [comment]
> Hello, I would like to ask if I can refer to your code injector to create my own injector and inject my own DLL? I'm not very familiar with DLL injection, so I think referring to your injector is a safe approach and also helps me avoid detection. I also want to ask if there are any issues with using LoadLibrary in League, as I've heard that LoadLibrary is a commonly detected injection method.

its not safe buddy its has a trojan horse
