### ISSUE TITLE
I just have banned from Korean LOL server by using this program

### ISSUE THREAD

**Issue by MINE113** [R3nzTheCodeGOD/R3nzSkin#55]
I just have banned from Korean LOL server by using this program. I just used this normally yesterday, but I banned from server when I checked it today

**Comment by rkdrlgh22** [comment]
I also got banned i guess need change programe name.

**Comment by W1nehazy** [comment]
Korean servers are notable for issuing bans against Skin Changers.

As many Rioters already stated, Skin Changers are a “use at your own risk” type of thing. Each region deals with this issue differently.

Still, 2 years using tools like this and no bans for me. EUW server as always.

**Comment by R3nzTheCodeGOD** [comment]
I recommend you to write your own injector on servers with extra protection such as Korea.

they can't detect a good **ManualMap** or **Kernel** injector
