### ISSUE TITLE
Neeko problem, maybe bannable?

### ISSUE THREAD

**Issue by lumivhs** [R3nzTheCodeGOD/R3nzSkin#562]
If you use R3nzSkin and you have a Neeko on the enemy team, you can see without any problem what she became... If you're on the red side, and Neeko transforms into a minion, the minion itself appears red instead of blue. this clearly gives an incredible advantage in the game, I hope you can do something before it becomes bannable.
![proof 1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/137399460/188ebb81-dae8-4b70-89bd-a4987c6a5e3c)

**Comment by cjaryou** [comment]
i got banned btw

**Comment by lumivhs** [comment]
> i got banned btw

today?

**Comment by Wiumm** [comment]
fr u got banned? im using it at least 3 months or more, and nothing happened to my account

**Comment by lumivhs** [comment]
> fr u got banned? im using it at least 3 months or more, and nothing happened to my account

yeah, same here, using it for 1 week and nothing happened, maybe he's from the chinese server, tencent detected some r3 users

**Comment by hotline1337** [comment]
The behavior of the player that particularly and obviously targets the transformed neeko might lead to a ban, everything else is safe.
