### ISSUE TITLE
banning chance

### ISSUE THREAD

**Issue by qqqqqqqqqqww** [R3nzTheCodeGOD/R3nzSkin#565]
Is it possible for users to be banned because of it?

**Comment by tragedyxxms** [comment]
R3nz Skin Changer is undetectable, meaning it is very difficult to get banned for using it. I have been using this program for 3 months and have not received a penalty for it. I got a penalty for insulting other players and that's it.

**Comment by bandyta69** [comment]
i got ban on 3 botted accounts for using third programms while i had only r3znskin opened, but the thing is im using this since like more than 1 year and didnt got banned before.

**Comment by tragedyxxms** [comment]
Hmm, maybe you sent the files to League of Legends player support and they detected an internal program that they may have recognized as scripts for the game.
Could you write me how it happened?

**Comment by bandyta69** [comment]
Yup, i just played on 1 account 20 games, botted account for sure. On one account i was kinda toxic, so i thought that somebody reported me for using third programms and toxic and i got banned for third programs. On another account i made placement, 10 games i was not using chat so i dont think i had a reports, and after 10 games i went sleep, turned on league another day and got banned for using third programs. Only r3nzskin turned on. I never send any files to riot. Maybe a screenshot few months ago.

**Comment by tragedyxxms** [comment]
Try creating a new account that will not be botted. Play as many games as you can, and if you get banned for third party programs let me know.

And about the screenshot, did you use **R3nzSkin** at the time? And did you hide it by the Insert button, or did you send a screenshot with the program shown?

**Comment by hotline1337** [comment]
Of course, it's possible to get banned.
By using this software, you are using it for your responsibility.
There is always a chance to get banned, so far R3nzSkin is safe and undetected.
