### ISSUE TITLE
BAN WAVE!!

### ISSUE THREAD

**Issue by bandyta69** [R3nzTheCodeGOD/R3nzSkin#567]
BECAREFUL WITH R3NZSKIN! MY LAST 2 ACCOUNTS GOT BANNED FOR USING THIRD PROGRAMS, WHILE I HAD ONLY R3NZSKIN OPENED! RIOT DOING BAN WAVES, ALSO MY FRIEND FROM DISCORD HAD SAME!

**Comment by hotline1337** [comment]
Have you used anything else than R3nzSkin? Like an orb bot, etc?

**Comment by NOBODYLOVED** [comment]
It's botted accounts banwave (means accounts lvlupd by bot till 30). R3nz is safe. (just ask for refund the guy who sold you account).

**Comment by bandyta69** [comment]
It was botted accounts, but reason was third programs not botted account. And i was using only r3nzskin

**Comment by hotline1337** [comment]
Not related to the project, R3nzSkin is safe.
