### ISSUE TITLE
Yasuo's tornado and ult sounds not changing

### ISSUE THREAD

**Issue by Naaz-E** [R3nzTheCodeGOD/R3nzSkin#57]
His sound effects for tornado and ult remain the same on all skins.

**Comment by R3nzTheCodeGOD** [comment]
#1

**Comment by Naaz-E** [comment]
There is changed Q sound when tornado is charged and then there's mostly a sound effect that follows. Spirit blossom yasuo 3rd Q should be the most noticeable. The initial Q3 sound remains the same even after changing the skin.
