### ISSUE TITLE
This is a temporary version of 13.13 while waiting for R3nzSkin UPDATE 

### ISSUE THREAD

**Issue by kkk000z** [R3nzTheCodeGOD/R3nzSkin#574]
https://raw.githubusercontent.com/kkk000z/file/main/13-13LOL-MODSKIN.zip

**Comment by XWayZi** [comment]
_String was not recognized as a valid DateTme_

**Comment by kkk000z** [comment]
> _String was not recognized as a valid DateTme_

ignore it and go to MODSKIN

**Comment by nhockan1** [comment]
lúc chết, nó tự đổi về skin mặc định bạn ơi, phải insert chọn lại

**Comment by wanvynk** [comment]
i downloaded it and it says trojan virus beware !

**Comment by S1NJED** [comment]
> i downloaded it and it says trojan virus beware !

it is not a trojan lmao

**Comment by gucan98** [comment]
i get an error message when i start the EXE what can  i do ?

**Comment by VenraUwU** [comment]
for me, it only works in practise tool when im the only player, when i go in a real game it disconnects my game or freezes my game and doesnt work

**Comment by meeezaezaa** [comment]
it only works in practice tool when i go to a real game it does not work

**Comment by gucan98** [comment]
works in real game for me

**Comment by gucan98** [comment]
nvm crashing too

**Comment by daotao123** [comment]
> hin

same

**Comment by hotline1337** [comment]
13.13 Update has been released. Please check the releases.
