### ISSUE TITLE
FIX FOR 13.13 - new SkinID sig

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#575]
replace SkinID sig in memory.hpp with this and recompile:

40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84

**Comment by VenraUwU** [comment]
where is the memory.hpp

**Comment by Ugolek7** [comment]
> where is the memory.hpp

same question

**Comment by prxvatescrxpts** [comment]
> where is the memory.hpp

Inside the source code, R3nzSkin/memory.hpp [https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/main/R3nzSkin/memory.hpp](url)

Change this as mentioned above:
`
{
	"**NEW SIG HERE**"
}, false, true, false, 0, &offsets::AIBaseCommon::SkinId
`

And simply compile, regards.

**Comment by rager123** [comment]
well, can someone compile for us and give us the link directly?

**Comment by nhockan1** [comment]
how to edit, pls more tutorial T_T

**Comment by miqheil** [comment]
> > where is the memory.hpp
> 
> Inside the source code, R3nzSkin/memory.hpp [Click here](https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/eba74d3b5b056d6f31681a3ecd84ccab2c05db9b/R3nzSkin/memory.hpp#L100C5-L100C5)
> 
> Change this as mentioned above: `{ "NEW SIG HERE" }, false, true, false, 0, &offsets::AIBaseCommon::SkinId`
> 
> And simply compile, regards.
> 
> _- Big thanks for the sig, **i4TsU**_

Hi,

Is there easier way to compile other than installing 9 gb compiler and ide?

**Comment by filipslezaklab** [comment]
> 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84

> { "NEW SIG HERE" }, false, true, false, 0, &offsets::AIBaseCommon::SkinId

Compiled with VS2022 Community, fix works.

**Comment by Jejfn** [comment]
> replace SkinID sig in memory.hpp with this and recompile:
> 
> 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84

Tysm, it helped.

**Comment by prxvatescrxpts** [comment]
> Is there easier way to compile other than installing 9 gb compiler and ide?

Sadly but no, it's not python interpreter that you can just run, it requires compilation.

**Comment by Dimmylol** [comment]
> > 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84
> 
> > { "NEW SIG HERE" }, false, true, false, 0, &offsets::AIBaseCommon::SkinId
> 
> Compiled with VS2022 Community, fix works.

Can you send files please?

**Comment by Dimmylol** [comment]
> > replace SkinID sig in memory.hpp with this and recompile:
> > 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84
> 
> Tysm, it helped.

can you send the files please?

**Comment by VenraUwU** [comment]
idk you guys explain it like everyone here is a pro coder. i am a league player nothing more plus i have VS installed

**Comment by filipslezaklab** [comment]
> idk you guys explain it like everyone here is a pro coder. i am a league player nothing more plus i have VS installed

This issue is just pointing out what is wrong so the author can fix it faster.
You don't need to be a pro coder to change a value from one to another.
You can pull up youtube on how to build files from project in VS.

--- how to, explained more ---

- Download VS2022 Community
- Download repository with `git` like explained in README.md
- If you have any anti virus software running on PC, like windows defender, make sure you add an exclusion for the whole repository folder, it will mark built files as dangerous BCS of how this program injects into league.
- When opening VS, click open project and point to the file `R3nzSkin.sln` that is inside root repository directory.
- In top bar of IDE there is a section with `x64` make sure you select options `RiotGamesServers` and `x64`
- In `Solution Explorer` found typically on the right side of the IDE, find `Memory.hpp` file and open it.
- Now value between `"` in line where it ends with `&offsets::AIBaseCommon::SkinId` like this:
```
			{
				"40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84"
			}, false, true, false, 0, &offsets::AIBaseCommon::SkinId
```
- Save changes and back in Solution explorer right click `R3nzSkin` and then build, same with `R3nzSkin_Injector`. 
- After that if build was successful, there will be `Release` directory inside repository root, there you will find compiled files, now you just need to run `.exe` and it will work again.

**Comment by meeezaezaa** [comment]
plz viedio tutorial it doesnt work for me

**Comment by Dimmylol** [comment]
> > idk you guys explain it like everyone here is a pro coder. i am a league player nothing more plus i have VS installed
> 
> This issue is just pointing out what is wrong so the author can fix it faster. You don't need to be a pro coder to change a value from one to another. You can pull up youtube on how to build files from project in VS.
> 
> --- how to, explained more ---
> 
> * Download VS2022 Community
> * Download repository with `git` like explained in README.md
> * If you have any anti virus software running on PC, like windows defender, make sure you add an exclusion for the whole repository folder, it will mark built files as dangerous BCS of how this program injects into league.
> * When opening VS, click open project and point to the file `R3nzSkin.sln` that is inside root repository directory.
> * In top bar of IDE there is a section with `x64` make sure you select options `RiotGamesServers` and `x64`
> * In `Solution Explorer` found typically on the right side of the IDE, find `Memory.hpp` file and open it.
> * Now change value between `"` in line where it ends with `&offsets::AIBaseCommon::SkinId` like this:
> 
> ```
> 			{
> 				"40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84"
> 			}, false, true, false, 0, &offsets::AIBaseCommon::SkinId
> ```
> 
> * Save changes and back in Solution explorer right click `R3nzSkin` and then build, same with `R3nzSkin_Injector`.
> * After that if build was successful, there will be `Release` directory inside repository root, there you will find compiled files, now you just need to run `.exe` and it will work again.

could you just send files?

**Comment by VenraUwU** [comment]
> > idk you guys explain it like everyone here is a pro coder. i am a league player nothing more plus i have VS installed
> 
> This issue is just pointing out what is wrong so the author can fix it faster. You don't need to be a pro coder to change a value from one to another. You can pull up youtube on how to build files from project in VS.
> 
> --- how to, explained more ---
> 
>     * Download VS2022 Community
> 
>     * Download repository with `git` like explained in README.md
> 
>     * If you have any anti virus software running on PC, like windows defender, make sure you add an exclusion for the whole repository folder, it will mark built files as dangerous BCS of how this program injects into league.
> 
>     * When opening VS, click open project and point to the file `R3nzSkin.sln` that is inside root repository directory.
> 
>     * In top bar of IDE there is a section with `x64` make sure you select options `RiotGamesServers` and `x64`
> 
>     * In `Solution Explorer` found typically on the right side of the IDE, find `Memory.hpp` file and open it.
> 
>     * Now change value between `"` in line where it ends with `&offsets::AIBaseCommon::SkinId` like this:
> 
> 
> ```
> 			{
> 				"40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84"
> 			}, false, true, false, 0, &offsets::AIBaseCommon::SkinId
> ```
> 
>     * Save changes and back in Solution explorer right click `R3nzSkin` and then build, same with `R3nzSkin_Injector`.
> 
>     * After that if build was successful, there will be `Release` directory inside repository root, there you will find compiled files, now you just need to run `.exe` and it will work again.

Again i dont know what half of this means, in the README it says "git clone --recursive https://github.com/R3nzTheCodeGOD/R3nzSkin.git" so i copied that and put it in GIT, so far so good, it spits out

Cloning into 'R3nzSkin'...
remote: Enumerating objects: 1362, done.
remote: Counting objects: 100% (876/876), done.
remote: Compressing objects: 100% (292/292), done.
remote: Total 1362 (delta 684), reused 606 (delta 579), pack-reused 486
Receiving objects: 100% (1362/1362), 1.03 MiB | 984.00 KiB/s, done.
Resolving deltas:  17% (166/975)
Resolving deltas: 100% (975/975), done.

now how do i download the repository? then next step where is the root repository directory, next step "in the top bar of IDE" what is ide. Also i understand that this issue is mainly for the author

**Comment by filipslezaklab** [comment]
> now how do i download the repository?
Cloning is a process of downloading git repository into your disk, bcs you "clone" from repository.
So essentially you have now the whole repository in R3nzSkin directory exactly where you executed git command.
>  what is ide
IDE stands for integrated development environment and it's basically what you see after opening project in VS

**Comment by Fi7rast** [comment]
can you please send the files directly or a make video tutorial it will be really easier , the most of us here are just still confused

**Comment by filipslezaklab** [comment]
> can you please send the files directly or a make video tutorial it will be really easier , the most of us here are just still confused

Please don't accept nor run any executables from random people. If you are not comfortable with building this project yourself just wait for an official release.

**Comment by gucan98** [comment]
> Cloning is a process of downloading git repository into your disk, bcs you "clone" from repository.
So essentially you have now the whole repository in R3nzSkin directory exactly where you executed git command.


Ok i understand  but where do i find the  whole repository that is downloaded by GIT that i have to put it back in VS.

**Comment by Dimmylol** [comment]
> > Cloning is a process of downloading git repository into your disk, bcs you "clone" from repository.
> > So essentially you have now the whole repository in R3nzSkin directory exactly where you executed git command.
> 
> Ok i understand but where do i find the whole repository that is downloaded by GIT that i have to put it back in VS.

https://discord.gg/Xk65Frks i found fixed r3nz here

**Comment by Jejfn** [comment]
> > > replace SkinID sig in memory.hpp with this and recompile:
> > > 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84
> > 
> > 
> > Tysm, it helped.
> 
> can you send the files please?



> 40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84



> > > idk you guys explain it like everyone here is a pro coder. i am a league player nothing more plus i have VS installed
> > 
> > 
> > This issue is just pointing out what is wrong so the author can fix it faster. You don't need to be a pro coder to change a value from one to another. You can pull up youtube on how to build files from project in VS.
> > --- how to, explained more ---
> > 
> > * Download VS2022 Community
> > * Download repository with `git` like explained in README.md
> > * If you have any anti virus software running on PC, like windows defender, make sure you add an exclusion for the whole repository folder, it will mark built files as dangerous BCS of how this program injects into league.
> > * When opening VS, click open project and point to the file `R3nzSkin.sln` that is inside root repository directory.
> > * In top bar of IDE there is a section with `x64` make sure you select options `RiotGamesServers` and `x64`
> > * In `Solution Explorer` found typically on the right side of the IDE, find `Memory.hpp` file and open it.
> > * Now change value between `"` in line where it ends with `&offsets::AIBaseCommon::SkinId` like this:
> > 
> > ```
> > 			{
> > 				"40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? ? 8B D7 41 BA ? 00 00 00 66 0F 1F 84"
> > 			}, false, true, false, 0, &offsets::AIBaseCommon::SkinId
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Save changes and back in Solution explorer right click `R3nzSkin` and then build, same with `R3nzSkin_Injector`.
> > * After that if build was successful, there will be `Release` directory inside repository root, there you will find compiled files, now you just need to run `.exe` and it will work again.
> 
> could you just send files?
there u go
https://drive.google.com/drive/folders/1ALxIPQqiOyHLqZJxU67UItwxcSc7islg?usp=sharing

**Comment by J-EnJay** [comment]
Great. It worked. My friend, can you tell me how you got the solution?

**Comment by meeezaezaa** [comment]
bruh they keep telling me zipping failed

**Comment by hotline1337** [comment]
13.13 Update has been released. Please check the releases.
