### ISSUE TITLE
failed to find pattern

### ISSUE THREAD

**Issue by sebo12h** [R3nzTheCodeGOD/R3nzSkin#577]
https://imgur.com/bLsreyR

what happend?

**Comment by Aeristoff** [comment]
here, take this update 
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/11895435/R3nzSkin.zip)

**Comment by kuba031008** [comment]
New update, also the guy sent a virus, don't download

**Comment by sebo12h** [comment]
okay thanks

**Comment by brokenfire321** [comment]
it understands some files like a virus, but it may not be a virus, I didn't detect it at all

**Comment by kuba031008** [comment]
> it understands some files like a virus, but it may not be a virus, I didn't detect it at all

the original renz skin is always detected by 3-5 things, this one is detected by far too many to be a false positive
