### ISSUE TITLE
Here's The updated R3nzSkin inj/dll it works ,enjoy guys

### ISSUE THREAD

**Issue by Dumyofficial800** [R3nzTheCodeGOD/R3nzSkin#579]
https://zippysha.re/q6R0e0zdzb/R3nzSkin_dll (DLL FILE)

https://zippysha.re/r9Rae1z8z7/R3nzSkin_Injector_exe (EXE File) 

Drag them both in League of Legendes Directory 

Enter the game and press Insert ,enjoy

**Comment by hotline1337** [comment]
13.13 Update has been released. Please check the releases.

**Comment by Mound1r** [comment]
thanksss @hotline1337 <3

**Comment by Shenie07** [comment]
fixed <3 ty
