### ISSUE TITLE
NOT WOKRING IN CHINA SERVER

### ISSUE THREAD

**Issue by rkdrlgh22** [R3nzTheCodeGOD/R3nzSkin#58]
![캡처3](https://user-images.githubusercontent.com/99127548/154061011-a3ef47da-575c-4c3d-8f16-7090c13ae08a.PNG)

actually not working skin changer in china srever

**Comment by Clownsw** [comment]
It can work normally in China server, you may need special means to inject it

**Comment by rkdrlgh22** [comment]
> 그것은 중국 서버에서 정상적으로 작동할 수 있습니다, 당신은 그것을 주입하기 위해 특별한 수단이 필요할 수 있습니다

I already used DX9 but actually not wokring

**Comment by R3nzTheCodeGOD** [comment]
You can hijack a legitimate dll.

For example, you can replace **LogitechLed.dll** with **R3nzSkin.dll** in the game's files, so that every time you enter the game, the cheat is injected automatically. (I do not recommend this method, but you do not need an injector in this method.)
