### ISSUE TITLE
when i enter a game it just keeps sending me an error and if i click  ok on the error it comes back again and again i tried reinstalling it and still happens can someone help me 

### ISSUE THREAD

**Issue by Bo7s7s** [R3nzTheCodeGOD/R3nzSkin#580]

**Comment by Bo7s7s** [comment]
yea  idk why is this happening it used to work  just fine for  me before that

**Comment by Mound1r** [comment]
I had the same problem, u need to uninstall all files, downloading the new update from R3nzSkin from 10min ago, open ur client, go to training tool and open the apps with injector, click start and normally it will be fine

**Comment by Bo7s7s** [comment]
what are the  files?

**Comment by magoxado** [comment]
closeable ticket, solved.

**Comment by Mound1r** [comment]
R3nZSkin here on github, league of legends made a patch so you have to download the new version of the skin changer

**Comment by hotline1337** [comment]
13.13 Update has been released. Please check the releases.
