### ISSUE TITLE
Interrupted:Network error

### ISSUE THREAD

**Issue by olojanicic** [R3nzTheCodeGOD/R3nzSkin#583]
i am trying for past hour to download R3nzSkin but every time I get Interrupted:Network error and its not that my network isnt working cuz i can play league or valorant or watch youtube twitch but it just wont download if anyone know how to fix it please help.

**Comment by Fi7rast** [comment]
you can download it from a discord server and this server contains even more and all the R3nzSkin version so i think you don't need to come to github at all again , here's the link : https://discord.gg/CbDFC64u
