### ISSUE TITLE
failed to find pattern : 40 38 BB 

### ISSUE THREAD

**Issue by Eon7s** [R3nzTheCodeGOD/R3nzSkin#585]
bro I searched so much and I found nothiing

**Comment by Necromancerx9** [comment]
I got this error too
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/66694283/c52533cc-80c9-4df2-a20e-ade1aeaad817)

**Comment by LeonimusTTV** [comment]
We need to wait for an update of the injector bc of the new patch from rito, just be patient

**Comment by miqheil** [comment]
Update has been made/pushed. Just download from [Release](https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v3.0.9) page.
