### ISSUE TITLE
Where to find the correct offset

### ISSUE THREAD

**Issue by lausannel** [R3nzTheCodeGOD/R3nzSkin#587]
Could anyone in the team explain to me, every time the LOL updates, how to find the correct offset?

**Comment by HadockKali** [comment]
> Could anyone in the team explain to me, every time the LOL updates, how to find the correct offset?

The process is quite complicated if you are new to reversing and coding and it takes a bit of effort, here's how to do it from A to Z, keep in mind the guide is targeting some other issues but in the process of looking through the tutorial you will discover how to get and how to update offsets.

All credits to UKCS: https://www.unknowncheats.me/forum/league-of-legends/567734-beginner-tutorial.html

**Comment by lausannel** [comment]
> > Could anyone in the team explain to me, every time the LOL updates, how to find the correct offset?
> 
> The process is quite complicated if you are new to reversing and coding and it takes a bit of effort, here's how to do it from A to Z, keep in mind the guide is targeting some other issues but in the process of looking through the tutorial you will discover how to get and how to update offsets.
> 
> All credits to UKCS: https://www.unknowncheats.me/forum/league-of-legends/567734-beginner-tutorial.html

Quite informative! Thanks!
