### ISSUE TITLE
遇到了报错

### ISSUE THREAD

**Issue by Cuiyim** [R3nzTheCodeGOD/R3nzSkin#588]
![1688053653865](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/51844650/8189151c-1efc-4f49-a73f-eea44d2e0e44)

![1688053881262](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/51844650/b105057f-321c-469f-b249-b4778c4fe9fb)

**Comment by hotline1337** [comment]
rename the hid.dll to R3nzSkin.dll
