### ISSUE TITLE
Something wrong about recognizing DateTime？

### ISSUE THREAD

**Issue by CharlesYHT** [R3nzTheCodeGOD/R3nzSkin#594]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/138274881/973bf38f-4645-4a10-b8a8-52239ab16d5b)

**Comment by Qilinq** [comment]
I have the same problem  
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/138016060/5ec2857e-6a6d-4287-80c6-af61266eabbc)

**Comment by hotline1337** [comment]
make sure the R3nzSkin.dll is in the same directory as the injector.
