### ISSUE TITLE
String and Pattern ERROR. 

### ISSUE THREAD

**Issue by Ackqib** [R3nzTheCodeGOD/R3nzSkin#595]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/79501927/1fea6304-d417-4e21-8254-5a316248bfce)
I've been getting these errors, and the skin changer hasn't been working. I re-installed multiple times.

**Comment by hotline1337** [comment]
Make sure the R3nzSkin.dll is in the same directory as the injector.
