### ISSUE TITLE
Sometimes I am experiencing some micro stutters while the skin changer is working. Is there a fix for it?

### ISSUE THREAD

**Issue by sshindae** [R3nzTheCodeGOD/R3nzSkin#596]
A notable moment was hitting Illaoi's E onto someone it makes my game stutter for a split second. Is there a fix to overall micro-stutters here and there?

**Comment by DonBlaze** [comment]
I also get huge FPS drops while using the skin changer is on.

**Comment by mitussss** [comment]
Same. When it happens, I press alt tab and it helps.

**Comment by zvbt** [comment]
Enabling DirectX 9 should fix your problem
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/61088560/f00ff986-9c4a-4ecc-aa12-54a6fae16fe9)

**Comment by HadockKali** [comment]
This depends on your overall system. Enabling DX9 (it's an old DirectX version that usually works better on very old hardware) does not necessarily mean better performance. DX 11 is the standard for league for a reason, it work's better and it's faster. It's normal that you have a performance drop.

**Comment by prxvatescrxpts** [comment]
Basing on the code I've seen and worked with this skin changer is active only in 2 cases:

- 1st when game started and you injected it, it will change your skin on injection and that's it.
- 2nd is when you change the skin via imgui menu.

In any other case this dll just idles doing **nothing**, which shouldn't cause any lags.
However if you experience such thing I've nothing to recommend, just letting you know how it works in general.

**Comment by potentate** [comment]
this probably won't help much because its been over a month. BUT the fix for me was just holding down pgup and holding pgdown so youd load in ALL the skins, after i did that it stopped stuttering for me.

**Comment by Reraz** [comment]
Strange, i just have stuttering when the skin window is opening, nothing else.

**Comment by hotline1337** [comment]
ur CPU might be heavily utilized, close useless programs or just upgrade the cpu.
