### ISSUE TITLE
Bug: Ekko goes invisible after he uses ult

### ISSUE THREAD

**Issue by DonBlaze** [R3nzTheCodeGOD/R3nzSkin#597]
Hi guys, when i set the ekko skin to default (i can't tell any of these new skins so i prefer to play vs default skin)
So when i set the ekko skin to default, it all works good until ekko uses ult, after that he goes invisible for the rest of the game (unless i change the skin)
just a small bug i thought you should know.
Thanks a lot for all of your efforts

**Comment by failure1975** [comment]
what r3nzskin are u currently using? are u using the temporary one?

**Comment by DonBlaze** [comment]
> what r3nzskin are u currently using? are u using the temporary one?

I'm using the latest version that was uploaded 4 days ago, v3.0.9
But i noticed this issue a couple of weeks ago, so I don't think it has anything to do with the current version.
