### ISSUE TITLE
I cant download the file

### ISSUE THREAD

**Issue by iquehb7** [R3nzTheCodeGOD/R3nzSkin#599]
I am using opera gx btw, but I have tried google, firefox even fk microsoft edge but still, every time I try to download the renz file the download gets flagged and I cant fisnish the download, and I havent figured out any way to finish the it. Any help would be appreciated.

**Comment by OssieFromDK** [comment]
This is cause of the .exe injector file, windows thinks its a virus, either download the source and compile, or turn off real-time protection from Windows Defender.

Virus & Threat Protection -> Manage Settings -> Real-Time Protection off

Its nothing to do with your browser :)
