### ISSUE TITLE
ban possibility?

### ISSUE THREAD

**Issue by Lestueurs** [R3nzTheCodeGOD/R3nzSkin#601]
Hello, I am writing to you to find out if there are any chances of getting banned?

**Comment by xenophullus** [comment]
> Hello, I am writing to you to find out if there are any chances of getting banned?

just dont stream using it...

**Comment by Xayayia** [comment]
0 unless you play against neeko 1 hour game and everytime she comes to u as minion u always hit her out of all minions

**Comment by eienjdn** [comment]
> 0 unless you play against neeko 1 hour game and everytime she comes to u as minion u always hit her out of all minions

you can do that?
so free

**Comment by OssieFromDK** [comment]
There is always a risk of being banned using third party programs editing memory, but you probably won't be
