### ISSUE TITLE
cant find file

### ISSUE THREAD

**Issue by dowla123** [R3nzTheCodeGOD/R3nzSkin#607]
when i go to riot games file i cant find a file wiht smile icon to open it

**Comment by dowla123** [comment]
i meant when i open league of legends file

**Comment by HadockKali** [comment]
Check your anti-virus software, the binary file is flagged as a false-positive, it might delete it before execution. Make sure to download the binary from the **Release** section of this repository, extract the files in a folder and then run the executable. Take care!

**Comment by mojoboy17** [comment]
> Check your anti-virus software, the binary file is flagged as a false-positive, it might delete it before execution. Make sure to download the binary from the **Release** section of this repository, extract the files in a folder and then run the executable. Take care!

what do you mean by run the executable, I downloaded and extracted the file and I cant find the application itself 
please help !!

**Comment by HadockKali** [comment]
> > Check your anti-virus software, the binary file is flagged as a false-positive, it might delete it before execution. Make sure to download the binary from the **Release** section of this repository, extract the files in a folder and then run the executable. Take care!
> 
> what do you mean by run the executable, I downloaded and extracted the file and I cant find the application itself 
> please help !!
> 

Turn off your anti-virus software, it's detecting the application as a false-positive, that might cause the system to delete it upon download. Or simply add an exception to the Download folder.
