### ISSUE TITLE
i dont know how to inject

### ISSUE THREAD

**Issue by Enruk12** [R3nzTheCodeGOD/R3nzSkin#610]
idk how to inject the dll or where i can find the dll and what suold i do 
i hope some hlep :D

**Comment by HadockKali** [comment]
Hello, if you would like some help, please add me on Discord: hadock

**Comment by HadockKali** [comment]
> idk how to inject the dll or where i can find the dll and what suold i do i hope some hlep :D

Everything you might need is found under the **Release** section, in the archive, the DLL and the Injector.

**Comment by lpszcpa** [comment]
@HadockKali Why can't I search for your username：hadock

**Comment by HadockKali** [comment]
> 

You might have searched with a space, the username is correct. 
Or if I accepted your friend request and you didn't respond within 30 minutes I might have unfriended you, I do that kind of issue when I have time and IF I have time, so don't expect 24/7 support. Thank you. If you still cannot add me, leave your Discord username and I will add you.
