### ISSUE TITLE
request to randomize window "R3nzSkin"

### ISSUE THREAD

**Issue by pmetemp** [R3nzTheCodeGOD/R3nzSkin#612]
I use cs-lol manager to use korean font but for whatever reason the dev decided to block off skin changers from running at the same time.

https://github.com/LeagueToolkit/cslol-manager/commit/7715ce6b3a76663ddd8e7f9779e7514f7d8b4fc5

Perhaps you could implement a bypass as the program only looks for the name R3nzSkin.

**Comment by devilExE3** [comment]
#613

**Comment by hotline1337** [comment]
944b7a92c37f4430e5accfb2b29ac1e7f46c2055
