### ISSUE TITLE
R3nzSkin The state is not injected

### ISSUE THREAD

**Issue by lpszcpa** [R3nzTheCodeGOD/R3nzSkin#615]
After opening the program, there is no pop-up window to enter the game, and the state is not injected

**Comment by lpszcpa** [comment]
Even if you run it with administrator privileges, you can't open the main program

**Comment by HadockKali** [comment]
> After opening the program, there is no pop-up window to enter the game, and the state is not injected

Have you pressed the "START" button after starting the executable? Is your anti-virus software disabled? It might prevent it from working correctly. Contact me on Discord if the issue persists: hadock
Have a good day!
