### ISSUE TITLE
Injector Name Change?

### ISSUE THREAD

**Issue by OssieFromDK** [R3nzTheCodeGOD/R3nzSkin#616]
https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/main/R3nzSkin_Injector/Injector.cpp#L223C1-L224C1

Why is this code implemented, what purpose does changing the injectors name on startup serve? Just wondering

**Comment by hotline1337** [comment]
Antivirus detection avoidance: Some malware or malicious software may attempt to modify the name of its executable file in an effort to avoid being detected by antivirus software. To find and stop known threats, antivirus software frequently utilizes signature-based detection or behavioral analysis. Malware producers try to make it more challenging for antivirus solutions to detect and block their harmful code by often altering the name of the executable.

Anticheat systems by-passing: When playing video games, some gamers may try to alter the executable name of the game or the cheat software that it uses. Anticheat software usually keeps an eye on the game's files and processes to find cheating or illegal alterations. By tricking the anticheat system, changing the executable name may assist cheat makers or users in avoiding detection for a while.
