### ISSUE TITLE
failed to find pattern 40 38 BB ?? 00 00 00 66 C7 83 ? ?

### ISSUE THREAD

**Issue by icantcode7** [R3nzTheCodeGOD/R3nzSkin#618]
i tried somethings but i didnt find anything that works 
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/139304402/703d5a0c-889e-4c99-b67d-7ebc3ef674be)

**Comment by hotline1337** [comment]
Make sure you are using the newest version of R3nzSkin.

**Comment by icantcode7** [comment]
i fixed it, i just got de skin id code from 3.0.8 and switched on the memory hpp
