### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by sdfgdshgF** [R3nzTheCodeGOD/R3nzSkin#620]
I got banned for 3rd party app, Im wondering did this cause it or https://github.com/Riotphobia/LobbyReveal

ty

**Comment by sdfgdshgF** [comment]
this is the acc https://www.op.gg/summoners/na/adcadcadc

**Comment by HadockKali** [comment]
> I got banned for 3rd party app, Im wondering did this cause it or https://github.com/Riotphobia/LobbyReveal
> 
> ty

R3nzSkin is not yet detected. On the other hand, the tool you seem to have used is now blacklisted by Riot, which caused your ban. For an alternative and safe solution try KBotExt by kebs, it's very up-to-date and supported, as for the detection vectors it was not blacklisted and will never be as the developer removed such detection vectors. Have a good day!
