### ISSUE TITLE
[request] toggle for default skin for all other players & store skin preferences

### ISSUE THREAD

**Issue by pmetemp** [R3nzTheCodeGOD/R3nzSkin#621]
As someone who always disables all skins it'd be nice to have a toggle option for the "no skin except local player" instead of doing it every game.

I've also had preselected skins wiped and reverted to "Default" after updates a few times. Maybe storing skin preferences somewhere on the computer that the program can load.

**Comment by Leshu7w7** [comment]
I agree with the fact of having a toggle button for all enemies default skin.

**Comment by hotline1337** [comment]
Closing due to Vanguard coming to League of Legends.

**Comment by Leshu7w7** [comment]
But there are skin changers on Valorant, why not continue with this project?
