### ISSUE TITLE
Is there a way to inject skins from PBE and play it on live, when it only available on PBE?

### ISSUE THREAD

**Issue by umythmaker** [R3nzTheCodeGOD/R3nzSkin#624]
Is there a way to inject skins from PBE and play it on live, when it only available on PBE?

**Comment by krukuhehe** [comment]
No, PBE and Live Servers are different. R3nzSkin cannot find the resources of the skins on the Live Servers. 



However, if you are that **desperate**, you can ask some hidden custom skin modders to help you.

**Comment by umythmaker** [comment]
hidden custom skin modders?
