### ISSUE TITLE
Just got perma banned

### ISSUE THREAD

**Issue by leonardo-vic3nte** [R3nzTheCodeGOD/R3nzSkin#628]
I've allways used the tool without any problems. But today i got perma banned for using "a thrid party application". And this r3nzskin was the only thing that i was using.

Is this something new? Or happens sometimes?

**Comment by victorfgomees** [comment]
I got perma too, right now, i've only used r3nzskin.

**Comment by xenophullus** [comment]
> I got perma too, right now, i've only used r3nzskin
while using the updated version>?

**Comment by victorfgomees** [comment]
> > I got perma too, right now, i've only used r3nzskin
> > while using the updated version>?

yes, downloaded today the update

**Comment by xenophullus** [comment]
> > > I got perma too, right now, i've only used r3nzskin
> > > while using the updated version>?
> 
> yes, downloaded today the update
i guess that thing it is...i havent used the newer one

**Comment by zackech** [comment]
i got perma too wtf guys dont use this app

**Comment by xenophullus** [comment]
> i got perma too wtf guys dont use this app

Omy im scared, stopping using it now...mbye gonna the end of skin changer...

**Comment by kiddovn** [comment]
I didn't even notice there was an update at first while using an older version, when I turn it on it announces something like an invalid date time, yall got banned for using the updated version?

**Comment by Sentilz** [comment]
I didn't get banned even using the newest version, i think bc of the time of release it was more detectable for league of legends anty cheat. But to be safe don't use it untill next update because we don't know how powerfull is league of legends anty cheat

**Comment by Skeley01** [comment]
> I've allways used the tool without any problems. But today i got perma banned for using "a thrid party application". And this r3nzskin was the only thing that i was using.
> 
> Is this something new? Or happens sometimes?

On what server?

**Comment by leonardo-vic3nte** [comment]
> On what server?

Brazillian, but idk if that makes a difference. The version i used was not the updated one, so that was my fault. I'm just trying to figure out if someone got banned with the updated version.

**Comment by Syrenaz** [comment]
Dude,I was also banned just now.

**Comment by Syrenaz** [comment]
> Dude,I was also banned just now.

banned for using "a thrid party application"

**Comment by leonardo-vic3nte** [comment]
>banned for using "a thrid party application"

Using the updated version?

**Comment by Syrenaz** [comment]
> > 因使用“第三方应用程序”而被禁止
> 
> 使用更新版本？

no,the same version as you used.I didnt even know there was an update yesterday.

**Comment by leonardo-vic3nte** [comment]
> no,the same version as you used.I didnt even know there was an update yesterday.

Yeah, guess that's our fault then. Need to keep an eye to stop using and wait for the update once a new patch drops.

But i'm still waiting to see if anyone with the updated version got banned or not

**Comment by KaSaYeN** [comment]
I updated skin changer and got banned aswell so its not about the version

**Comment by leonardo-vic3nte** [comment]
> I updated skin changer and got banned aswell so its not about the version It didnt even take too long, bcs i played only 1 game

If that's true, then that's a shame. I used to love using this tool bcz some skins have better animations and just feel better to play with

**Comment by Heliox01** [comment]
I don't know today I did one game with skin changer but no ban,I'll try to play with a new account and see if I get banned

**Comment by sdfgdshgF** [comment]
has something like this ever happen before?

**Comment by mitussss** [comment]
No, it's the first time. Let's wait and see from the dev what they say.

**Comment by slajdenzicek** [comment]
Used and perm banned

**Comment by leonardo-vic3nte** [comment]
> Used and perm banned

Updated version?

**Comment by slajdenzicek** [comment]
> > Used and perm banned
> 
> Updated version?

yep

**Comment by RinF1n** [comment]
Been using it the whole day and yesterday on EUW. And I have gotten no bans. Although i did use a custom build where all i did was change the aibasecommon::skinid signature to "40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? 38 8B D7 41 ? 01 00 00 00 66 0f 1F 84 00 00 00 00 00 48" (from the pull requests by maofeichao11)

**Comment by leonardo-vic3nte** [comment]
> Been using it the whole day and yesterday on EUW. And I have gotten no bans. Although i did use a custom build where all i did was change the aibasecommon::skinid signature to "40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? 38 8B D7 41 ? 01 00 00 00 66 0f 1F 84 00 00 00 00 00 48" (from the pull requests by maofeichao11)

Could you please provide a link with the compiled versions with these changes? If its not a problem... I would need to install Vs just to change and recompiled it, it would be a pain for my slow pc

**Comment by sdfgdshgF** [comment]
updated  verision 20mins ago but i cant open it

**Comment by victorfgomees** [comment]
@leonardo-vic3nte a conta que vc tomou ban era smurf? parece tb que uns amigos que compraram conta em site que upa com bot tomaram ban ontem tb

**Comment by leonardo-vic3nte** [comment]
> @leonardo-vic3nte a conta que vc tomou ban era smurf? parece tb que uns amigos que compraram conta em site que upa com bot tomaram ban ontem tb

@victorfgomees Era sim, só que eu tenho umas 5 smurf, não tomei em ban em nenhuma. Foi por causa do app mesmo...

**Comment by Bl1nterS** [comment]
> > Been using it the whole day and yesterday on EUW. And I have gotten no bans. Although i did use a custom build where all i did was change the aibasecommon::skinid signature to "40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 ? 38 8B D7 41 ? 01 00 00 00 66 0f 1F 84 00 00 00 00 00 48" (from the pull requests by maofeichao11)
> 
> Could you please provide a link with the compiled versions with these changes? If its not a problem... I would need to install Vs just to change and recompiled it, it would be a pain for my slow pc

@leonardo-vic3nte here's my compiled version with the same change, tell me if it's any better for you
[Release.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12123050/Release.zip)

**Comment by RinF1n** [comment]
> > @leonardo-vic3nte a conta que vc tomou ban era smurf? parece tb que uns amigos que compraram conta em site que upa com bot tomaram ban ontem tb
> 
> @victorfgomees Era sim, só que eu tenho umas 5 smurf, não tomei em ban em nenhuma, além da que relatei. Foi por causa do app mesmo...
> 
> @edit https://twitter.com/RiotK3o/status/1682122977050238980 You all got banned on smurfs? Maybe it was a coincidence and it was not r3nzskin fault

I did also test it on a botted smurf account and i have had no issues for now, maybe the only issue was that the signature pattern wasn't accurate enough and was giving addresses it shouldn't have?

**Comment by Souplax1** [comment]
Gj 2 banned accounts

**Comment by HackPC** [comment]
how long to get perma ban? i use un v3.1.1 13.14 Update yesterday and i did't read this topic and use the lastest version today ?
i'm use a thai server

**Comment by KaSaYeN** [comment]
From what i heard some people also got banned for botted accounts and my account actually was botted so maybe thats why i got banned, maybe not bcs of skin changer

**Comment by pmetemp** [comment]
It most likely is from the recent botted account ban wave. I've used it on non botted account with no issue. Still going to refrain from using it until there's confirmation.

**Comment by SimonCarabajal** [comment]
why when i download it i got my antivirus saying that its ransomware lol

**Comment by Ali229** [comment]
> why when i download it i got my antivirus saying that its ransomware lol 

False positive due to how it works, also unrelated to the issue

**Comment by cariocacpp** [comment]
> its safe to use R3nzSkin? i dont want to get banned

its safe ,botted accounts are getting banned.

**Comment by Bl1nterS** [comment]
> why when i download it i got my antivirus saying that its ransomware lol

@SimonCarabajal because it injects a dll to make its own code into the game and your computer is pretty much like "ayo that doesn't seem too great what if it's going to harm us" so it flags it as malicious
Download the code and compile it for yourself, since it's open source you can see if there's any malware or any code that could harm your computer and delete it

**Comment by qq1403498204** [comment]
封号是正常的，谢谢！

**Comment by KinXandor** [comment]
> > its safe to use R3nzSkin? i dont want to get banned
> 
> its safe ,botted accounts are getting banned.

interesting that i havent got banned on the botted accounts for months and now its banning me while im playing with the skinchanger, kinda random isnt it?

**Comment by cariocacpp** [comment]
> interesting that i havent got banned on the botted accounts for months and now its banning me while im playing with the skinchanger, kinda random isnt it?

this new update is banning the accounts uploaded with bot this is not random, the skinchanger is safe, yesterday and today on the main account xD

**Comment by Zeanz2** [comment]
Bro im using this R3nzskin 2021 and untill im not getting banned

**Comment by Jenkiessss** [comment]
so if i use it now, I will not get banned ye ?

**Comment by Magicfenixx** [comment]
Hello, guys, what is botted account?

**Comment by WitheredRose7** [comment]
> Hello, guys, what is botted account?

Account leveled up to level 30 using a bot playing only vs AI games and then sold cheaply.

**Comment by Magicfenixx** [comment]
> > Hello, guys, what is botted account?
> 
> Account leveled up to level 30 using a bot playing only vs AI games and then sold cheaply.

Oooh, thank you, so if i never used such thing i can safely use r3nz?

**Comment by WitheredRose7** [comment]
> > > Hello, guys, what is botted account?
> > 
> > 
> > Account leveled up to level 30 using a bot playing only vs AI games and then sold cheaply.
> 
> Oooh, thank you, so if i never used such thing i can safely use r3nz?

There is always a risk in using 3rd party applications that's not endorsed by RIOT, but at this moment there is no case of anyone getting banned for using R3nzSkin, so you should be safe. Only action being taken by RIOT right now is against botted accounts.

**Comment by KinXandor** [comment]
> > > > Hello, guys, what is botted account?
> > > 
> > > 
> > > Account leveled up to level 30 using a bot playing only vs AI games and then sold cheaply.
> > 
> > 
> > Oooh, thank you, so if i never used such thing i can safely use r3nz?
> 
> There is always a risk in using 3rd party applications that are not endorsed by RIOT, but at this moment there is no case of anyone getting banned for using R3nzSkin, so you should be safe. Only action being taken by RIOT right now is against botted accounts.

okay, ill try it main

**Comment by tuliocf3** [comment]
i got permabanned in two accounts, but i dont know if its caused by r3nz or it is because my accs are botted.

**Comment by cariocacpp** [comment]
> i got permabanned in two accounts, but i dont know if its caused by r3nz or it is because my accs are botted.

estou jogando na minha conta principal e por enquanto nada aconteceu ,quando eu vi esse post sabia que tinha nada haver com o skinchanger, esta havendo uma onda de bans de contas upadas com bot , apenas provocaram histeria atoa.

**Comment by tuliocf3** [comment]
> > i got permabanned in two accounts, but i dont know if its caused by r3nz or it is because my accs are botted.
> 
> estou jogando na minha conta principal e por enquanto nada aconteceu ,quando eu vi esse post sabia que tinha nada haver com o skinchanger, esta havendo uma onda de bans de contas upadas com bot , apenas provocaram histeria atoa.

entendi, as minhas duas contas q tomaram ban eram contas upadas com bot

**Comment by hotline1337** [comment]
R3nzSkin is safe. Played with the latest release on my main account for 2 days now. It was for sure botted account ban wave.
