### ISSUE TITLE
Is ban issue gone?

### ISSUE THREAD

**Issue by mariostart01** [R3nzTheCodeGOD/R3nzSkin#633]
Saw a lot of ppl get perma banned so i was wondering is it solved

**Comment by maxxxcoder** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/80669598/3ff42a82-6746-42b7-95e7-5e6f69d31830)
Just got perma banned

**Comment by cariocacpp** [comment]
> ![image](https://user-images.githubusercontent.com/80669598/255255391-3ff42a82-6746-42b7-95e7-5e6f69d31830.png) Just got perma banned

smurf account?

**Comment by maxxxcoder** [comment]
> > ![image](https://user-images.githubusercontent.com/80669598/255255391-3ff42a82-6746-42b7-95e7-5e6f69d31830.png) Just got perma banned
> 
> smurf account?

Bought bot account level 30 almost 4 months ago

**Comment by WitheredRose7** [comment]
> 

Botted accounts are getting banned right now.

**Comment by maxxxcoder** [comment]
> Botted accounts are getting banned right now.

damn, sad :(

**Comment by mariostart01** [comment]
So its not about r3nz skin?

**Comment by maxxxcoder** [comment]
> So its not about r3nz skin?

no clue, i bought smurf account with my friend to play on another level, we bout 2 accs from same shop and played only together till today, i used r3nzskin, my frined not, i got banned right after the game and he is still not banned. Possible that r3nzskin triggering Riot to take a look at the account and so they spot that it is bot/smurf.

**Comment by meeezaezaa** [comment]
guys i dont think its r3nzskin cuzz i have been using it for a reallly really long time and they still didnt ban me so maybe r3nzskin isnt the problem

**Comment by mariostart01** [comment]
> guys i dont think its r3nzskin cuzz i have been using it for a reallly really long time and they still didnt ban me so maybe r3nzskin isnt the problem

Have you tried the latetest version?

**Comment by meeezaezaa** [comment]
yes

**Comment by mariostart01** [comment]
> yes

Okay thanks for everyone's comments 
The ban was about bought accounts.

**Comment by maxxxcoder** [comment]
> > yes
> 
> Okay thanks for everyone's comments The ban was about bought accounts.

Not sure yet, we will see tomorrow if my friend will get banned too i will confirm it here, if he will not get banned next week then its skin changer
