### ISSUE TITLE
new version not opening

### ISSUE THREAD

**Issue by sdfgdshgF** [R3nzTheCodeGOD/R3nzSkin#635]
how to fix?

**Comment by cariocacpp** [comment]
disable real time protection

**Comment by Ali229** [comment]
I disabled the antivirus fully
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/11164440/f911487f-c850-4ddc-acf5-e3b4d0d6bcd1)
Still the icon shows up in the taskbar but doesn't open. Started happening after the latest update
