### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by Lunacyyy31** [R3nzTheCodeGOD/R3nzSkin#637]
I get this error trying to open the skin changer, I'm not really not good at computer stuff so if someone can help me that would be very appreciated. 

I checked previous closed cases, and it was said to have them in the directory, which I have done.

Likewise, I also completely removed my antivirus and windows real time protection is disabled.

Thank you:)
![Screenshot 2023-07-21 203352](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140215998/8715e5b6-6bae-4689-94f8-b2fadb63c181)

**Comment by qq1403498204** [comment]
啥意思？

**Comment by hotline1337** [comment]
Make sure you have R3nzSkin.dll in the same directory as the injector.

**Comment by tvpham9** [comment]
I have the same issue, it was working with previous versions, could there be something wrong with the compiled folder?
