### ISSUE TITLE
Latest patch String was not recognized as valid DateTime

### ISSUE THREAD

**Issue by jdfsndksjfdsf** [R3nzTheCodeGOD/R3nzSkin#638]
Hello, i am having the error "String was not recognized as valid DateTime" and my dll is in the same directory as my injector, the windows defender has an exlcusion for this folder and my downloads folder, therefore it cannot be my antivirus. Any ideas?

**Comment by cariocacpp** [comment]
click on exit or on the bottom button and continue playing normally

**Comment by NoodleWonton** [comment]
My work around was just using the DLL of the new release, and the old injector of the previous patch, it seems the issue is the compiled version's new injection application, so I guess just use the old until another update comes out?

**Comment by jdfsndksjfdsf** [comment]
> My work around was just using the DLL of the new release, and the old injector of the previous patch, it seems the issue is the compiled version's new injection application, so I guess just use the old until another update comes out?

yeah i just decided to go back 1 update and it works fine. Thanks for the responses.
