### ISSUE TITLE
galaxy slayer zed Q animation not right and the shadow emotion isnt right if you W Q and running animation not like the normal skin

### ISSUE THREAD

**Issue by meeezaezaa** [R3nzTheCodeGOD/R3nzSkin#639]
galaxy slayer zed Q animation not right and the shadow emotion isnt right if you W Q

_Originally posted by @meeezaezaa in https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/1#issuecomment-1636827070_

**Comment by hotline1337** [comment]
#1
