### ISSUE TITLE
PBE 2.5 is crash

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#64]
![image](https://user-images.githubusercontent.com/50578587/154675041-fbaf4b21-6fd7-49f9-b2dc-9d8534d2433a.png)

**Comment by senmao1994** [comment]
<img width="973" alt="QQ浏览器截图20220218193337" src="https://user-images.githubusercontent.com/50578587/154675158-10b8ad42-6dd9-48b4-9f3c-5f0d33922216.png">

**Comment by R3nzTheCodeGOD** [comment]
should work now

**Comment by senmao1994** [comment]
12.7 pbe 崩溃
