### ISSUE TITLE
Perma ban

### ISSUE THREAD

**Issue by Watoryuk** [R3nzTheCodeGOD/R3nzSkin#642]
Just got permabanned for using this.
![Screenshot 2023-07-23 184422](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140338062/acec7964-e165-4b6b-9eba-dc87f0db6eaf)

**Comment by meeezaezaa** [comment]
i dont think its the program my friend

**Comment by Watoryuk** [comment]
It says for using 3rd party program. I don't use anything else.

ne 23. 7. 2023 v 19:16 odesílatel meeezaezaa ***@***.***>
napsal:

**Comment by Watoryuk** [comment]
It says "use of third-party tools" I don't use any other program.

**Comment by meeezaezaa** [comment]
idk been using it for ages and i never got banned maybe you bought a botted account?

**Comment by Watoryuk** [comment]
I did. But then I have many botted accounts. Was using this for 3 months. First ban.

**Comment by meeezaezaa** [comment]
yes botted accounts are being banned now in patch 13.14

**Comment by Watoryuk** [comment]
Interesting. Only this one got banned.

**Comment by meeezaezaa** [comment]
if you dont believe it i really dont care tbh im just telling you that this program doesnt have anything with the ban

**Comment by Watoryuk** [comment]
Confirmed its banning botted accounts. Got banned without using skin changer on another account.
