### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by notsynonym** [R3nzTheCodeGOD/R3nzSkin#643]
when i try to open the injector all i get is this warning, the injector is in the same folder that the dll.

**Comment by Jyrim** [comment]
same error here

**Comment by AmineDrissi** [comment]
me too

**Comment by Leviathoon** [comment]
anyone found a fix?

**Comment by PwccaCode** [comment]
remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp

**Comment by notsynonym** [comment]
> remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp

 i managed to remove the autoupdate but what do i do now?

**Comment by PwccaCode** [comment]
> > remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp
> 
> i managed to remove the autoupdate but what do i do now?

in main.cpp remove the autoupdate call, then build the code normally it will run without problems, this is an issue with time format expected by the program being differente from your computer.

**Comment by PwccaCode** [comment]
pr #646 should fix the issue without disabling autoupdate feature

**Comment by notsynonym** [comment]
> > > remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp
> > 
> > 
> > i managed to remove the autoupdate but what do i do now?
> 
> in main.cpp remove the autoupdate call, then build the code normally it will run without problems, this is an issue with time format expected by the program being differente from your computer.

sorry for my lack of knowledge, but i have no idea how to build the code

**Comment by PwccaCode** [comment]
> > > > remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp
> > > 
> > > 
> > > i managed to remove the autoupdate but what do i do now?
> > 
> > 
> > in main.cpp remove the autoupdate call, then build the code normally it will run without problems, this is an issue with time format expected by the program being differente from your computer.
> 
> sorry for my lack of knowledge, but i have no idea how to build the code

just clone the code from pr #646 open select your server and build

**Comment by notsynonym** [comment]
> > > > > remove the entire codeblock for autoupdate function from injector.cpp and remove its mention in main.cpp
> > > > 
> > > > 
> > > > i managed to remove the autoupdate but what do i do now?
> > > 
> > > 
> > > in main.cpp remove the autoupdate call, then build the code normally it will run without problems, this is an issue with time format expected by the program being differente from your computer.
> > 
> > 
> > sorry for my lack of knowledge, but i have no idea how to build the code
> 
> just clone the code from pr #646 open select your server and build

wdym with select server and build? sorry, my knowledge are really low on this topic

**Comment by PwccaCode** [comment]
follow the instructions on the readme page, just change the link when doing git clone --recursive

**Comment by notsynonym** [comment]
> follow the instructions on the readme page, just change the link when doing git clone --recursive

ok i did it but there are some error in the includes?? and i cant build

**Comment by PwccaCode** [comment]
> > follow the instructions on the readme page, just change the link when doing git clone --recursive
> 
> ok i did it but there are some error in the includes?? and i cant build

you have to show the errors for us to help you

**Comment by Grapester** [comment]
> 

Do you have discord or something where I can msg u on how to do this? im lost

**Comment by Avelis16** [comment]
Guys, funny enough I think I got a solution to use the injector and fix the ''String was not recognized as a valid DateTime'' problem. 
I just changed my date format to dd-MMM-yy and it works. :D

**Comment by PwccaCode** [comment]
just download the release i made without the auto update function until the issue is fixed or my pull request is accepted

https://github.com/PwccaCode/R3nzSkin

**Comment by notsynonym** [comment]
> just download the release i made without the auto update function until the issue is fixed or my pull request is accepted
> 
> https://github.com/PwccaCode/R3nzSkin

the injector opened  when i first opened in the rar folder, then i extracted it to a normal folder and it worked normally?????

**Comment by PwccaCode** [comment]
> > just download the release i made without the auto update function until the issue is fixed or my pull request is accepted
> > [PwccaCode/R3nzSkin](https://github.com/PwccaCode/R3nzSkin)
> 
> the injector opened when i first opened in the rar folder, then i extracted it to a normal folder and it worked normally?????

you are asking? i dont know??????????

**Comment by notsynonym** [comment]
> > > just download the release i made without the auto update function until the issue is fixed or my pull request is accepted
> > > [PwccaCode/R3nzSkin](https://github.com/PwccaCode/R3nzSkin)
> > 
> > 
> > the injector opened when i first opened in the rar folder, then i extracted it to a normal folder and it worked normally?????
> 
> you are asking? i dont know??????????

no, i was just expressing my surprise at the moment

**Comment by hotline1337** [comment]
should be working as of now.
