### ISSUE TITLE
Failed to find R3nzSkin.dll in the current directory

### ISSUE THREAD

**Issue by wocs1337** [R3nzTheCodeGOD/R3nzSkin#644]

**Comment by wocs1337** [comment]
when running the injector, error pops up "Failed to find R3nzskin.dll in the current directory".

**Comment by hotline1337** [comment]
put the R3nzSkin.dll in the same folder as the injector?

**Comment by kmeric61** [comment]
help me pls

**Comment by kmeric61** [comment]
> enjektörü çalıştırırken, "Geçerli dizinde R3nzskin.dll bulunamadı" hatası çıkıyor.

sorunu çözebildinmi
