### ISSUE TITLE
Banned Account!

### ISSUE THREAD

**Issue by KarenRemover** [R3nzTheCodeGOD/R3nzSkin#647]
I recently got my account perma banned because I was using this program. 
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/134144750/be254d37-611d-4ff8-920d-778b029a7714)
Wasn't it supposed to be undetectable?

**Comment by hotline1337** [comment]
R3nzSkin is undetected, your ban may be caused by a botted account ban wave
