### ISSUE TITLE
unable to connect to the remote server

### ISSUE THREAD

**Issue by Mohammedamr1** [R3nzTheCodeGOD/R3nzSkin#649]
anyone knows how to fix this issue ?

**Comment by hotline1337** [comment]
elaborate more, what is it related to, the injector or the dll?

**Comment by Mohammedamr1** [comment]
> elaborate more, what is it related to, the injector or the dll?

The injector

**Comment by hotline1337** [comment]
> > elaborate more, what is it related to, the injector or the dll?
> 
> The injector

Your ISP may be blocking the auto-update https request, try using dns over https (cloudflare warp), or delete the auto-update function call in the source and compile it.
