### ISSUE TITLE
Cant open in win 11

### ISSUE THREAD

**Issue by Hatsukooo** [R3nzTheCodeGOD/R3nzSkin#654]
Software doesnt open on windows 11

**Comment by hotline1337** [comment]
Make sure you have .NET Framework 4.8+ and C++ Redistributable 2015-2023 x64/x86 installed

**Comment by Hatsukooo** [comment]
i Have it, .NET 6 and C++ 23 x64, it still doesn't open, after i click Ok, nothing happends..
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/133507370/8944fd3f-b2b3-411c-865c-9c7ca8496d7e)

**Comment by hotline1337** [comment]
> i Have it, .NET 6 and C++ 23 x64, it still doesn't open, after i click Ok, nothing happends.. ![image](https://user-images.githubusercontent.com/133507370/258593952-8944fd3f-b2b3-411c-865c-9c7ca8496d7e.png)

Make sure you have the newest Release, also make sure the R3nzSkin.dll is in the same directory as the injector

**Comment by Hatsukooo** [comment]
Okay, now it is working, sorry, somehow i was downloading 2week old release, sorry man D
