### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by aasga** [R3nzTheCodeGOD/R3nzSkin#655]

**Comment by Mayapixi** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/75144231/86cc0022-e09e-4266-83c3-ef80de67f177)
I got it too but the app still works

**Comment by hotline1337** [comment]
Make sure R3nzSkin.dll is in the same directory as injector.
