### ISSUE TITLE
what if you use the "13.14 update" version instead of the newest one 

### ISSUE THREAD

**Issue by ivqz** [R3nzTheCodeGOD/R3nzSkin#661]
when i try to open the newest version i get "string was not recognized as valid DateTime" and the changer doesn't open, but on the previous version it says the same thing but it opens and its works.

**Comment by Ali229** [comment]
I use the older version as well, new one doesn't work, so use old exe use new dll.

**Comment by hotline1337** [comment]
> when i try to open the newest version i get "string was not recognized as valid DateTime" and the changer doesn't open, but on the previous version it says the same thing but it opens and its works.

make sure to have R3nzSkin.dll in the same file directory as the injector

**Comment by Ali229** [comment]
This isn't due to dll not being in the same directory, already tried that, it's the new exe producing this error, there is a pull request to rectify this problem.
