### ISSUE TITLE
Game updated 13.15, into the game pop-up

### ISSUE THREAD

**Issue by qq1403498204** [R3nzTheCodeGOD/R3nzSkin#662]

**Comment by qq1403498204** [comment]
![QQ截图20230802083038](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140217111/2a4cf0e5-6d41-47d8-9430-2af238bc9daa)

**Comment by kiddovn** [comment]
me too

**Comment by Zeanz2** [comment]
same i think it need to be update

**Comment by 000ICEY000** [comment]
me too

**Comment by ComplexQa** [comment]
Same here, cant be used at the moment

**Comment by NicsMontesco** [comment]
We all have that problem i think

**Comment by kiril203** [comment]
да у меня тоже это есть

**Comment by hotline1337** [comment]
Please check out the new release.
