### ISSUE TITLE
Need to update 13.15!

### ISSUE THREAD

**Issue by Zeanz2** [R3nzTheCodeGOD/R3nzSkin#663]

**Comment by TheNei** [comment]
it will be soon

**Comment by kiril203** [comment]
что нужно делать

**Comment by Franker091** [comment]
when will be updated anyone knows?

**Comment by kiril203** [comment]
я не понял обнова 13 15 это обнова игры?

**Comment by Zeanz2** [comment]
R3nzskin u need to awake right now to update!

**Comment by hotline1337** [comment]
Please check out the new release.
