### ISSUE TITLE
R3nzskin

### ISSUE THREAD

**Issue by Franker091** [R3nzTheCodeGOD/R3nzSkin#665]
hello, i was trying to install r3nzskin but when i try to inject the skin a screen shots appears, anyone knows how to fix it?

![Captura de pantalla 2023-08-02 153113](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/141248309/e05d3e5c-bba4-4414-a412-5e0eb77fd89b)

**Comment by Ryanleary9** [comment]
Same i think it need to update or smt like that

**Comment by Zeanz2** [comment]
yea the R3nzskin need to be update cuz 13.14 now its 13.15 so we wait for the New Update

**Comment by kiril203** [comment]
аа типо R3nzskin не совместим с версией 13 15 и нужно его обновить?

**Comment by Gipost** [comment]
U need to change offset:AIBaseCommon::SkinId by dumping league client cause of 13.15 and recompile this to work. I am too lazy to do it

**Comment by Franker091** [comment]
but thx

**Comment by hotline1337** [comment]
Please check out the new release.
