### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by suiyq1** [R3nzTheCodeGOD/R3nzSkin#666]
For some reason when I try and download the skin changer my antivirus software (ESET antivirus) keeps detecting trojan virus in the files and it gets removed when I download it. Please help ;*(

**Comment by suiyq1** [comment]
Also if you were wondering witch file it removes it is this one (Win64/Agent_AGen.AKX)

**Comment by hotline1337** [comment]
Disable your antivirus since the program use unsual win32 apis, thats why its false positive
