### ISSUE TITLE
13.15 fix

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#667]
change Riot__g_window to `48 8B 0D ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? 48 8B 5C`

**Comment by Snoozesterr** [comment]
Can you add me on discord jerzy1090 and show me what to do after i change the offsets

**Comment by azac4d** [comment]
> change Riot__g_window to `48 8B 0D ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? 48 8B 5C`

How can you tell me?

**Comment by kiril203** [comment]
зайти на диск с игрой и поменять папку riot games на 48 8B 0D ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? 48 8B 5C?

**Comment by azac4d** [comment]
> зайти на диск с игрой и поменять папку riot games на 48 8B 0D ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? 48 8B 5C?

Далбаеб чтоле

**Comment by kiril203** [comment]
сам ты долбаёб критин конченый

**Comment by kiril203** [comment]
чмо блять

**Comment by kiril203** [comment]
кем ты себя возамнил олень?

**Comment by kiril203** [comment]
нахуй ты мне не здался олух

**Comment by kiril203** [comment]
хуеглот

**Comment by kiril203** [comment]
не пиши сюда больше

**Comment by BacalaoPlus** [comment]
[Updated R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12243003/Updated.R3nzSkin.zip)

I compiled it myself if you're struggling to do it.

**Comment by kiril203** [comment]
спасибо

**Comment by Laqezz** [comment]
> [Updated R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12243003/Updated.R3nzSkin.zip)
> 
> I compiled it myself if you're struggling to do it.

love you bro

**Comment by hotline1337** [comment]
Please check out the new release.

**Comment by azac4d** [comment]
> сам ты долбаёб критин конченый

Я твою маму ебал конченый соска хуй твой в рот сосал гандон ебаный ты че нечеш какой переименовать папку мамин хуйышный сынок

**Comment by kiril203** [comment]
школьник

**Comment by kiril203** [comment]
тебе мамкиного внимания не хватает и ты на людях срываешься?

**Comment by kiril203** [comment]
ааа у тебя её нет

**Comment by kiril203** [comment]
забыл

**Comment by kiril203** [comment]
она же у тебя в канаве подохла мразь конченая

**Comment by kiril203** [comment]
писать научись

**Comment by kiril203** [comment]
уёбище конченное

**Comment by kiril203** [comment]
не пиши чмо 2 раз повтаряю

**Comment by kiril203** [comment]
ты вообще видел что высрал?

**Comment by kiril203** [comment]
как ты ты сосал

**Comment by kiril203** [comment]
сам у себя

**Comment by kiril203** [comment]
хотя и нечего

**Comment by kiril203** [comment]
нет у тебя его

**Comment by kiril203** [comment]
откуда ты взялся вообще

**Comment by kiril203** [comment]
из жопы отца своего

**Comment by azac4d** [comment]
> писать научись

Я всю твою семью тразну уебище малолетнее я тебя тразну и твою мамашу тоже чмошник ебаный ты откуда вообще взялся хохол ебаный укрвйнец я твою украйнскиую кровь ебал

**Comment by kiril203** [comment]
давай высри ещё

**Comment by kiril203** [comment]
тварь блять

**Comment by kiril203** [comment]
заебал

**Comment by kiril203** [comment]
я уже понял что внимания матери не хватает

**Comment by kiril203** [comment]
так что пошол нахуй клоун ебаный

**Comment by kiril203** [comment]
развлекать братьев на помойке будешь

**Comment by xiyangbaofengx** [comment]
Hello, could you teach me how to find it？Thank you！

**Comment by azac4d** [comment]
> развлекать братьев на помойке будешь

хуйло сука я твою мать ебал
