### ISSUE TITLE
erdem abi 13.15 pattern hata veriyo bi el at be <3

### ISSUE THREAD

**Issue by xenomati** [R3nzTheCodeGOD/R3nzSkin#669]

**Comment by xenomati** [comment]
> https://github.com/Sheelia/R3nzSkin-v13.15

<3

**Comment by kaan1957** [comment]
> > https://github.com/Sheelia/R3nzSkin-v13.15
> 
> <3

adam turk degil

**Comment by hotline1337** [comment]
Please check out the new release.
