### ISSUE TITLE
13.5 update 

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#670]
you can find it in my github repo
https://github.com/Sheelia/R3nzSkin-v13.15

**Comment by azac4d** [comment]
virus?
if no prove

**Comment by Sheelia** [comment]
> virus? if no prove

compile it yourself

**Comment by Ryudock** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140745737/29a98fbb-8cdc-42d4-95f6-63987707390d)

**Comment by aderuu** [comment]
bro why you update the hpp like give directly the exe comon

**Comment by maark6ix** [comment]
can u help me how to make it work? it just downloads the hpp file and theres nothing to do with it can u explain it where to input it or something

**Comment by MihaiTheAwsm** [comment]
thanks for the update big man

**Comment by bulanden815** [comment]
> thanks for the update big man

does it work?

**Comment by StuTheCoder** [comment]
> 

Yep it works

**Comment by MihaiTheAwsm** [comment]
> 

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/47987723/bdbd0abb-1ddb-4f97-8c89-4ad0e4776671)
its like nobody understands github

**Comment by maark6ix** [comment]
how does it work can someone explain?

**Comment by Ryanleary9** [comment]
can you guys compile it please T.T

**Comment by MihaiTheAwsm** [comment]
> can you guys compile it please T.T

its already compiled just download it from his github

**Comment by kaan1957** [comment]
github says you've only updated memory.hpp but .exe file literally has your name everywhere

**Comment by tuchicoanime** [comment]
i don't know how to open the injector from this file can someone help :/

**Comment by augustorsn** [comment]
@Sheelia 
how did you know you had to modify that string?

"48 8B 0D ? ? ? ? PF 15? ? ? ? E8? ? ? ? 48 8B"

**Comment by SushiYae** [comment]
> 

Cuz if u run the old one it shows you as an error msg

**Comment by SushiYae** [comment]
i replaced memory myself still doesnt work since 
,,String was not recognized as a valid DateTime"
any1 knows how to go ttrough this?

**Comment by hotline1337** [comment]
Please check out the new release.
