### ISSUE TITLE
What is the SSL/TLS error?

### ISSUE THREAD

**Issue by Quillett** [R3nzTheCodeGOD/R3nzSkin#671]
"the request was aborted: Could not crate ssl/tls secure channel"  error. 

![image1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/141269925/04b4b9e1-59af-4dd1-91aa-18811a0e30e9)

**Comment by hotline1337** [comment]
You are using windows 7, the injector has been made to work on windows 10+ systems
