### ISSUE TITLE
Discord to download the 13.15 version with .exe file 

### ISSUE THREAD

**Issue by aderuu** [R3nzTheCodeGOD/R3nzSkin#672]
https://discord.gg/j26ecWZDG (free)

**Comment by kaan1957** [comment]
yea do not trust this guy

**Comment by MihaiTheAwsm** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/47987723/510b71a9-d121-49d5-8d79-0085d8789d97)
its here its already compiled and it works

**Comment by MihaiTheAwsm** [comment]
do not join this discord, the compiled version is in a fork with a safe exe

**Comment by 112frosta** [comment]
xD

**Comment by 112frosta** [comment]
how is this even open yet
