### ISSUE TITLE
How safe is this program ? 

### ISSUE THREAD

**Issue by Sbustamante301** [R3nzTheCodeGOD/R3nzSkin#674]
A botted account of mine just got permanently banned for using third party programs, I know this is probably because it was botted but still has anyone else had the same problem ?

**Comment by Dimmylol** [comment]
> A botted account of mine just got permanently banned for using third party programs, I know this is probably because it was botted but still has anyone else had the same problem ?

it was cuz its botted, you need now only 1 report for botted account to get banned

**Comment by hotline1337** [comment]
As Dimmylol said.
