### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by slajders1** [R3nzTheCodeGOD/R3nzSkin#678]
After trying to open the injector this message appears and nothing happens. With last version it was the same but after the message skin changer just opened and everything was fine, now nothing happens

**Comment by hotline1337** [comment]
The following commit fixes the issue: https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/70fd37c8882c6f92013be2609f24dd46445888c3
