### ISSUE TITLE
Big issues

### ISSUE THREAD

**Issue by 14fedora** [R3nzTheCodeGOD/R3nzSkin#679]
hi i just wanna say this. i tried downloading skin changer last week but the windows defender did not keep the files and tried to disable defender but it still deletes it bc it detectes it as a trojan i tried many solution and totorials to disable windows defender and bc it deletes the files i was downloading it again and again. but one time when i redownload the skin changer but defender did not delete the files but it still detecte torjan,i tried deleting it from defender but it cant delete ,after that my pc strated slowing down .so i had to do a full clean up to my pc ,do u have a reason for this?

**Comment by hotline1337** [comment]
Just disable Run-Time Protection
