### ISSUE TITLE
I was banned by r3nzskins :/

### ISSUE THREAD

**Issue by pdrflp** [R3nzTheCodeGOD/R3nzSkin#681]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/46250623/3c047f6b-9b16-4f31-841d-c7cf752b205a)
and no, I didn't tell anyone I was using r3nz or anything like that

**Comment by Synchell** [comment]
is your account botted?

**Comment by hotline1337** [comment]
this might be the reason of a botted account ban wave

**Comment by Sniper5224** [comment]
me too

**Comment by leonardo-vic3nte** [comment]
This is the result of new system RIOT put in place to ban botted account. If your account was made with botting in the last year (according to an RIOT tweet it will catch up to an year), and you get reported for a botted account, you will get banned.

I lost two account to this, and also thought it was r3nzskin, but it was not, 

I got hold of a botted account that was made 3 years ago, and been playing using r3nzskin for about 50 matches now with no problem.

So yeah, to resolve your problem, you need to get a botted account that was botted more than a year ago.

**Comment by Sniper5224** [comment]
What is botted accounts mean? sorry my english is not good

> This is the result of new system RIOT put in place to ban botted accounts. If your account was made with botting in the last year (according to an RIOT tweet it will catch up to an year), and you get reported for being botted account (smurf), you will get banned.
> 
> I lost two account to this, and also thought it was r3nzskin, but it was not,
> 
> I got hold of a botted account that was made 3 years ago, and been playing using r3nzskin for about 50 matches now with no problem.
> 
> So yeah, to resolve your problem, you need to get a botted account that was botted more than a year ago.

What is botted accounts mean? sorry my english is not good

**Comment by leonardo-vic3nte** [comment]
> What is botted accounts mean? sorry my english is not good

It means an account that was leveled up to lvl 30 using a program, a roBOT, that plays the game instead of a real person. 
100% of the accounts that are sold in various websites to be used as smurfs are leveled up this way.

**Comment by Sniper5224** [comment]
> > What is botted accounts mean? sorry my english is not good
> 
> It means an account that was leveled up to lvl 30 using a program, a roBOT, that plays the game instead of a real person. 100% of the accounts that are sold in various websites to be used as smurfs are leveled up this way.

i see. My account is an all-champions account purchased on the website.Maybe it cause the banned

**Comment by leonardo-vic3nte** [comment]
> i see. My account is an all-champions account purchased on the website.Maybe it cause the banned

If it was purchased, then it was the reason of the ban. It sucks, but it is what it is.

**Comment by pdrflp** [comment]
thanks guys, the account was actually uploaded with bot.
