### ISSUE TITLE
BANNABLE !

### ISSUE THREAD

**Issue by cowjsn** [R3nzTheCodeGOD/R3nzSkin#686]
My boyfriend just got banned after using R3nzSkin ONE single time. while on his smurf, but it was a bought account. I've been using the software a while ago and i've NEVER got banned, but ill stop using it rn. This is just a warning for all people, it might be bc of the bought account but take care yall.

**Comment by debilo1d** [comment]
Hello! I'm a long time RU and EUW server player. My first ever account on EUW was bought and i've used this skinchanger while playing on it and on RU server. recently got banned on EU as well. Seems like EU is getting a banwave. I would love to know if  your boyfriend's account was bought from a website or was it his own personal account. Just curious

**Comment by Sheelia** [comment]
Joined 5 hours ago ???

**Comment by Sheelia** [comment]
I think you're trying to defame this project.

**Comment by cjaryou** [comment]
Riot did banwave for scripters and botted accounts prob you banned for this.

**Comment by cowjsn** [comment]
> I think you're trying to defame this project.

LMAO i literally just joined to let people know about it. I dont use github at all, not much XDDD???

**Comment by cowjsn** [comment]
> Hello! I'm a long time RU and EUW server player. My first ever account on EUW was bought and i've used this skinchanger while playing on it and on RU server. recently got banned on EU as well. Seems like EU is getting a banwave. I would love to know if your boyfriend's account was bought from a website or was it his own personal account. Just curious

It was a bought account from a website, o it might be as well bc of both things, the skin changer and the seller that has been targeted already or something like that, bc he got an account for his friend and got banned bc third party programs but he didnt used anything, so is really really weird

**Comment by fernbacher** [comment]
You seem like a sad hater or something? I bought accounts too and they got banned, they are botted accounts, they level them up with bots and you buy them, simple as that, sometimes they get banned, the good ones offer you a refund/another account, the shit 1$ ones won't give you shit if you get banned, it's all your own risk, people EXTREMELY rarely get banned for using a skinchanger, they didn't get banned in the times of horrible skinchangers like lolskin, so it's even less likely nowadays, still not saying it's not possible, but it's extremely low chances of getting banned anywhere else but Asia for skinchanging, probably not even 1%

**Comment by cowjsn** [comment]
> You seem like a sad hater or something? I bought accounts too and they got banned, they are botted accounts, they level them up with bots and you buy them, simple as that, sometimes they get banned, the good ones offer you a refund/another account, the shit 1$ ones won't give you shit if you get banned, it's all your own risk, people EXTREMELY rarely get banned for using a skinchanger, they didn't get banned in the times of horrible skinchangers like lolskin, so it's even less likely nowadays, still not saying it's not possible, but it's extremely low chances of getting banned anywhere else but Asia for skinchanging, probably not even 1%

ye im a sad hater of a skin changer i use LMAOO pls, read before commenting, i edited the comment to clear what i wanted to say and ask if this happened to someone before xdd

**Comment by ogisan-7** [comment]
Can confirm of this, my account also got banned after 1 game of usage. It doesn't matter if the account is botted or not/ because this software triggers the ban. Botted accounts usually last until diamond rank before they get banned so something is up.

**Comment by fernbacher** [comment]
I'm still using it every single day and i have been using it since it came out, i've never been banned because of this tool or any other skin tool, you lot must be special, which i think you might be, just not in the good way

**Comment by hotline1337** [comment]
I've been playing on my main 600 level account every day and I can say the software is undetected.
