### ISSUE TITLE
got permabanned

### ISSUE THREAD

**Issue by viegod** [R3nzTheCodeGOD/R3nzSkin#687]
all my accounts got perma after probably 2 days of using it. Just a warning for all people dont use it

**Comment by debilo1d** [comment]
Hello, just checking out the issue. I'm just a regular player, but it seems like there was a ban wave going on for a while now. A couple of days at the very least. Can you share the information about the origin of your account. Was it a bought account of sorts or was it your personal  long-time used account

**Comment by viegod** [comment]
> Hello, just checking out the issue. I'm just a regular player, but it seems like there was a ban wave going on for a while now. A couple of days at the very least. Can you share the information about the origin of your account. Was it a bought account of sorts or was it your personal long-time used account

my smurf and my main got banned. the smurf was bought. the main was played from 1 level to 197 level just by me. Both got banned, i did send tickets to riot so i will def say what was their response and what was the reason it got banned (either skinchanger or bought acc)

**Comment by Sheelia** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/681

**Comment by Sheelia** [comment]
there is no ban

**Comment by cjaryou** [comment]
Riot did banwave for scripters and botted accounts prob you banned for this.

**Comment by viegod** [comment]
thanks guys, riot wont respond me but its probably cuz of the bought account. program is safe
