### ISSUE TITLE
Error when trying to run injector

### ISSUE THREAD

**Issue by themoxxy** [R3nzTheCodeGOD/R3nzSkin#691]
Hi how can I fix this error message that pops up when I try to launch the injector.
![rznskin error](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/139259398/be28668f-14f4-4f02-a80f-5ffe1d91f5b6)

**Comment by Sheelia** [comment]
disable defender

**Comment by HadockKali** [comment]
> Hi how can I fix this error message that pops up when I try to launch the injector. ![rznskin error](https://user-images.githubusercontent.com/139259398/259816415-be28668f-14f4-4f02-a80f-5ffe1d91f5b6.png)

Your anti-virus software may block the connection from the injector to check for updates, that's what that error means. You have 2 fixes:
- Disable the anti-virus software
- Delete the autoUpdate() function from the source code then compile the project yourself

Hope it helps!

**Comment by BBxBBoes** [comment]
> 

how can I delete the autoupdate from the source code?

**Comment by hotline1337** [comment]
> > 
> 
> how can I delete the autoupdate from the source code?

comment it out.
