### ISSUE TITLE
Bugged with cslolmanager

### ISSUE THREAD

**Issue by Visionnary** [R3nzTheCodeGOD/R3nzSkin#694]
I noticed that when I try to use the original championship riven skin along with a cslolmanager mod that gives me old riven vfx, the championship riven skin just becomes the 2016 one instead of the 2012 one. (The crown isn't there and the vfx are the same as the 2016 one)

**Comment by Visionnary** [comment]
I want to add that it works normally if I turn off the old riven vfx mod

**Comment by hotline1337** [comment]
not related.
