### ISSUE TITLE
13.16 fix plz!!<3

### ISSUE THREAD

**Issue by xenomati** [R3nzTheCodeGOD/R3nzSkin#699]

**Comment by jihongyu-GYC** [comment]
+1, It is so sad when I turn on LOL without skin today.

**Comment by xenomati** [comment]
> +1, It is so sad when I turn on LOL without skin today.

yea so bad without skins... felt like bronze

**Comment by iluvketamine** [comment]
tag me or something when its done, life is sad

**Comment by sansbruhgaming** [comment]
https://github.com/sansbruhgaming/R3nzSkin/releases/tag/v3.1.5

**Comment by hotline1337** [comment]
13.16 Update has been pushed to the main branch.
