### ISSUE TITLE
Why dose the source code not give me any trojan warnings and android app warning?

### ISSUE THREAD

**Issue by axeltibur** [R3nzTheCodeGOD/R3nzSkin#700]

**Comment by snxiee** [comment]
Because the application is compressed into an exe and an antivirus finds it malicious because it injects dlls into league while source code is complete source antivirus won't find anything malicious because it's not compressed into an exe

**Comment by axeltibur** [comment]
Also I know the way it dose is by injecting it but have you ever found another way to do it. Mod skin lol never trips antivirus lol it’s just kinda annoying with the window popping up every sec

Sent from my iPhone

On Aug 16, 2023, at 5:39 AM, Queen ***@***.***> wrote:

﻿

Because the application is compressed into an exe and an antivirus finds it malicious because it injects dlls into league while source code is complete source antivirus won't find anything malicious because it's not compressed into an exe

**Comment by hotline1337** [comment]
Because it's text. Not executables.
