### ISSUE TITLE
Can we have an Update please sir !!! 

### ISSUE THREAD

**Issue by xavihachem** [R3nzTheCodeGOD/R3nzSkin#704]
Please an update sir !!!

**Comment by sansbruhgaming** [comment]
https://github.com/sansbruhgaming/R3nzSkin/releases/tag/v3.1.5

**Comment by lkphan6103** [comment]
> https://github.com/sansbruhgaming/R3nzSkin/releases/tag/v3.1.5

@sansbruhgaming is it possible for you to teach me how to find the pattern to edit and compile them? I have Visual Studio 2022 but I'm a noob at this but would love to learn.

**Comment by sansbruhgaming** [comment]
@lkphan6103 To be honest with you, I'm in the exact same boat. Although to compile it, you just need to follow the steps outlined in the readme. 

I just got the pattern from: https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-515.html
To determine what pattern you need to find, just go to memory.cpp and match up what pattern isn't being found.

**Comment by ultaking** [comment]
> @lkphan6103 To be honest with you, I'm in the exact same boat. Although to compile it, you just need to follow the steps outlined in the readme.
> 
> I just got the pattern from: https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-515.html To determine what pattern you need to find, just go to memory.cpp and match up what pattern isn't being found.

i can't seem to find the characterdatastack offset anywhere on that site, mind telling me it?

**Comment by sansbruhgaming** [comment]
> 
> i can't seem to find the characterdatastack offset anywhere on that site, mind telling me it?

You don’t need the CharacterDataStack pattern. To find what you need to change, you read the error: “Failed to find pattern 48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05” and you Ctrl + F ‘48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05’ in the memory.cpp file. That pattern is AITurretManager, so you ask for that in the UnknownCheats.me thread

**Comment by ultaking** [comment]
> > i can't seem to find the characterdatastack offset anywhere on that site, mind telling me it?
> 
> You don’t need the CharacterDataStack pattern. To find what you need to change, you read the error: “Failed to find pattern 48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05” and you Ctrl + F ‘48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05’ in the memory.cpp file. That pattern is AITurretManager, so you ask for that in the UnknownCheats.me thread

ic, my bad and thx for the help.

**Comment by hotline1337** [comment]
13.16 Update has been pushed to the main branch.
