### ISSUE TITLE
Pls Fix: Failed to find pattern 48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05

### ISSUE THREAD

**Issue by drastamat200** [R3nzTheCodeGOD/R3nzSkin#705]
Failed to find pattern 48 89 0D ??? 33 C9 48 8D 05 ? ? ? ? 4C 8D 05

**Comment by xavihachem** [comment]
> game updated, need to update offsets

When do you think this would be happening ? would it take a long time ?

**Comment by iluvketamine** [comment]
65 years

**Comment by dctrlight** [comment]
XD

**Comment by masamunesephy** [comment]
real pls fix that

**Comment by kiril203** [comment]
омг оу ноу почените мод плз

**Comment by kiril203** [comment]
спасибо большое!!!!!!!

**Comment by hotline1337** [comment]
13.16 Update has been pushed to the main branch.
