### ISSUE TITLE
Need to update! NO SKIN NO SKILL!

### ISSUE THREAD

**Issue by Zeanz2** [R3nzTheCodeGOD/R3nzSkin#706]

**Comment by xavihachem** [comment]
That's a fact, tag me when the update is out please

**Comment by sansbruhgaming** [comment]
https://github.com/sansbruhgaming/R3nzSkin/releases/tag/v3.1.5

**Comment by aderuu** [comment]
dont download hes link nice bitcoin usage

**Comment by sansbruhgaming** [comment]
> dont download hes link nice bitcoin usage

I’m going to get suspended if I say what I want to

**Comment by xavihachem** [comment]
> dont download hes link nice bitcoin usage

i Allready did, but it is working is it a harmfull or somthing ?

**Comment by hotline1337** [comment]
13.16 Update has been pushed to the main branch.
