### ISSUE TITLE
The voice for Yasuo nightbringer ultimate pls :v

### ISSUE THREAD

**Issue by Reraz** [R3nzTheCodeGOD/R3nzSkin#708]
Please, and when viego consumes a soul it's green no matter the skin you are using.

**Comment by sxybeast** [comment]
Hey there, how are you able to use it on patch 13.16 did he update skinchanger already ?

**Comment by Reraz** [comment]
use this link https://github.com/sansbruhgaming/R3nzSkin/releases/tag/v3.1.5

**Comment by hotline1337** [comment]
#1
