### ISSUE TITLE
R3nzSkin lol version 13.16

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#710]
https://github.com/Sheelia/R3nzSkin-v13.16

**Comment by Sheelia** [comment]
you can find the updated version on my github repository

**Comment by pilusoyyo** [comment]
Hi, love the program, I found that the Super Galaxy Rumble skin has a bug in the Q and in the R, the Q lands in the left and the R is invisible <3, can that be fixed?, thx

**Comment by iluvketamine** [comment]
ayo can i use this?
its not from the OG creators

**Comment by hotline1337** [comment]
13.16 Update has been pushed to the main branch.
