### ISSUE TITLE
r3nzskin 13.16 doesnt work for me

### ISSUE THREAD

**Issue by lucsaurus** [R3nzTheCodeGOD/R3nzSkin#713]
Whenever i start the program it says this error 
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/142527062/4a7c9be9-6197-41b5-9801-70455f6f2c7b)

**Comment by fabian260** [comment]
how to work ?

**Comment by kelvin012** [comment]
i'm pretty sure you are opening the wrong version of the program! can you please download again in the following link: **https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v3.1.5** and verify if it still doesn't work ?

**Comment by hotline1337** [comment]
You are using an outdated version, please delete all the old files and download the latest one from the Release tab.
