### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by waffapo9** [R3nzTheCodeGOD/R3nzSkin#719]
hello i instaled the program and i got a win defender error abt a trojan virus i read abt it on the issues page and it stated that its a fals positive and i disabled the win defender and since then my pc is acting strange and i scanned it with virus total and 33/65 antiviruses detected it as a virus and the antiviruses that detected it were some of the best.
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/142713475/d05e087d-2761-4da9-b5fd-9c311f5c49d9)

**Comment by kelvin012** [comment]
instead of disabling windows defender you can add the program folder to the windows defender exclusions list and look for a way to add the folder to an exception to the antivirus you mentioned

**Comment by Arda0801** [comment]
DO NOT RUN. This is a trojan and they will steal your money.

**Comment by Wadoo69** [comment]
> DO NOT RUN. This is a trojan and they will steal your money.

You are so brain damaged, Jesus. ALL DLL INJECTORS GIVE FALSE POSITIVES ON ANTIVIRUSES.

All the injectors are flagged as "viruses", but nothing is wrong with them, fucking idiot.

**Comment by Arda0801** [comment]
> > DO NOT RUN. This is a trojan and they will steal your money.
> 
> You are so brain damaged, Jesus. ALL DLL INJECTORS GIVE FALSE POSITIVES ON ANTIVIRUSES.
> 
> All the injectors are flagged as "viruses", but nothing is wrong with them, fucking idiot.

The day I ran this "False Positive" injector, my steam account was compromised. Saw many people with the same issue. Do NOT install this app and risk your creditentials.

**Comment by Wadoo69** [comment]
> > > DO NOT RUN. This is a trojan and they will steal your money.
> > 
> > 
> > You are so brain damaged, Jesus. ALL DLL INJECTORS GIVE FALSE POSITIVES ON ANTIVIRUSES.
> > All the injectors are flagged as "viruses", but nothing is wrong with them, fucking idiot.
> 
> The day I ran this "False Positive" injector, my steam account was compromised. Saw many people with the same issue. Do NOT install this app and risk your creditentials.

Ive used this for months and didnt get shit compromised, you just pirated some shit from some shady torrent site like 1337x and got viruses. And where are the "many" people with the same issue. I have friends that use this and have no issue, sounds like a you problem because you have no fucking clue what you are talking about.

**Comment by hotline1337** [comment]
I'm tired of this.

**Comment by LuccasFreire** [comment]
> > > DO NOT RUN. This is a trojan and they will steal your money.
> > 
> > 
> > You are so brain damaged, Jesus. ALL DLL INJECTORS GIVE FALSE POSITIVES ON ANTIVIRUSES.
> > All the injectors are flagged as "viruses", but nothing is wrong with them, fucking idiot.
> 
> The day I ran this "False Positive" injector, my steam account was compromised. Saw many people with the same issue. Do NOT install this app and risk your creditentials.

Jesus christ, at least provide some kind of proof you donkey, you've got the whole repository to look on, or you dont know shit about coding and how the Windows architecture and processes works?

**Comment by sansbruhgaming** [comment]
> > > DO NOT RUN. This is a trojan and they will steal your money.
> 
> > 
> 
> > You are so brain damaged, Jesus. ALL DLL INJECTORS GIVE FALSE POSITIVES ON ANTIVIRUSES.
> 
> > 
> 
> > All the injectors are flagged as "viruses", but nothing is wrong with them, fucking idiot.
> 
> 
> 
> The day I ran this "False Positive" injector, my steam account was compromised. Saw many people with the same issue. Do NOT install this app and risk your creditentials.

Arda don't attempt to smear R3nz's name with your terrible cyber security practices. You should never type in your password when you are forced to log into a steam page. Instead open steam in a new tab, and make sure you are logged in. The next time you click onto a steam login page, you will simply need to click that you are logging in. If a page does not have that steam auth, it is a phishing page designed to steal your account
