### ISSUE TITLE
About automatic updates

### ISSUE THREAD

**Issue by 1873505600** [R3nzTheCodeGOD/R3nzSkin#720]
Whether automatic update can be set as an optional configuration item, thanks

**Comment by kyrioA** [comment]
Automatic updates? Not possible because every time league releases a new patch, the offsets for skin loading will change, there is no easy way to automatically update them. Someone needs to find and retest.

**Comment by 1873505600** [comment]
> Automatic updates? Not possible because every time League releases a new patch, the offsets for skin loading (and every other method in-game) will change, there is no easy way to automatically update them. Someone needs to find and retest before it is released every time.

Sorry, you may have misunderstood me, I was talking about the steps to detect updates from github every time the software is started. I know that the base address offset in the skin needs to be updated whenever the client is updated, so just click Update at that time
