### ISSUE TITLE
2 Questions: How to Build? Another files have a Trojan?

### ISSUE THREAD

**Issue by Sammyns** [R3nzTheCodeGOD/R3nzSkin#722]
1 - I don't know how to 'BUILD' the file from your GitHub to test through it.

2 - When I tried to download the same application from a YouTube video, it was a HEAVY Trojan that infected my PC, and some moments later I found out that the channel owner was also infected with the Trojan and he posted the video not on his own accord. (The owner of the channel was a Brazilian kid, didn't even speak English. But the video was in English...)

**Comment by Arda0801** [comment]
Someone modified this to add a trojan. What did you lose? Also change passwords immidiately and redownload windows from a usb installed from another pc.

**Comment by cjaryou** [comment]
is this safe to use ? @Arda0801

**Comment by Arda0801** [comment]
My antivirus says this one is the safe one to use but I would still be very careful

> is this safe to use ? @Arda0801
