### ISSUE TITLE
I got 2 permaban accounts after using this Programm for 2 days. 

### ISSUE THREAD

**Issue by qMezero** [R3nzTheCodeGOD/R3nzSkin#724]
I got 2 permabans account after using this Programm for 2 days.  The reason in the window is " Using third-party programs".
Dont use this anymore guys if u want to stay on your account.

**Comment by qMezero** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/138614258/572fc5dd-6b72-4c22-93dd-26cd0cc7f676)

**Comment by kuba031008** [comment]
I've been using this for bout a year now with no issues, maybe russian server has extra protection like korean?

**Comment by qMezero** [comment]
> I've been using this for bout a year now with no issues, maybe russian server has extra protection like korean?

I also played on the Russian server with this program for about a year and everything was fine, but now, while my main account is in a monthly bath, I bought a smurf account of LVL 30 and played on it under the same program, which I downloaded from here with the latest version and that one such account was permanently banned after 2 days "for using third-party programs", that the second Smurf account was banned in the same way after 2 days for the same reason. Since I didn't use anything else except League of Legends and this program, I have no idea then what other software could have blocked me. I am now afraid to turn it on when playing on my main account.

**Comment by chimxwind** [comment]
idk if they are botted or not but its usually because of botted accounts they cant say anything so they just write third party programs there is a banwawe so even if u buy accounts they just get banned but idk if its botted or not

**Comment by qMezero** [comment]
> 

That is, you assume that accounts that have been raised to level 30 only on bots will be banned over time, right?

**Comment by chimxwind** [comment]
ye actually i got an account to smurf 5 hours ago or smth like that and it was banned after 2 games so :D

**Comment by qMezero** [comment]
> 

hmmm.... interesting.. so need to buy already played accounts to play when your main isnt active :P

**Comment by kuba031008** [comment]
So in the end, is it safe?

**Comment by qMezero** [comment]
> So in the end, is it safe?

I can't say for sure. But in my case with a ban of 2 new accounts with only this program running, I couldn't think of anything else but it. We need to check, anyway.

**Comment by Crowmeir** [comment]
This is probably part of the ongoing ban wave against account sellers since they probably botted those accounts.

**Comment by qMezero** [comment]
> 

yeah maybe but its stupid so sell this accounts if u know that he will be banned soon.

**Comment by hotline1337** [comment]
> > I've been using this for bout a year now with no issues, maybe russian server has extra protection like korean?
> 
> I also played on the Russian server with this program for about a year and everything was fine, but now, while my main account is in a monthly bath, I bought a smurf account of LVL 30 and played on it under the same program, which I downloaded from here with the latest version and that one such account was permanently banned after 2 days "for using third-party programs", that the second Smurf account was banned in the same way after 2 days for the same reason. Since I didn't use anything else except League of Legends and this program, I have no idea then what other software could have blocked me. I am now afraid to turn it on when playing on my main account.

"I bought a smurf account of LVL 30 and played on it under the same program"

You have answered your question yourself.
