### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by eienjdn** [R3nzTheCodeGOD/R3nzSkin#726]
When running, in system tray, if i am idle off my pc, the cpu fans go crazy and cpu usage supposedly spikes very high. when i open task manager, it just stops and dies down. would it be mining on my pc or something?

**Comment by kuba031008** [comment]
It's open source, if you know what you're doing just check it

**Comment by hotline1337** [comment]
Please download the skin changer from valuable sources, like this GitHub repository.
