### ISSUE TITLE
HERE COMES AGAIN AND AGAIN...( ERROR )

### ISSUE THREAD

**Issue by NelasDeSearun** [R3nzTheCodeGOD/R3nzSkin#728]
![1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/73052704/8574140d-f19c-4c88-9305-027a08b70177)
We need a hero to fix it

**Comment by NelasDeSearun** [comment]
Always shown the error after the new version's update :(

**Comment by nsthanh1307** [comment]
it's not working anymore

**Comment by seth007-moo** [comment]
> Always shown the error after the new version's update :(

That's normal

**Comment by DyroS3** [comment]
Waiting for an update, bro.

**Comment by liqingbang** [comment]
please fix it

**Comment by good-ideal** [comment]
please fix it

**Comment by IAKILL** [comment]
please fix <3

**Comment by Reraz** [comment]
That's normal when there is an update.
