### ISSUE TITLE
Malwarebytes and windows defender scan it as a virus

### ISSUE THREAD

**Issue by meatydangle** [R3nzTheCodeGOD/R3nzSkin#73]
So i just want to know from the creator if i should be worried or is it just a false positive.
<3

**Comment by B3aa3** [comment]
although im not the creator i can tell u its safe

**Comment by Clownsw** [comment]
The code is public, you can see if it is safe or not

**Comment by meatydangle** [comment]
> The code is public, you can see if it is safe or not
if i knew what im looking at i would
