### ISSUE TITLE
PLZ NEW PATCH 13.17 UPDAT

### ISSUE THREAD

**Issue by hasanatef** [R3nzTheCodeGOD/R3nzSkin#732]

**Comment by X4STA** [comment]
+1

**Comment by Bl1nterS** [comment]
+1

**Comment by Aperodry** [comment]
new Riot__g_window's sig:48 8B 0D ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? 84 C0
SkinId:40 38 BB ? ? 00 00 0F 85 ? 00 00 00 66 C7 83 ? ? 00 00 00 04 0F 31 48 C1 E2 ? 4C 8D 83 ? ? 00 00 48 0B C2 44 8B CF 48 89 44 24 ? 8B D7 48

**Comment by hasanatef** [comment]
yah wait new update
