### ISSUE TITLE
Compiled and updated R3nzSkin

### ISSUE THREAD

**Issue by Bl1nterS** [R3nzTheCodeGOD/R3nzSkin#733]
There's for everyone asking an update, since they didn't update the software yet and I'm tired of seeing everyone asking for an update, here it is
[R3nzSkin UPDATE.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12476277/R3nzSkin.UPDATE.zip)

**Comment by TraxYzq** [comment]
TYSM

**Comment by X4STA** [comment]
THANKS BRO WORKİNG !

**Comment by Bl1nterS** [comment]
Just to say, it probably doesn't work for chinese servers, so you have to wait for the official release for that i guess

**Comment by artcevvv** [comment]
can you drop the source code?

**Comment by Vincoz** [comment]
Can you share the new offset?

**Comment by randomguygithub00** [comment]
> There's for everyone asking an update, since they didn't update the software yet and I'm tired of seeing everyone asking for an update, here it is [R3nzSkin UPDATE.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12476277/R3nzSkin.UPDATE.zip)

Please upload the source code for this one. I appreciate it

**Comment by Bl1nterS** [comment]
> can you drop the source code?

https://drive.google.com/file/d/1Og7hMmtcxRLL81R6ZI5EtGY1NoWNBSj0/view?usp=sharing

**Comment by artcevvv** [comment]
tysm!

**Comment by randomguygithub00** [comment]
> > can you drop the source code?
> 
> https://drive.google.com/file/d/1Og7hMmtcxRLL81R6ZI5EtGY1NoWNBSj0/view?usp=sharing

It got blocked please upload new link

**Comment by Bl1nterS** [comment]
https://www.mediafire.com/file/rkmhmj4isb2r0ux/R3nzSkin-main.zip/file
Here

**Comment by AminLeon** [comment]
<3

**Comment by damian06github** [comment]
can someone help me? I downloaded both and It wont work,my discord is : _altokemirey

**Comment by damian06github** [comment]
> https://www.mediafire.com/file/rkmhmj4isb2r0ux/R3nzSkin-main.zip/file Here

can u help me? my discord is _altokemirey
