### ISSUE TITLE
Super Galaxy Rumble Bug

### ISSUE THREAD

**Issue by pilusoyyo** [R3nzTheCodeGOD/R3nzSkin#737]
Hi, im new in github, i hope this is the right place to talk about this <3
Im love the Super Galaxy Rumble Skin (the only good skin for rumble) and at the moment its very bug, the worst think right now its his (Q) when you press it, it land on the side, Also de (R) is invisible, but this isin´t really bad.
If possible to fix the bug with the (Q)?, its show perfect the animation and colors, but in the side of the champ xd
Thx- Pilu. 
![236019564-0106667d-f006-4d9d-85ce-e970274501d1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/110200446/ec59f774-f2a1-4b51-946a-ae0b1351cb5a)

**Comment by hotline1337** [comment]
#1
