### ISSUE TITLE
Do NOT under any circumstance use this software

### ISSUE THREAD

**Issue by kuba031008** [R3nzTheCodeGOD/R3nzSkin#743]
I got permamently banned for using third party tools on EUNE, with this happening in russia too the software isn't safe anymore.

**Comment by hotline1337** [comment]
This is because you have played on a botted 30 level account. The software is safe.

**Comment by kuba031008** [comment]
> This is because you have played on a botted 30 level account. The software is safe.

No, I did not, I hand leveled this account and had it for over 2 years, it is bannable
