### ISSUE TITLE
cancel hibernation mode and fps huge drop 

### ISSUE THREAD

**Issue by alox92** [R3nzTheCodeGOD/R3nzSkin#746]
hi , could you please fix your code , there is a lot of fps drop when i start it and i cant put my computer on hibernation mode , i have to reopen the software and kill it with task manager bro , your software is wonderful but need optimizations bro , go ahead pls <3 allah u akbar

**Comment by hotline1337** [comment]
if you have the "Hide to tray" option enable you have to close the injector in the task array or bring up the menu and close the main window, there's no need to use task manager.

**Comment by alox92** [comment]
It doesn’t work man , ans what about fps drop ? Cordialement Maaroufi AlainLe 5 sept. 2023 à 00:10, hotline ***@***.***> a écrit :﻿
if you have the "Hide to tray" option enable you have to close the injector in the task array or bring up the menu and close the main window, there's no need to use task manager.
