### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Tlhqdklii-S** [R3nzTheCodeGOD/R3nzSkin#749]
![Adsız](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/124883799/78c156ef-c8bc-4826-9a8d-0f1d0232c6c5)
are there anyone who see this error? how can i fix?

**Comment by tianyu0919** [comment]
me too

**Comment by hotline1337** [comment]
Use a proxy, like Cloudflare WARP
