### ISSUE TITLE
I think it needs an update

### ISSUE THREAD

**Issue by Crybik** [R3nzTheCodeGOD/R3nzSkin#75]
Hey, sup I think League of legends has updated the offsets so you gotta make another release with the new Offsets :P

**Comment by noNickidea** [comment]
> Hey, sup I think League of legends has updated the offsets so you gotta make another release with the new Offsets :P

program still works for me, what do you mean by that?

**Comment by Crybik** [comment]
When I inject the SkinChanger to the game, The game freezez

**Comment by Crybik** [comment]
Never mind, it worked after I redownloaded it. Closed
