### ISSUE TITLE
Just got perm banned after using program gg lmao

### ISSUE THREAD

**Issue by mrbetsy** [R3nzTheCodeGOD/R3nzSkin#750]
https://gyazo.com/26f6cd9e7c7c34a9738e4165320e751d

**Comment by Isizz9** [comment]
was your account bought or botted?

**Comment by mrbetsy** [comment]
bought yes not botted im not asking why it was banned btw just thought i was funny but more so also a warning to ppl with bought even handleveled account that they may get banned

**Comment by sansbruhgaming** [comment]
ok sure I'm just going to believe it wasn't botted, when you have no proof of the contrary. Kappa

**Comment by mackmudge** [comment]
Yeah I just got permbanned for using this

**Comment by AquaCobell** [comment]
you most likely got not banned for using skin changer, with your game id we can check which game you got banned for https://www.leagueofgraphs.com/de/match/euw/6310778829
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/71768923/0f5ec062-38e5-4cf6-8988-376decfbb01b)

This was clearly a bot game to level up the account.


League recently pushed out a new banwave, which you receive after playing one game, mine also got banned and my first thought was also  the skinchanger.
