### ISSUE TITLE
Failed to find pattern

### ISSUE THREAD

**Issue by nikefire55** [R3nzTheCodeGOD/R3nzSkin#756]
Anyone know how to fix this?
![fehler](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/101905817/60cf5c80-9152-43b0-9935-7a62e24b5905)

**Comment by crypoxyz** [comment]
its because league had an update (13.18) today and the new pattern still needs to be added, just wait for an update :)

**Comment by nikefire55** [comment]
ah okay ty

**Comment by NelasDeSearun** [comment]
> > its because league had an update (13.18) today and the new offsets still need to be added, just wait for an update :)
> 
> any idea how long it might take?

NOT FOR LONG
