### ISSUE TITLE
R3nzskin 13.18 Update + with source code

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#758]
https://github.com/Sheelia/R3nzSkin-v13.18

**Comment by alexcama12** [comment]
How do I update it? or do I have to delete and install it again?

**Comment by artcevvv** [comment]
you can compile dll file by using visual studio and replace it in the lol folder, there are guide pinned in issues.

**Comment by zhunanvv** [comment]
It works. Thank you

**Comment by artcevvv** [comment]
> you can compile dll file by using visual studio and replace it in the lol folder, there are guide pinned in issues.

or just download compiled files in Release section on the Sheelia's update page

**Comment by sxybeast** [comment]
> you can compile dll file by using visual studio and replace it in the lol folder, there are guide pinned in issues.

which version of visual studio should I use ?

**Comment by artcevvv** [comment]
> > you can compile dll file by using visual studio and replace it in the lol folder, there are guide pinned in issues.
> 
> which version of visual studio should I use ?

2022 is fine
