### ISSUE TITLE
2023年09/13，R3该怎么用？

### ISSUE THREAD

**Issue by 8917007** [R3nzTheCodeGOD/R3nzSkin#759]
一年前，我知道修改LogitechLed.dll文件，但现在没有这个文件了，请问该怎么操作？
A year ago, I knew how to modify the LogitechLed.dll file, but now I don't have this file. What should I do?

**Comment by hotline1337** [comment]
You can name R3nzSkin.dll to Hid.dll and put it in Game folder in League of Legends to automatically inject R3nzSkin.
