### ISSUE TITLE
Error 403: Cant open skinchanger

### ISSUE THREAD

**Issue by KapitanMarco** [R3nzTheCodeGOD/R3nzSkin#760]
![obrázek_2023-09-13_190405124](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/144942008/f69014e3-e0b4-4dcf-a8c1-a74b82a2341d)
Hello, this is the error that i get when i want to open skinchanger, I tried a lot of things and nothing worked for me, can you help? 
Thanks

**Comment by J-EnJay** [comment]
try noautoupdate edition of [this](https://github.com/J-EnJay/R3nzSkinCN/releases/tag/3.3.0)

**Comment by diyooor** [comment]
> ![obrázek_2023-09-13_190405124](https://user-images.githubusercontent.com/144942008/267732063-f69014e3-e0b4-4dcf-a8c1-a74b82a2341d.png) Hello, this is the error that i get when i want to open skinchanger, I tried a lot of things and nothing worked for me, can you help? Thanks

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin_Injector/main.cpp#L21

`	Injector::autoUpdate();`

Try commenting out this line, then making the changes to R3nzSkin/memory.hpp

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin/memory.hpp#L105

From 
` "48 8B 8F ? ? 00 00 45 33 C0 8B D3 48 8B 01 FF 90 ? ? 00 00"`

to 

`"48 8B 8F ? ? ? ? BA 37 00 00"`

per

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/466#issuecomment-1533246957

Reply if you have anymore issues, if it's not difficult paste the error dialogs in english please.

**Comment by CsKillua007** [comment]
> > ![obrázek_2023-09-13_190405124](https://user-images.githubusercontent.com/144942008/267732063-f69014e3-e0b4-4dcf-a8c1-a74b82a2341d.png) Hello, this is the error that i get when i want to open skinchanger, I tried a lot of things and nothing worked for me, can you help? Thanks
> 
> https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin_Injector/main.cpp#L21
> 
> `Injector::autoUpdate();`
> 
> Try commenting out this line like this:
> 
> `//Injector::autoUpdate();`
> 
> Then make the changes to R3nzSkin/memory.hpp per [#466 (comment)](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/466#issuecomment-1533246957)
> 
> https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin/memory.hpp#L105
> 
> From `"48 8B 8F ? ? 00 00 45 33 C0 8B D3 48 8B 01 FF 90 ? ? 00 00"`
> 
> to
> 
> `"48 8B 8F ? ? ? ? BA 37 00 00"`
> 
> Reply if you have anymore issues, if it's not difficult paste the error dialogs in english please.

Can you please explain how to open and edit the required files and how to then compile them back into exe DLL files

**Comment by diyooor** [comment]
> > > ![obrázek_2023-09-13_190405124](https://user-images.githubusercontent.com/144942008/267732063-f69014e3-e0b4-4dcf-a8c1-a74b82a2341d.png) Hello, this is the error that i get when i want to open skinchanger, I tried a lot of things and nothing worked for me, can you help? Thanks
> > 
> > 
> > https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin_Injector/main.cpp#L21
> > 
> > `Injector::autoUpdate();`
> > Try commenting out this line like this:
> > `//Injector::autoUpdate();`
> > Then make the changes to R3nzSkin/memory.hpp per [#466 (comment)](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/466#issuecomment-1533246957)
> > https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin/memory.hpp#L105
> > 
> > From `"48 8B 8F ? ? 00 00 45 33 C0 8B D3 48 8B 01 FF 90 ? ? 00 00"`
> > to
> > `"48 8B 8F ? ? ? ? BA 37 00 00"`
> > Reply if you have anymore issues, if it's not difficult paste the error dialogs in english please.
> 
> Can you please explain how to open and edit the required files and how to then compile them back into exe DLL files

#2
