### ISSUE TITLE
Kindred's marks

### ISSUE THREAD

**Issue by Bl1nterS** [R3nzTheCodeGOD/R3nzSkin#762]
Whenever I play Kindred with the skin changer on and Kindred has a mark on a jungle monster (whatever it may be), the mark is just a single blue dot on the map and It's really hard to see has it is a small as the orange spot indicating the monster on the map
Is there a fix to that? I find it weird since the mark on the map doesn't change depending on the skin though...

**Comment by hotline1337** [comment]
#1
