### ISSUE TITLE
Detected trojan

### ISSUE THREAD

**Issue by cursings** [R3nzTheCodeGOD/R3nzSkin#767]
is this real or false[https://i.imgur.com/QG4jEPr.png](url)

**Comment by priti921** [comment]
my browser isn't even letting me download it

**Comment by cursings** [comment]
yeah idk pretty sketchy

**Comment by hotline1337** [comment]
read closed issues

**Comment by Yaniv277** [comment]
he says read closed Issues  but he says that to all issues.....
so where's the answer?

**Comment by cursings** [comment]
i found it and basically says that its false positive and that its open source so u can compile it urself if ur scared

**Comment by priti921** [comment]
or you can just allow it on your system

**Comment by cursings** [comment]
how does that fix the concerns about virus? just allowing it? XD

**Comment by gustavocsb** [comment]
u can read the entire code and compile it yourself, that ends your worry 😉

**Comment by Yaniv277** [comment]
do I even need to mention how moronic and useless your "advice" is gustavocsb?

**Comment by gustavocsb** [comment]
do I even need to mention how moronic and useless is to claim trojan on a open source when u can read entire code and compile it? lol

**Comment by cursings** [comment]
or just stop being brainless under my issue perhaps? yall have no money or info that could be stolen anyways so why care abt a trojan? XD

**Comment by gustavocsb** [comment]
you opened the issue about trojan, do u have brain dmg? lol

**Comment by gustavocsb** [comment]
kkkkkkkkk tu é um nerdola do crlh msm
