### ISSUE TITLE
China server cannot enter the game

### ISSUE THREAD

**Issue by loverorser** [R3nzTheCodeGOD/R3nzSkin#768]
When I rename the dll to hid.dll and put it in to the Game folder,I found that I cannot enter the game,it turns black and then crush without any infomation(like zigs),and then it returns to the reconnect panel.However,when I remove the hid.dll and reinstall the client,it works well.Can you please fix it?

**Comment by hkthomas** [comment]
Chinese servers are not supported.

You can try to find the offset yourself and compile again.

**Comment by hkthomas** [comment]
win11 stable working.

Try reinstalling the client or system.

**Comment by loverorser** [comment]
thanks.I'm using win10 and for now I'm unwilling to upgrade to win11 since win11 is not nice for me X(
Is there other way to fix this pls?Everything goes well until League of Legends upgrades to 13.18

**Comment by hkthomas** [comment]
At which step did it turn black.

Did you check the display card driver? 

Maybe you can Try changing to another windows 10 system version.

**Comment by lnkikee** [comment]
win10 can run normally.

**Comment by hotline1337** [comment]
Chinese League of Legends has an anti-cheat, which R3nzSkin doesn't provide a bypass for.
