### ISSUE TITLE
random error

### ISSUE THREAD

**Issue by t9nzo** [R3nzTheCodeGOD/R3nzSkin#774]
![dsasdadsa](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/138014508/c65bbdcb-de87-47e2-b82e-530e5bd5c668)
So i get this every patch when i use the skinchanger for 1 week then it wont open showing this error. I have tried reinstalling it multiple times. Any idea on fixes?

**Comment by hotline1337** [comment]
Just read the error.
