### ISSUE TITLE
Failed to find pattern ;...

### ISSUE THREAD

**Issue by niegh1** [R3nzTheCodeGOD/R3nzSkin#775]
![Screenshot_1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/145729137/434988b1-ff15-4d0e-8001-30973c3314d6)
I was fixing it by reinstalling the program constantly, now even that is not working, reinstalled program many times and i still get this error when my game loads.?

**Comment by hotline1337** [comment]
Make sure you use the latest release of R3nzSkin.
