### ISSUE TITLE
Error when injecting.

### ISSUE THREAD

**Issue by NotKhimz** [R3nzTheCodeGOD/R3nzSkin#780]
I entered a game like usual and pressed injected, but this error popped up after a bit. Please take a look into this, thanks. After closing it, it keeps popping up until I close League.
![Captur123123111e](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/146163470/cca89d89-3d26-432f-a41a-4be1789cdb38)

**Comment by athernalz** [comment]
its because of the new 13.19 patch, wait for an update

**Comment by diyooor** [comment]
#782
