### ISSUE TITLE
fix for 13.19

### ISSUE THREAD

**Issue by i4TsU** [R3nzTheCodeGOD/R3nzSkin#782]
replace the Riot__g_window sig with this:

`48 8B 0D ? ? ? ? FF 15 ? ? ? ? 48 8B 05 ? ? ? ?`

**Comment by 301yve** [comment]
work ?

**Comment by NotKhimz** [comment]
Where do I find that?

**Comment by brkforlol** [comment]
how i do that ?

**Comment by artcevvv** [comment]
tysm!

**Comment by artcevvv** [comment]
> how i do that ?

check the pinned problem "Tutorial : How to change offsets by yourself", there are full guide how to do it by yourself

**Comment by brkforlol** [comment]
i dont undrestand bro becuse i dont know english

**Comment by brkforlol** [comment]
> > how i do that ?
> 
> check the pinned problem "Tutorial : How to change offsets by yourself", there are full guide how to do it by yourself

**Comment by diyooor** [comment]
> > > how i do that ?
> > 
> > 
> > check the pinned problem "Tutorial : How to change offsets by yourself", there are full guide how to do it by yourself

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/6b41f7b1c47ebbc9a7ca04bf6f1895d94df94e97/R3nzSkin/memory.hpp#L90

**Comment by a491363060** [comment]
You are a hero, bro

**Comment by brkforlol** [comment]
i do Riot_g  but he says failed to pattern

**Comment by brkforlol** [comment]
![Ekran Alıntısı](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/144036504/c8171a0b-bb80-452e-b44b-682db375b27d)

**Comment by brkforlol** [comment]
pls help me

**Comment by artcevvv** [comment]
> pls help me

Here are the link for already compiled dll file, you need just to change it in the LoL folder https://mega.nz/folder/6nomVJgA#bLEgLwlU3sdg3xh_Q2XIbQ

**Comment by desmond315** [comment]
> > pls help me
> 
> Here are the link for already compiled dll file, you need just to change it in the LoL folder https://mega.nz/folder/6nomVJgA#bLEgLwlU3sdg3xh_Q2XIbQ

and how do u do that ? where should i put this file to

**Comment by artcevvv** [comment]
> > > pls help me
> > 
> > 
> > Here are the link for already compiled dll file, you need just to change it in the LoL folder https://mega.nz/folder/6nomVJgA#bLEgLwlU3sdg3xh_Q2XIbQ
> 
> and how do u do that ? where should i put this file to

you need just to download the file from the link and replace the file in League of Legends folder with the downloaded one.

**Comment by desmond315** [comment]
> > > > pls help me
> > > 
> > > 
> > > Here are the link for already compiled dll file, you need just to change it in the LoL folder https://mega.nz/folder/6nomVJgA#bLEgLwlU3sdg3xh_Q2XIbQ
> > 
> > 
> > and how do u do that ? where should i put this file to
> 
> you need just to download the file from the link and replace the file in League of Legends folder with the downloaded one.

thx bud !

**Comment by willTrindade01** [comment]
When I put the file "RENZSKIN.DLL" inside the lol folder, "replace" doesn't appear, can anyone help me?

**Comment by Satturn77** [comment]
> > > > pls help me
> > > 
> > > 
> > > Here are the link for already compiled dll file, you need just to change it in the LoL folder https://mega.nz/folder/6nomVJgA#bLEgLwlU3sdg3xh_Q2XIbQ
> > 
> > 
> > and how do u do that ? where should i put this file to
> 
> you need just to download the file from the link and replace the file in League of Legends folder with the downloaded one.

hey bro, i did this but the error of patern stills, you can help me?

**Comment by qxb3** [comment]
@artcevvv the mega link does not seem to be working
