### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by mrbetsy** [R3nzTheCodeGOD/R3nzSkin#785]
cant figure all that coding stuff out, anyone that can just drop a downloadable file in here for us that dont have the brains to figure out coding

**Comment by brian8544** [comment]
https://github.com/brian8544/R3nzSkin/releases/download/v3.1.8/R3nzSkin.zip

**Comment by mrbetsy** [comment]
appreaciate you dawg thank u

**Comment by cursings** [comment]
dont download this lmao XD its from a random. might as well just download trojan

**Comment by cursings** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/108147265/01db3a56-489c-4a5b-ac1a-922f437efe5c)
 HE LITERALLY POSTED A RAT XD

**Comment by k510i** [comment]
> ![image](https://user-images.githubusercontent.com/108147265/271070387-01db3a56-489c-4a5b-ac1a-922f437efe5c.png) HE LITERALLY POSTED A RAT XD

You can literally see all commits he did to his fork. Only offsets were changes. Do some research before lynching people on this site.

**Comment by srekXD** [comment]
> https://github.com/brian8544/R3nzSkin/releases/download/v3.1.8/R3nzSkin.zip



this shit not working

:{

**Comment by brian8544** [comment]
> > ![image](https://user-images.githubusercontent.com/108147265/271070387-01db3a56-489c-4a5b-ac1a-922f437efe5c.png) HE LITERALLY POSTED A RAT XD
> 
> You can literally see all commits he did to his fork. Only offsets were changed. Do some research before lynching people on this site.

Appreciated! :)
