### ISSUE TITLE
R3nzSkin 13.19

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#786]
https://github.com/Sheelia/R3nzSkin-v13.19

You can find the updated version in my repository

https://github.com/Sheelia/R3nzSkinTFT

**Comment by strangerobj** [comment]
is this legit?

**Comment by null15** [comment]
> https://github.com/Sheelia/R3nzSkin-v13.19
> 
> You can find the updated version in my repository
> 
> https://github.com/Sheelia/R3nzSkinTFT

Thanks <3 Sheelia can I somehow contact you? also yes its legit, it works

**Comment by kattenstar11** [comment]
@Sheelia i cant open tft can u help me

**Comment by makabaka2869** [comment]
> https://github.com/Sheelia/R3nzSkin-v13.19
> 
> 您可以在我的存储库中找到更新的版本
> 
> https://github.com/Sheelia/R3nzSkinTFT

Thank you very much, thank you for everything, so that I can use this program, come on, come on

**Comment by theodorsky6** [comment]
![εικόνα_2023-09-28_055646167](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/146308071/902edea7-d6ca-446b-8020-5abac2ae8310)

Still doesn't work for me
