### ISSUE TITLE
why the newest version have a lot more false positive ans the file weighs more? and name of injector is changing after each execution 

### ISSUE THREAD

**Issue by StraaFy** [R3nzTheCodeGOD/R3nzSkin#79]

**Comment by serekAlmette** [comment]
yup, probably the additional weigh it got from last one is random name generator

**Comment by Viqnish** [comment]
Everytime I allow the app through windef it opens only for it to rename next time. I have to do it every single time I reboot. Is there a way to stop it?

**Comment by maIwina** [comment]
> Everytime I allow the app through windef it opens only for it to rename next time. I have to do it every single time I reboot. Is there a way to stop it?

add whole folder BRUH
