### ISSUE TITLE
Update 13.19 Download

### ISSUE THREAD

**Issue by DemoorBug** [R3nzTheCodeGOD/R3nzSkin#790]
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12745155/R3nzSkin.zip)

**Comment by ZiyuWangs** [comment]
国服可以用了，谢谢了

**Comment by asdfbs** [comment]
> 国服可以用了，谢谢了

请问国服怎么用？

**Comment by ZiyuWangs** [comment]
> > 国服可以用了，谢谢了
> 
> 请问国服怎么用？

把这个解压放到英雄联盟文件的game目录，改个名字hid.dll就可以进游戏了

**Comment by makabaka2869** [comment]
> [R3nz皮肤.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/12745155/R3nzSkin.zip)

how did you do it? brother

**Comment by DemoorBug** [comment]
> how did you do it? brother

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2#issue-1006893839

https://github.com/R3nzTheCodeGOD/R3nzSkin/pull/784/files

**Comment by asdfbs** [comment]
> > > 国服可以用了，谢谢了
> > 
> > 
> > 请问国服怎么用？
> 
> 把这个解压放到英雄联盟文件的game目录，改个名字hid.dll就可以进游戏了

谢谢

**Comment by bellyr** [comment]
古德古德

**Comment by qing-shang** [comment]
古德古德

**Comment by bianchen1997** [comment]
古德古德
