### ISSUE TITLE
How to update yourself

### ISSUE THREAD

**Issue by ajihua** [R3nzTheCodeGOD/R3nzSkin#793]
I compiled it myself last time and it can run on the Chinese server. When updating the minor version, do I need to modify the memory address? I know a little bit about C++, but I’m not very proficient yet.

**Comment by Account231** [comment]
Precompiled for v13.19: https://file.io/1wHXTPwn3EDP

**Comment by damian06github** [comment]
@Account231 it has been deleted

**Comment by Account231** [comment]
![R3nzSkin](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/115872091/294f8515-bb71-416c-b399-8f0251a2ae56)
download this and change extension name to .dll from .gif because github dont allow .dll files to upload

**Comment by Account231** [comment]
wait for owner to update, because all file hostings will block it
