### ISSUE TITLE
R3nzSkin updated version 13.19 + open source

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#794]
https://github.com/Sheelia/R3nzSkin-v13.19

**Comment by pollitobiolador** [comment]
no funciona!!

**Comment by Leshu7w7** [comment]
Que te aparece? Yo uso el skin changer de lol y TFT de @Sheelia y me funcionan de maravilla. Estas usando la precompilada o lo estas intentando compilar por tu cuenta?
