### ISSUE TITLE
There's a problem with the gui text.

### ISSUE THREAD

**Issue by say2256** [R3nzTheCodeGOD/R3nzSkin#8]
I'm going to play on an Asian server. But there's an error in the name of the skin. Is there an easy way to solve it
![캡처](https://user-images.githubusercontent.com/64476960/136028690-c2119e0d-7523-43d2-8753-2be215e602be.PNG)
?

**Comment by say2256** [comment]
Please tell me how to solve it easily.

**Comment by R3nzTheCodeGOD** [comment]
Now supports all Asian languages.
