### ISSUE TITLE
Windows Defender detects "R3nzSkin.dll" as potentially dangerous.

### ISSUE THREAD

**Issue by Th3Nigh7mare** [R3nzTheCodeGOD/R3nzSkin#81]
I don't know if you could fix this, I know it's not something "malicious" I don't know if you could fix it in future updates!

Thank you very much
![windows_defender](https://user-images.githubusercontent.com/66384195/161148615-5e9647a9-dcfa-4538-ae43-335c52fdd7a9.png)
!

**Comment by Sterbenm** [comment]
Becauae it changes dll's in C:/Riot Games i think.
