### ISSUE TITLE
error plz help me

### ISSUE THREAD

**Issue by gqx1111** [R3nzTheCodeGOD/R3nzSkin#817]
![屏幕截图 2023-10-03 233152](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/146861269/90274fcb-b67c-401f-b6cf-a1d29e6c8dc4)

**Comment by gqx1111** [comment]
it happende when i open the R3nzSkin.dll

**Comment by hotline1337** [comment]
not related to the project.
