### ISSUE TITLE
Compiling from source on Visual Studio 2022 Community Edition generates only intermediary files.

### ISSUE THREAD

**Issue by B44-x** [R3nzTheCodeGOD/R3nzSkin#819]
This seems to be the case as of latest release, the compile logs all indicate that everything has gone well and even point to the location of the dll and injector, however opening the target folders there are only intermediary compilation files and unlinked object files. There has been no AV tampering as I've excluded it from scanning the solution folder.

**Comment by hotline1337** [comment]
the builded dll is located in Release/RiotGamesServers
