### ISSUE TITLE
I have some delay 

### ISSUE THREAD

**Issue by Dz4ke** [R3nzTheCodeGOD/R3nzSkin#823]
Hello lately i fell him my champion have delay when i press example q on yas e too idk why before wasnt like that idk what is happening.I get teleport lags too like my champ floating.

**Comment by diyooor** [comment]
Could be #1 also could be on your end but don't know as you don't put much information regarding the bug.

**Comment by Dz4ke** [comment]
Check this video its kinda simular but a lot smaller teleportation and affects spell too

**Comment by Dz4ke** [comment]
https://www.youtube.com/watch?v=LB6vgc1i6Bs&ab_channel=ShowmenTV

**Comment by diyooor** [comment]
> Check this video its kinda simular but a lot smaller teleportation and affects spell too

What kind of system are you using?

**Comment by Dz4ke** [comment]
You mean windows ? 10

**Comment by hotline1337** [comment]
It's caused by ur pc itsef.
