### ISSUE TITLE
i got perma ban hahahahaha idk if its bcs of the skinchanger or its bcs its a smurf

### ISSUE THREAD

**Issue by PresetyX** [R3nzTheCodeGOD/R3nzSkin#827]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/147277727/12ddd65b-b492-41f8-b74d-16226786345b)

**Comment by mariomo16** [comment]
That happens when you buy a booted lvl30 account (usually).

**Comment by katawinacx** [comment]
same XD ig its because it was botted acc dont think it was cuz of the skin changer 
![Uploading image (4).png…]()

**Comment by PresetyX** [comment]
> That happens when you buy a booted lvl30 account (usually).

lol, how unlucky, i literally have this acc for 9 months, and only got banned now

**Comment by hotline1337** [comment]
Caused by a botted account.
