### ISSUE TITLE
Language on R3nz

### ISSUE THREAD

**Issue by Dimmylol** [R3nzTheCodeGOD/R3nzSkin#828]
Is there a possibility to change language on r3nz without having to change language of client, and otherwise?

**Comment by hotline1337** [comment]
No. But you are welcome to rewrite the source to make it in your language.

**Comment by Dimmylol** [comment]
Ive havent meant like that, I have my league on korean, and im asking if
its possible to change it back to English while having league still on
korean. Thanks for your help and response. Have a good day
