### ISSUE TITLE
[Request]Nightbringer Yasuo Animation is bugged if EQ before his R

### ISSUE THREAD

**Issue by hieutlee** [R3nzTheCodeGOD/R3nzSkin#831]
During Yasuo Nightbringer R the animation is bugged if you EQ before R. Furthermore, his Ult Voice is STILL base skin voice instead of Nightbringer one(I know this is #1). Thanks heaps

**Comment by hotline1337** [comment]
#1 If you know its #1 then why do you even bother to open a issue.
