### ISSUE TITLE
gui not working on some champions

### ISSUE THREAD

**Issue by Nemanjica** [R3nzTheCodeGOD/R3nzSkin#833]
today i was playing nautilus and evelynn, everything worked great. But when I played shaco and veigar I pressed " insert " and the gui doesn't show up. is it cuz of the 13.20v coming out or is it issue w me?

**Comment by suerxyy** [comment]
the same happens to me

**Comment by RoadToManualBan** [comment]
the new patch of league came out, which is the 19.20 and because of that the skin changer isnt updated yet to the new version. u need to wait

**Comment by sansbruhgaming** [comment]
Appears to be an issue with you. The GUI automatically shows up when it injects why would you need to press Insert after that?

**Comment by Nemanjica** [comment]
sans the point is tha the gui does not even show up if you join the game, thats why everyone wants it to be updated
