### ISSUE TITLE
how to find memory patterns after update

### ISSUE THREAD

**Issue by Saleh-Alikhani** [R3nzTheCodeGOD/R3nzSkin#835]
After each update of riot the memory patterns may change which is gonna end up releasing new version of this program but how do you find the pattern of the memory which is mentioned in memory.hpp file?

**Comment by hotline1337** [comment]
When the dll injects and the pattern is wrong, you will see a prompt. Dump the league process, dissasemble it and search for the pattern with less bytes.

**Comment by Saleh-Alikhani** [comment]
@hotline1337 hi thanks a lot for the information you just share but can you please explain a bit more like which process should I dump since there are 5 or 6 process to league and which debugging type should be done and which tool of debugging should I use to get the new address please help me if possible I am obsessed with this subject and thank you again.
