### ISSUE TITLE
It says it has viruses

### ISSUE THREAD

**Issue by Eurelex** [R3nzTheCodeGOD/R3nzSkin#839]
my browser (brave) doesnt let me dowloand any version cause of viruses even though i say keep file this time windows defender deletes it directly what am i supposed to do 

edit: I got keylocked 1 time after downloaded r3nzskin 

edit 2: and pls do not say disable antivirus i do not want to get keylocked again. thanks for your helps.

**Comment by Pankye** [comment]
says it is a virus because it behaves like one, but it is not, it is mandatory to disable the antivirus or create an exception

**Comment by hotline1337** [comment]
Disable your antivirus (Real-time protection). Then the browser will allow you to download the binaries.
