### ISSUE TITLE
13.20 Update?????

### ISSUE THREAD

**Issue by ScottSun0201** [R3nzTheCodeGOD/R3nzSkin#840]
13.20 When will it be updated? Grandpa Cow

**Comment by Leshu7w7** [comment]
#836

**Comment by Saleh-Alikhani** [comment]
any news ? we are waiting for new patterns.

**Comment by Leshu7w7** [comment]
@Saleh-Alikhani, there's no need for an update since there were not changes on the offset patterns. Check #832, #836 and #843 for reference
