### ISSUE TITLE
Is this app safe, heard a lot of comments about this app and they weren't good, specially with data and that it consumes a lot of cpu usage

### ISSUE THREAD

**Issue by kowyy** [R3nzTheCodeGOD/R3nzSkin#841]

**Comment by diyooor** [comment]
Uses less than 1% CPU for me. Care to provide more context?

**Comment by kowyy** [comment]
Well, many posts in reddit (as this one, https://www.reddit.com/r/LoLcustom/comments/13qrg5a/the_virus_of_r3nzskin_is_not_false_positive_its/) say that it's not safe to download it and that it consumes a lot (5-10%)

**Comment by hotline1337** [comment]
It might consume some of the CPU because it checks for league process pretty often. The project is open source, so you can check the code for yourself and confirm it's not malicious.
