### ISSUE TITLE
We need the update of 13.20 patch please.

### ISSUE THREAD

**Issue by TraxYzq** [R3nzTheCodeGOD/R3nzSkin#842]

**Comment by Leshu7w7** [comment]
Bro just read #832 and #836

**Comment by Nemanjica** [comment]
everything works but when i want to press insert nothing happens, am i doing something wrong??

**Comment by hotline1337** [comment]
No need for an update.

**Comment by Malshan-svg** [comment]
> No need for an update.

It only works in ARAM , Custom and practice tool games.. when we enter ranked games the game crashes... Please update thank you
