### ISSUE TITLE
13.19 release is working on 13.20

### ISSUE THREAD

**Issue by Leshu7w7** [R3nzTheCodeGOD/R3nzSkin#843]
### **This issue is for the ones who don't check closed issues prior creating a new one.**

As the title says, the previous release is working on 13.20 since the offsets were not changed. Therefore, no update is needed. Just use it as usual, and it should work. 

Please, @hotline1337, do not close this issue to avoid the creation of new ones.

**Comment by Saleh-Alikhani** [comment]
ok my problem is solved by downloading the last release from github and deleted the .dll file which I built myself with VS.

**Comment by mayacopeland** [comment]
Even using the latest release, changing the skins of towers seems to cause crashes, otherwise, everything else is fine
