### ISSUE TITLE
Gui doesnt work on some champions.

### ISSUE THREAD

**Issue by DarkArtz0** [R3nzTheCodeGOD/R3nzSkin#845]
With the latest update the GUI doesnt work on some champions, it says injected but ingame you dont have a skinchanger

**Comment by Nemanjica** [comment]
same happens with me, did you find the fix or they have to update it
cuz i saw that they dont need to update it

**Comment by DarkArtz0** [comment]
> same happens with me, did you find the fix or they have to update it cuz i saw that they dont need to update it

Nope, I'm just waiting for like an update or a response from a dev.

**Comment by hotline1337** [comment]
duplicate issue.
