### ISSUE TITLE
Issue with 13.20

### ISSUE THREAD

**Issue by Bim7777777** [R3nzTheCodeGOD/R3nzSkin#848]
I have had no issues with this skinchanger so far, but when it autoupdated? or what happened so that the version for 13.19 worked in 13.20 it suddenly started crashing my game every time i try to use it now. Do you have an idea of what could be wrong?

**Comment by E1ehDogon** [comment]
just wait for new update in site. No ways to play with changer while didn't update

**Comment by TraxYzq** [comment]
Sometimes it will crashing on every game, its happened to me too you need to just restart the skin changer and it will work.

**Comment by OttoDelane** [comment]
better wait new update 13.19 really crashing game i  lose my rang game :D

**Comment by Bim7777777** [comment]
Thanks for the comments but the issue has fixed itself without me updating to the new version so it now works.
