### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by Ali229** [R3nzTheCodeGOD/R3nzSkin#849]
I'm not sure why issue about this error keeps getting closed, I'm trying this mod after months and it still suffers from this error... maybe it's because I'm in US region and there is datetime formatting issue?

Not sure, please fix this, putting dll and exe in same folder is NOT the solution, it throws this error and the exe never opens. This has been going on since 13.14 (or even before).

**Comment by RoadToManualBan** [comment]
gives u the error because u aint updating the skin changer. everytime the patch comes out, u need to download the skin changer again from the site. now u wont be able to use since there is no 19.20 patch. but it will come soon

**Comment by Ali229** [comment]
Of course I do download the new skin changer every time, this error has nothing to do with the version of skin changer, the version is only updated to change the offset, this error has always been there, there is also a solution to it, but the creator never merged it.
https://github.com/R3nzTheCodeGOD/R3nzSkin/pull/646

As I said putting the DLL in the same folder as EXE is not the solution, implying i'm already doing this, and I don't know why anyone would not do this.

**Comment by diyooor** [comment]
Can you post any screenshots or logs of the error?

**Comment by hotline1337** [comment]
> Of course I do download the new skin changer every time, this error has nothing to do with the version of skin changer, the version is only updated to change the offset, this error has always been there, there is also a solution to it, but the creator never merged it. #646
> 
> As I said putting the DLL in the same folder as EXE is not the solution, implying i'm already doing this, and I don't know why anyone would not do this.

I never merged it because there is no point. The exact code is already pushed to the main origin.
