### ISSUE TITLE
please update.

### ISSUE THREAD

**Issue by GhostOfSparta1** [R3nzTheCodeGOD/R3nzSkin#853]
You say there is no need to update, but the costumes are not working, please update the skin changer.

**Comment by Saleh-Alikhani** [comment]
If you built the .dll file youself with visual studio then just try downloading GitHub version.

**Comment by OttoDelane** [comment]
> If you built the .dll file youself with visual studio then just try downloading GitHub version.

what explain pls how it work

**Comment by TraxYzq** [comment]
> If you built the .dll file youself with visual studio then just try downloading GitHub version.

then can you put the new here pls

**Comment by hotline1337** [comment]
opening more and more issues like this is pointless.
