### ISSUE TITLE
Switching forms on Jayce without using a spell shows you the initial form.

### ISSUE THREAD

**Issue by sshindae** [R3nzTheCodeGOD/R3nzSkin#855]
Sometimes when you change forms on Jayce, you get stuck on your previous form (only visually) until you use a spell then your model looks fine. Is there any fix to this? I also want to believe it's a recent bug since I've played Jayce for a long time using this skin changer and never seen it happen before.

**Comment by kuba031008** [comment]
How'd you even get it to work? It isn't updated yet

**Comment by sshindae** [comment]
> How'd you even get it to work? It isn't updated yet

It didn't need an update for this patch.

**Comment by kuba031008** [comment]
wtf I'm stupid af 😭

**Comment by hotline1337** [comment]
#1
