### ISSUE TITLE
Request: Tutorial for scanning the memory pointer addresses

### ISSUE THREAD

**Issue by devCore1** [R3nzTheCodeGOD/R3nzSkin#856]
Hello,

since you are pretty much only changing the memory pointer addresses to the specific categories on every patch, can you make a tutorial on how to do that? If so you could link the tutorial and everyone could change it up by themselves if you dont have time to do it.

Love your efforts

**Comment by hotline1337** [comment]
You can start by looking in League of Legends category on UnknownCheats.
