### ISSUE TITLE
> Can't use mod in Ubuntu Linux using Wine

### ISSUE THREAD

**Issue by helioLJ** [R3nzTheCodeGOD/R3nzSkin#858]
> By using Lutris. Here's a couple of links:

I get this error when I try to run the R3nzSkin_Injector.exe

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/42224962/40f5766b-cfdd-47a7-b91f-c377effcf717)

_Originally posted by @helioLJ in https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/45#issuecomment-1767055783_

**Comment by hotline1337** [comment]
It doesn't support Linuxx.

**Comment by AndersonVilela** [comment]
For those of us who use Linux, we use Wine which creates a Windows layer to be able to work, in this case the injector.exe opens but it does not find the .dll in the directory

**Comment by boobthecat** [comment]
bump
