### ISSUE TITLE
could you please update 13.20😭

### ISSUE THREAD

**Issue by KKilos964** [R3nzTheCodeGOD/R3nzSkin#861]
thanks！No skin no game👿

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/pull/757/commits/9a2a0380e143594d29a8983b2ddeca31d1c6676d

**Comment by sansbruhgaming** [comment]
It still works for 13.20?????

**Comment by J-EnJay** [comment]
Why don't you try to see if it works before you ask such useless questions
