### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by GhostOfSparta1** [R3nzTheCodeGOD/R3nzSkin#864]
Yes, after the update, my game started crashing and I cannot play with skin changer.

**Comment by Vizarthy** [comment]
> Yes, after the update, my game started crashing and I cannot play with skin changer.

same here

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/9a2a0380e143594d29a8983b2ddeca31d1c6676d

With this update R3nzSkin and the injector still work for me. Download the repository, compile it and run it yourself.

Closes #864

**Comment by hotline1337** [comment]
> [9a2a038](https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/9a2a0380e143594d29a8983b2ddeca31d1c6676d)
> 
> With this update R3nzSkin and the injector still work for me. Download the repository, compile it and run it yourself.
> 
> Closes #864

The commit that u keep referencing has outdated offsets.

**Comment by diyooor** [comment]
> > [9a2a038](https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/9a2a0380e143594d29a8983b2ddeca31d1c6676d)
> > With this update R3nzSkin and the injector still work for me. Download the repository, compile it and run it yourself.
> > Closes #864
> 
> The commit that u keep referencing has outdated offsets.

My apologies I will use the correct commit hash: https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/f42bb66c19381ef4e066ed8001055008692dc3c4
