### ISSUE TITLE
can't run the injector

### ISSUE THREAD

**Issue by proman123g** [R3nzTheCodeGOD/R3nzSkin#865]
I downloaded the already compiled zip file and
 extracted it like so. but when i try to open the injector i get these errors. 

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/110601722/0809e171-4f62-4901-a7b9-97b5b09364ab)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/110601722/4b82af4a-5bc3-432f-8a49-3f76ec880fbd)

**Comment by proman123g** [comment]
also i tried redownloading i forgot to mention.

**Comment by proman123g** [comment]
fixed it by downloading some things from microsoft

**Comment by JulianOcmp12** [comment]
what did you download to make it work? i had the same problem with VCRUNTIME140.dll/VCRUNTIME140_1.dll and MSVCP140.dll but now when i try to open it this error pops up
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/148950809/796bc602-cebf-4f4d-8095-20ed86fba311)

**Comment by JulianOcmp12** [comment]
what did you download to fix it? i had the same problem with msvcp140.dll and vcruntime140.dll or vcruntime140_1.dll but then this error pops up
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/148950809/b1c6243c-1a45-4ccc-9797-58e6b118e4e7)
(The application could not be started correctly (0xc000007b))
