### ISSUE TITLE
kinda odd to update r3nzskin right before patch came out

### ISSUE THREAD

**Issue by mish20011** [R3nzTheCodeGOD/R3nzSkin#867]
Now its bugged failed pattern

**Comment by diyooor** [comment]
Are you using https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/08554e36c4131a4798b88fadb3cc0b79fd5e6d53 or https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/f42bb66c19381ef4e066ed8001055008692dc3c4 ?
