### ISSUE TITLE
Version 3.1.9 update: Failed to find pattern

### ISSUE THREAD

**Issue by hieutlee** [R3nzTheCodeGOD/R3nzSkin#868]
The game crashed and notified "Failed to find pattern: E8 ? ? ? ? 48 8D 8D ? ? 00 00 E8 ? ? ? ? 48 85 C0". Latest release version onto 13.21 Patch (OCE server)

**Comment by yinjun8462593** [comment]
I have the same problem. Is there a solution?

**Comment by wuchenc1** [comment]
the same problem, wait for update

**Comment by sansbruhgaming** [comment]
https://github.com/sansbruhgaming/R3nzSkin/releases/tag/THEYRE_COMING_HELPME_HELPHEMHEHELPHELPHELPHELPHELP
updated

**Comment by JulianOcmp12** [comment]
anyone know something about the error (0xc000007b) i already installed a lot of dll´s but r3nzskin wont open due to this error
