### ISSUE TITLE
Game update version 13.21, now can not enter, which Big Brother Know the new feature code to share, grateful ~ !

### ISSUE THREAD

**Issue by qq1403498204** [R3nzTheCodeGOD/R3nzSkin#869]
Game update version 13.21, now can not enter, which Big Brother Know the new feature code to share, grateful ~ !
![举证](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140217111/fac39ebe-644f-4899-8b4a-f183cd360368)

**Comment by sansbruhgaming** [comment]
https://github.com/sansbruhgaming/R3nzSkin/releases/tag/THEYRE_COMING_HELPME_HELPHEMHEHELPHELPHELPHELPHELP
updated

**Comment by StayAlivez** [comment]
E8 ? ? ? ? 41 8B 97 C8 11 00 00 
[R3nzSkinDll.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13163764/R3nzSkinDll.zip)

**Comment by TraxYzq** [comment]
> https://github.com/sansbruhgaming/R3nzSkin/releases/tag/THEYRE_COMING_HELPME_HELPHEMHEHELPHELPHELPHELPHELP updated

Doesnt work, it keeps crashing my game

**Comment by Borefaat** [comment]
WORKED THANKS <3
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/869#issuecomment-1778745255

**Comment by Gasferr** [comment]
CharacterDataStack__Push: E8 ? ? ? ? 41 8B 97 C8 11 00 00  update 13.21
