### ISSUE TITLE
failed to find pattern

### ISSUE THREAD

**Issue by magoOo33** [R3nzTheCodeGOD/R3nzSkin#870]

**Comment by fxw2142** [comment]
[R3nzSkinLite.txt](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13168058/R3nzSkinLite.txt)
rename txt file to .dll and inject with prochacker or any other injectors (r3nzskininjector doesnt work)

**Comment by fxw2142** [comment]
or use updated pattern - 			{
				"E8 ? ? ? ? 48 8D 8D ? ? 00 00 E8"
			}, true, false, false, 0, &offsets::functions::CharacterDataStack__Push
