### ISSUE TITLE
crashing game

### ISSUE THREAD

**Issue by 1castagnoli** [R3nzTheCodeGOD/R3nzSkin#872]
the program is causing the game to crash

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/965e1516ddafc02aab370d4a1242c253829ff931

Closes #872

**Comment by 1castagnoli** [comment]
?

**Comment by diyooor** [comment]
> ?

Download the solution, build it, add the release folder to windows security exclusions, put the R3nzskin.dll folder in the same folder as the injector and it should work. 

![Screenshot 2023-10-25 133324](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/38271173/606ba801-70df-4b6f-81df-6e3eda4531a3)

Or just download https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v3.2.0

**Comment by 1castagnoli** [comment]
I've already downloaded and extracted it, but unfortunately it's still crashing, even after enabling it in Windows Defender :( i'm dumb sorry

**Comment by 1castagnoli** [comment]
I have the most updated version, I'm from the BR server, if that matters

**Comment by diyooor** [comment]
> I've already downloaded and extracted it, but unfortunately it's still crashing, even after enabling it in Windows Defender :( i'm dumb sorry

> I have the most updated version, I'm from the BR server, if that matters

Can you try building the solution yourself and provide more information on your system, screenshots of every step. It's impossible to help you unless you're detailed with the issues you're facing.

**Comment by 1castagnoli** [comment]
I just did the usual, download the zip folder, extract, run, it used to work, but since the last update the program crashes the game and closes it. If you don't run the program, the game works normally. I haven't really made any changes to R3skin or my pc.

**Comment by hotline1337** [comment]
> I just did the usual, download the zip folder, extract, run, it used to work, but since the last update the program crashes the game and closes it. If you don't run the program, the game works normally. I haven't really made any changes to R3skin or my pc.

does the injector work (you can see the menu) ?

**Comment by 1castagnoli** [comment]
Yeah, the injector opens normally, I can start it and minimize it. The problem is in game, where the screen freezes while loading the game. even if I try to launch after the match starts, the program will crash the game instantly. It was normal until the last updt

**Comment by hotline1337** [comment]
> Yeah, the injector opens normally, I can start it and minimize it. The problem is in game, where the screen freezes while loading the game. even if I try to launch after the match starts, the program will crash the game instantly. It was normal until the last updt

Please try to download and use the following dll and injector: [https://gofile.io/d/P3sGvu](https://gofile.io/d/P3sGvu)
Tell me if the problem still occures.

**Comment by Bloodlust1212** [comment]
hi, iam facing the same problem, before update its fine, then now the game keep crashing

**Comment by 1castagnoli** [comment]
Wow, the one you sent is working perfectly. thank you very much

**Comment by Bloodlust1212** [comment]
> Wow, the one you sent is working perfectly. thank you very much

lemme try it too :D

**Comment by sentinela007nh** [comment]
memory error maybe, i will try later (today) if have update, also in BR version.

**Comment by Bloodlust1212** [comment]
> > Yeah, the injector opens normally, I can start it and minimize it. The problem is in game, where the screen freezes while loading the game. even if I try to launch after the match starts, the program will crash the game instantly. It was normal until the last updt
> 
> Please try to download and use the following dll and injector: https://gofile.io/d/P3sGvu Tell me if the problem still occures.

Thank you, its works

**Comment by hotline1337** [comment]
Perfect, I will push an update in a second. The issue is resolved.

**Comment by C1mplex** [comment]
guys to fix this 
go to client settings 
go to game
switch off prefer dx9 legacy mode
and enjoy

**Comment by xCrashzx** [comment]
> Please try to download and use the following dll and injector: https://gofile.io/d/P3sGvu Tell me if the problem still occures.

hello bro i have the same problem and the file you uploaded is not found can you upload it again?
