### ISSUE TITLE
Where is the injector located?

### ISSUE THREAD

**Issue by jospis** [R3nzTheCodeGOD/R3nzSkin#874]
When I download the latest version of R3nz skin I only have the R3nzSkin.dll file inside

**Comment by zskm01** [comment]
Me too.Have you sloved this problem?

**Comment by jospis** [comment]
> Me too.Have you sloved this problem?

Yes! You just have to turn off your anti cheat before downloading the file, you also need to turn off your anti cheat every time before turning on the anti cheat
