### ISSUE TITLE
DONT USE IT. ITS BANNABLE

### ISSUE THREAD

**Issue by 6uv** [R3nzTheCodeGOD/R3nzSkin#875]
Just got banned on my smurf for using it. 

https://cdn.discordapp.com/attachments/750255302473154640/1166945166582620251/image.png?ex=654c5560&is=6539e060&hm=4b18f229a91c7a75ab072b62be59de246f4223027af84ade9099348096ee76d7&

**Comment by diyooor** [comment]
I've used it for many patches and have not gotten banned. Did you purchase the account, or did you use a bot to level it up? Are you using any other 3rd party programs?

**Comment by 6uv** [comment]
> I've used it for many patches and have not gotten banned. Did you purchase the account, or did you use a bot to level it up? Are you using any other 3rd party programs?

yeah i did oopsie
