### ISSUE TITLE
Can't use R3nzSKin

### ISSUE THREAD

**Issue by insomnia7Step** [R3nzTheCodeGOD/R3nzSkin#876]
![Screenshot 2023-10-25 223704](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/149037848/44a99acc-3186-4372-b6d7-91288438b69b) 
it said  failed to find pattern. hm,,,? any Idea?

**Comment by crnapagoda** [comment]
do you have the latest version?

**Comment by jospis** [comment]
> do you have the latest version?

When I dowload the lates r3nz skin version I only get .dll file inside the folder without injector. Where do I download the injector?

**Comment by hotline1337** [comment]
> ![Screenshot 2023-10-25 223704](https://user-images.githubusercontent.com/149037848/278215536-44a99acc-3186-4372-b6d7-91288438b69b.png) it said failed to find pattern. hm,,,? any Idea?

Use the latest version of R3nzSkin

> When I dowload the lates r3nz skin version I only get .dll file inside the folder without injector. Where do I download the injector?

Disable your anti-virus when downloading the zipped release
