### ISSUE TITLE
Curser is stuttering in game

### ISSUE THREAD

**Issue by sarunoid** [R3nzTheCodeGOD/R3nzSkin#878]
Kral selam. Soruyu ingilizce yazmak istemedim Türk olduğunu öğrenince :D öncelikle harika bir iş çıkarmışsın tebrik etmek istiyorum seni ellerine sağlık. Onun dışında bir maruzatım olacaktı. Oyuna girip çalıştırdığımda programı genelde 2 dakika içinde farede takılma başlıyo ama sadece fare özelinde oyunda fps düşmese de sürekli takılarak ilerliyor fare oyun boyunca. Araştırdım ancak bir çözüm yolu bulamadım sana sormak istedim. Hayırlı tezkereler.

**Comment by hotline1337** [comment]
Update your graphics driver.
Disable mouse hardware acceleration.
Disable mouse scroll on hover.
