### ISSUE TITLE
Text display " ? " in Vietnamese (Garena VietNam server)

### ISSUE THREAD

**Issue by sonitaaaaa** [R3nzTheCodeGOD/R3nzSkin#88]
![image](https://user-images.githubusercontent.com/40225192/163170809-c2aec282-0e5d-4a87-8f5e-8baec8c076e5.png)

can you support char8_t for skin dll or you can tell me what can I do in here so I can try to change the code my self

**Comment by Aperodry** [comment]
first,add supported fonts at “init_imgui(void* device, bool is_d3d11)”,eg io.Fonts->AddFontFromFileTTF((path / "malgun.ttf").string().c_str(), 16.0f, &cfg, getFontGlyphRangesKr());

second,use “#define __CN(str) (const char*)u8##str” to convert your text

**Comment by sonitaaaaa** [comment]
> first,add supported fonts at “init_imgui(void* device, bool is_d3d11)”,eg io.Fonts->AddFontFromFileTTF((path / "malgun.ttf").string().c_str(), 16.0f, &cfg, getFontGlyphRangesKr());
> 
> second,use “#define __CN(str) (const char*)u8##str” to convert your text

umm sorry but where should I put with (#define __CN(str) (const char*)u8##str)

**Comment by sonitaaaaa** [comment]
#I will update the modified here

[**Update 12.11 - 15-Jun-2022**](https://drive.google.com/file/d/1voCnzjqoZkl2jjXHl8vlIIZK2aqaRTr2/view?usp=sharing)

**Comment by xinWas** [comment]
Sorry to disturb you, after I modified it according to your method, the skin name was displayed normally, but the menu option could not be displayed correctly, it still showed???

**Comment by sonitaaaaa** [comment]
> Sorry to disturb you, after I modified it according to your method, the skin name was displayed normally, but the menu option could not be displayed correctly, it still showed???

### **Make sure you do exactly what I do**

**1. Player tab**

![image](https://user-images.githubusercontent.com/40225192/185689056-7597d03d-1dfb-430f-a9d5-e0853d339b16.png)

**2. Other player tab**
![image](https://user-images.githubusercontent.com/40225192/185689199-f0a809f2-19c6-44dd-b75f-36d0e20ffaf8.png)

**3. Map tab**

![image](https://user-images.githubusercontent.com/40225192/185689334-666a6ee3-0c21-4dfa-8c6f-933db977615f.png)

**4. Extras tab**

![image](https://user-images.githubusercontent.com/40225192/185689402-81b3a8e2-6281-48af-af4a-d91056c4a46d.png)

**Comment by R3nzTheCodeGOD** [comment]
Vietnamese should now look correct.
