### ISSUE TITLE
Aatrox ultimate sound effect not working.

### ISSUE THREAD

**Issue by iaiaian1** [R3nzTheCodeGOD/R3nzSkin#882]
This is the classic skin of Aatrox, notice the ultimate sound.
https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/92788616/2d651eb9-e522-4669-93d9-e4b2b6e8aee0

This is Odyssey Aatrox, notice the ultimate sound is still the same as the classic although the everything else (voiceline, voice filter, skill sound effects etc.) is working.
https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/92788616/b451c671-8117-4a74-bfe2-6b563c4d5d7a

This bug also applies to his other skins with other ultimate sound effects. Pardon the video quality as I don't have a graphics card right now.

**Comment by hotline1337** [comment]
#1
