### ISSUE TITLE
possible malware?

### ISSUE THREAD

**Issue by synzxd** [R3nzTheCodeGOD/R3nzSkin#892]
a ton of ppl are saying that this contains malware and i just wanted to know if u can clarify this:
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/132475239/d2f1eac4-50e7-4dec-80b9-ae6b581d1aff)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/132475239/067243d4-1a23-4084-a315-fa4236a438dc)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/132475239/d3a55c18-bfd2-466d-9931-74322f8c1ed8)

Would appreciate if u are transparent and explain wat this is ifnot ill just assume its malware ty.

**Comment by hotline1337** [comment]
it touches internet explorer registry keys because it uses https requests.
second image contains a path to newest downloaded release.
