### ISSUE TITLE
My windows defender is throwing false positives, how can solve it?

### ISSUE THREAD

**Issue by limatila** [R3nzTheCodeGOD/R3nzSkin#893]
The Windows Defender is frequently throwing false positive warnings, how can i at least disable them? I already have permitted the program archives through the defender menu.

**Comment by hotline1337** [comment]
Disable your antivirus temporarily, put the binaries (injector and the dll) in a folder, in your antivirus add the folder to an exception list, enable your antivirus, profit.

**Comment by limatila** [comment]
thanks!
