### ISSUE TITLE
i dont know how to inject it help

### ISSUE THREAD

**Issue by Neroka** [R3nzTheCodeGOD/R3nzSkin#894]
i tried many times and i couldnt

**Comment by limatila** [comment]
What did you tried yet?
You should download the compiled .rar, extract it to a folder and open the ".exe" app. Just press Start and the program will automatically be injected.

**Comment by hotline1337** [comment]
Extract the injector and the dll from the archive, disable your antivirus, run the injector, clik start in the injector, go into the game.
