### ISSUE TITLE
Error altough i have antivirus off ( Win 11 ) 

### ISSUE THREAD

**Issue by d1fwn** [R3nzTheCodeGOD/R3nzSkin#897]
When I press on the injector, it says : the code execution cannot proceed because MSVCP140.dll was not found.Reinstalling the program fix this problem. 
I reinstalled it  10 times, restarted the computer, tried to add to allowed apps  on windows security but nothing worked. What can i do  ?

**Comment by hotline1337** [comment]
Install .NET Framework 4.8 Runtime and C++ Redistributable 2015-2022 x64.
