### ISSUE TITLE
Is there any new code for today's update 13.22?

### ISSUE THREAD

**Issue by qq1403498204** [R3nzTheCodeGOD/R3nzSkin#898]
Is there any new code for today's update 13.22?

**Comment by diyooor** [comment]
Nope, works just fine as usual. Thank @hotline1337 for keeping it up.

**Comment by WitheredRose7** [comment]
Last patch version appears to be working just fine after 13.22 patch. It's probably since offset pattern wasn't changed.

**Comment by diyooor** [comment]
cb55f10a89f26d74f639dc7a237c164adb97484b or [v3.2.2](https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v3.2.2) both still work


Closes #898

**Comment by hotline1337** [comment]
There's no need for an update.
