### ISSUE TITLE
Odyssey Kayn animations not working

### ISSUE THREAD

**Issue by mhmaharas** [R3nzTheCodeGOD/R3nzSkin#899]
Odyssey Kayn animations aren't working proper, the animations of E in the wall isn't working nor showing on both forms and also the hologram above the champions when ulting someoning isn't showing either on all three forms, i'm hoping for a fix because it's one of my favorite skins from kayn

**Comment by desmond315** [comment]
is skin changer working for u except for the kayn skin? Since the update recently, i cant even use it lol

**Comment by diyooor** [comment]
#1 

Closes #899 @hotline1337

**Comment by hotline1337** [comment]
#1
