### ISSUE TITLE
Failed to find pattern (v1.5.3 release)

### ISSUE THREAD

**Issue by vondyhaar** [R3nzTheCodeGOD/R3nzSkin#90]
![Screenshot (100)](https://user-images.githubusercontent.com/81117410/163281785-f65129dd-17d7-4db9-bf9a-3adc15bf16cb.png)

Happens sometimes, and doesn't seem to affect functionality

**Comment by Xarond12** [comment]
same problem

**Comment by vondyhaar** [comment]
I've exchanged https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/8d1a1cd07460ccefeb8b2186a1025de22dc7cc69/R3nzSkin/memory.hpp#L47 with: 
`"A1 ? ? ? ? 68 ? ? ? ? 8B 70 08",` and my problem stopped. However I'm clueless as to what it actually does and as to any problems.
