### ISSUE TITLE
is this a virus or not 

### ISSUE THREAD

**Issue by thedemeaner321** [R3nzTheCodeGOD/R3nzSkin#901]
https://www.reddit.com/r/LoLcustom/comments/13qrg5a/the_virus_of_r3nzskin_is_not_false_positive_its/ 

read this thread and someone explain this shit to me

**Comment by crkwizzyv2** [comment]
> https://www.reddit.com/r/LoLcustom/comments/13qrg5a/the_virus_of_r3nzskin_is_not_false_positive_its/
> 
> read this thread and someone explain this shit to me

it aint a virus, been using it for months, its the injector, any injector will be classified as a false positive, its safe to download

**Comment by potentate** [comment]
your first mistake is going onto a league of legends subreddit and truly thinking youll find a human with a capable functioning brain, injector is fine and it has false positives just like any other "cheat" or skinchanger youd see

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/892#issuecomment-1791689704

**Comment by hotline1337** [comment]
Please check closed issues related to "virus", "malware" in R3nzSkin.
