### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by ShuwaibAkhtar** [R3nzTheCodeGOD/R3nzSkin#904]
People who say it's a false positive are blind. No one has checked the code and people are just believing what they hear.

**Comment by Exorich64** [comment]
you mean its a virus ?

**Comment by victorzambelli** [comment]
not virus bro open source xD

**Comment by artcevvv** [comment]
Checked the whole code, it's pretty clear. The only reason why antivirus/virustotal says abt viruses is because this program works straightforward with memory proccesses on your PC.

**Comment by hotline1337** [comment]
> People who say it's a false positive are blind. No one has checked the code and people are just believing what they hear.

you obviously didn't check it urself.

**Comment by ShuwaibAkhtar** [comment]
Do not download. It is a keylogger
