### ISSUE TITLE
[Feature Request] I will give you 20 bucks if you manage to make a linux compatible build

### ISSUE THREAD

**Issue by boobthecat** [R3nzTheCodeGOD/R3nzSkin#905]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/127695532/023dbd50-5ce4-4227-be9f-44c3bb5656c2)

**Comment by boobthecat** [comment]
Lol. You're probably retarded so I won't go any further. Have a good day

**Comment by Xayayia** [comment]
Average social interaction from a linux user. Nurse recieving your birth wondered if she has to report bestiality to authorities u gruesome abomination.

**Comment by boobthecat** [comment]
Receiving*

**Comment by ywwa** [comment]
league of legends does not have linux client
and you can inject dll just like on windows (cause running through wine)

**Comment by boobthecat** [comment]
I tried injecting it but it just caused league to crash.

**Comment by boobthecat** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/127695532/540b02b4-1da8-4d6b-8543-6042861b3c0d)
Nevermind! For future problems like this, all you need is to install NET 4.8 on the dependencies. I'm running through bottles.

**Comment by boobthecat** [comment]
The only problem is the exe keeps changing it's name so I can't add it as a shortcut

**Comment by ywwa** [comment]
> The only problem is the exe keeps changing it's name so I can't add it as a shortcut

you can inject using any injector 
provided executable is not necessary for skinchanger to work
but if you want to use it still then just write script that automatically checks for the new name and changes path to it in shortcut (shouldn't be that easy if you keep dll and exe under one directory)

**Comment by boobthecat** [comment]
@ywwa Could I also just download a older build of this injector where this feature wasn't introduced? Not too familiar with writing scripts and I couldn't find any trust worthy injectors to use

**Comment by ywwa** [comment]
you can use anything for injection, even processhacker2 (yes it has functionality to inject)
but i`d not recommend to use old builds of r3nz injector

**Comment by boobthecat** [comment]
Thanks. I just stuck with the solution from [477](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/477#issuecomment-1789840314)
