### ISSUE TITLE
"detected"

### ISSUE THREAD

**Issue by jvisp** [R3nzTheCodeGOD/R3nzSkin#91]
my avast antivirus detects malware but i dont want to turn it off and i cant install skin changer now, but past versions of skin changer i could download with no problem, it just puts file into quarantine

**Comment by sonitaaaaa** [comment]
whitelist the file or folder -> [Add an exception](https://support.avast.com/en-us/article/Antivirus-scan-exclusions)

**Comment by jvisp** [comment]
> whitelist the file or folder -> [Add an exception](https://support.avast.com/en-us/article/Antivirus-scan-exclusions)

thank you so much!!
