### ISSUE TITLE
How to change the language of this software? What is a good way? Brothers, ask for answers

### ISSUE THREAD

**Issue by makabaka2869** [R3nzTheCodeGOD/R3nzSkin#910]
How to change the language of this software? What is a good way? Brothers, ask for answers

**Comment by SomUrim** [comment]
Download the source code, translate it into the language you need on your own, and then compile it. Alternatively, find a branch version in the same language you are using.

**Comment by makabaka2869** [comment]
> 下载源代码，自行将其翻译成您需要的语言，然后进行编译。或者，查找您正在使用的相同语言的分支版本。

Hello, I want to know which folder it is, I want to know its name, because my technology is not particularly good, thank you very much

**Comment by hotline1337** [comment]
> Download the source code, translate it into the language you need on your own, and then compile it. Alternatively, find a branch version in the same language you are using.

As stated above.
