### ISSUE TITLE
update alert keeping showing while using the latest version

### ISSUE THREAD

**Issue by Szyoo** [R3nzTheCodeGOD/R3nzSkin#912]
I'm currently using version 3.2.2. However, every time I open the software, I receive this alert suggesting that a new update is available and asking if I wish to update.

I've attempted to resolve this by completely deleteing and then re-downloading and extracting it, but the issue persists. Interestingly, I do not encounter this problem on another computer of mine.

Could you please advise on what might be causing this issue and how I might resolve it? While it does not affect the functionality, it is quite bothersome to receive this prompt repeatedly.

Thank you for your assistance.

**Comment by Demonwls** [comment]
has it been updated?

**Comment by Szyoo** [comment]
Clicking 'Agree' just downloads the same version 3.2.2 zip file(perhaps? I can't find where the version shows) again to the installation path. I've tried both unzipping it to replace the old file and deleting the old file before unzipping, but neither method works. Isn't version 3.2.2 supposed to be the latest version?
