### ISSUE TITLE
open injector failed

### ISSUE THREAD

**Issue by zzqw** [R3nzTheCodeGOD/R3nzSkin#913]
I have downloaded the latest version,but still the same problem，I suspect it's a problem with my computer, but I don't know how to solve it
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/32407444/27342daa-1bf1-493a-ab81-347100056af4)

**Comment by ywwa** [comment]
check if .net libraries are installed on  system

**Comment by zzqw** [comment]
> check if .net libraries are installed on system

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/32407444/7aaccb55-01a1-4b1b-954a-c0c0b094b988)
If what you say is .net framework, the version is 4.8. The weird thing is that it still worked a while ago

**Comment by zzqw** [comment]
is there any log files the injector save on my system?  I can offer to you

**Comment by ywwa** [comment]
> is there any log files the injector save on my system? I can offer to you

im not sure but windows may automatically log in `event viewer`

**Comment by zzqw** [comment]
> > is there any log files the injector save on my system? I can offer to you
> 
> im not sure but windows may automatically log in `event viewer`

I try running a demo using Visual Studio to inject the dll and it works but throws an error like this, I think this might be because of the new version of  LOL?
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/32407444/8e6693e7-7ca1-4dbd-9863-e95c64985c2c)

**Comment by ywwa** [comment]
thats right, you have to update patterns how to do it you can find in this issue #2

**Comment by BakaFT** [comment]
I assume OP is playing on Tencent server.

So just rename the target dll int o`hid.dll` and put it under `Game` Folder. `League of Legends.exe` will load it automaticlly.

This method works on global versions too.

**Comment by hotline1337** [comment]
install .net framework 4.8 and c++ redistributable 2015-2023
