### ISSUE TITLE
Injector error

### ISSUE THREAD

**Issue by PlamG** [R3nzTheCodeGOD/R3nzSkin#918]
It doesnt let me inject it 
![r3nz](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/123259263/8653e512-0d7d-49fa-bc8d-6d3a0403e51b)

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/912#issuecomment-1820331229
