### ISSUE TITLE
Lee Sin God First hit problem

### ISSUE THREAD

**Issue by lovecanyon** [R3nzTheCodeGOD/R3nzSkin#923]
Lee Sin God First has a hit issue, when hit, the hit does damage but the animation doesn't cast.
![League of Legends_11-27-2023_13-7-36-839](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/152199939/c8c13981-3f2e-48ce-ae67-285184ce8df6)

**Comment by diyooor** [comment]
#1 

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/157#issuecomment-1190366059

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/237#issuecomment-1296824169

https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/885#issuecomment-1786264952
