### ISSUE TITLE
Universal default skins

### ISSUE THREAD

**Issue by sisby-folk** [R3nzTheCodeGOD/R3nzSkin#928]
Hey there! I'd love to use this tool to override every single champion in the game to use their default skin, as I struggle with the readability of projectiles and skill wind-up animations on a lot of skins with my vision. 

It seems like this is a bit arduous to set up with the current configuration style - would it be possible to add a special case in the json for this? I'd like to not have to touch the overlay GUI at all (and disable it entirely ideally).

**Comment by hotline1337** [comment]
You can add your own features by yourself! If the feature is useful, i might add it myself, but I don't see this one that important.
