### ISSUE TITLE
Neeko minion tranform gets changed with skin (Potencial Ban?)

### ISSUE THREAD

**Issue by Xyrn265** [R3nzTheCodeGOD/R3nzSkin#929]
Hello Red,

I have discovered that if Neeko tranforms into a minion with your Injector on, she gets a event minion skin and her color becomes the opposite of what should be. Keep in mind i use blue for my side always and red for enemy setting.

If I am the one using neeko, my minion is red. if enemy uses neeko herr hp bar becomes blue and so I can tell who is the fake minion just by looking at the hp bar

**Comment by hotline1337** [comment]
#1
