### ISSUE TITLE
unstoppable

### ISSUE THREAD

**Issue by oemanm8** [R3nzTheCodeGOD/R3nzSkin#932]
We might want to fix this ?
![fix](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/152918903/b0fba034-badb-4638-9ef2-260e2fa2bb3c)

**Comment by oemanm8** [comment]
But for real, is there any way to fix this?. Cause i do wanna try it out, but when you get spammed down with .exe harmful file. It aint fun xD

**Comment by hotline1337** [comment]
disable your anti-virus. the project is open-source.
