### ISSUE TITLE
Riot disabled r3nzskin in 13.24?

### ISSUE THREAD

**Issue by prim0oo** [R3nzTheCodeGOD/R3nzSkin#935]
Hey, 
is it only me or r3nz skin doesnt work anymore after the 13.24 patch? 
Also i had another problem with kassadin skins, his sword skin is always default using a skin

**Comment by thanhlqno1** [comment]
Yeah me too, im waiting for the new fix

**Comment by H4x0rModdz** [comment]
just wait for the new R3nz patch to come out.

**Comment by 1relking** [comment]
> Hey, is it only me or r3nz skin doesnt work anymore after the 13.24 patch? Also i had another problem with kassadin skins, his sword skin is always default using a skin

you need use the w to change sword

**Comment by tanerkennedy** [comment]
hot fix needed , all eyes on @hotline1337 ^^

**Comment by kadnesS** [comment]
file could not be found try reinstalling hatası alıyorum yardımcı olabılıcek varmı

**Comment by tanerkennedy** [comment]
> file could not be found try reinstalling hatası alıyorum yardımcı olabılıcek varmı

bro tamamen sil önce , dosyayı genelde viruslu buluyor tüm antivirus programlarını kapat indir  tehdit bulundu yazdığında izin ver de çalışıyor ama şuan hot fix gerekiyor yeni yama da çalışmıyor.
