### ISSUE TITLE
First-time use of this software

### ISSUE THREAD

**Issue by Akira0196** [R3nzTheCodeGOD/R3nzSkin#936]
Hello, this is my first time using this program.
It has been working normally in the past few days.
However, today, after the game version was updated to 13.24, it no longer functions.
When I open the program, there is no prompt for an update.
Do I need to wait for the release of a new version of the program to continue using it?
Thank you.
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/97196486/a5b25885-4721-479c-8e43-9c52acb19880)
I used ChatGPT to translate.

**Comment by sighterz** [comment]
It doesnt work for anyone it seems, riot disabled it with the new patch, we just have to wait for the fix it seems

**Comment by sighterz** [comment]
Oh I see, thank you. A bit of a bummer cause I was excited to try out some skins today.

**Comment by Papermars** [comment]
> Oh I see, thank you. A bit of a bummer cause I was excited to try out some skins today.

He says he's serving the army in his profile and it's gonna be like 3 days or even a week, :(

**Comment by sighterz** [comment]
> > Oh I see, thank you. A bit of a bummer cause I was excited to try out some skins today.
> 
> He says he's serving the army in his profile and it's gonna be like 3 days or even a week, :(

Oh rip

**Comment by PBCOnGit** [comment]
Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig
	{
		{
			{
				"48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02"
			}, true, false, true, 0, &offsets::global::GameClient
		}
	};`

**Comment by Faizan2001** [comment]
> Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`

can you elaborate a bit more on where we can find Memory.hpp

**Comment by PBCOnGit** [comment]
> > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> 
> can you elaborate a bit more on where we can find Memory.hpp

if you compile the project yourself inside the visual studio project at memory/memory.hpp

**Comment by isak102** [comment]
> > > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> > 
> > 
> > can you elaborate a bit more on where we can find Memory.hpp
> 
> if you compile the project yourself inside the visual studio project at memory/memory.hpp

Can you upload the compiled `R3nzSkin.dll` file? I dont have visual studio and it takes too long to install everything again

**Comment by PBCOnGit** [comment]
> > > > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> > > 
> > > 
> > > can you elaborate a bit more on where we can find Memory.hpp
> > 
> > 
> > if you compile the project yourself inside the visual studio project at memory/memory.hpp
> 
> I've edited the file in VS I just don't know how to launch the script now. I'm legit trying to speedrun learning everything to make it work. Any help?

CRTL + SHIFT + B should build everything

**Comment by solaxio** [comment]
> > > > > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> > > > 
> > > > 
> > > > can you elaborate a bit more on where we can find Memory.hpp
> > > 
> > > 
> > > if you compile the project yourself inside the visual studio project at memory/memory.hpp
> > 
> > 
> > I've edited the file in VS I just don't know how to launch the script now. I'm legit trying to speedrun learning everything to make it work. Any help?
> 
> CRTL + SHIFT + B should build everything

Which file am I supposed to open in Visual Studio? I edited the memory.hpp but how do I turn the whole file soup into an actual executable programme

**Comment by aikoxyz** [comment]
> > > > > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> > > > 
> > > > 
> > > > can you elaborate a bit more on where we can find Memory.hpp
> > > 
> > > 
> > > if you compile the project yourself inside the visual studio project at memory/memory.hpp
> > 
> > 
> > I've edited the file in VS I just don't know how to launch the script now. I'm legit trying to speedrun learning everything to make it work. Any help?
> 
> CRTL + SHIFT + B should build everything

I am not able to build the projects because of errors, is there a way around the errors?

**Comment by PBCOnGit** [comment]
ur supposed to open the .sln file

**Comment by aikoxyz** [comment]
> > > > > > > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> > > > > > 
> > > > > > 
> > > > > > can you elaborate a bit more on where we can find Memory.hpp
> > > > > 
> > > > > 
> > > > > if you compile the project yourself inside the visual studio project at memory/memory.hpp
> > > > 
> > > > 
> > > > I've edited the file in VS I just don't know how to launch the script now. I'm legit trying to speedrun learning everything to make it work. Any help?
> > > 
> > > 
> > > CRTL + SHIFT + B should build everything
> > 
> > 
> > I am not able to build the projects because of errors, is there a way around the errors?
> 
> ur supposed to open the .sln file

Yes i did, after that i went into the Memory.hpp and changed the signature, but i am not able to build because of errors

**Comment by aikoxyz** [comment]
\Visual Studio\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020:

thats the main error that prevents me from building

**Comment by solaxio** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/153121415/fd7fee1d-f494-489b-8ed8-3d279d606a5e)

**Comment by Thiplusg** [comment]
How do I compile it to become executable? I changed the signature in memory, but I don't know how to run the program.

**Comment by aikoxyz** [comment]
> How do I compile it to become executable? I changed the signature in memory, but I don't know how to run the program.

you dont

**Comment by ryuwrld** [comment]
https://file.io/o01NTs5LBQSq updated dll

**Comment by PBCOnGit** [comment]
[R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13590703/R3nzSkin.zip)

**Comment by Maestrotlgg** [comment]
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13590703/R3nzSkin.zip)

WORK! Thanks a lot

**Comment by tanerkennedy** [comment]
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13590703/R3nzSkin.zip)

woow it works ! thanks even w new skins!! enjoy people.

**Comment by solaxio** [comment]
> [R3nzSkin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13590703/R3nzSkin.zip)

i love you

**Comment by Alperah** [comment]
There is only one dll in this, how do I run it?

**Comment by Alperah** [comment]
What is pr? my English is not good

**Comment by solaxio** [comment]
> There is only one dll in this, how do I run it?

just replace the existing dll in the folder with the exe and run it

**Comment by tangmuduo** [comment]
不用客气我的朋友，我还在更新游戏，羡慕你现在能玩






                       
原始邮件
                       
                     

发件人："Alperah"< ***@***.*** &gt;;

发件时间：2023/12/7 4:00

收件人："R3nzTheCodeGOD/R3nzSkin"< ***@***.*** &gt;;

抄送人："tangmuduo"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [R3nzTheCodeGOD/R3nzSkin] First-time use of this software (Issue#936)




 
Ok I think I did it, thank you :)

**Comment by Alperah** [comment]
By the way, I'm not Chinese, I'm Turkish :) Haha Thank you again for your help my friend.

**Comment by tangmuduo** [comment]
这款软件造福了很多人，我们都是收益者，然而我们的中国服务器却对这些软件施行打压，我们玩家也确实很感谢他的开发主人，真的感谢


                       
原始邮件
                       
                     

发件人："Alperah"< ***@***.*** &gt;;

发件时间：2023/12/7 4:06

收件人："R3nzTheCodeGOD/R3nzSkin"< ***@***.*** &gt;;

抄送人："tangmuduo"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [R3nzTheCodeGOD/R3nzSkin] First-time use of this software (Issue#936)




 
By the way, I'm not Chinese, I'm Turkish :) Haha Thank you again for your help my friend.

**Comment by diyooor** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/938

**Comment by tangmuduo** [comment]
> > 这里面只有一个dll，我怎么运行？
> 
> 只需用exe替换文件夹中现有的dll并运行它

Thank you my friend, we are all beneficiaries.

**Comment by tangmuduo** [comment]
自己做？开发主人已经发布了最新的13.24连接，你下载打开然后进入游戏就可以了



                       
原始邮件
                       
                     

发件人："Kerballl"< ***@***.*** &gt;;

发件时间：2023/12/7 13:38

收件人："R3nzTheCodeGOD/R3nzSkin"< ***@***.*** &gt;;

抄送人："tangmuduo"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [R3nzTheCodeGOD/R3nzSkin] First-time use of this software (Issue#936)




  
R3nzSkin.zip
  
how did you know where to replace and how did you change i dont know anything and i want to do by myself

**Comment by jasperan** [comment]
> Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`

How do you find these offsets? They change every patch, so I'm wondering.

I tried to do hex to string conversion but these numbers don't look to represent any text either

**Comment by Kerballl** [comment]
> > Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`
> 
> How do you find these offsets? They change every patch, so I'm wondering.
> 
> I tried to do hex to string conversion but these numbers don't look to represent any text either

i wonder the samething i search a bit but couldnt find anything about it

**Comment by aikoxyz** [comment]
> Change the GameClient signature in Memory.hpp to `std::vector<offset_signature> gameClientSig { { { "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" }, true, false, true, 0, &offsets::global::GameClient } };`

yo quick question, how did you find the new pattern, did you dumb the game?
