### ISSUE TITLE
R3nzSkin & TFT UPDATED V13.24 + WITH SOURCE CODE

### ISSUE THREAD

**Issue by Sheelia** [R3nzTheCodeGOD/R3nzSkin#938]
You can find it in my repo.

https://github.com/Sheelia/R3nzSkin-v13.24/tree/v2.4.2

https://github.com/Sheelia/R3nzSkinTFT/releases

**Comment by diyooor** [comment]
> please release a zipped option for those who don't know how to do it

![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/38271173/be7490f7-51c6-4c1e-a17e-9a5d8a613b64)

https://github.com/Sheelia/R3nzSkin-v13.24/releases

**Comment by sighterz** [comment]
Guys this might be malware be careful, my steam account just got hacked and I downloaded this a few hours ago. Dont trust the creator. Also give me back my damn account!!!

**Comment by sighterz** [comment]
Wait for the official update please.

**Comment by Shatteringv9** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/104527204/09028db0-819d-4326-aef5-783d9e2a609d)
Thoughts?

**Comment by 2198h341jn** [comment]
> > Guys this might be malware be careful, my steam account just got hacked and I downloaded this a few hours ago. Dont trust the creator. Also give me back my damn account!!!
> 
> you have an open source code xd

why always the "its open source" retarded answer, if it's affecting people, it means it have a malware.
