### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by Maskiao1** [R3nzTheCodeGOD/R3nzSkin#939]
I have only installed League of Legends and Steam on my system, and yet, after downloading this particular program, unauthorised individuals gained access to my accounts on Steam and Google. Despite using complex passwords and experiencing no database breaches, it is evident that this program is, without a doubt, a keylogging software.

**Comment by falcononrails** [comment]
The code is available, you can compile it yourself. Do you see any keylogging code?

**Comment by victorzambelli** [comment]
xD

**Comment by sighterz** [comment]
> I have only installed League of Legends and Steam on my system, and yet, after downloading this particular program, unauthorised individuals gained access to my accounts on Steam and Google. Despite using complex passwords and experiencing no database breaches, it is evident that this program is, without a doubt, a keylogging software.

Same exact thing happened to me. This is malware.

**Comment by waveiro** [comment]
Honest question: Could you please highlight the place where the keys are collected? I've checked the code and haven't found this part, so could you please point it to me?

**Comment by Boenka** [comment]
I had the same problem dont use this program it works but its a key logger

**Comment by H4x0rModdz** [comment]
I’ve checked the code multiple times for maintenance when I wanted to update the patches for myself, and there’s really nothing in them, zero malwares.

**Comment by hotline1337** [comment]
> "I've experienced no database breaches" "I use complex passwords"
> 
> > I open issues on open source software claiming open source code is malware
> 
> Are you retarded

best quote for this issue here.

**Comment by sighterz** [comment]
> best quote for this issue here.

Right, I guess the keylogging software that spammed my discord and steam friends was because on microsoft word... be so fr now instead of using slurs, y'all dont trust this version.

**Comment by zkxjzmswkwl** [comment]
> > best quote for this issue here.
> 
> Right, I guess the keylogging software that spammed my discord and steam friends was on microsoft word... be so fr now instead of using slurs, y'all dont trust this version.

"Don't trust this version"

We have read the code.

We compile it ourselves.

You don't know what you're talking about. You're retarded.
