### ISSUE TITLE
where is the new update?

### ISSUE THREAD

**Issue by Fusorvanahil** [R3nzTheCodeGOD/R3nzSkin#941]
hello skin changer is not working rn

**Comment by eqfaaeqr** [comment]
Wair for the official update, so that u won't comeback crying about your passwords/accounts.

**Comment by Reraz** [comment]
Just wait

**Comment by Alperyeager** [comment]
> > Wair for the official update, so that u won't comeback crying about your passwords/accounts.
> 
> [Sheelia@960e671](https://github.com/Sheelia/R3nzSkin-v13.24/commit/960e6719f49fe738416fb79b8e1f0bf7c9616194)
> 
> If you download the official repo, and are capable of building it yourself you can just update the offset yourself and use it.

hey,
can you tell me what you mean with update the offset yourself! I dont really know much about it and would like to do it myself

**Comment by LennyAmin** [comment]
> > > Wair for the official update, so that u won't comeback crying about your passwords/accounts.
> > 
> > 
> > [Sheelia@960e671](https://github.com/Sheelia/R3nzSkin-v13.24/commit/960e6719f49fe738416fb79b8e1f0bf7c9616194)
> > If you download the official repo, and are capable of building it yourself you can just update the offset yourself and use it.
> 
> hey, can you tell me what you mean with update the offset yourself! I dont really know much about it and would like to do it myself

there is an tutorial

**Comment by Alperyeager** [comment]
> > > > Wair for the official update, so that u won't comeback crying about your passwords/accounts.
> > > 
> > > 
> > > [Sheelia@960e671](https://github.com/Sheelia/R3nzSkin-v13.24/commit/960e6719f49fe738416fb79b8e1f0bf7c9616194)
> > > If you download the official repo, and are capable of building it yourself you can just update the offset yourself and use it.
> > 
> > 
> > hey, can you tell me what you mean with update the offset yourself! I dont really know much about it and would like to do it myself
> 
> there is an tutorial

can u send me it?
