### ISSUE TITLE
Sharing update ?

### ISSUE THREAD

**Issue by Chiitose** [R3nzTheCodeGOD/R3nzSkin#942]
Hello, i have managed to uptade the tool using Visual studio 2022 (it's my first time doing something like this)
It gave me a R3nzSkin.dll and all i had to do was drop it in the same folder as the R3nzSkin_injector.exe that already exist and it works.
All i did was change the line 56 in memory.hpp from "48 8B 05 ? ? ? ? 8B 58 0C" to "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02"
I created this account today and i never uploaded a file on Github. I don't know how i could share it with someone from the project maybe ? So they could verify it's legit and maybe use it to update faster.

**Comment by SulCool** [comment]
It actually works lol, patched dll in folder
Ty for solution :З
also works with new skins*
[rz3nsskin.zip](https://github.com/R3nzTheCodeGOD/R3nzSkin/files/13602122/rz3nsskin.zip)

**Comment by SulCool** [comment]
How did you figure it out
?

**Comment by LennyAmin** [comment]
> I didn't. I saw that @Sheelia released an "updated" version of the tool, all credits goes to that person for the update at least. , but peoples were saying it was working but that it could be a keylogger. So i didn't want to download any new file. I checked what was changed in the files that were already in R3nzskin folders and saw that change in this line. Tried it myself and it worked.


> Hello, i have managed to uptade the tool using Visual studio 2022 (it's my first time doing something like this) It gave me a R3nzSkin.dll and all i had to do was drop it in the same folder as the R3nzSkin_injector.exe that already exist and it works. All i did was change the line 56 in memory.hpp from "48 8B 05 ? ? ? ? 8B 58 0C" to "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" I created this account today and i never uploaded a file on Github. I don't know how i could share it with someone from the project maybe ? So they could verify it's legit and maybe use it to update faster.

cant find it :(

**Comment by Chiitose** [comment]
> > I didn't. I saw that @Sheelia released an "updated" version of the tool, all credits goes to that person for the update at least. , but peoples were saying it was working but that it could be a keylogger. So i didn't want to download any new file. I checked what was changed in the files that were already in R3nzskin folders and saw that change in this line. Tried it myself and it worked.
> 
> > Hello, i have managed to uptade the tool using Visual studio 2022 (it's my first time doing something like this) It gave me a R3nzSkin.dll and all i had to do was drop it in the same folder as the R3nzSkin_injector.exe that already exist and it works. All i did was change the line 56 in memory.hpp from "48 8B 05 ? ? ? ? 8B 58 0C" to "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02" I created this account today and i never uploaded a file on Github. I don't know how i could share it with someone from the project maybe ? So they could verify it's legit and maybe use it to update faster.
> 
> cant find it :(

What can't you find ?

**Comment by LennyAmin** [comment]
nvm

**Comment by SulCool** [comment]
> I didn't. I saw that @Sheelia released an "updated" version of the tool, all credits goes to that person for the update at least. , but peoples were saying it was working but that it could be a keylogger. So i didn't want to download any new file. I checked what was changed in the files that were already in R3nzskin folders and saw that change in this line. Tried it myself and it worked.
Wow, that sounds true, it makes sense, but thank you anyway

**Comment by SulCool** [comment]
> I didn't. I saw that @Sheelia released an "updated" version of the tool, all credits goes to that person for the update at least. , but peoples were saying it was working but that it could be a keylogger. So i didn't want to download any new file. I checked what was changed in the files that were already in R3nzskin folders and saw that change in this line. Tried it myself and it worked.

Wow, that sounds true, it makes sense, but thank you anyway
