### ISSUE TITLE
Unofficial Patch 13.24 DOWNLOAD HERE

### ISSUE THREAD

**Issue by H4x0rModdz** [R3nzTheCodeGOD/R3nzSkin#943]
I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.

**Comment by Democles85** [comment]
It has been blocked by Mediafire.

**Comment by KinXandor** [comment]
> I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.

link got blocked, can u maybe post it on git? ur u can try to go for something like dropbox or google drive

**Comment by H4x0rModdz** [comment]
> > I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.
> 
> link got blocked, can u maybe post it on git? ur u can try to go for something like dropbox or google drive

[Github](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24) <= My Github Release

**Comment by H4x0rModdz** [comment]
> It has been blocked by Mediafire.

[Here](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24)

> брат Mediafire блокирует этот файл что делать?

[Here](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24)

**Comment by H4x0rModdz** [comment]
Srry guys, ended up being away from my pc

**Comment by kiril203** [comment]
спасибо тебе огромное!

**Comment by Gamer-spec** [comment]
You are awesome, Thanks for updating it.

**Comment by H4x0rModdz** [comment]
> You are awesome, Thanks for updating it.

no prob bro <3

**Comment by KinXandor** [comment]
> > > I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.
> > 
> > 
> > link got blocked, can u maybe post it on git? ur u can try to go for something like dropbox or google drive
> 
> [Github](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24) <= My Github Release

I already got it from somewhere else, but thanks buddy, have a nice day :-)

**Comment by GoldGatherer** [comment]
Друг, а что делать если ничего не происходит, а статус Injected ?

**Comment by H4x0rModdz** [comment]
> > > > I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.
> > > 
> > > 
> > > link got blocked, can u maybe post it on git? ur u can try to go for something like dropbox or google drive
> > 
> > 
> > [Github](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24) <= My Github Release
> 
> I already got it from somewhere else, but thanks buddy, have a nice day :-)



> > > > I know I’m not R3nz, but I’ve been tweaking the project since yesterday to get it working again, and I succeeded. I’ll try a commit to see if they approve, but for now, the link is [Mediafire](https://www.mediafire.com/file/yn29su117mub89e/13242023.rar/file) Here’s the Release with the dll and injector.
> > > 
> > > 
> > > link got blocked, can u maybe post it on git? ur u can try to go for something like dropbox or google drive
> > 
> > 
> > [Github](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24) <= My Github Release
> 
> I already got it from somewhere else, but thanks buddy, have a nice day :-)

woww, nice bro

**Comment by H4x0rModdz** [comment]
> valeu pitbull

tmj meu mano

> Друг, а что делать если ничего не происходит, а статус Injected ?

Попробуйте перезапустить игру, если она не работает, это потому, что у вас версия, которая не обновлена ​​с правильными блоками памяти.
