### ISSUE TITLE
injector error 

### ISSUE THREAD

**Issue by mavramanko0707** [R3nzTheCodeGOD/R3nzSkin#945]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/152088180/61e5e756-d204-446b-9308-a23e4a365af1)
I have the newest version, and cloudflare didn't help. I still got the same error

**Comment by H4x0rModdz** [comment]
Use my version  [13.24](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24). The WebClient Request probably configured wrong.

**Comment by mavramanko0707** [comment]
still got same error

**Comment by mavramanko0707** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/152088180/869a9c24-23b2-4182-a414-c33bd448a76d)

**Comment by H4x0rModdz** [comment]
> ![image](https://private-user-images.githubusercontent.com/152088180/288878442-869a9c24-23b2-4182-a414-c33bd448a76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODExODcsIm5iZiI6MTcwMTk4MDg4NywicGF0aCI6Ii8xNTIwODgxODAvMjg4ODc4NDQyLTg2OWE5YzI0LTIzYjItNDE4Mi1hNDE0LWMzM2JkNDQ4YTc2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMDI4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWZiNGYzMWZmMmI4OWVjODZhYTVkZmM4Y2RhY2JkM2FiNTkxNDExZGVkMzMzMjFlNjM0NTIwMmE3MWExOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6QCtylWpRK8BektJNGezqzxw2h0BvEWIfPjElazVGbY)

u have all .NET requirements on your pc? because this error is about the WebClient request not being able to run the DownloadString

**Comment by H4x0rModdz** [comment]
> > ![image](https://private-user-images.githubusercontent.com/152088180/288878442-869a9c24-23b2-4182-a414-c33bd448a76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODExODcsIm5iZiI6MTcwMTk4MDg4NywicGF0aCI6Ii8xNTIwODgxODAvMjg4ODc4NDQyLTg2OWE5YzI0LTIzYjItNDE4Mi1hNDE0LWMzM2JkNDQ4YTc2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMDI4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWZiNGYzMWZmMmI4OWVjODZhYTVkZmM4Y2RhY2JkM2FiNTkxNDExZGVkMzMzMjFlNjM0NTIwMmE3MWExOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6QCtylWpRK8BektJNGezqzxw2h0BvEWIfPjElazVGbY)
> 
> u have all C++* requirements on your pc? because this error is about the WebClient request not being able to run the DownloadString

[C++](https://learn.microsoft.com/ru-RU/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by mavramanko0707** [comment]
so what i have to do? idc anything about that xdd

**Comment by H4x0rModdz** [comment]
> so what i have to do? idc anything about that xdd

download vc_redist according to your windows. [x86 32bits](https://aka.ms/vs/17/release/vc_redist.x86.exe) or [x64 64bits](https://aka.ms/vs/17/release/vc_redist.x64.exe). i'm not sure if it will work, but it could be a solution.

**Comment by mavramanko0707** [comment]
nope, even that didn`t help, still got same error
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/152088180/b2a6318a-d35a-4b27-a9a0-e7d048c509b5)

**Comment by H4x0rModdz** [comment]
> nope, even that didn`t help, still got same error ![image](https://private-user-images.githubusercontent.com/152088180/288905368-b2a6318a-d35a-4b27-a9a0-e7d048c509b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODczNjQsIm5iZiI6MTcwMTk4NzA2NCwicGF0aCI6Ii8xNTIwODgxODAvMjg4OTA1MzY4LWIyYTYzMThhLWQzNWEtNGIyNy1hOWEwLWU3ZDA0OGM1MDliNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMjExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzNmYmM5NjA3NTc5M2ZjODEwMjM4MGNjZGNlM2YxOWNhMGFiYTgyZmU4OWQ3NTBiYjJkOGMzMmJlY2ZhNzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3D_w1OkdAvK1rCxe4ErhlwTS4XsimTgAbvXynxVDbXU)

are u running as admin? do u also have the .NET Framework SDK installed too? any idea if the firewall might be causing issues? It's working for me even in a vm... is weird bro

**Comment by H4x0rModdz** [comment]
> > nope, even that didn`t help, still got same error ![image](https://private-user-images.githubusercontent.com/152088180/288905368-b2a6318a-d35a-4b27-a9a0-e7d048c509b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODczNjQsIm5iZiI6MTcwMTk4NzA2NCwicGF0aCI6Ii8xNTIwODgxODAvMjg4OTA1MzY4LWIyYTYzMThhLWQzNWEtNGIyNy1hOWEwLWU3ZDA0OGM1MDliNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMjExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzNmYmM5NjA3NTc5M2ZjODEwMjM4MGNjZGNlM2YxOWNhMGFiYTgyZmU4OWQ3NTBiYjJkOGMzMmJlY2ZhNzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3D_w1OkdAvK1rCxe4ErhlwTS4XsimTgAbvXynxVDbXU)
> 
> are u running as admin? do u also have the .NET Framework SDK installed too? any idea if the firewall might be causing issues? It's working for me even in a vm... is weird bro

u can download my source and compile it yourself to see if this error continues [here](https://github.com/H4x0rModdz/R3nzSkin)

**Comment by 1relking** [comment]
> > > nope, even that didn`t help, still got same error ![image](https://private-user-images.githubusercontent.com/152088180/288905368-b2a6318a-d35a-4b27-a9a0-e7d048c509b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODczNjQsIm5iZiI6MTcwMTk4NzA2NCwicGF0aCI6Ii8xNTIwODgxODAvMjg4OTA1MzY4LWIyYTYzMThhLWQzNWEtNGIyNy1hOWEwLWU3ZDA0OGM1MDliNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMjExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzNmYmM5NjA3NTc5M2ZjODEwMjM4MGNjZGNlM2YxOWNhMGFiYTgyZmU4OWQ3NTBiYjJkOGMzMmJlY2ZhNzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3D_w1OkdAvK1rCxe4ErhlwTS4XsimTgAbvXynxVDbXU)
> > 
> > 
> > are u running as admin? do u also have the .NET Framework SDK installed too? any idea if the firewall might be causing issues? It's working for me even in a vm... is weird bro
> 
> u can download my source and compile it yourself to see if this error continues [here](https://github.com/H4x0rModdz/R3nzSkin)

how i download?

**Comment by mavramanko0707** [comment]
> > nope, even that didn`t help, still got same error ![image](https://private-user-images.githubusercontent.com/152088180/288905368-b2a6318a-d35a-4b27-a9a0-e7d048c509b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODczNjQsIm5iZiI6MTcwMTk4NzA2NCwicGF0aCI6Ii8xNTIwODgxODAvMjg4OTA1MzY4LWIyYTYzMThhLWQzNWEtNGIyNy1hOWEwLWU3ZDA0OGM1MDliNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMjExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzNmYmM5NjA3NTc5M2ZjODEwMjM4MGNjZGNlM2YxOWNhMGFiYTgyZmU4OWQ3NTBiYjJkOGMzMmJlY2ZhNzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3D_w1OkdAvK1rCxe4ErhlwTS4XsimTgAbvXynxVDbXU)
> 
> are u running as admin? do u also have the .NET Framework SDK installed too? any idea if the firewall might be causing issues? It's working for me even in a vm... is weird bro

I don't know what to do, bro. I did everything you said. downloaded everything you said. i used to use different skin changer, and the injector worked well, but Autor stopped making new versions of it. I tryed to use R3 before, but I had the same issue.
