### ISSUE TITLE
Compiling tutoral

### ISSUE THREAD

**Issue by rehicaa** [R3nzTheCodeGOD/R3nzSkin#946]
How do I go about compiling this, cause the zipped version is not working but i see its updated 4 hours ago, so I am guessing that if I compile it myself It might work? i need visual studio, what do I do to compile it?

**Comment by H4x0rModdz** [comment]
i made an update that R3nz hasn't accepted yet (4 hours ago). u can download it [Here](https://github.com/H4x0rModdz/R3nzUpdated/releases/tag/v13.24)
