### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by yunyty** [R3nzTheCodeGOD/R3nzSkin#95]
Please consider changing the interface
Only show the main skins
Show the chroma skins if the main skin available chroma skins

![2022-04-18-112519_mspaint_WEypgb94cH](https://user-images.githubusercontent.com/16714994/163754222-89ba3128-d9e8-4bc8-b47f-fdd8690bbc46.jpg)

**Comment by sonitaaaaa** [comment]
Alternative you can manually remove or add in

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/34f180109a3c5a17a66fa7ddf217db0f5a8dca2e/R3nzSkin/SkinDatabase.cpp#L33

and

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/34f180109a3c5a17a66fa7ddf217db0f5a8dca2e/R3nzSkin/SkinDatabase.cpp#L38

### You can find my instructions on how to fix the Vietnamese language display "?" **[here](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/88#issuecomment-1107855571)**
