### ISSUE TITLE
What does it need to work on legenday , ultimate skins ?

### ISSUE THREAD

**Issue by Reraz** [R3nzTheCodeGOD/R3nzSkin#951]
I wonder what does the program need to work on those skins, does it need time ? knowledge ?
If its solved, the new patches would be just to add more skins and not to do everything again ?
I may willing to help if its time what it needs.

**Comment by PwccaCode** [comment]
What do you know about coding?

**Comment by Reraz** [comment]
What has to be done? 
Ill help based on that.
