### ISSUE TITLE
When opening injector, nothing happens

### ISSUE THREAD

**Issue by qesuram** [R3nzTheCodeGOD/R3nzSkin#956]
I factory reseted my PC few days ago, before it was working perfectly, no issues. Now, after reset I did everything like always, disabling antivirus, added folder to exclusions, run as administrator and it just doesn't open. 
When I tried downloading and using it on different windows account (on the same PC) it works perfectly fine, but on mine for some reason not?

I've been searching closed issues and similar one was #902 
I disabled antivirus, firewall and everything, many times.
I downloaded .NET Framework 4.8+ and C++ Redistributable 2015-2022 (x64 and x86), as @hotline1337  said in different issue.
Tried  Sheelia's fork and issue was the same.

**Comment by hotline1337** [comment]
Try downloading this particular [.NET Framework 4.8.1 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer) as well as [ASP.NET Core Runtime 8.0.0](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer). You can also try to download older C++ Redistributables for x64 architecture, but I doubt it will help. .NET Framework Targeting Pack or SDK might also help, but I'm unsure.
