### ISSUE TITLE
4 viruses

### ISSUE THREAD

**Issue by ensanez** [R3nzTheCodeGOD/R3nzSkin#957]
![image_2023-12-11_164948547](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/153331316/fe6ea1d1-f857-410d-9c61-fa0281547a9f)

before it was just 1 trojan sure that was fine no big deal but now there is 2 trojans and 2 hacktools???

**Comment by jrk1qu** [comment]
false positives, since the dll in the file uses functions that can be triggered as a virus or malware in general.
software is safe, been using it since forever and can confirm nothing happened to my pc so yours is also good.

**Comment by hotline1337** [comment]
False positives, and 3 of these are not related to R3nzSkin but to Extreme Injector.
