### ISSUE TITLE
无法连接到远程服务器- System.Net.WebClient.DownloadDatalnternal(Uriaddress, WebRequest8 request)在 System.Net.WebClient.Downloadstring(Uri address)  InjectorautoUpdate0

### ISSUE THREAD

**Issue by dsnaaa** [R3nzTheCodeGOD/R3nzSkin#958]
无法连接到远程服务器- System.Net.WebClient.DownloadDatalnternal(Uriaddress, WebRequest8 request)在 System.Net.WebClient.Downloadstring(Uri address)
 InjectorautoUpdate0

**Comment by hotline1337** [comment]
Fix https://github.com/R3nzTheCodeGOD/R3nzSkin/commit/1d5d371aa943ab9c77e94267cf71a997371d297c
