### ISSUE TITLE
Why is the window so big after I inject it?

### ISSUE THREAD

**Issue by SynTaozi** [R3nzTheCodeGOD/R3nzSkin#960]
![微信图片_20231213172950](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/87955875/6465f7d6-8dd5-4f0c-99ed-ec748a60e2e5)

**Comment by hotline1337** [comment]
ur font DPI must have broken. Change it in your settings in `C:\Users\{your_user}\Documents\R3nzskin` and open the file `R3nzSkin64`. Then find the `"fontScale":x.y`, and replace the `x` with `1` and `y` with `0`. This should fix the problem.

**Comment by SynTaozi** [comment]
> ur font DPI must have broken. Change it in your settings in `C:\Users\{your_user}\Documents\R3nzskin` and open the file `R3nzSkin64`. Then find the `"fontScale":x.y`, and replace the `x` with `1` and `y` with `0`. This should fix the problem.

Thank you for taking care of it
