### ISSUE TITLE
How do you make it smaller so it doesn't get that big

### ISSUE THREAD

**Issue by K1TOrsrs** [R3nzTheCodeGOD/R3nzSkin#962]
how???
![r3nzzz](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/139722529/fe2dcf16-f374-4588-9d85-3a71d439b366)

**Comment by K1TOrsrs** [comment]
Above the image there is a crack in the game What do I do now?

**Comment by hotline1337** [comment]
Edit the config, fontScale variable, set it to 1.0
