### ISSUE TITLE
My computer keeps saying this file contains a virus how do you fix this?

### ISSUE THREAD

**Issue by Krod7435** [R3nzTheCodeGOD/R3nzSkin#963]
I need help if someone can help me out.

**Comment by Enjoyerconsumer4801** [comment]
Its not a total problem that you can fix this injector lolskin code contains 3rd party program stuff thats why that error always pops up i dont think there is anything you can do to fix.

**Comment by iaiaian1** [comment]
Windows Defender > Folder exclusion.
