### ISSUE TITLE
R3NZSKINS trojan v2

### ISSUE THREAD

**Issue by jacaaha11** [R3nzTheCodeGOD/R3nzSkin#964]
I have a problem with r3nzskins, a Trojan is displayed, but I'm wondering why, even after accepting this Trojan, the computer deletes this program every few hours because a new Trojan is still displayed?
How can i deal with IT and repair that fact ? Its annoying af

#665 
#950 #665

**Comment by iaiaian1** [comment]
Folder exclusion.
