### ISSUE TITLE
Windows defender keeps deleting the skin changer no matter what i do 

### ISSUE THREAD

**Issue by castelyo** [R3nzTheCodeGOD/R3nzSkin#966]
its been two years since i started using this skin changer, never had a problem till recently when i did a factory reset. 

since then, windows defender kept deleting both files (the .exe n the dll) 

i tried **EVERYTHING**, from regediting the fuck out of it, turning off real time protection, disabling it in group policy, downloading another av, adding the skin changer as an exclusion, BUT **NOTHING WORKS**. It always ends up being deleted after some hours and doesnt even show up in the defender history. ion know what to do anymore, pls help

**Comment by iaiaian1** [comment]
Any issue regarding anti-virus can be resolved by adding it into some kind of exclusion list.

Windows Defender > Exclusions. You can even exclude a whole drive if you want.

**Comment by castelyo** [comment]
> Any issue regarding anti-virus can be resolved by adding it into some kind of exclusion list.
> 
> Windows Defender > Exclusions. You can even exclude a whole drive if you want.

already did that. multiple times and in different ways. didnt work.

**Comment by hotline1337** [comment]
> > Any issue regarding anti-virus can be resolved by adding it into some kind of exclusion list.
> > Windows Defender > Exclusions. You can even exclude a whole drive if you want.
> 
> already did that. multiple times and in different ways. didnt work.

Exclude the whole folder since r3nzskin injector changes names to avoid detection.

**Comment by castelyo** [comment]
> > > Any issue regarding anti-virus can be resolved by adding it into some kind of exclusion list.
> > > Windows Defender > Exclusions. You can even exclude a whole drive if you want.
> > 
> > 
> > already did that. multiple times and in different ways. didnt work.
> 
> Exclude the whole folder since r3nzskin injector changes names to avoid detection.

![imagem_2023-12-20_161158895](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/106618721/23b64b7d-65fe-4cf6-aa36-c2eae3f444f8)

It doesnt work.
