### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by SageKatalyst** [R3nzTheCodeGOD/R3nzSkin#967]
<img width="731" alt="Screenshot 2023-12-17 111839" src="https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/142864511/e817149c-ec3d-4d09-a59f-1d2aa091aa99">

How to solve this problem please? Thank you.

**Comment by hotline1337** [comment]
Disable your anti-virus, or try moving the injector and the R3nzSkin.dll to a different folder.
