### ISSUE TITLE
I STRONGLY advise anyone from downloading as it has over 30+ different froms of malware. From Keyloggers to cryptominers.... Nice try buddy

### ISSUE THREAD

**Issue by OfficialDio** [R3nzTheCodeGOD/R3nzSkin#968]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/102207880/3113b152-c5a3-4bf9-8318-c9fd3ebb7fa2)

**Comment by Kivooeo** [comment]
Any software that is injected into other processes is shown as malware on such sites, this does not mean anything.

**Comment by Leshu7w7** [comment]
you didn't check the source code, did you?

**Comment by Viqnish** [comment]
Blud said "NICE TRY BUDDY"

**Comment by sepehrkiller** [comment]
read what Malwarebytes says, "RiskWare.DLLInjector"
where did you get the "Keyloggers to cryptominers" from?
im not saying this is safe because i've never checked the source code but this program is supposedly open source meaning you can read the whole source code and compile it yourself
