### ISSUE TITLE
DownloadDataInternal Exception

### ISSUE THREAD

**Issue by Persenuaa** [R3nzTheCodeGOD/R3nzSkin#969]
I've tried following the tutorials as well in the closed issues tab, but nothing works. I'm using the compiled version
![Screenshot_1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154069331/12101671-318c-4f1a-bbc4-f99fa086d57a)

**Comment by hotline1337** [comment]
What country are you from?

**Comment by Persenuaa** [comment]
Hi! I live in Brazil.

**Comment by hotline1337** [comment]
> Hi! I live in Brazil.

Will push an update.

**Comment by Persenuaa** [comment]
Thank you so much partner :D
