### ISSUE TITLE
How stop windows defender from quarantining/deleting the app please help

### ISSUE THREAD

**Issue by Gazalives00** [R3nzTheCodeGOD/R3nzSkin#970]
As titles says how do i stop my windows antivirus from quarantining my app? I've tried adding all the files as exclusions in windows defender settings but it keeps reverting it after i restart my computer. Really annoying is there a permanent solution other than disabling my antivirus permanently from windows registry?

**Comment by jayel223** [comment]
turn of your windows realtime defender, Virus & threat protection > Virus & threat protection > manage settings > real-time protection ( turn it off) delete the skin injector and turn on the realtime projeciton

**Comment by Gazalives00** [comment]
Well the skin injector gets removed automatically after i run it the first time and gets replaced by the same smiley icon but a different name (usually random letters). when i turned real-time protection back on it still detected it as a virus and quarantined it


![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/567ccb42-d2ef-4b78-964e-a3c2e515f33a)

**Comment by Lesleeeee** [comment]
Whitelist it from your windows defender

**Comment by hotline1337** [comment]
as above.

**Comment by Gazalives00** [comment]
> Whitelist it from your windows defender

still not working 😔

**Comment by Gazalives00** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/09f80a6d-49f1-4a77-9fbe-df9d2dff4ad5)

**Comment by Gazalives00** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/020b675e-4271-437a-a2ae-287740d33ded)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/abccf847-638b-436c-96d1-b2d30af7c66e)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/d010e13f-459a-4852-9e2f-da4efce28eb0)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/b5598fb2-9152-49ff-becb-b697745c315b)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/48e72f4e-4a2a-4def-9dc6-49afe7828418)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/e0cc8a21-2555-47e1-8765-44b6e3e18f35)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/d4460e0a-3c9e-4ccc-b98a-0e9f3fa98e44)
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/154278576/c37979b7-0ea9-4625-98cf-00e0905db055)

**Comment by nxllone** [comment]
> > Whitelist it from your windows defender
> 
> still not working 😔

Try compiling it to exe again
