### ISSUE TITLE
Subject: Inquiry Regarding Mouse Control Functionality in Executable and Antivirus Interaction

### ISSUE THREAD

**Issue by meticulously-impeteous** [R3nzTheCodeGOD/R3nzSkin#971]
I am inquiring about the presence of mouse control functionality in the executable. I would like to understand the purpose and functionality of this feature, as my antivirus software flags and deletes the executable when it engages in such activities. Could you please provide clarification on the intended use and necessity of the mouse control feature, and address the concerns related to antivirus detection and deletion? Thank you.

**Comment by hotline1337** [comment]
? There's no mouse control?
