### ISSUE TITLE
big Question

### ISSUE THREAD

**Issue by Andrewzhere** [R3nzTheCodeGOD/R3nzSkin#973]
I dont know shit about the code, but I have a big question, is  the app actually safe? Can one of the admins answer to this please? I ve seen a lot  of guys  saying that its not safe, and a lot of  guys saying it  is  fine and everything  works okay. Are those guys who  say  that they got hacked, actually installed  a  youtube version or something?

**Comment by Andrewzhere** [comment]
i also got a trojan from dll thing, and my windows defender is uninstalling it on  its own .

**Comment by hotline1337** [comment]
It is safe. Please read the closed issues about "virus, malware, trojan". I explained it there in detail.
