### ISSUE TITLE
Insert Keybind

### ISSUE THREAD

**Issue by sweatysoles** [R3nzTheCodeGOD/R3nzSkin#975]
Can I somehow change the insert keybind to any other key? Im getting a 60% keyboard with no insert key

**Comment by crtl-ryan** [comment]
It's possible to do that; I think that option is over there in the right tabs of the application.

**Comment by hotline1337** [comment]
> Can I somehow change the insert keybind to any other key? Im getting a 60% keyboard with no insert key

You will have Insert Key, i own a 60% keyboard, just hold the "keyboard logo" or "function key" and click the key that has Insert under it (for me it's P)
