### ISSUE TITLE
Finding the correct offset

### ISSUE THREAD

**Issue by DragonDC1** [R3nzTheCodeGOD/R3nzSkin#976]
Hello,

how do I find the new offset? Do I always have to ask in the UnknownCheats forum?
Thanks!

**Comment by hotline1337** [comment]
Dump the League of Legends when it updates, take off a couple of bytes of broken pattern, make a new pattern, profit!

**Comment by DragonDC1** [comment]
Thanks, is there any guide how to dump League? I don't really know how to do it.

**Comment by DragonDC1** [comment]
@hotline1337 I successfully dumped my league. I also generated the string list but could't find the "CharacterDataStack". How do I get this address?

Thanks
