### ISSUE TITLE
Anivia W no change

### ISSUE THREAD

**Issue by senmao1994** [R3nzTheCodeGOD/R3nzSkin#98]
![League of Legends 2022-04-23 18-01-06-447](https://user-images.githubusercontent.com/50578587/164889959-9946b7cd-2f36-42d2-98c6-b066e2dc1838.png)
![League of Legends 2022-04-23 18-01-13-586](https://user-images.githubusercontent.com/50578587/164889962-7d730bee-41bd-467c-8b86-e23501d6aa44.png)
![League of Legends 2022-04-23 18-01-25-099](https://user-images.githubusercontent.com/50578587/164889963-2f2fb535-b97f-47ec-a690-4ca6936a40ec.png)

**Comment by alphaaced** [comment]
still no fix.
