### ISSUE TITLE
Hello, may I ask why the window becomes so big after I enter the game and use insert to open it? thank you！

### ISSUE THREAD

**Issue by Marklo11** [R3nzTheCodeGOD/R3nzSkin#982]
![QQ图片20240102153953](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/63784765/2807dd9b-09e6-4084-a58a-5e804ffe9edd)

**Comment by hotline1337** [comment]
Try to edit the config in Documents/R3nzSkin in file R3nzSkin64. Set fontScale to "1.0"

**Comment by Marklo11** [comment]
Can you show me plz😭
My Computer skills are very poor





------------------ Original ------------------
From: hotline ***@***.***&gt;
Date: Thu,Jan 4,2024 7:00 AM
To: R3nzTheCodeGOD/R3nzSkin ***@***.***&gt;
Cc: Marklo11 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [R3nzTheCodeGOD/R3nzSkin] Hello, may I ask why the window becomes so big after I enter the game and use insert to open it? thank you！ (Issue #982)





 
Try to edit the config in Documents/R3nzSkin in file R3nzSkin64. Set fontScale to "1.0"
