### ISSUE TITLE
Failed to find pattern: 48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02

### ISSUE THREAD

**Issue by fisuri** [R3nzTheCodeGOD/R3nzSkin#983]
The [v3.2.4 release](https://github.com/R3nzTheCodeGOD/R3nzSkin/releases/tag/v3.2.4) is in use
I use this [type](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/477#issuecomment-1789840314) of injection
![Снимок экрана от 2024-01-02 15-48-36](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/37468176/4b9389c5-3865-4ab8-8965-d5350247e12d)

**Comment by hotline1337** [comment]
Is that Linux window? Perhaps Wine is messing up the pattern

**Comment by fisuri** [comment]
yep

**Comment by Sapphire-e** [comment]
I got the same issue on Windows
