### ISSUE TITLE
A key to change to next skin.

### ISSUE THREAD

**Issue by Reraz** [R3nzTheCodeGOD/R3nzSkin#987]
I dont know if there is and if not, a key to change to the next  and previous skin would be useful instead of scrolling and click.

**Comment by juani0mixx** [comment]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/155585854/6818c563-00cd-4c94-982d-332ec95e6c45)

In Quick change skin you can choose which key you want to change your skin

**Comment by Reraz** [comment]
thank you
