### ISSUE TITLE
i have question

### ISSUE THREAD

**Issue by uzcre** [R3nzTheCodeGOD/R3nzSkin#99]
can i use this in PBE server ?

**Comment by sonitaaaaa** [comment]
Yes, offsets must be changed before use. [See how to change offsets](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)

**Comment by senmao1994** [comment]
> Yes, offsets must be changed before use. [See how to change offsets](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)

Where can I see the new offset

**Comment by sonitaaaaa** [comment]
> > Yes, offsets must be changed before use. [See how to change offsets](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)
> 
> Where can I see the new offset

Come on I'm literally put the [link](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2) here. If its blue then it's a link.

**Comment by senmao1994** [comment]
Thank you. I know this link. I'm curious about what tools can be used to find the offset

**Comment by sonitaaaaa** [comment]
> > > > Yes, offsets must be changed before use. [See how to change offsets](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)
> > > 
> > > 
> > > Where can I see the new offset
> > 
> > 
> > Come on I'm literally put the [link](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2) here. If its blue then it's a link.
> 
> Thank you. I know the link. I'm curious about the offset. What tool did they use to find it

If you know Reverse Engineering then you can use [IDA Freeware](https://hex-rays.com/ida-free/), or [Cutter](https://github.com/rizinorg/cutter), many more depends on your taste


E.g
![image](https://user-images.githubusercontent.com/40225192/165880811-6a17bac1-878a-4a31-a9af-a2c78b8db801.png)

**Comment by senmao1994** [comment]
> > > > > Yes, offsets must be changed before use. [See how to change offsets](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2)
> > > > 
> > > > 
> > > > Where can I see the new offset
> > > 
> > > 
> > > Come on I'm literally put the [link](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/2) here. If its blue then it's a link.
> > 
> > 
> > Thank you. I know the link. I'm curious about the offset. What tool did they use to find it
> 
> If you know Reverse Engineering then you can use [IDA Freeware](https://hex-rays.com/ida-free/), or [Cutter](https://github.com/rizinorg/cutter), many more depends on your taste
> 
> E.g ![image](https://user-images.githubusercontent.com/40225192/165880811-6a17bac1-878a-4a31-a9af-a2c78b8db801.png)

This is so cool. Thank you for your answer and your tool. It has helped me too much

**Comment by R3nzTheCodeGOD** [comment]
While adding new EDG skins, riot seems to have corrupted the skin database. Until they fix the database, you can prevent the crash in PBE with the code I gave below.

![image](https://user-images.githubusercontent.com/58574988/165990718-a673d9e9-1d40-4a67-9ccf-70017b8226f0.png)

**Comment by R3nzTheCodeGOD** [comment]
@alphaaced R3nzSkin already replaces the particles created by champions as soon as they are created, this also applies to items like gankplank barrels, teemo mushrooms that will be created later, but riot seems to protect some items on the server side. For example. The snowball appearance is the default when Nunu has a snowball in hand, but if you manually release the snowball, r3nzskin will automatically replace it. Anyway, let's come to the conclusion, maybe it can be fixed, but I will not deal with this troublesome work.

**Comment by alphaaced** [comment]
> @alphaaced R3nzSkin already replaces the particles created by champions as soon as they are created, this also applies to items like gankplank barrels, teemo mushrooms that will be created later, but riot seems to protect some items on the server side. For example. The snowball appearance is the default when Nunu has a snowball in hand, but if you manually release the snowball, r3nzskin will automatically replace it. Anyway, let's come to the conclusion, maybe it can be fixed, but I will not deal with this troublesome work.

I see, it just depends if riot releases these server based effects then it can automatically work. Thank you.
