### ISSUE TITLE
Regarding vanguard and ban 

### ISSUE THREAD

**Issue by corelyoooo** [R3nzTheCodeGOD/R3nzSkin#991]
With vanguard coming to league, should I remove the skin changer right now? If so, is it just the dll and the injector I should remove?

**Comment by desumachii** [comment]
you can still use the skin changer, but never do it when vanguard released on league

**Comment by Reraz** [comment]
is this the end of skin changer then ?

**Comment by eternal-art** [comment]
I think this is the end of using the skin changer, just like using custom skins and cs lol manager to set a different font for example

**Comment by eternal-art** [comment]
vanguard is really tough anti cheat. After all, I heard that when someone play Valorant in the early days Vanguard could control the fans in the computer or something like that

**Comment by Reraz** [comment]
Yeah vanguard goes deeply into your computer, it even goes to your system tray.
