### ISSUE TITLE
How to uninstall completely of my system?

### ISSUE THREAD

**Issue by predomaquilare** [R3nzTheCodeGOD/R3nzSkin#993]
Due to new changes with the addition of Vanguard, im little afraid of leave some parts of the program in my machine, can anyone help with this?

**Comment by Reraz** [comment]
As far as i know just delete the injector and dll, you still have 1 month

**Comment by xennvv** [comment]
He does not have a month. Its most probably the patch on 24.
But they say if u played valorant u dont have to do download it,so if u played it u must probably could get banned from season start.

**Comment by WitheredRose7** [comment]
> He does not have a month. Its most probably the patch on 24. But they say if u played valorant u dont have to do download it,so if u played it u must probably could get banned from season start.

They said late february/early march for Vanguard

**Comment by Reraz** [comment]
yes thats why i say 1 month, this patch wont bring in vanguard.

**Comment by Reraz** [comment]
Yes, this patch wont bring in vanguard.

**Comment by hotline1337** [comment]
just delete the injector and the dll.
