### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by WitheredRose7** [R3nzTheCodeGOD/R3nzSkin#996]
@hotline1337 will it still receives updates until Vanguard comes in upcoming month or two?

**Comment by lesbianmomskissing2016** [comment]
The Vanguard anti cheat can hardware ban people so it doesn't worth updating it

**Comment by hotline1337** [comment]
It will not receive any updates.

**Comment by ibai7** [comment]
> It will not receive any updates, the current method of loading the cheat will 100% not work, and finding a bypass might right with a hardware id ban.

it is working right now, for me at least without any changes
