### ISSUE TITLE
14.1 renzskin closing game

### ISSUE THREAD

**Issue by Xayayia** [R3nzTheCodeGOD/R3nzSkin#998]
aram euw riven worlds 2012 skin selected in game (owned), game just closes at the time when usually the skin menu opens

**Comment by thegreenflash1** [comment]
Can confirm, also ARAM its several skins, straight up disconnects at the time the menu would open...i also noticed that wards changing does not work on SR

**Comment by Lazuli7070** [comment]
Yes, it's happening to me too. When I enter the match with R3nzskin open the game closes by itself, I think this is just the beginning of the other anti-cheat protections that Riot is implementing, I believe that in the future, when Vanguard officially arrives on lol and a crude layer of defense is installed , it will not be possible to bypass this system, then yes, that will be the end of SkinChangers 😥

**Comment by thegreenflash1** [comment]
It will be the end of it yes, due to Kernel lvl but until then it should be fine...they did have a bit of an issue with 2 much traffic so they disabled practice tool and alike until they resolved it, so its possible it just needs an update...because i loaded into a custom game of Aram with the same champ and skins changed fine...it also worked prior to those moments as i played a few games of aram with it working

**Comment by Reraz** [comment]
I had no probem in all my matchs.
The only difference i noticed was some skin dpont work properly like syndra W, maokai E.

**Comment by desumachii** [comment]
the reason why the game closes because the pattern was different now

**Comment by tangmuduo** [comment]
So, sir, I want to know how to avoid the problem of game exit when using R3 in version 14.1. Or is there any chance to do some repair work? We need it so much that we are not used to it now.

**Comment by tangmuduo** [comment]
> aram euw riven worlds 2012在游戏中选择了皮肤(已拥有)，游戏只是在通常皮肤菜单打开时关闭

Sir, I did a test. I found that R3 can play the 14.1 client game normally by injecting the 13.24 dll extension file, and the built-in dragon skin in the new version is also synchronized, so the game will not flash back. I hope it will be helpful to you and the author's update.

**Comment by hotline1337** [comment]
The patterns might be mismatched, but soon there will be Vanguard implemented into the game, for your safety I suggest you to not use the skin changer.
