### ISSUE TITLE
Flash back for the new version 14.1 version R3sk game.

### ISSUE THREAD

**Issue by tangmuduo** [R3nzTheCodeGOD/R3nzSkin#999]
In response to LOL version 14.1, R3 no longer works normally. I did the following tests: I injected the game file with the DLL extension file of version 13.24 R3, and found that the new version of the game can run normally and will not exit. Does that prove that we can combine the 13.24 file with 14.1 to carry out a series of fusion upgrades? What do you think, Mr. Author?

**Comment by xiaonian233** [comment]
The Tencent server's anticheat is different from the global server's anticheat project. It cannot be generalized.

**Comment by tangmuduo** [comment]
> 腾讯服务器的反热与全球服务器的反热项目不同。不能一概而论。目前，vanguard for global server尚未投入使用。谁也无法预测以后会发生什么。

Sir, is there room for optimization in the extension file of version 14.1? If we lose this R3sk, we will lose our enthusiasm for the game.
